### ISSUE TITLE
Join me in keeping up MV development

### ISSUE THREAD

**Issue by lutzhorn** [mediathekview/MediathekView#100]
I am starting to continue work on the three MV modules. Join me in performing these steps:

* port MSearch to Maven (see https://github.com/lutzhorn/MSearchMaven)
* port MServer to Maven
* port Mediathek to Maven
* set up servers to generate and host the lists

**Comment by Nicklas2751** [comment]
This github repository should be the central point of development for MediathekView, it is now a [github organization](https://github.com/blog/674-introducing-organizations) and should be future proof. So better join here then to clutter up the development.
