### ISSUE TITLE
EOL? Gar nich'!

### ISSUE THREAD

**Issue by criztovyl** [mediathekview/MediathekView#113]
"Es geht weiter Info" hinzufügen:
- [x] prog-info-xx.xml
- [x] http://zdfmediathk.sourceforge.net/
- [x] http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=1&t=2215

--

Originaltext
Anscheinend gab es in MV ein EOL Popup, das ist für die Nutzer etwas verwirrend, ist es für uns möglich ein „Es geht weiter!”-Popup auszurollen?

**Comment by Nicklas2751** [comment]
Ich nutze die Software selbst und in der Software ist mir dazu nichts bekannt. Ich kenne nur den Hinweis auf der Webseite.

**Comment by alex1702** [comment]
Ich habs auch gesehen, ja das sollte vllt abgeändert werden.

**Comment by Nicklas2751** [comment]
Wird wohl scheinbar von der folgenden Webseite geladen: http://zdfmediathk.sourceforge.net/prog-info-12.xml

**Comment by criztovyl** [comment]
Nen Screenshot: ![https://mobile.twitter.com/realgiggls/status/791941341190103040/photo/1]

**Comment by zxsd** [comment]
So viel ich es verstehe, resultieren derartige Nachrichten nur wenn die Option "Programmupdate" angekreuzt ist:

![mv-phonehome](https://cloud.githubusercontent.com/assets/23268595/20027690/fffa291a-a2f0-11e6-800a-120eb3a81d7a.PNG)


Diese Frage wäre wohl sofort von einigen im MV-Forum beantwortet worden ...

**Comment by claell** [comment]
Es geht ja nicht draum, wodurch die Nachricht angezeigt wird, sondern ob man die mal ändern könnte, um die User nicht zu verwirren. Die Entwicklung soll ja weiter gehen.

**Comment by alex1702** [comment]
Dieses Pop-Up kommt aber auch nach einer Neuinstallation. Und ich wollte mit xaver noch drüber sprechen.
Gebt mal Tipps was man schreiben könnte. Einerseits sollte klar gemacht werden, dass xaver aufhört und wir oder die organisation dass dann jetzt übernimmt.

**Comment by Siggi0904** [comment]
Dann schreib es so. Xaver gibt sein Projekt in Community Hände, bleibt im Hintergrund aber noch aktiv.
Der Support und die Entwicklung wurden auf breitere Schultern verteilt.

**Comment by criztovyl** [comment]
Auch hier sollten einfügen das es weitergeht:
- http://zdfmediathk.sourceforge.net/
- http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=1&t=2215

**Comment by alex1702** [comment]
Wurde geändert.
