### ISSUE TITLE
Use the JSON interface for the ZDF scraper

### ISSUE THREAD

**Issue by prof-membrane** [mediathekview/MediathekView#120]
I suggest that you move to the JSON API to get more metadata, a stable interface and control over the content you want to scrape.

I've written a Kodi add-on some days ago, the interface is quite extensive. You could use it to get some pointers: https://github.com/prof-membrane/script.module.libZdf

Feel free to ask me some questions. I will monitor this thread.

**Comment by pidoubleyou** [comment]
That's great. I'm going to give it a try.
Is there any documentation of the JSON API?

**Comment by Nicklas2751** [comment]
Discussin about the new ZDF API (in german): http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=3&t=2226&sid=91bd4be96251b6d7b2d54512af24bdeb

and:

https://hub.mediathekview.de/s/72bdb6bb-07b0-497a-b227-19a7234d063c/

**Comment by prof-membrane** [comment]
>  Is there any documentation of the JSON API?
Nope, but the interface is straight forward.

I am also using special interfaces of some other channels: 
- 3sat (Xml)
- BR (Json)
- Das Erste (Json)
- Funk.net (Json)
- MDR (Xml)
- Phoenix (Json)
- SR (Json)
- WDR (Xml)

I've seperated the scraper from the Kodi specific parts. You could run the Python code outside of Kodi if you want. The only thing left to do is to put some glue logic behind it to get a fully fledged craweler.

If you are open to this, we could join forces.

**Comment by Siggi0904** [comment]
Habt ein Auge auf https://github.com/raptor2101/Mediathek. Hier wird die "neue" JSON-API verwendet.
So muss das Rad nicht neu erfunden werden.

**Comment by prof-membrane** [comment]
Wieso neu erfinden? Das API was ich verwende ist vom ZDF, das von Raptor ist von nem Drittanbieter.

**Comment by criztovyl** [comment]
Dieser Issue betrifft MSearch, nicht MediathekView, daher dorthin verschoben.
mediathekview/msearch#41
