### ISSUE TITLE
version.properties / *.build

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MediathekView#122]
I don't see why we need thes two files in the three projects. I think the actual version will be clear through git tags and branches, the name of the zip/jar. If the version.properties is used in the programm to show the actual version i think the version number only should be enough. I don't think annyone needs the date of the last build or the number how often the project was builded. And i think if we remove the *.build file and only have the project version in the version.properties it will be a lot easier to build.

**Comment by derreisende77** [comment]
Das ist ein Überbleibsel aus der Zeit der NetBeans builds. Von mir aus kann man das Anpassen und muss halt nur die Logik im Programm unter anderem im About Dialog Anpassen. Sollte aber nicht schwer sein.

**Comment by zxsd** [comment]
Als User der zwischen Versionen/Entwicklerversionen immer wieder (und gerne) testen konnte -- und auch per Forum-PN, Ergebnissen melden konnte -- fürchte ich Tendenzen wie, 'weniger übersichtlich, aber dafür leichter zu tun.'  Bis MV13-1132 (scheinbar "Entwicklerversion," 13-1134 gleich), wußte ich Bescheid. Das was ich jetzt hier finde, ist mir ein Wirrwarr ... an und fuer sich nichts schlimmes; ich bin eh User nicht Entwickler.  Aber von einem Mangel an Dokumentation wurde schon im Forum diskutiert. Prozess, falls vorhanden, könnte zum Teil Dokumentationslücken überbrücken.  

Ich hoffe, daß neuere Entwicklerversionen ab und zu veröffentlicht werden, und darauf hingewiesen werden.

**Comment by alex1702** [comment]
Ich werde mal drüber nachdenken wie man am besten das macht.

**Comment by Nicklas2751** [comment]
Bei maven ist es üblich, dass eine Entwickler Version als "-SNAPSHOT" rausgeht und eine Stable ohne.
Beispiel:
Entwicklervesion: 14.0.1-SNAPSHOT
Realese nach Test Phase: 14.0.1

Gehandlet wird das ganze so, dass für 14.0.1.-SNAPSHOT dann diese Version im gradle eingetragen wird. Dann wird im git ein Tag dafür erzeugt, der tarivs baut das ganze dann und, sobald wir ihm das beigebracht haben, lädt er dann automatisch auf GitHub die Zip und die Tar usw. hoch. (Evtl. auch direkt sourceforge wenn das geht?). Und wenn dann noch Bugs gefunden werden werden die in einem Bug Fixing Branch behoben und dann wird die Version auf 14.0.1 geändert und wieder ein Tag erstellt und wieder durch Travis gebaut.

**Comment by alex1702** [comment]
Abänderung wie bei MSearch.
