### ISSUE TITLE
[TODO] Windows Executabels

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MediathekView#134]
# EN
The actual gradle implementation with #132 is missing a generation for new Windows executables on build.
Ant hadn't it too but to really automate the building we need this.
One solution could be the gradle launch4j plugin but this has a problem it can only build one single Windows executable per build.
See for this: https://github.com/TheBoegl/gradle-launch4j/issues/7

# DE
Dem Bauen des Projekts mit gradle wie wir es aktuell haben fehlt eine Neu-Erzeugung der `EXE`-Dateien für Windows.
Ant hatte dies zwar auch nicht aber um das bauen vollständig zu automatisieren brauchen wir das.
Eine Lösungsmöglichkeit könnte das Gradle Launch4J Plugin sein, das Problem damit ist aber, dass es immer nur eine Windows `EXE` Datei pro Build erzeugen kann. Siehe hierzu auch: https://github.com/TheBoegl/gradle-launch4j/issues/7

**Comment by zxsd** [comment]
Eine Frage von einem Laien ...

Wäre es möglich mehrere, verwandt benannte Instanzen von dem gradle-launch4j Plugin zu kreieren, und diese dann der Reihe nach aufrufen (Plugin_1 + xml_1, Plugin_2 + xml_2, Plugin__n_ + xml__n_)?  Elegant möge es nicht sein ... aber die Polyinstanziierung genießt ein zu schlechtem Ruf IMO.  Wenn die Plugin-Modulen nicht gleich sein dürfen, dann hilft vielleicht ein manuell zugefügtes NOP (Null-Op, bzw., Nulloperation) innerhalb des jeweiligen Plugins ...

**Comment by criztovyl** [comment]
Braucht es denn überhaupt mehrere Windows `EXE`?

**Comment by Nicklas2751** [comment]
Mein Ticket wurde bearbeitet. Ich werde es direkt ausprobieren ob ich nun die verschiedenen Exes erstellen kann.

**Comment by Nicklas2751** [comment]
Die Exe Datein werden generiert und funktionieren. Ich warte mit dem shcließen noch, ob der von mir gemeldete Fehler behoben wird so, dass ich keine Workaround mehr brauche. 

Fehler: https://github.com/TheBoegl/gradle-launch4j/issues/36

**Comment by Nicklas2751** [comment]
Mit hilfe von @TheBoegl konnte ich den Fehler, der wie es sich herausstellte bei mir lag, finden und beheben.

@TheBoegl Thanks a lot for the quick help.

**Comment by TheBoegl** [comment]
Gerne

**Comment by alex1702** [comment]
Generierung der Exe-Dateien abgeschlossen. 
Was noch zu tun ist: Einstellungen per Configdatei laden, anstatt 4 einzelne Exe Dateien.

**Comment by TheBoegl** [comment]
Ich habe gestern Abend mehr durch Zufall einen Fehler in der Konfiguration der exe ohne Speichereinstellungen gesehen und kommentiert.

**Comment by alex1702** [comment]
> Ich habe gestern Abend mehr durch Zufall einen Fehler in der Konfiguration der exe ohne Speichereinstellungen gesehen und kommentiert.

Öhm und wo?

**Comment by Nicklas2751** [comment]
Soweit passt das und ist mit dem nächsten Realese auch wieder im master.
