### ISSUE TITLE
Migration Webseite von Sourceforge

### ISSUE THREAD

**Issue by criztovyl** [mediathekview/MediathekView#139]
Namentlich http://zdfmediathk.sourceforge.net

**Comment by alex1702** [comment]
nope
und zdfmediathek?
sourceforge zu eigener anständiger Seite.

**Comment by criztovyl** [comment]
Was statisches?

**Comment by alex1702** [comment]
ja zum größten teil

**Comment by claell** [comment]
Ich verlinke hier auch mal die neue Seite: https://mediathekview.de/

**Comment by criztovyl** [comment]
[mediathekview/MediathekViewDE](https://github.com/mediathekview/MediathekViewDE)
