### ISSUE TITLE
Umzug des Projekts und Wiki von Sourceforge nach Github

### ISSUE THREAD

**Issue by claell** [mediathekview/MediathekView#141]
Im Zusammenhang mit #139 schlage ich vor, auch einen Umzug der Projektseite auf Sourceforge (https://sourceforge.net/projects/zdfmediathk/) in Betracht zu ziehen. Wohin sei mal dahingestellt, GitHub würde sich ja anbieten, aber ggf. gibt es auch (bessere?) Alternativen.

**Comment by alex1702** [comment]
warum erwähnst du das jetzt nochmal?

**Comment by claell** [comment]
Hast du den Link angeklickt? So wie ich es verstanden habe, gibt es eine gehostete Homepage und eine Projektseite unter anderem mit Downloadlinks und einem Wiki, ähnlich wie ein GitHub Projekt.

#139 bezieht sich so wie ich das sehe auf die Website, während dieser Issue sich auf das Projekt bezieht.

**Comment by claell** [comment]
Habs durch das Editieren deines Kommentars erst jetzt gesehen.
> Der Umzug galt auch dafür.
Steht im Issue anders.
> Und wir sind schon auf Github.
Das stimmt, ist aber schon seit mindestens einem Jahr so. Mir ging es um eine vollständige Migration. Also Wiki und andere Dinge, die Momentan noch ausschließlich auf Sourceforge verfügbar sind. Auch wurde bis zuletzt darüber der Download angeboten.

**Comment by alex1702** [comment]
Ja das wird auch noch ein wenig weiter gehen bis wir halt alles eingerichtet haben.

**Comment by claell** [comment]
Alles klar. Mir ging es mit diesem Issue halt darum, über eine Umstellung zu diskutieren (also ob alles nach GitHub soll, oder auf Sourceforge bleiben, oder ganz anders) und ggf. dann auch schon mal in Angriff zu nehmen (also z.B. Wiki transferieren).

**Comment by claell** [comment]
So, ich komme nochmal hierauf zurück.
So wie ich es verstanden habe, ist so ziemlich klar, dass die ganze Projektseite von Sourceforge nach GitHub umgezogen werden soll.

Das ist aber denke ich erstens noch nicht wirklich diskutiert und auch nicht kommuniziert und auch noch nicht vollständig vollzogen, beispielsweise fehlen noch Bilder aus dem Sourceforge-Wiki etc.

Ist es dann nicht sinnvoll, hier wieder aufzumachen, damit der Fortschritt verfolgt werden kann?

**Comment by alex1702** [comment]
Nicht die komplette Seite wird nach Github umgezogen.
Wiki ja
Rest kommt nach mediathekview.de

**Comment by claell** [comment]
Welcher Rest? Die Source-Forge **Projekt**-Seite (https://sourceforge.net/projects/zdfmediathk/) besteht doch im Grunde nur aus Wiki und den Dateien.

**Comment by alex1702** [comment]
Meine http://zdfmediathk.sourceforge.net/ noch.

**Comment by claell** [comment]
Ok. Das meinte ich nicht mit "Sourceforge-Projekt" sondern lediglich die Projektseite und nichts, was da gehostet ist. Und da es für den Umzug der Projektseite noch kein Issue gibt, wäre dieses doch geeignet, oder?

**Comment by alex1702** [comment]
ja ok

**Comment by claell** [comment]
Danke!

**Comment by galan** [comment]
Was ist mit https://sourceforge.net/projects/zdfmediathk/? Bei den sf Einstellungen kann man setzen, das das Projekt nun woanders gehostet wird, Beispiel: https://sourceforge.net/projects/packtag/ (siehe turkise schriftzug unter dem projektnamen). Zudem sollten releases nicht mehr über sf verfügbar sein. Das hat immer noch einen schalen Beigeschmack...

**Comment by alex1702** [comment]
werde ich mal umsetzen. danke für den Tipp.

**Comment by zxsd** [comment]
403-Fehler nichtsdestotrotz werden allem Anschein nach [die Setvorlagen](http://zdfmediathk.sourceforge.net/programmgruppen11/) auch noch vom Sourceforge serviert ... 

![setvorlagen](https://cloud.githubusercontent.com/assets/23268595/22854217/96b103c2-f037-11e6-9607-af76035d2597.PNG)

**Comment by alex1702** [comment]
das ist mir leider auch schon aufgefallen. muss da nochmal im code gucken.

**Comment by xaverW** [comment]
da stimmen die Pfade in der Vorlagenliste nicht:
https://res.mediathekview.de/programmgruppen11/programmgruppen.xml

**Comment by xaverW** [comment]
@galan habs geändert und die Downloads der Versionen >12 entfernt
ganz schließen kann man es nicht, da die alten Programmversionen (und davon laufen noch einige) darauf verweisen.

**Comment by alex1702** [comment]
ach da müssen die angepasst werden? da kann ich ja lange suchen... xD ok werde ich heute mal anpassen, danke für den Tipp.
