### ISSUE TITLE
Workflow Doku

### ISSUE THREAD

**Issue by criztovyl** [mediathekview/MediathekView#149]
Workflow Doku verbessern. Entweder git-flow erklären (v.a. die Motivation dahinter), muss ja nicht selbstgeschrieben sein, da hat sich sicher schomal jmd Gedanken drüber gemacht und das niedergeschrieben.
Und ich würde den Workflow mit git-flow-Tools und ohne nicht auf einer (Wiki-)Seite behandeln, ich würde das eher trennen, das macht das ganze etwas übersichtlicher.

**Comment by zxsd** [comment]
Ich kann "Workflow" als solches unter **github/mediathekview** nicht finden ... Für eine Link wäre ich dankbar.

**Comment by Nicklas2751** [comment]
Algemeine Entwicklung: https://github.com/mediathekview/MediathekView/wiki/Entwicklung
git-flow Workflow: https://github.com/mediathekview/MediathekView/wiki/Entwicklung:-git-flow
Workflow ohne git-flow: https://github.com/mediathekview/MediathekView/wiki/Entwicklung:-Ohne-git-flow

**Comment by alex1702** [comment]
Die Trennung hat nur den Nachteil, dass man sich als aussenstehnder eventuell schlechter entscheiden kann. Es sind jetzt auch keine ewig langen Texte wo man sagen kann, dass die Übersichtlichkeit darunter leidet. 
Zur Motivation muss ich mal was raussuchen, wenn das unbedingt gewünscht ist.

**Comment by criztovyl** [comment]
Hm, alles auf einer Seite empfinde ich jetzt nicht viel hilfreicher um sich zu entscheiden.
Ich würde eher eindeutig klarstellen was wir bevorzugen (soweit ich das verstanden hab' ist das der Weg mit den Git Flow Tools).

**Comment by criztovyl** [comment]
Huh, lt. Cheatsheet ist der Befehl `git flow release start RELEASE` wobei RELEASE für die Version des Hotfix steht, da können wir als eig. gar kein Issue-Namen nehmen?

**Comment by alex1702** [comment]
Doch können wir, da ich den Hotfix Branch umbenenne in die neue Release Version.

**Comment by criztovyl** [comment]
Ukay, ich nehm' das so auf. :+1:
