### ISSUE TITLE
version.properties

### ISSUE THREAD

**Issue by criztovyl** [mediathekview/MediathekView#153]
mediathekview/mSearch#52

**Comment by criztovyl** [comment]
Wird mit mediathekview/msearch#59 einfacher zu lösen sein, s. https://github.com/mediathekview/MediathekView/compare/develop...criztovyl:feature/%23153-version.properties

**Comment by Nicklas2751** [comment]
Durch diese Änderung haben wir eine zweite unnötige Versionsnummer die von der Allgemeingültigen Versionsnummer aus dem Build.Gradle abweicht. Dies führt meiner Meinung nach nur zu Problemen und es gibt hierfür keinen Sinnvollen Grund da die Version aus der Properties nur zum anzeigen für den Benutzer benötigt wird.

**Comment by alex1702** [comment]
siehe #122
