### ISSUE TITLE
MSearch als JAR referenzieren

### ISSUE THREAD

**Issue by criztovyl** [mediathekview/MediathekView#154]

**Comment by Nicklas2751** [comment]
Auf die Übersicht bezogen: 
Wie so sollte man das tun? Dafür gibt es ja gradle mit dependeny management. 

Und ansonsten: 
Beschreibung?!

**Comment by derreisende77** [comment]
Ich stimme nicklas zu. Ich sehe auch keinen Grund hierfür ein Jar zu nutzen.

**Comment by criztovyl** [comment]
Ich habe nur entdeckt, das wenn ich bspw. Plugins in MSearch einsetzte, er dann MV nicht mehr baut.
Und wenn ich die Plugins in MV hab, kann ich  MSrc nicht mehr ohne MV bau'n.
Vllt gibt's dazu aber auch ne andere Lösung, hab nur oberflächlich nachgeguckt.

**Comment by Nicklas2751** [comment]
#163 wird genau das lösen. ;)
