### ISSUE TITLE
zip-file in distributions

### ISSUE THREAD

**Issue by xaverW** [mediathekview/MediathekView#156]
das Startscript funktioniert (zumindest unter Linux) nicht, da das jar:
MediathekView-13.jar
die Versionsnummer im Namen trägt. Eins von beiden muss angepasst werden.

**Comment by alex1702** [comment]
Ja hab mir gedacht, dass das irgendwann passieren wird. Ich werde das Startskript heute anpassen.

**Comment by Nicklas2751** [comment]
Wir können über File filtering da mit gradle automatisch den richtigen Dateinamen einfügen lassen. https://docs.gradle.org/current/userguide/working_with_files.html#sec:filtering_files

**Comment by claell** [comment]
Also ist gewünscht, dass die Versionsnummer im Dateinamen enthalten ist?

**Comment by alex1702** [comment]
Ich denke es ist besser wenn sie nicht im Dateinamen ist. EInzige Ausnahme ist MSearch (später MLib), da macht es Sinn.

**Comment by claell** [comment]
Also dann das Startscript doch nicht anpassen, sondern die Benennung ändern?

**Comment by Nicklas2751** [comment]
Ok, auch gut.
