### ISSUE TITLE
HD Option ausblenden, wenn nicht verfügbar

### ISSUE THREAD

**Issue by ThirtySomething** [mediathekview/MediathekView#158]
Die HD Option wird beim Download nur auf Readonly gesetzt. Das ist unter Umständen nicht direkt sichtbar, weil alles Grautöne. Ein komplettes ausblenden ist besser.

**Comment by zxsd** [comment]
Diese Art von Änderung würde ich (und vielleicht andere User) gerne ausprobieren, bevor sie in ein neues Release aufgenommen wird. Ich verstehe die Beschreibung nicht ganz ... aber bin mir sicher die Unterschiede verstehen zu können, wenn ich eine Art von 'Probefahrt' damit machen könnte.  

**_Folgender Text stammt von einem User, der github kaum versteht._**

Wenn ein leicht findbares, gut abgegrenztes und beschriebenes "Test" Branch (vielleicht von @alex1702 erstellt) mitsamt einer (oder mehreren) derartigen Änderung(en) vorhanden wäre -- welches als ganzes Release (ZIP-Datei) von normalsterblichen runtergeladen werden könnte -- fände ich es klasse. Ich verspreche davon Gebrauch zu machen.  Feedback würde ich immer liefern, eventuell klipp und klar wie, "Finde ich spitze!"  

Bestünde eine derartige Möglichkeit, glaube ich andere Langzeit-Anwender (also MV-Power-Users) auch davon Gebrauch machen würde ... nachdem sie von der Testen-Möglichkeit ins Kenntnis gesetzt worden wären.

**Comment by criztovyl** [comment]
@zxsd 
Den Quellcode kannst du dir natürlich jederzeit runterladen, aber das ist wahrscheinlich nicht das was du suchst ^^ Außerdem wäre natürlich möglich eine solche Branch anzulegen, aber auch das hilft in dem Fall nicht weiter.

Das was du suchts ist ja, soweit ich verstandne hab', eine ZIP die du runterladen, entpacken & dann einfach MV ausführen kannst.
Das ist so ohne weiteres nicht möglich, dazu müssen wir erst ein "Release" anlegen. Das aber für jede Änderung zu machen ist etwas zu viel, wir sollten da vllt wieder so eine Art Entwicklerversion einführen, die sich aber nicht an Entwickler sonder an "Beta" Tester oder sowas ähnliches richtet. Das gehört hier jetzt aber überhaupt nicht zu diesem Issue, ich werde dazu eine neuen aufmachen.

**Comment by derreisende77** [comment]
Code commit compiled nicht.

**Comment by derreisende77** [comment]
gefixt. Bitte vorher vernünftig testen vor dem commit.

**Comment by derreisende77** [comment]
Bitte zur Erläuterung: Warum ist ausblenden besser als das deaktivieren? Grundsätzlich ist die HD-Option in diesem Dialog vorhanden, kann aber in dem Fall wenn kein HD-Film vorhanden ist, nicht ausgewählt werden. 
Dies Verhalten entspricht meiner Meinung nach gängigen Human Interface Guidelines (OSX, Windows), ausblenden jedoch nicht.

**Comment by criztovyl** [comment]
Es ging darum, das aufgrund der generellen Grautöne in MV die ausgegraute Schaltfläche/Checkbox/wasauchimmer nicht also deaktiviert zu erkennen war.

**Comment by ThirtySomething** [comment]
Mit ist es in letzter Zeit öfters passiert, dass  ich bei schummriger Beleuchtung auf HD geklickt habe. Es gab aber kein HD. Also habe ich mich gefragt: Warum wird eine Option angezeigt, die man nicht auswählen kann? Es ergibt für mich mehr Sinn, dem Benutzer nur das anzuzeigen, was er auch tatsächlich auswählen kann. Das erscheint mir klarer zu sein.

**Comment by derreisende77** [comment]
Dann wäre die Implementierung einer dynamisch gefüllten ComboBox zukünftig evtl sinnvoller als die bisherigen radio buttons.
Ich persönlich finde die Lösung mit dem ausblenden nicht elegant.

**Comment by ThirtySomething** [comment]
Auch eine Combobox wäre eine Lösung. Sobald ich mal eine funktionierende Umgebung habe, schaue ich mir das nochmal an.

**Comment by derreisende77** [comment]
Bitte dann als Feature implementieren.


Am 28. November 2016 10:12:16 schrieb Jochen Paul <notifications@github.com>:

**Comment by xaverW** [comment]
ich finde das wie es jetzt ist besser, da seh ich auf einen Blick, welche Auflösungen es gibt und auch gleich die dazugehörige Dateigröße. In einer Combobox muss ich erst wieder klicken.
vielleicht erst mal mit angepassten Bildschirmfarben versuchen, auf anderen Desktops ist es gut zu sehen.

**Comment by derreisende77** [comment]
Die Farben entsprechen den jeweiligen stabdardfarben des Betriebssystem. 
Dies zu ändern halte ich für schlichtweg nicht sinnvoll da es keinem User 
Interface Guideline entspricht.
Ich sehe hier drei Optionen:
1. Radio Button ausblenden
2. Das ganze als angepasste combobox.
3. Licht heller machen ;-)

Ich persönlich bevorzuge Nummer 2, da der Dialog dann an sich aufgeräumter 
wirkt.
Mit Nr. 1 könnte ich knirsxhend leben.
Letztendlich tendiere ich jedoch zu Nr. 3


Am 28. November 2016 16:27:03 schrieb xaverW <notifications@github.com>:

**Comment by xaverW** [comment]
ich habe nicht gemeint, dass das Programm die Bildschirmfarben ändern soll, sonder der User (vielleicht ist ein Theme eingestellt dass halt nicht die Standardfarben enthält)
ich würde auch nichts ändern am Programm, mir gefallen die Radio am besten.

**Comment by alex1702** [comment]
Ich hab mir das jetzt auch nochmal angesehen und bin zu dem Schluss geommen, dass ich ausgrauen auch besser finde als ausblenden.
Aber über das Deutsch müssen wir nochmal reden.
"hoher Auflösung" und "niedriger Auflösung" ?
Wie wäre es mit "hohe Auflösung" und "niedrige Auflösung"?

**Comment by xaverW** [comment]
darüber steht: "Film laden" [in] 
hoher/niedriger Auflösung

**Comment by ThirtySomething** [comment]
@xaverW Die HD Option wird immer angezeigt, auch wenn sie gar nicht zur Verfügung steht. Dann wird lediglich die Dateigröße nicht angezeigt - verständlicherweise. Es wird dem User also suggeriert, es könnte eine HD Option geben, aber er darf bzw. kann sie nicht auswählen. Ich bin dafür, nur das anzuzeigen, was auch möglich ist. So sieht man sofort, ob es das in (hoher/)mittlerer/niedriger Auflösung gibt. Das Ausgrauen ist fast so, als ob Du bei einem 50 PS Auto einen Tacho bis 250 km/h hast - es wird zwar auf der Skala angezeigt, aber erreichen wird man die Geschwindigkeit nie. Die Information, daß man es könnte, aber nicht erreichen kann, ist in dem Moment also nicht hilfreich. Bezüglich den Radio Buttons gebe ich dir recht, damit ist es besser als mit der Combobox.

**Comment by alex1702** [comment]
> darüber steht: "Film laden" [in]
> hoher/niedriger Auflösung
ok dann finde ich da sollte noch ein in hin.

> Das Ausgrauen ist fast so, als ob man bei einem 50 PS Auto einen Tacho bis 250 km/h hat
Ich will dich ja nicht ärgern, aber das gibt es xD

Es wird die Dateigröße nicht engezeigt und der Button ist ausgegraut/nicht klickbar. Ich finde das suggeriert ganz gut, dass es keine HD Option gibt. Wenn man den jetzt entfernt rutschen die anderen beiden Buttons nach links, was sehr unschön designtechnisch ist. Weil dann könnte man ja denken das hohe Auslösung bei dem Film HD ist ^^
Also wie gesagt, es bleibt beim ausgrauen und nicht ausblenden.

**Comment by Nicklas2751** [comment]
Ich nutze MV schon länger und wenn der Bildschirm nicht übertrieben Hell oder der Kontrast sehr schlecht ist finde ich erkennt man das problemlos als ausgegraut. Ich schlisse mich also Alex und Xaver an.

**Comment by claell** [comment]
Finde das Argument von @alex1702 auch wichtig, dass es sonst leichter zu Verwechslungen kommen könnte bzw. man schwieriger erkennen kann, dass der Film nicht in HD verfügbar ist. Ob man diese Information jetzt braucht oder nicht sei mal dahingestellt.

**Comment by derreisende77** [comment]
Ich baue es zurück.


Am 29. November 2016 18:09:35 schrieb Claudius Ellsel 
<notifications@github.com>:
