### ISSUE TITLE
MediathekView Preview-Releases?

### ISSUE THREAD

**Issue by criztovyl** [mediathekview/MediathekView#159]
@zxsd hat in #158 angemerkt das sowas doch ganz nett wäre, u.a. auch um vllt Feedback von den Nutzern zu bekommen.

**Comment by zxsd** [comment]
Danke für das Housekeeping, @criztovyl. Ich werde was dieses Wochenende hinzuschreiben ... aber jetzt habe ich keine Zeit dafür.

**Comment by zxsd** [comment]
Fragen tue ich gerne beantworten ...

**Comment by Nicklas2751** [comment]
Idee ist gut. Die Aktuelle Version ist noch recht unspannend ich würde also mit einem Entwickler Realese noch etwas warten. Es ist aber natürlich jedem frei überlassen sich den aktuellen Stand zu ziehen und zu bauen. ;)

**Comment by alex1702** [comment]
Es gibt mittlerweile Nightly-Releases.
