### ISSUE TITLE
cant find show in mediathek which I can find on the online website of arte

### ISSUE THREAD

**Issue by derWalter** [mediathekview/MediathekView#160]
I cant find this program in Mediathek, but I can view and download it directly on the website:
http://www.arte.tv/guide/de/050775-000-A/thorium-atomkraft-ohne-risiko

(I can download it by manually extracting the link from the json file)

**Comment by zxsd** [comment]
> Wenn eine Sendung nur über die Such-Funktion in der Mediathek eines Senders gefunden werden kann, dann wird sie von MediathekView nicht gelistet werden, denn MediathekView sucht nur auf bestimmten Webseiten der Sender (z.B. Sendungen A–Z) und extrahiert die Video-URLs. 

([Quelle](https://sourceforge.net/p/zdfmediathk/wiki/FAQ/#in-der-mediathek-des-senders-xyz-ist-die-sendung-vorhanden-in-der-filmliste-jedoch-nicht))

I'm glad you can get the file on your own!

**Comment by derWalter** [comment]
yes, all versions are listed in the json.

is there a possibility to manually add those shows into mediathek,
or even add those shows in general?
