### ISSUE TITLE
Anbinden von MSearch als normales Dependency.

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MediathekView#163]
## Allgemeine Beschreibung
Damit MSearch nicht immer mitgeklont werden muss sollten das ganze wie folgt umgebaut werden.

MSearch, MServer, MLib und Co. mit dem Gradle Maven Plugin bauen (https://docs.gradle.org/current/userguide/maven_plugin.html) und in das Repo (https://repo.mediathekview.de) hochladen. Dadurch kann in den referenzierenden Projekten wie auf z.B MSearch wie auf eine normale Dependency verwiesen werden.

Ziel ist es, dass wenn das Projekt nicht im lokalen Repo (durch einen Build) vorliegt, es aus dem zentralen Repo geladen werden kann. Wichtig ist hierbei die korrekte Versionsvergabe wie "[version]-SNAPSHOT" für  Entwicklerversionen.

Hierbei würde ich vorschlagen, dass der `develop`-Branch von Travis zum Deployen der Entwicklerversionen und der `master` für das Deployen von norm. Versionen verwendet wird, bzw. als Entwicklerversion wenn es Branch `master` oder deploy ist und norm. Version wenn es Branch `master` und ein Tag ist.

Wichtig ist natürlich auch, dass eine Dependency vom Server Repo nur geladen werden soll wenn sie älter ist als die aus dem lokalen Repo.

Ich würde mich dem gemeinsam mit @alex1702 annehmen.

## Zusammenfassend sehe ich folgende Aufgaben:

- [x] Einfügen von Repo Deployment für MSearch
- [x] Einfügen von Repo Deployment für MediathekView
- [x] Einfügen von Repo Deployment für MServer
- [x] Anpassen der Travis Configs
- [x] Anpassen der Referenzierung auf MSearch für MediathekView
- [x] Anpassen der Referenzierung auf MSearch für MServer
- [x] Testen des richtigen Zusammenspiels

**Comment by xaverW** [comment]
vielleicht wäre es sinnvoll, vor den ganzen Änderungen, die geplanten Umbenennungen zuerst durchzuführen, dann müsste da nichts doppelt gemacht werden und die Module hätten dann mal die endgültigen Namen.

**Comment by alex1702** [comment]
Stimmt das sollte vllt vorher geschehen, aber was man vorbereiten kann, kann man ja schonmal machen.
