### ISSUE TITLE
MediathekView an aktuellen MSearch master anpassen

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MediathekView#166]
Mit dem aktuellsten Stand vom MSearch master baut MediathekView nicht mehr. U.a. hat sich die API der Klasse ListeFilme geändert. MediathekView muss entsprechend daran angepasst werden.

**Comment by derreisende77** [comment]
Das ist richtig. Die Änderungen sind in develop drin.
Evtl sollte man Mal drüber nachdenken ein stabiles develop nach Master zu 
mergen auch wenn es kein Release ist.


Am 2. Dezember 2016 09:39:08 schrieb Nicklas Wiegandt 
<notifications@github.com>:
