### ISSUE TITLE
Umstellung auf neue Links

### ISSUE THREAD

**Issue by alex1702** [mediathekview/MediathekView#167]
Die Links wie akt.xml umstellen auf die neuen.
Neue URL: https://res.mediathekview.de/

**Comment by alex1702** [comment]
puh. die hälfte der URLs sind ja in msearch. Aber die werden nicht vom Crawler gebraucht oder?

**Comment by Nicklas2751** [comment]
Wir sollten auf kurz oder lang alle URLS und so weiter in config Datein auslagern.
