### ISSUE TITLE
Durchreichen von args bei gradle run ermöglichen

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MediathekView#170]

**Comment by TheBoegl** [comment]
Das kann man eigentlich eigentlich einfach erledigen.
Folgende Zeilen im _build.gradle_ bringen die Funktionalität jeden JavaExecTask mit `-Pargs=param1,param2,--moreParams` aufzurufen:
```
tasks.withType(JavaExec) {
    if (project.hasProperty('args')) {
        args(project.args.split(','))
    }
}
```

Benötigt ihr jedoch einen gewissen Task öfters, so sollte dieser auch erstellt werden. Z. B.:

```
task runGerman(type: JavaExec, dependsOn: installDist, overwrite: true) {
    description 'Runs this project as a JVM application'
    group 'application'
    main 'your.main.ClassName'
    args "--language=de"
    classpath fileTree("$installDist.destinationDir/lib")
}
```

**Comment by Nicklas2751** [comment]
Im develop branch nun enthalten. Mit dem nächsten realese kann das Ticket dann geschlossen werden.
