### ISSUE TITLE
OffTopic: Team für Gradle-Migration gesucht

### ISSUE THREAD

**Issue by bmhm** [mediathekview/MediathekView#171]
Hallo,

bitte schließt/löscht den Issue gleich wieder, da offtopic. Ich finde die Gradle-Umstellung dieses Projektes wirklich toll. Ich hatte des öfteren schon nach Projekten gesucht, wo ich Java-Code committen könnte.

Vielleicht hat ja jemand wie @alex1702, @Nicklas2751  oder @kaklakariada  Lust, noch ein weiteres Projekt umzustellen. Das wird allerdings zu forken sein müssen.

Ich denke da an: https://github.com/willuhn/hibiscus.

Problem: Ich hatte mal eine Maven-Umstellung versucht, die aber nur teilweise gemergt wurde. Derzeit baut das Projekt nur mit Eclipse und SWT-Libraries, die in Unterordnern liegen. Außerdem scheint Java 1.6-Support für den bisherigen Autor Priorität zu haben (trotz JavaFX-Abhängigkeit).
Um hier keine Issues in anderen Projekten zu spammen, würde ich mich freuen, falls man hier ein Team zusammenstellen könnte.
In dem Zusammenhang entstanden: Plugins für andere non-HBCI-Banken, etwa: https://github.com/bmhm/ffb.depot.client

Noch einmal entschuldigung für das Eröffnen im falschen Projekt. Aber durch die entferne Nachrichten-Funktion wusste ich mir leider nicht anders zu helfen.

**Comment by alex1702** [comment]
Kann man vielleicht mal in Jabber besprechen mediathekview@conference.elaon.de der mediathekviewdev@conference.elaon.de
