### ISSUE TITLE
Idee: MediathekView Browser Add-Ons

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MediathekView#173]
Folgene Idee kam mir heute:

Entwickeln eines Browser Plugins welches bei Beuschen einer der Mediatheken mit dem Browser ein Icon aktiviert welches es einmem dann ermöglicht z.B. die gerade von der Mediathek angezeigte Sendung zu abonieren mit MediathekView (der Übliche neues Abo Dialog geht auf), anzuzeigen (Suche Wird mit Sender und Titel befüllt) oder diese Folge herunter zu laden (MediathekView kriegt Sender + Titel und Auftrag zum Download).

Umsetbar wäre dies u.A. indem sich MediathekView beim entsprechenden Betriebssystem für eine URL registriert wie z.B.:
mediathekview://search/SenderZbZDF/TitelZBHeute-show
mediathekview://subscribe/SenderZbZDF/TitelZBHeute-show
mediathekview://download/SenderZbZDF/TitelZBHeute-show

Oder wenn der Benutzer dies auch in MediathekView aktiviert (opt-in!) öffnet MediathekView einen Port und das Plugin sendet die entsprechenden Informationen anschließend an diesen Port.

Ich freue mich auch eure Meinungen zu der Idee. ;)

---
Dies ist eine Idee für ein nettes nice-to-have Feature. Bugs so wie Arbeiten an der Stabilisierung von MediathekView haben natürlich absoluten Vorrang.

**Comment by criztovyl** [comment]
Ich schätzen das registrieren im BS sollte nicht nötig sein, das Plugin (oder Addon?) kann ja auch so lokal über nen Socket mit MV kommunizieren. Und das womöglich sogar via HTTP, das kann der Browser am besten :D

**Comment by zxsd** [comment]
Das Signal-Geräusch-Verhältnis bei den Mediatheken ist derart gering, daß ich die Websites möglichst vermeide.  Ab und zu klicke ich einen Link im Beschreibungsfeld, aber nur wenn ich was nachforschen will.

Wenn es als API implementiert würde, wäre es wohl von den Nutzern der alternativen MV-Front-Ends (wie der späteste, [MediathekViewWeb](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=2&t=2220)), mit lokaler MV-Instanz bestimmt von Interesse ... da die Funktionalität bestimmt von den Front-End Entwicklern 'übernommen'/integriert werden würde.

**Comment by criztovyl** [comment]
Ich entferne mal das "feature" Tag, das ist doch eher für MediathekView als Software gedacht, nicht für's Projekt. Dafür füge ich das Tag "meta" hinzu.

**Comment by genodeftest** [comment]
Browser-Plugins sterben gerade aus, und dass ist auch gut so. Gegen ein Addon gibt es nicht viel einzuwenden, außer dass die Entwicklung aufwändig ist, weil jeder Browser etwas anders ist.

**Comment by alex1702** [comment]
Es gibt ja nur 2 große Browser wo sich ein Plugin lohnt ^^
Und ich denke nicht, dass Addons/Plugins aussterben.

**Comment by genodeftest** [comment]
> Und ich denke nicht, dass Addons/Plugins aussterben.

Naja, Plugins per NPAPI werden in Firefox in 2017 komplett abgeschaltet und die Unterstützung dafür entfernt. Chrome hat NPAPI schon vor ein paar Jahren deaktiviert und entfernt, und es gibt nur noch die PPAPI, die aber kaum genutzt wird.

Aber ja, Addons gibt es trotzdem noch.

**Comment by styroll** [comment]
Die Aussagen von "genodeftest" sind zutreffend. Damit alle vom gleichen sprechen: "Plug-ins" in der Terminologie von Mozilla/Netscape dienen der Anzeige von Medieninhalten (Animationen, Videos, Dokumente) via die NPAPI-Schnittstelle (z.B. Flash, Quicktime, Silverlight, Adobe PDF, Java). Diese Technologie ist am sterben und teilweise schon tot. 
Erweiterungen via PPAPI gibt's meines Wissens nur bei Chrome und Derivaten.

Add-ons sind in der Terminologie von Mozilla alle anderen Erweiterungen (z.B. Adblock Plus, Ghostery, Firebug). Und die gibt's weiterhin.

**Comment by Nicklas2751** [comment]
Ich meinte Add-ons ;)

**Comment by alex1702** [comment]
Oh entschuldigt da hab ich auch etwas verallgemeinert. Plugins hab ich nie wirklich gemeint, sondern immer AddOns, da für mich plugins in firefox eigentlich schon tod sind und ich auch nicht daran gedacht habe das auf der ebene zu entwickeln.
