### ISSUE TITLE
Wo kommen die Daten her?

### ISSUE THREAD

**Issue by roschaefer** [mediathekview/MediathekView#174]
Für ein [anderes Projekt](https://github.com/roschaefer/rundfunk-mitbestimmen) würde ich gerne die `filme.json` Datei verwenden.

Erst einmal ist der JSON Standard recht eigenwillig implementiert. Also dachte ich, vielleicht findet man den Code und kann ihn anpassen. Nach ein bisschen Schnitzeljagd stößt man über `mediathekdirekt` auf die [eigentlichen Quellen](http://zdfmediathk.sourceforge.net/update-json.xml).

Auf welche magische Weise entstehen die Daten dort? Werden die Daten gescraped? Ist der Quellcode von den scrapern online?

**Comment by alex1702** [comment]
ja es gibt den MServer in verbindung mit MSearch der die Filme sammelt und auf diese angegeben Server verteilt.
Um Traffic zu sparen ist es ein nicht ganz so konformes JSON Format.

**Comment by criztovyl** [comment]
MV-JSON Reader: [FilmlitseLesen#readFilmListe](https://github.com/mediathekview/MSearch/blob/master/src/main/java/mSearch/filmlisten/FilmlisteLesen.java#L122)
MV-JSON Writer: [WriteFilmlistJson#filmlisteSchreibenJson](https://github.com/mediathekview/MSearch/blob/master/src/main/java/mSearch/filmlisten/WriteFilmlistJson.java#L39)

**Comment by roschaefer** [comment]
Ich konnte [MSearch modifizieren](https://github.com/roschaefer/MSearch/commit/49bb4a272301e50a43b1a4a5000cdc88ffd5239a), dass es jetzt ein Standard CSV ausspuckt. Bestimmt tauchen noch weitere Fragen auf. Habt ihr einen öffentlichen Chat? 

[gitter](https://gitter.im) ist übrigens für diesen Fall gemacht

**Comment by Nicklas2751** [comment]
Und was willst du mit csv wo Json doch viel einfacher zu parsen ist und Objekte unterstützt?.

**Comment by roschaefer** [comment]
Die `filme.json` ist kein valides JSON. Das war mit der "eigenwilligen" Implementierung gemeint. Wenn ich mit einer Standard-Bibliothek die Datei einlese, ist das Array bis auf ein Element fast leer. Das liegt an den duplizierten Schlüsseln "X: ...". Vermutlich aus Gründen der Dateigröße werden Schlüssel wie Sender und Sendung bei Wiederholung leer gelassen und sollen sich dann auf das vorherige Element im Array beziehen. Anstelle Code zu schreiben, der das beim Lesen berücksichtigt, habe ich einfach den verursachenden Code angepasst, der die Daten schreibt. Warum CSV? Naja, die Daten sind eine Tabelle, kein Baum. Da liegt es einfach näher, CSV als Austauschformat zu nehmen.
