### ISSUE TITLE
[Enhancement] Correct the text "2 Downloads: 0 laufen, 0 warten" to "Keine aktiven Downloads"

### ISSUE THREAD

**Issue by Wikinaut** [mediathekview/MediathekView#182]
I never understood the "2 Downloads: 0 laufen, 0 warten".

#### Suggestion

s/2 Downloads: 0 laufen, 0 warten/Keine aktiven Downloads/

**Comment by zxsd** [comment]
> I never understood ...

Könnte vielleicht die User-Dokumentation auch betrachtet werden?  Ein Extra-`Else` (beispielsweise ... oder neue ElseIf, bei If-Anweisung) oder Extra-`Case` (Case-Bedingung) für diesen spezifischen Fall wäre meines Erachtens nicht angebracht.  Wenn die Dokumentation für eine Erläuterung sorgt, wäre die vorgeschlagene Änderung nicht nötig.

Hier sind Beispiele dieser Statusleiste, soeben abgelichtet:

![dl-reiter-status-004](https://cloud.githubusercontent.com/assets/23268595/21255559/a76eca3e-c33a-11e6-8647-e29a71863b6a.PNG)

![dl-reiter-status-003](https://cloud.githubusercontent.com/assets/23268595/21255566/afa7cd68-c33a-11e6-9db9-4659ac381379.PNG)

![dl-reiter-status-002](https://cloud.githubusercontent.com/assets/23268595/21255572/b6e53106-c33a-11e6-9360-4e75b2b4089b.PNG)

![dl-reiter-status-001](https://cloud.githubusercontent.com/assets/23268595/21255577/c0eb4f96-c33a-11e6-8f11-5b038e8a99e2.PNG)

**Comment by Wikinaut** [comment]
Ich lese keine Manuals wegen so einer Anzeige. Ich verstehe den Begriff immer noch nicht.

Was bedeutet die "3", "25", "80", "11" ? Ich verstehe es nicht. Während sonst alles prima ist, ist dieser Text "xx Downloads" nichtssagend. Schau mal, im letzten Bild zum Beispiel steht dort einmal "11 Downloads" und dann steht dort auch "7 Downloads", das ist wirklich Unfug.

**Comment by claell** [comment]
Das ist (ohne die Anleitung gelesen zu haben) denke ich folgendermaßen, bezogen auf das letzte Bild:
11 Downloads sagt, dass im Download Reiter 11 Dateien sind. Davon sind 4 Dateien durch ein Abo hinzugefügt worden und 7 durch den Nutzer selbst als "Download" angelegt worden.
Ist aber wirklich vielleicht nicht sehr selbsterklärend.

**Comment by Wikinaut** [comment]
Ich meine, dass man nicht zweimal das gleiche Wort ("Download") in verschiedener Bedeutung benutzen sollte.

**Comment by zxsd** [comment]
> Ich bitte um Erklärung.

MV im Betrieb ...

![dl-reiter-user-01](https://cloud.githubusercontent.com/assets/23268595/21258607/c6cab8dc-c34b-11e6-9d6e-e03985ec18d1.PNG)

Nach dem Aktualisieren der Filmliste ...

![dl-reiter-user-02](https://cloud.githubusercontent.com/assets/23268595/21258617/cfe37b20-c34b-11e6-941d-ff7a1735a886.PNG)

Meines Erachtens ist die Statusleiste dafür vorgesehen, eine schnelle Überblick zu sein ... für diejenigen die MV konsequent anwenden.  Da diese Statusleiste scheinbar für gelegentliche User verwirrend sein könnte, sollte es vielleicht eine Konfigurations-Option sein ... und Default-mäßig nicht angezeigt werden.  

Mit der zweifachen Anwendung von "Downloads" habe ich kein Vorschlag parat. Die Bilder sollten erst als Beispiel für User-Dokumentation dienen ...

**Comment by alex1702** [comment]
Also auf den ersten Blick ist es nicht ersichtlich stimmt. Also wenn es möglich ist, würde ich eine Mouseover extra Info machen, sodass eine kurze Erklärung anzeigt was damit gemeint ist.

**Comment by Wikinaut** [comment]
Was mir auch immer vollkommen unklar ist: warum bleibt *manchmal* ein Download (der aber fertig war), nach Neustart im Downloadfenster sichtbar ? Ist mit vollkommen unklar.

**Comment by derreisende77** [comment]
@alex1702 Und was soll in dem Tooltip drin stehen? Genau diesselben Informationen aus der Anzeige? Dann versteht es wieder keiner....und wenn ich versuche in einem Tooltip die Bibel zu erklären wird es keiner lesen können weil es zu schnell verschwindet.
@Wikinaut unter welchem OS verwendest Du MV?

**Comment by alex1702** [comment]
@derreisende77 Ne das was zxsd auf seinem Bild geschrieben hat ca.

**Comment by Wikinaut** [comment]
@derreisende77 debian 8, Mac El Captian, Mac OS Sierra

**Comment by zxsd** [comment]
In Bezug auf Status im DL-Reiter, ist die letzte [Entwickler-Version](https://sourceforge.net/projects/zdfmediathk/files/Entwicklerversion/) noch weiterentwickelt als MV12 ... und bei der Handhabung leichter zu justieren, für diejenigen die DL-Schwierigkeiten haben könnten.  (Status-Einzelheiten werden da angezeigt, wo im Filme-Reiter der Filter ist.)  

![dl-reiter-status-010](https://cloud.githubusercontent.com/assets/23268595/21261774/72a494e8-c35b-11e6-8f17-36be9e4a5606.PNG)

(Im obigen Bild wurde MV halt zusammengequetscht, um hierin besser zu passen. Bei vollkommenem Fenster schaut's meiner Meinung nach gut aus.) Ich weiß nicht ob es noch verwirrender für gelegentliche MV-Anwender wäre.
