### ISSUE TITLE
Wrong file linked up for DMG of v13

### ISSUE THREAD

**Issue by neutric** [mediathekview/MediathekView#190]
The links to the macOS version of MediathekView 13 on Sourceforge as well as mediathekview.de lead to a small snippet of HTML instead of the dmg.

**Comment by andrev68** [comment]
https://download.mediathekview.de/stabil/
File Size for DMG - 10252 vs 12975691 for zip

**Comment by neutric** [comment]
Resolved.

**Comment by andrev68** [comment]
Das DMG lässt sich jetzt lffnen, aber "Das Programm „MediathekView“ kann nicht geöffnet werden."

**Comment by neutric** [comment]
@andrev68 Das klingt nach Gatekeeper, siehe [Abschnitt Gatekeeper-Meldungen](https://support.apple.com/de-de/HT202491). Wie auch im Hintergrundbild des DMG beschrieben den erstmaligen Start via CTRL-Klick auf das Icon und "Öffnen" ausführen, um die Warnung zu umgehen. Bei mir startet es so tadellos.
