### ISSUE TITLE
Option zum umschalten zwischen HTTPS und HTTP

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MediathekView#193]
Da es bei Usern zu Problemen beim abspielen von HTTPS Inhalten kommen kann, wäre eine Option in den Einstellungen zum umschalten zwischen HTTP und HTTPS nützlich.

Dies sollte durch eine einfache Ersetzung wenn die jeweilige option angehakt ist gemacht sein. ;)

**Comment by Nicklas2751** [comment]
https://forum.mediathekview.de/topic/18/probleme-mit-https-streaming

**Comment by styroll** [comment]
> Da es bei Usern zu Problemen beim abspielen von HTTPS Inhalten kommen kann, wäre eine Option in den Einstellungen zum umschalten zwischen HTTP und HTTPS nützlich.

Zur Info: Diese User verwenden veraltete Software: Aktuelle Versionen von SMPlayer, VLC und das Multimedia-Framework von Windows 7 (und neuer) sowie macOS funktionieren sehr wohl mit TLS (https). Scheint also eher nicht notwendig bzw. sinnvoll zu sein (vielleicht höchstens für einige Linuxer mit veralteten LTS-Versionen und ohne Bereitschaft eine neuere Version selbst zu installieren).

FFmpeg, welches zum Decodieren in vielen Playern verwendet wird, kann damit auch umgehen, muss aber geeignet kompiliert werden:
`https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.`

**Comment by derreisende77** [comment]
Ich kann nur für OSX sprechen, die windows binaries kenne ich nicht. Die nächste Mac-Version wird eine aktualisierte HTTPS-fähige ffmpeg version enthalten.
@Nicklas2751 :
Am einfachsten wäre jedoch die crawler so anzupassen dass sie die HTTPS links in HTTP umschreiben. Das behebt am schnellsten das Problem für die Leute und benötigt kein Update.
Dies sollte jedoch nur eine temporäre Lösung bis zu einem nächsten Release sein da es ja durchaus passieren kann das nur HTTPS funktioniert, nicht jedoch HTTP.

Wenn jemand veraltete Software verwendet bin ich jedoch dafür, nicht für alles irgendwelche checks und fix-versuche zu integrieren. Soweit ich weiß unterstützen wir "offiziell" nur VLC als player. Das andere funktionieren ist schön, aber nur Kür. Ich sehe keine Notwendigkeit, aufgrund (meist vorhandener) Faulheit einzelner User irgendwelche Updates mit nicht wirklich notwendigen "Fixes" rauszubringen. Man kann es nicht allen Recht machen.

**Comment by Nicklas2751** [comment]
Ich habe des ganze aufgenommen weil ich es generell gut finde wenn eine Software in den Optionen möglichst gut an die eigenen Bedürfnisse anpassbar ist. Deshalb das ganze auch als feature und nicht als Bug o.ä.

**Comment by xaverW** [comment]
ich habe mal die https URLs angeschaut, die ließen sich auf http ändern. Habe das auch mal als Patch im branch https->http eingestellt. Es wird jede URL zuerst getestet ob vorhanden. Allerdings läuft das ZDF in "develop" nicht richtig.
-> aber es sind dann andere URLs und werden als "neu" angezeigt.

**Comment by pidoubleyou** [comment]
Die Idee, https bereits durch die Crawler entfernen zu lassen, sehe ich persönlich als die schlechteste Option an: Viele Webseiten werden in der letzten Zeit auf HTTPS umgestellt, um sichere Verbindungen zu gewährleiten. Warum sollen alle MediathekView-Nutzer die unsichere Verbindung verwenden, wenn das Problem nur wenige User betrifft. 
 
Wäre es nicht sinnvoller, z.B. in der Konfiguration der Sets die Möglichkeit zu bieten, HTTPS zu deaktivieren?

**Comment by derreisende77** [comment]
Wie ich geschrieben habe ist der Crawler die schnellste Option, die Probleme für alle User zu beheben bis es ein Update der Software gibt. 
Ich habe für die nächste OSX Version die ffmpeg binary ausgetauscht, so dass sie HTTPS-fähig sein wird. Wer die binaries für Windows tauscht weiß ich erst mal nicht. 
Bis dahin muß das Problem jedoch erst mal "schnell" behoben werden.
Und mit xavers patch prüft der Crawler ob es neben HTTPS auch eine HTTP-erreichbare Variante gibt. Also ist das IMHO die beste, sicherste und schnellste Variante. 

Der bedarfte User kann auch jetzt schon einfach selbst die ffmpeg version austauschen und die PSets dementsprechend anpassen. Da sich die Meldungen im Forum jedoch dazu häufen scheinen die meisten User sich nicht damit auszukennen bzw haben Sie keine Ahnung wie man das macht oder einfach keine Lust an den Standardkonfigurationen etwas zu ändern.  Von daher sind die Möglichkeiten aus meiner Sicht schon da, nur werden sie aus allerlei Gründen eben nicht genutzt.

**Comment by pidoubleyou** [comment]
Was spricht dagegen einfach eine neue MediathekView-Version bereitzustellen, bei denen die ffmpeg binary in der neuen Version enthalten sind?

**Comment by derreisende77** [comment]
Unter anderem das sich Stand heute die Minimum OS X Version für MediathekView von OSX 10.8 auf OS X 10.9 anhebt. Und das mit einem bugfix-release. Das liegt an den derzeit verfügbaren Builds für ffmpeg.
Zumindest @styroll wird sich darüber freuen. ;)

**Comment by derreisende77** [comment]
@vitusson Was soll das mit den thumbs down? Wenn Du etwas beizutragen hast kannst Du gerne hier kommentieren...ansonsten ist das hier Entwickler-Talk für Erwachsene.

**Comment by styroll** [comment]
> Ich habe für die nächste OSX Version die ffmpeg binary ausgetauscht, so dass sie HTTPS-fähig sein wird.

Nur zur Erinnerung: [Der Post](https://forum.mediathekview.de/post/87), der diese Issue zur Folge hatte, bezog sich nicht auf FFmpeg, sondern auf einen externen Medienplayer, nämlich SMPlayer, der – weil eine veraltete Version verwendet wurde – mit den https-URLs des ZDFs nicht zurecht kam. Einem User mit diesem Problem wäre mit einer neuen Version von FFmpeg nicht geholfen. Ich bin aber wie "derreisende77" der Meinung, dass man updatefaule User nicht zwingend unterstützen muss.

Zurzeit finden sich in der Filmliste nur beim ZDF "https-URLs". Wenn ich mich richtig erinnere, werden jedoch beim (FFmpeg benötigenden) SRF https-Adressen in http-Adressen umgewandelt. Falls das stimmt, dann wäre ein FFmpeg-Update längerfristig schon sinnvoll, da keine unverschlüsselten Streams bzw. keine URL-Umwandlung mehr nötig wären.

Ich habe übrigens FFmpeg bloss erwähnt, weil die meisten OSS-Player – als Backend quasi – FFmpeg zum Decodieren verwenden. So auch bei meinem Player der Wahl "mpv". Und wie gesagt: Aktuelle Versionen von SMPlayer (der neu default mpv als Multimedia-Engine mitbringt) können wie "mpv" selbst oder "vlc" auch "https".

**Comment by alex1702** [comment]
Ich denke eine Liste der Mindestversionen von den Abhängigkeiten zur verfügung zu stellen macht mehr sinn, als uns darum zu kümmern alles abwärtskompatibel zu machen.

**Comment by smitsohu** [comment]
Die Probleme mit HTTPS lassen sich mutmaßlich auf einen [Bug in GnuTLS](https://gitlab.com/gnutls/gnutls/issues/223) zurückführen.

VLC beispielsweise verwendet GnuTLS und ist (auch unabhängig von MediathekView) auf Debian Stretch immer noch davon betroffen. Da es abhängig von der Updatepolitik der Distributionen noch dauern kann, in einzelnen Fällen wohl auch Jahre, bis sich das Problem von selbst löst, sollte es vielleicht irgendwo dokumentiert werden.

In jedem Fall stimme ich @derreisende77 zu: 
> Wenn jemand veraltete Software verwendet bin ich jedoch dafür, nicht für alles irgendwelche checks und fix-versuche zu integrieren

Auf Debian Stretch kann das Problem übrigens behoben werden, indem `gnutls-bin` aus sid installiert wird.
