### ISSUE TITLE
Gleichzeitiges einstellen von Mindes- und Maximallänge 

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MediathekView#195]
Prüfen ob es möglich ist die Mindest- und Maximallänge mit einem Regler einzustellen und wenn möglich umsetzen. 

Dieser Vorschlag stammt aus dem Forum: https://forum.mediathekview.de/topic/17/mindestl%C3%A4nge-oder-maximall%C3%A4nge

**Comment by Georg-J** [comment]
Bei exakter Übereinstimmung sollte ein Film angezeigt werden. Dies ist nicht der Fall. Getestet habe ich mit einem Film (Titel: Die "Duftstars" sind vergeben) mit einer Dauer von 00:03:00.

Bei der Einstellung "Mindestlänge 3" wird der Film ausgeblendet, mit der Einstellung "Mindestlänge 2" wird er sichtbar.
Bei der Einstellung "Maximallänge 3" wird der Film ausgeblendet, mit der Einstellung "Maximallänge 4" wird er sichtbar.

**Comment by derreisende77** [comment]
Verlangtes Feature wurde für 13.1 realisiert und ist schon committed.
