### ISSUE TITLE
(Mac version): Kann "Zeitraum" nicht per Tastatur setzen

### ISSUE THREAD

**Issue by gernotstarke** [mediathekview/MediathekView#196]
kann den Defaut-Wert von 6 Tagen NUR per Maus über den slider ändern,
nicht aber per Tastatur.

Version: 13.0.0
Java: 1.8.0_112

![mediathekview_13_0_0](https://cloud.githubusercontent.com/assets/1233990/21605863/3428f89e-d1ac-11e6-9084-eb89c634d48a.png)

**Comment by derreisende77** [comment]
Ja, das ist so korrekt. Die derzeitige Implementierung sieht keine Eingabe per Tastatur vor, das Textfeld dient nur der Visualisierung.
