### ISSUE TITLE
Proxy Unterstützung

### ISSUE THREAD

**Issue by s256** [mediathekview/MediathekView#197]
Wäre es möglich über die Downloadsettings noch Proxy Parameter mitzugeben? Socks, HTTP-Proxy & wpad vielleicht. Oder die Systemvariablen nutzen?

**Comment by xaverW** [comment]
man kann die Proxyeinstellungen der JavaVM beim Start des Programms direkt über die JavaVM:

java -jar ....

nutzen, die werden ausgewertet. Aber das ist ganz bewusst nicht im Programm (bzw. wurde wieder entfernt) um den Sendern keinen Anlass zur Kritik zu geben (wegen der Umgehung von Geo-Sperren)
