### ISSUE TITLE
Start-Skript für Linux fehlt in V13

### ISSUE THREAD

**Issue by rkbwde** [mediathekview/MediathekView#200]
Anscheinend wurde MediathekView__Linux.sh im zip-Archiv vergessen. Workaround: Das File aus V12 herüberkopieren.

**Comment by vitusson** [comment]
MediathekView.sh ist das Startskript, das wurde nur umbenannt von MediathekView__Linux.sh

**Comment by alex1702** [comment]
Genau, es handelt sich einfach nur um eine Umbenennung
