### ISSUE TITLE
Software-Aktualiesierung Version 13.0.1

### ISSUE THREAD

**Issue by terrie1000** [mediathekview/MediathekView#201]
Hallo,

erst mal vielen Dank das ihr den MediathekView weiter führt.

Bei der Version 13.0.1 bekomme ich nach dem Start die Fehlermeldung:
"Es ist ein Fehler bei der Softwareaktualisierung aufgetreten. Die aktuelle Version konnte nicht ermittelt werden."

Bei Version 12 läuft diese Funktion noch fehlerfrei.

So long,

Terrie

**Comment by pidoubleyou** [comment]
siehe #191

**Comment by xaverW** [comment]
Hallo,

solche Fragen bitte im Forum stellen:

https://forum.mediathekview.de/

Grüße




Am Sun, 08 Jan 2017 00:28:59 -0800
schrieb terrie1000 <notifications@github.com>:

> Hallo,
> 
> erst mal vielen Dank das ihr den MediathekView weiter führt.
> 
> Bei der Version 13.0.1 bekomme ich nach dem Start die Fehlermeldung:
> "Es ist ein Fehler bei der Softwareaktualisierung aufgetreten. Die
> aktuelle Version konnte nicht ermittelt werden."
> 
> Bei Version 12 läuft diese Funktion noch fehlerfrei.
> 
> So long,
> 
> Terrie
> 
>
