### ISSUE TITLE
[WIKI] Anleitung zum start ohne UI

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MediathekView#202]
Im Wiki fehlt aktuell noch eine ordentliche Anleitung wie MV ohne UI gestartet werden kann.

**Comment by styroll** [comment]
Ja, weil die entsprechenden Stellen offenbar nicht aus dem alten Wiki übernommen wurden. Evtl. finde ich diese Stellen auch einfach nicht, da die ganze Struktur (Inhaltsverzeichnis) leider zerschossen wurde (und die Auflistung der Seiten im rechten Teil entzieht sich eher dem logischen Aufbau). Hier aus einem alten Backup:

## Starten mit zusätzlichen Parametern
    java -jar MediathekView.jar [Pfad] [Parameter]
    java -jar MediathekView.jar c:\temp -M

Nach dem obigen Schema kann das Programm auch mit zusätzlichen Parametern gestartet werden.

    java -jar MediathekView.jar Einstellungen/.mediathek3

Das Programm verwendet – durch einen relativen Pfad – das Verzeichnis "Einstellungen" im MediathekView-Verzeichnis auf dem USB-Stick (der Ordner "Einstellungen" muss zuerst erstellt werden). Hinweis: Die Programmeinstellungen (Filmliste, Einstellungen, gesehene Filme) werden standardmässig im Home-Verzeichnis (Benutzer-Verzeichnis) in einem Ordner ".mediathek3" gespeichert. 
 
    java -jar MediathekView.jar -M 
 
Das Programm startet mit einem maximierten Fenster: 

    java -jar MediathekView.jar -v 

Das Programm gibt nur die Versionsnummer aus.

<font color="white">space</font>

## Auto
    java -jar MediathekView.jar [Pfad] -auto
    java -jar Mediathek.jar -auto

Das Programm startet im Auto-Modus. Es wird die Filmliste aktualisiert und dann alle neuen Abos geladen. Das Programm beendet sich dann selbst wieder. Diese Funktion eignet sich dazu, alles automatisch aktuell zu halten. Das Programm (Abos, Downloadpfade) muss zuerst im "normalen" Modus eingerichtet werden. Der Auto-Modus startet ohne grafische Oberfläche und kann so auch auf Rechnern ohne grafische Oberfläche (ohne X) laufen.

<font color="white">space</font>

## Parameter, die die Einstellungen der JavaVM ändern

    java -jar -Dhttp.proxyHost=proxyserver -Dhttp.proxyPort=8080 MediathekView.jar
Es wird ein Proxyserver verwendet. 

    java -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -jar MediathekView.jar
Es wird ein anderes LookAndFeel verwendet. Dazu darf aber in den Programmeinstellungen der MediathekView keines ausgewählt sein, diese Angabe wird sonst überschrieben.

    java -Djava.awt.headless=true -jar MediathekView.jar -noGui
Wird das Programm ohne GUI auf einem Rechner mit grafischer Oberfläche gestartet (-noGui, -auto), kann man damit den Splashscreen unterdrücken

    java -Djava.net.preferIPv4Stack=true -Xms128M -Xmx1G -jar MediathekView.jar
Die Parameter "-Xms128M -Xmx1G" helfen bei geringem Arbeitsspeicher. Der Parameter "-Djava.net.preferIPv4Stack=true" ermöglicht eine Verbindung zum Internet, wenn der verwendete Netzwerk-Stack von Java nicht automatisch richtig erkannt wird, wodurch die Filmliste nicht geladen werden könnte.
[nach oben](#top)

**Comment by AngieSoft** [comment]
Leider wird diese Option scheinbar in der aktuellen V13 *nicht* mehr unterstützt.
 siehe: [https://github.com/mediathekview/MediathekView/issues/204](url)

**Comment by derreisende77** [comment]
@AngieSoft Nochmal, auch wenn ich es in Issue 204 schon beschrieben habe: Es funktioniert auf den unterstützten Betriebssystemen...die oben beschriebene Vorgehensweise funktioniert. Deine Konfiguration ist das Problem.

**Comment by derreisende77** [comment]
Hat das schon jemand in das wiki integriert?

**Comment by derreisende77** [comment]
Auto Modus ist dokumentiert also schließe ich das hier.
