### ISSUE TITLE
Downloadpfad bei Abos

### ISSUE THREAD

**Issue by Kettenknecht** [mediathekview/MediathekView#203]
Man könnte in der Hilfe noch erwähnen, dass der Downloadpfad in der Aboverwaltung relativ zu dem im gewählten Downloadset angegeben werden müssen. Oder noch besser, in der Aboverwaltung einen aboluten Pfad setzen lassen. Das würde einiges vereinfachen.

**Comment by derreisende77** [comment]
Im PSet wird die entsprechende Info angezeigt, absolute Pfade im Abo entsprechen nicht der Philosophie des Programms.
