### ISSUE TITLE
TUI für's Ausführen in Terminals auf entfernten Rechnern mit schnellerer Internetanbindung

### ISSUE THREAD

**Issue by gitaeuber** [mediathekview/MediathekView#204]
Hallo Zusammen,

ich nutze MediathekView eigentlich nur zum Herunterladen von aktuellen Filmen. Zum Ansehen komme ich meist erst Wochen später.
Es wäre schön, wenn es zumindest für diese Funktionialität ein einfaches Text User Interface (TUI) gäbe. Es dürften nicht nur die Abos bearbeitet werden, man müsste auch die Liste der (neuen) Filme sehen und dort welche zum Download auswählen können.

Könnte das jemand umsetzen? Vielleicht wäre https://sourceforge.net/projects/javacurses/ eine Möglichkeit für die Umsetzung, oder auch: https://github.com/mabe02/lanterna

Vielen Dank für das tolle Engagement!

Viel Glück für das neue Projekt

**Comment by derreisende77** [comment]
Also ich persönlich habe kein Interesse so etwas zu implementieren. Du weisst schon dass Du via SSH die Grafikausgabe umleiten kannst? Dann kannst Du das Programm ganz normal verwenden. Ist evtl die einfachste Lösung zumal Du schreibst dass eine schnelle Internetverbindung vorhanden ist.

**Comment by gitaeuber** [comment]
Es ging mir um eine Möglichkeit, von einem Rechner mit _sehr_ langsamer Internetanbindung einen entfernten Rechner mit schneller Anbindung für Mediatheview nutzen zu können.
Ein Umleitung der Grafikausgabe ist sehr zäh und träge. Evtl. sogar durch Konfiguration des ssh-Servers unterbunden. Auf jedenfall nicht nutzbar.

Schade.
Danke dennoch

**Comment by claell** [comment]
Ist der Rechner mit langsamer Verbindung denn in der Lage, die Filmliste von MediathekView zu laden? Dann könnte man damit die Filme suchen und Abos laufen haben und anschließend entweder irgendwie automatisiert oder halt manuell die Links per SSH am schnellen Rechner laden.

**Comment by gitaeuber** [comment]
Das wäre eine Variante, wenn MediathekView einfach ein kleines Shellskript als Ergebnis anlegt, dass dann auf dem Entfernten Rechner ausgeführt werden kann.
Oder eine Datei, die mittels:

```
while read URL FILENAME;
do
  wget -cO "$FILENAME" "$URL"
done < MV.wget
```

zum Herunterladen ausgelesen werden kann.
Aber schon das Laden der Liste dauert eine halbe Ewigkeit (ca. 1/2 h).

Oder MediathekView wartet auf der Kommandozeile auf Befehle, so dass man ein "dialog"-Skript als TUI basteln kann.
```
MV_loadFileList;
MV_listFiles;
MV_addAbo(…);
MV_addBlacklistSender("ABC");
MV_startDownloadFile(5463);
MV_showActiveDownloads;
MV_exit;
…
```

**Comment by Nicklas2751** [comment]
Du kanns auch deine Abo Datei auf den entfernten Rechner übertagen und dort MV ohne GUI ausführen (`-auto`)

**Comment by gitaeuber** [comment]
Abos habe ich keine, da ich mich weniger für Serien interessiere.
Danke

**Comment by AngieSoft** [comment]
Der Aufruf von 
`java -Djava.awt.headless=true -Xms256M -Xmx512M -jar MediathekView.jar ./Einstellungen/.mediathek3/ -fastauto` 
unter raspbian Jessie (ohne X11) führt zu Fehler.
"JavaFX wurde nicht im klassenpfad gefunden....."

Bei vorigen Versionen klappte das noch ohne Probleme. Eine TUI ist dafür nicht notwendig.

**Comment by derreisende77** [comment]
OpenJFX 8 ist auf dem System nicht installiert. Bitte installieren dann klappt es.

**Comment by AngieSoft** [comment]
Was soll die Kommandozeilenversion, die mit "-Djava.awt.headless=true" gestartet wird und nur die Aufgabe hat, die Liste der Downloads auf einem Raspi ohne Display (nur bedienbar via ssh ohne grafischen "schickschnak") abzuarbeiten, so wie es die MV Versionen bis V11 auch konnten, mit einer JFX? 
Ganz abgesehn davon, dass die JFX nicht in den offiziellen Quellen des verwendeten Jessie zur Verfügung steht. Ich benutze wie schon oben angedeutet ein Rasbian Jessie LITE ohne X11.
Installierte JRE: 
`java -v` -->
_java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)_
installiert mit 
`apt-get install oracle-java8-jdk`

Meine Bitte: Die Version, die mit o.g. Option ganz ohne JFX startet wäre sinnvoll. Ein wie auch immer geartetes GUI/TUI ist dafür nicht notwendig.  Die Daten zum Abarbeiten der Downloads werden dem Raspi via Einstellungsverzeichnis zur Verfügung gestellt.

**Comment by derreisende77** [comment]
MV benutzt seit Version 12 Java 8. Wir haben uns entschieden zukünftig von Swing zu JavaFX zu migrieren. Die Version 11 ist Geschichte und solange sie mit den derzeitigen Listen funktioniert - feel free to use it. Die Zukunft läuft in eine andere Richtung und Abwärtskompatibilität wird von uns gewährleistet solange es machbar ist. Ich bitte zu beachten dass wir ein GPL-Programm sind und keinen kommerziellen Support anbieten der den zusätzlichen Aufwand dafür abdecken würde. Dies bedeutet aber auch dass es Ihnen freisteht einen Fork des Programms zu starten der ohne die von Ihnen bemängelten Features auskommt. Sowohl der client als auch die server software sind hier verfügbar. Freie Software lebt davon das andere mitmachen. Also go ahead und ich persönlich freue mich über merge requests die sinnvolle Features nachrüsten.
Mal davon abgesehen das Programme ohne irgendein GUI/TUI durchaus JavaFX nutzen können. Dies besteht nämlich neben dem UI-Zeugs auch aus Klassen die wirklich gut sind und ohne UI genutzt werden können - also kein "schnickschnack"...
Weiterhin möchte ich anmerken dass sie eine bedeutend veraltete Java 8 version verwenden. Aktuell ist Java 8u112. Offensichtlich gibt es (bisher bei uns bis jre8u92 gemeldet) Probleme bei der Verarbeitung von HTTPS-Seiten mit MV, so dass diese java-version dringend aktualisiert werden sollte - von bekannten Sicherheitslücken mal ganz abgesehen. 
Abschließend halte ich fest dass wir offiziell folgende Plattformen unterstützen:
- Windows
- Mac OS X
- Linux x86/amd64
Dafür testen wir und bieten Downloads an. Alle anderen Plattform-Variationen sind unsupported und wenn sie funktionieren ist es eine schöne Sache. Und sollte Java8 in Debian veraltet sein und JavaFX dort fehlen sind nicht wir die Ansprechpartner sondern Debian. Wir sind nicht für die Pakete dort verantwortlich UND wir sind auch nicht verpflichtet unsere Software für jede windige Linux-Distribution anzupassen die meint aus irgendwelchen esotherischen Beweggründen bestimmte Software nicht mitliefern zu wollen oder zu können. Das sind Entscheidungen der Verantwortlichen die man mit der Installation akzeptiert und deren Konsequenzen man akzeptieren muss.

**Comment by gitaeuber** [comment]
Ich hätte nicht gedacht, dass ich mit meiner Anfrage nach einer TUI eine so schlecht gestimmte Diskussion verursache.
Es war doch nur eine Frage.
Schade, dass ich kein Javaprogrammierer bin. Vielleicht findet sich noch jemand, der das machen kann und möchte.

Grüße und gute Nacht

**Comment by derreisende77** [comment]
@gitaeuber Deine Anfrage nach TUI ist nicht verkehrt. Aber es können nun mal nicht alle Wünsche erfüllt werden da es durchaus legitime Gründe gibt, Sachen nicht zu implementieren. Issues und Threads feindlich zu übernehmen - zumal wenn sie nicht zusammen hängen - ist das eigentliche Problem. Aber damit bist Du nicht gemeint.

**Comment by claell** [comment]
Gut, wenn ein Issue "feindlich übernommen wird" könnte man darauf ja auch Hinweisen, damit ein neues Issue gestartet wird.

Die Frage von @AngieSoft war ja, ob JFX überhaupt im headless-mode benötigt wird. Das scheint ja der Fall zu sein, da auch andere nicht UI-bezogene Klassen genutzt werden.

**Comment by gitaeuber** [comment]
Hallo zusammen,

ich überlege, mir selbst ein UI zu schreiben.
Leider bin ich nicht so fit in Java. Ich bräuchte ein wenig Hilfe.
Könnte mir jemand folgende Fragen beantworten?:

- Woher wird die filme.json heruntergeladen? (Gibt es mehr als nur einen Server?)
- Was bedeuten die einzelnen Felder in der filme.json?

Vielen Dank und schöne Grüße

**Comment by claell** [comment]
Vorher könntest du dir noch alterative Frontends ansehen, evtl. reicht das schon: https://mediathekviewweb.de/ oder http://mediathekdirekt.de/
