### ISSUE TITLE
User Agent setting fehlt

### ISSUE THREAD

**Issue by Kettenknecht** [mediathekview/MediathekView#206]
Wo ist denn das Eingabefeld für den User Agent String hin?

**Comment by styroll** [comment]
Den String gibt's seit mehreren Versionen nicht mehr in den Einstellungen…
aber im Config-File "mediathek.xml" kannst du den UA ändern.

Bitte solche Fragen im Forum stellen.

**Comment by styroll** [comment]
Die Option ist jetzt wieder drin (Version 13.1.0).
