### ISSUE TITLE
Download does not work with current JAVA version

### ISSUE THREAD

**Issue by Tom6813** [mediathekview/MediathekView#207]
Hi,

i installed the last version of the Mediathek View and tried to download a film. But whatever i tried, it ended with the following error message:

![java error message](https://cloud.githubusercontent.com/assets/25184070/22036979/b7af67e4-dcf5-11e6-9616-3bc72f8ab256.JPG)

I installed Java new and as well the Mediathek View software. Can someone help me to solve the issue and explain this to me in normal words? 

Thanks for your help

Kind regards,

Tom

**Comment by claell** [comment]
This is the same error message like in #155, but it happens on Windows for you.

**Comment by Tom6813** [comment]
Hi,

 

thanks for the quick response. I found the chat , but as I am not an IT expert and it was related to Ubuntu I thought it is something different. Nevertheless, I do not know how to fix it and I am more an end user of this program. Is there something you can help me with, what exactly I have to install or to run to fix it?

 

Thanks

 

Tom

 

Von: Claudius Ellsel [mailto:notifications@github.com] 
Gesendet: Mittwoch, 18. Januar 2017 10:11
An: mediathekview/MediathekView
Cc: Tom6813; Author
Betreff: Re: [mediathekview/MediathekView] Download does not work with current JAVA version (#207)

 

This is the same error message like in #155 <https://github.com/mediathekview/MediathekView/issues/155> , but it happens on Windows for you.

**Comment by claell** [comment]
Unfortunately I don't know, what might fix this on Windows.

**Comment by Tom6813** [comment]
Thanks for the feedback. Currently i cannot use this software and hope someone has an answer on this.

 

Von: Claudius Ellsel [mailto:notifications@github.com] 
Gesendet: Mittwoch, 18. Januar 2017 10:32
An: mediathekview/MediathekView
Cc: Tom6813; Author
Betreff: Re: [mediathekview/MediathekView] Download does not work with current JAVA version (#207)

 

Unfortunately I don't know, what might fix this on Windows.

**Comment by pidoubleyou** [comment]
There is a problem with your java keystore. The SSL certificate of the url is not trusted.

Follow the steps under section "To configure the Baltimore CyberTrust Root": [https://msdn.microsoft.com/en-us/library/dn135313.aspx](https://msdn.microsoft.com/en-us/library/dn135313.aspx)

**Comment by Tom6813** [comment]
Thanks a lot for the information, i will try it.

Gesendet: Mittwoch, 18. Januar 2017 um 20:31 Uhr
Von: pidoubleyou <notifications@github.com>
An: mediathekview/MediathekView <MediathekView@noreply.github.com>
Cc: Tom6813 <tom99@gmx.net>, Author <author@noreply.github.com>
Betreff: Re: [mediathekview/MediathekView] Download does not work with current JAVA version (#207)


There is a problem with your java keystore. The SSL certificate of the url is not trusted.

Follow the steps under section "To configure the Baltimore CyberTrust Root": https://msdn.microsoft.com/en-us/library/dn135313.aspx
