### ISSUE TITLE
Softwareaktualisierung: Die aktuelle Version kann nicht ermittelt werden

### ISSUE THREAD

**Issue by hebu** [mediathekview/MediathekView#208]
Hallo,

seit Version 13.0.0 bekomme ich beim Programmstart die Fehlermeldung:

> Es ist ein Fehler bei der Softwareaktualisierung aufgetreten. Die aktuelle Version konnte nicht ermittelt werden.

Ich hab eine Protokolldatei erstellt, konnte aber keinen Hinweis auf den Fehler darin entdecken. Ist das Problem vielleicht noch bei anderen Usern aufgetreten?

Viele Grüße,
HeBu

**Comment by claell** [comment]
Ja, das Problem liegt an einer veralteten Java-Version, siehe #191 #201

**Comment by hebu** [comment]
Oh, danke! Sorry für den Doppelpost. Hatte vorher über die Suche nichts dazu gefunden. Ich wusste gar nicht, dass mein Java ein Update braucht, ich muss wohl mal die Aktualisierungseinstellungen bei mir prüfen :(

**Comment by claell** [comment]
Kein Problem :)
