### ISSUE TITLE
Fortschritt des Downloads in der Taskleiste anzeigen

### ISSUE THREAD

**Issue by alex1702** [mediathekview/MediathekView#209]
> Deshalb mein erneuter Vorschlag, weil ich - und möglicherweise auch andere User - das ganz nützlich fände. So braucht man bei laufenden Downloads nicht immer das Programm zu öffnen um den Fortschritt zu sehen.

https://forum.mediathekview.de/topic/97/idee-fortschritt-des-downloads-in-der-taskleiste-anzeigen

**Comment by Nicklas2751** [comment]
Eventuell hilft uns das: http://stackoverflow.com/questions/39192528/how-can-you-send-information-to-the-windows-task-bar-from-java-o-javafx

**Comment by derreisende77** [comment]
Feature ist implementiert im nächsten commit. Getestet unter Windows 7 (32/64bit) und Windows 10 (64bit)
