### ISSUE TITLE
SRT saved in wrong codepage

### ISSUE THREAD

**Issue by mogol07** [mediathekview/MediathekView#210]
I am using Windows 10 PRO with default Russian locale and MediathekView 13.0.1.
When I saved subtitle, ttml has UTF-8 codepage, SRT file has 8bit CP1251 with completely broken text  like 

> so, bitte sch?n, prost!

All symbols which doesn't exist in CP1251, is replaced by question marks. I suspect, it happens, because MediathekView assumes that system codepage is always CP1252, and tries to write in this codepage. 

It's not critical bug, because I have a ttml file in UTF-8, which has correct text and could be converted to SRT with external utility. But it would be great, if it could be fixed in future release.

**Comment by derreisende77** [comment]
it will be fixed in the next update. For the time being you should modify your start script to contain the following setting for java:
**-Dfile.encoding=UTF-8**

Would be nice to hear if it already fixes your problem.

**Comment by mogol07** [comment]
I run MediathekView.exe since I am working with Windows. But I could find a script only for Linux system.

**Comment by Nicklas2751** [comment]
@mogol07 Then right click on the Exe open the Settings and add this to the start arguments. ;)

**Comment by mogol07** [comment]
I try to run 
`MediathekView.exe -Dfile.encoding=UTF-8`
Nothing is changed. SRT files is still wrote in 8bit CP1251
> 18
> 00:01:31,900 --> 00:01:34,100
> <font color="#00ffff">K?nnten Sie auch etwas  </font>

**Comment by zxsd** [comment]
Hhhmmm.  Could something else be going on with your PC, @mogol07?

On this PC the default US "locale" (accessed via "All Settings" -> "Time & Language" -> "Region & Language")  and MediathekView 13.0.0 are active:

![codepage_win10_settings locale](https://cloud.githubusercontent.com/assets/23268595/22403186/c7c14666-e5dd-11e6-8c88-bd8c5fc681d3.PNG)

I have _no_ character-display problems for either file-type, as shown below using both Notepad (SRT) and Notepad++ (TTML). Note also the active code page (red arrow) ... a more primitive codepage would be hard to find {g}.

![codepage_win10](https://cloud.githubusercontent.com/assets/23268595/22403208/68b6ecf6-e5de-11e6-9c8e-3088d0e771e4.PNG)

**Comment by mogol07** [comment]
@zxsd thanks!
After I have used
`"C:\Program Files\Java\jre1.8.0_121\bin\java.exe" -Xmx1256M -Xms256M -Dfile.encoding=UTF-8 -jar "mediathekview.jar"` 
I got an correct SRT file in UTF-8, and also I could save to a file with umlaut in the name.
Before it, ttml file was in UTF-8, srt file was in CP1251 and I couldn't use an German specific letter in file name.
Just for information, my language settings is following: location - Germany, but interface language is Russian, and default input language is US English. It could be little bit confusing.
![image](https://cloud.githubusercontent.com/assets/25278978/22406882/d13a9a02-e65b-11e6-8350-6150eca1428f.png)

**Comment by derreisende77** [comment]
Then you might want to save this trick for future MV releases. The SRT UTF fix is only for SRT. It does not impact the encoding settings for the rest of the applications. You might need to reapply this again in another release. We don't have too many user with such "strange" settings

**Comment by mogol07** [comment]
@derreisende77 for me fixing issue with SRT would be enough. Folder name is not a big deal. Thanks again
