### ISSUE TITLE
Problems with downloads from ARTE

### ISSUE THREAD

**Issue by Exco07** [mediathekview/MediathekView#213]
Hi,
almost every download from the ARTE channel stops after about 2/3 of the playing time.
Do You have any idea, how to solve that problem?

**Comment by Exco07** [comment]
Sorry, war als Neuling etwas verunsichert, da die Anmeldung auf GitHub total in Englisch verlief.
Hier also nochmal auf Deutsch:
Fast alle meine Downloads vom ARTE-Kanal lassen sich nur teilweise abspielen, dann stoppt das Bild plötzlich - meist nach etwa 2/3 der Filmdauer. Auch mehrmaliges Downloaden hilft nicht.

**Comment by claell** [comment]
Hat sich das Problem jetzt erledigt?

**Comment by Exco07** [comment]
Gestern haben die Downloads mit MediathekView funktioniert.

Es ist immer nur der Kanal ARTE, der Schwierigkeiten macht.

Wenn ich die Sendung in der ARTE-Mediathek abspiele und dabei mit dem 
Download-Helper kopiere, klappt es.


Am 03.02.2017 um 10:38 schrieb Claudius Ellsel:

**Comment by claell** [comment]
Ok, hatte nur gefragt, weil du den Issue geschlossen hast.

**Comment by Exco07** [comment]
Das war "Fingertrouble", ich hatte den falschen Button gedrückt - ich 
war in diesem Forum noch nicht so richtig zu Hause.

Sorry:-\


Am 04.02.2017 um 11:06 schrieb Claudius Ellsel:
