### ISSUE TITLE
ARTE-Downloads

### ISSUE THREAD

**Issue by Exco07** [mediathekview/MediathekView#214]
Falls hier ein paar halbfertige Kommentare meinerseits erscheinen sollten, bitte ich um Entschuldigung. Habe mich gerade erst bei GitHub angemeldet.
Mein Problem: Die meisten Downloads vom ARTE-Kanal hören beim Abspielen nach etwa 2/3 der Spielfilm-Dauer einfach auf: Das Bild bleibt stehen.
Gibt's da eine Lösung?

**Comment by Nicklas2751** [comment]
Das Thema wird aktuell im Forum behandelt:
https://forum.mediathekview.de/topic/116/sammelthema-fehler-nach-download-eines-videos
