### ISSUE TITLE
[Wiki] Abo-Download: Auflösung ändern

### ISSUE THREAD

**Issue by electronum** [mediathekview/MediathekView#215]
https://github.com/mediathekview/MediathekView/wiki/Bedienung:-Reiter-Abos
Eine kurze Ergänzung im Wiki wäre nützlich, etwa:

In der Standardeinstellung werden Abos in "hoher Auflösung geladen". Dies wird durch das "Programmset" in den Abo-Einstellungen festgelegt.
* Datei > Einstellungen (F4) > Aufzeichnen und Abspielen > "Set bearbeiten"
* Das entsprechende Set auswählen
* "alle Einstellungen anzeigen" > Tab "Download" > Auflösung > Auflösung wählen

**Comment by styroll** [comment]
Nur als Hinweis: Damit ändert man allerdings nicht nur die Auflösung von Abos, sondern von allen DLs, was nicht alle User schätzen würden.

In der[ FAQ](https://mediathekview.de/faq/#wie-kann-man-bei-abos-die-hd-auflösung-wählen) wird dem Rechnung getragen.

**Comment by electronum** [comment]
* Ich bin nur deswegen darauf gekommen, weil es bei normalen Downloads immer nach der Auflösung gefragt wird (sehr praktisch), bei Abos jedoch die Nachfrage fehlt.
  * Was ist bei mir anders bzw. ich sehe nicht, wie damit alle Downloads betroffen sein können? (Frage nur zu meiner Verständnis)
* Die Anleitung kann ich an dieser Stell ändern, richtig? https://github.com/mediathekview/MediathekViewDE/blob/master/content/anleitung.md  <br />(die Struktur hat sich seit kurzem verändert und die Seite https://github.com/mediathekview/MediathekView/wiki/Bedienung:-Reiter-Abos fehlt mittlerweile)

**Comment by Nicklas2751** [comment]
ja die Stelle zum ändern ist richtig.

**Comment by styroll** [comment]
> ich sehe nicht, wie damit alle Downloads betroffen sein können? 

Die **Grundeinstellung** aller manueller Downloads ist damit auch anders (die Auflösung kann natürlich im DL-Dialog für jeden einzelnen DL geändert werden). Bei den abonnierten Sendungen ist die Auflösung jedoch fix, d.h. von der Auflösungseinstellung im Speichern-Set anhängig.
