### ISSUE TITLE
Verhalten von "Gespeicherten Film (Datei) Löschen" ändern

### ISSUE THREAD

**Issue by lcnittl** [mediathekview/MediathekView#216]
Ich fände es sehr praktisch, kenn man bei einem Film auf `Gespeicherten Film (Datei) Löschen` klickt, dass dann auch die Infodatei (`*.txt`) und etwaige Untertiteldateien gelöscht werden, oder zumindest nachgefragt wird ob sie gelöscht werden sollen. Ansonsten endet man auf kurz oder lang mit einigen Leichenteilen die unzuordbar sein könnten. Wäre dies ein nützliches Feature?

**Comment by derreisende77** [comment]
Da nach einem Download nicht mehr zugeordnet werden kann welche einzelnen Dateien geladen wurden wird dies nicht umgesetzt. Für Aufräumarbeiten ist der User zuständig. Es könnte so passieren das MV aus Versehen falsche Dateien löscht. 
Ich bin daher sogar eher geneigt die Löschfunktion komplett aus dem Client zu entfernen da sie u.a. auch dann überflüssige Verzeichnisse zurücklässt.
