### ISSUE TITLE
build MediathekView from sources - MediathekView aus den Quellen bauen

### ISSUE THREAD

**Issue by martinkg** [mediathekview/MediathekView#217]
Hallo,

ich versuch MediathekView 3.0.1 aus den Sourcen unter Linux Fedora 25 zu erstellen, scheitere aber bereits
am Anfang mit dieser Meldung:

`+ /usr/bin/python3 /usr/share/java-utils/mvn_build.py --gradle
Executing: gradle-local --no-daemon --offline build xmvnInstall
['gradle-local', '--no-daemon', '--offline', 'build', 'xmvnInstall']

FAILURE: Build failed with an exception.

* Where:
Build file '/home/martin/rpmbuild/BUILD/MediathekView-0c4c821267110a0b7504a9a098e25281bf23a721/build.gradle' line: 5

* What went wrong:
Error resolving plugin [id: 'com.github.jk1.dependency-license-report', version: '0.3.5']
> Plugin cannot be resolved from https://plugins.gradle.org/api/gradle because Gradle is running in offline mode

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED`

was bedeutet diese Meldung und wie kann ich das beheben ?

**Comment by Nicklas2751** [comment]
Was ist mvn_build.py?

Du kannst MediathekView wie folgt bauen:
`./gradlew build`

**Comment by martinkg** [comment]
unter Fedora gibt es dazu rpm Macro's, z.B. nehme ich anstatt dem Befehl ./gradlew build
das Macro %gradle_build dahinter verbirgt sich der Befehl:

`/usr/bin/python3 /usr/share/java-utils/mvn_build.py --gradle`

aus dem rpm-Paket javapackages-local-4.7.0-6.1.fc25.noarch

Jedenfalls bin schon etwas weitergekommen:
Aus der Datei build.gradle musste ich erstmal die 2 nicht verfügbaren Plugins löschen.

 -plugins {
 -    id "com.github.jk1.dependency-license-report" version "0.3.5"
 -    id 'edu.sc.seis.launch4j' version '2.0.1'
 -}

Als nächstes fehlt jchart2d und das muss noch packetiert werden :(

**Comment by Nicklas2751** [comment]
Oder du nutzt gradle direkt? Das ganze sollte OS unabhängig funktionieren. Dann hast du auch die richtige Gradle Version. Deswegen ist da ja ein wrapper (gradlew).

**Comment by alex1702** [comment]
Also was auch immer du da rum probierst sieht nicht so danach aus, als ob es direkt uns hier betrifft, bzw. dass wir da eine große hilfe sein könnten.
aktuell kann man es halt nur mit source runterladen und darin mit `./gradlew build` bauen, wenn du da Probleme hast können wir dir gerne helfen.
