### ISSUE TITLE
[Enhancement] Einstellen lassen, ob Geo-Standort beim Eintragen von Abos berücksichtigt wird

### ISSUE THREAD

**Issue by zxsd** [mediathekview/MediathekView#218]
Der Vorschlag ... oder halt 'was ähnliches:

![geo_einstellungen_proposed](https://cloud.githubusercontent.com/assets/23268595/22855617/596539ce-f051-11e6-88e7-0d5b8c553a48.png)

In früheren Versionen wurde beim Eintragen von Abos der Geo-Standort nicht berücksichtigt. Ab MV 13.0.0 ist das Abo-Verhalten diesbezüglich anders geworden.  Obwohl als [Feature](https://mediathekview.de/changelog/13-0-0/) nicht verkündet, glaube ich _**nicht**_, daß das neue Verhalten ein Bug ist. Manche MV-Anwender, u.a., diejenigen die alles 'auto' herunterladen,  mißfallen wohl, sich damit im Nachhinein zu beschäftigen, warum ein Abo-Hit fehlschlug ... konkret mit 403-Fehler endet.  Diese begrüßen bestimmt die Änderung!

Ich wußte das alte Verhalten beim Eintragen von Abos zu schätzen. Ich glaube nicht, dass ich der Einzige bin, wohlgemerkt hier im Übersee der DL-Reiter mir als [EPG](https://de.wikipedia.org/wiki/Electronic_Program_Guide) nebenbei auch Dienst leistet. Anwender wie ich**, ist es jetzt umständlicher geworden.  Der Geo-Standort muß geändert werden (einmal DE, einmal AT, einmal EBU) ... um feststellen zu können, ob geoblockierten Abo-Hits eventuell vorhanden sind. 

Hier ist ein junger Beispiel, von einer Sendung die im [Youtube](https://www.youtube.com/watch?v=UM-GUTGZSSc) zur Zeit Deutschen (bzw., der ganzen Welt ... und mir) zugänglich ist, trotz ORF-Geotargeting.

![alles unter kontrolle](https://cloud.githubusercontent.com/assets/23268595/22855684/1a37cef0-f052-11e6-9503-b556db70819e.PNG)_{Anmerkung: Wegen Browser-Einstellungen muß ich Youtube-Clips erst herunterladen, bevor ich sie anschauen kann; daher das pechschwarze Bild im Browser.}_

Deswegen meine Bitte, bei Gelegenheit (und wenn es nicht allzu kompliziert zu verwirklichen sein sollte) das Abo-Verhalten hinsichtlich dem Geo-Standort konfigurieren zu lassen. Der Grund zusammengefaßt? Was in den Sender-Mediatheken nur als geoblockiert serviert wird, kann oft irgendwo anders gefunden werden ... vorausgesetzt man rechtzeitig weiß, derartige Sendungen zu suchen.***  

---
** Natürlich gilt dies auch allen Anwendern die ggf. von geoblockiertem Inhalt, welcher von einem Abo identifiziert wurde, lernen wollen ... Österreichern die vielleicht DE-Geo suchen würden, und umgekehrt, Deutschen die nach ORF-Geo Inhalt suchen würden.

*** Sendereihen wie _Der Staatsanwalt_, _Der Bergdoktor_ und _Lena Lorenz_ (AT-Geo in der ORF-Mediathek, und weltoffen in der ZDF-Webpräsenz obgleich zeitversetzt) sind nicht Ziel dieser Thematik.

**Comment by zxsd** [comment]
Möglich scheint es, daß das Verhalten nicht vorsätzlich programmiert wurde (siehe: [Pull Request: Abos suchen; Blacklist wird immer ausgewertet](https://github.com/mediathekview/MediathekView/issues/236) und Ende vom https://github.com/mediathekview/MediathekView/issues/223). Wenn ich (als gewöhnlicher User) eine MV-Version mitsamt dieser Verbesserung herunterzuladen weiß, werde ich eine Probefahrt machen.

Da die Implementierung dieser beschriebenen Weiterentwicklung von einigen MV-Anwendern wohl geschätzt werde, und durchaus im Sinne von 'User nicht einschränken' wäre (siehe Bild unten für eine vorhandene, sinngemäße Option), laß ich diese Issue auf. 

![blacklist-geo-option](https://cloud.githubusercontent.com/assets/23268595/23596259/d1ce7450-01f6-11e7-94d4-359fafaa6acf.png)

**Comment by zxsd** [comment]
@xaverW fragte:
> Wären dann schon etwas viel "zerstückelte" Einstellungen der Blacklist

Wie ich im OP schrieb:
> oder halt 'was ähnliches.

![blacklist-geo-option-2](https://cloud.githubusercontent.com/assets/23268595/23607809/5e288c32-0234-11e7-8610-ab630b26e663.png)

**Comment by xaverW** [comment]
habe ich das jetzt richtig verstanden?: Du möchtest die Blacklist für die Abos einschalten, Geo in der Filmliste einschalten und beim Suchen von Abos Geo ausschalten? Also die Funktion Geo soll für die Filmliste <-> Abo getrennt ein-ausschaltbar sein?

**Comment by zxsd** [comment]
Wenn das ehemalige Geo-Abo-Verhalten durch https://github.com/mediathekview/MediathekView/issues/236 wieder hergestellt wurde, ist für mich die Sache erledigt.  Ich nehme an diese Änderung wird heute im Nightly-Build vorhanden sein, wobei ich sie 'probefahren' kann.

> Du möchtest die Blacklist für die Abos einschalten, Geo in der Filmliste einschalten und beim Suchen von Abos Geo ausschalten? 

Wenn Du es so fragst, möchte ich:
1. Die Blacklist für Abos einschalten ... d.h., Häkchen gesetzt bei `Die Blacklist beim Suchen der Abos berücksichtigen (sonst komplette Filmliste)`.
2. Geo in der Filmliste ausschalten, d.h., Häkchen **nicht** gesetzt bei `Filme, die per Geoblocking gesperrt sind nicht anzeigen`. _(Anmerkung:  Ich will Geo-Sendungen sehen können, wenn sie sonst **nicht** durch andere Blacklist-Einträgen (`Sender-Thema-Titel`) rausgefiltert wurden.)_
3. Beim Suchen (Eintragen) von Abos, Geo nicht berücksichtigt wird. _(Anmerkung:  Ein MV-User mit deutschem Standort, der mit österreichischen Geo-Sendungen nicht auseinander setzen will, möchte bestimmt das Gegenteil.)_

![blacklist-settings](https://cloud.githubusercontent.com/assets/23268595/23613259/b8ddea1a-024c-11e7-8e81-b7c22c1e6ae0.PNG)

---

> Also die Funktion Geo soll für die Filmliste <-> Abo getrennt ein-ausschaltbar sein? 

Ja. Wenn das ehemalige Geo-Abo-Verhalten wieder hergestellt ist, glaube ich daß `auto-Modus` User davon Gebrauch machen könnten/würden.  Für mich reicht das ehemalige Verhalten vollkommen aus.

---

Hier eine Zusammenfassung:

1.  Das ehemalige Geo-Abo-Verhalten

`<__system-parameter__dl-geo-abo__>true</__system-parameter__dl-geo-abo__>`

Alle Abo-Hits erscheinen im DL-Reiter; der Geo-Standort wird nicht berücksichtigt.  Also dürften Abo-Hits, die mit 403-Fehler enden würden, auch als DLs vorkommen.  (Diese Abo-Hits dienen nur der Aufmerksamkeit; die müssen im DL-Reiter manuell bearbeitet werden.)

Vorteil. Klugscheißer dürften diese geoblockierten Sendungen demnächst beispielsweise bei YouTube suchen.  (Oft werden derartige Clips einigen Tagen nach deren Erstveröffentlichung vom YouTube gelöscht.  Ohne das geoblockierte Abo-Hit in MV, wüßte der User überhaupt nicht von der Sendung.) 

Nachteil. Im “auto“-Modus versucht MV die geoblockierten Sendung(en) mit herunterzuladen.  Je nach Konfiguration von `<__system-parameter__download-***>` wird letztendlich der jeweilige Eintrag als rosarot (und ohne Dateigröße) erscheinen.  Der Anwender müßte eventuell am darauffolgenden Tag damit auseinandersetzen, und der Eintrag im DL-Reiter manuell bearbeiten.

2.  Das jetzige (MV 13.0.0) Geo-Abo-Verhalten

`<__system-parameter__dl-geo-abo__>false</__system-parameter__dl-geo-abo__>`

Im Einklang mit dem Geo-Standort erscheinen Abo-Hits im DL-Reiter; also der Geo-Standort wird berücksichtigt, indem Abos eingetragen werden.  Abo-Hits kommen nicht vor, die mit 403-Fehler enden würden. 

Vorteil.  Im `auto-Modus` laufen die DLs hinsichtlich Geoblocking fehlerfrei, und der Eintrag im DL-Reiter muss nicht manuell bearbeitet werden.

Nachteil.  Klugscheißer müssen möglich interessante geoblockierten Sendungen extra suchen.  _(Randbemerkung: Mangels passendem Abo habe ich das Abo-Verhalten bei EBU Sendungen nicht kontrollieren können.)_
