### ISSUE TITLE
error: unmappable character for encoding ASCII

### ISSUE THREAD

**Issue by martinkg** [mediathekview/MediathekView#219]
ich bekomme bei Bauen mit den Sourcen folgende Fehlermeldungen:

/usr/bin/python3 /usr/share/java-utils/mvn_build.py --gradle
Executing: gradle-local --no-daemon --offline build xmvnInstall
['gradle-local', '--no-daemon', '--offline', 'build', 'xmvnInstall']
Copying Programm icons.
Copying Sender icons.
:compileJava
/home/martin/rpmbuild/BUILD/MediathekView-0c4c821267110a0b7504a9a098e25281bf23a721/src/main/java/mediathek/filmlisten/ImportFilmliste.java:66: error: unmappable character for encoding ASCII
    // Filmeliste importieren, URL automatisch w??hlen

momentan ändere ich die Datei wie folgend: (Es sind noch einige Dateien mehr ...)
`# fix non ASCII chars`
for file in src/main/java/mediathek/filmlisten/ImportFilmliste.java \
src/main/java/mediathek/filmlisten/FilmeLaden.java \
src/main/java/mediathek/filmlisten/GetModelTabFilme.java \
src/main/java/mediathek/tool/BeobTableHeader.java \
src/main/java/mediathek/tool/DirOpenAction.java \
src/main/java/mediathek/tool/EscBeenden.java \
src/main/java/mediathek/tool/Filter.java \
src/main/java/mediathek/tool/GuiFunktionen.java \
src/main/java/mediathek/tool/GuiFunktionenProgramme.java \
src/main/java/mediathek/tool/HinweisKeineAuswahl.java \
src/main/java/mediathek/tool/MVMediaDBFileSize.java \
src/main/java/mediathek/tool/MVFilmSize.java \
src/main/java/mediathek/tool/MVNotification.java \
src/main/java/mediathek/tool/MVSubtitle.java \
src/main/java/mediathek/tool/MVTable.java \
src/main/java/mediathek/tool/OpenPlayerAction.java \
src/main/java/mediathek/tool/TModel.java \
src/main/java/mediathek/tool/TextCopyPaste.java \
src/main/java/mediathek/mac/MediathekGuiMac.java \
src/main/java/mediathek/mac/OsxIndicatorThread.java \
src/main/java/mediathek/mac/OsxIndicatorThread.java \
src/main/java/mediathek/mac/SpotlightCommentWriter.java \
src/main/java/mediathek/daten/ListePsetVorlagen.java \
src/main/java/mediathek/daten/ListeAbo.java \
src/main/java/mediathek/daten/DatenDownload.java \
src/main/java/mediathek/daten/DownloadInfos.java \
src/main/java/mediathek/daten/DatenAbo.java \
src/main/java/mediathek/daten/DatenMediaDB.java \
src/main/java/mediathek/daten/DatenPset.java \
src/main/java/mediathek/daten/DatenProg.java \
src/main/java/mediathek/daten/ListePset.java \
src/main/java/mediathek/daten/ListeMediaDB.java \
src/main/java/mediathek/daten/ListeDownloads.java \
src/main/java/mediathek/daten/ListeBlacklist.java \
src/main/java/mediathek/update/CheckUpdate.java \
src/main/java/mediathek/update/ProgrammUpdateSuchen.java
do
  native2ascii -encoding UTF8 ${file} ${file}
done

**Comment by Nicklas2751** [comment]
Auch hier würde ich raten, es mal mit dem gradle wrapper gradlew zu versuchen.

**Comment by martinkg** [comment]
momentan mit folgendem Eintrag in build.gradle gelöst (Debian macht es ebenfalls so).
compileJava.options.encoding = 'UTF-8'

**Comment by alex1702** [comment]
Diese Option gibt es in etwas anderer Schreibweise schon in der build.gradle
