### ISSUE TITLE
Filmliste automatisch aktualisieren

### ISSUE THREAD

**Issue by Siggi0904** [mediathekview/MediathekView#220]
Eine zusätzliche Option, abhängig von aktuellen Downloads, Abos und Nutzereinstellungen, welche es erlaubt die Filmliste automatisch zu aktualisieren, wäre super.

Somit könnte man zyklisch (z,B. alle 2 Stunden) die Filmliste aktualisieren.

**Comment by derreisende77** [comment]
Verstehe ich jetzt nicht wirklich. Folgender Text steht bei der RadioBox zum automatischen laden der Filmliste:

> Die Filmliste wird beim Programmstart automatisch geladen (wenn sie
> älter als 3h ist). Zusätzlich kann sie über den Button "Neue Filmliste laden"
> aktualisiert werden. Zum Update werden dann nur noch die Differenzlisten geladen (enthalten
> nur die neuen Filme).

Also ist das Feature vorhanden. Wieso sollte es nun eine zusätzliche Option geben??

**Comment by Siggi0904** [comment]
Die Filmliste wird so aber nicht zyklisch aktualisiert.
Die Option "Neue Filmliste laden" sollte die Option bekommen, auch entsprechender Rahmenbedingungen auch die Filmliste automatisch zyklisch zu aktualisieren.

Das ist gerade dann wichtig, wenn man Mediathekview 24/7 laufen lässt.

**Comment by Georg-J** [comment]
Das halte ich nicht für sinnvoll. 

Fall a) Alte Filmliste nicht löschen, nur erweitern:
Diese Auswahl muss bei jedem Laden neu gesetzt werden. Für das automatische Aktualisieren müsste (und sollte unabhängig davon auf jeden Fall) dieser Punkt zuerst umgesetzt werden.
Wenn man einmal verhindert wäre, die NEUEN Filme durchzublättern, bevor sich die Filmliste wieder automatisch aktualisiert, dann wären danach die ehemals NEUEN Filme nicht mehr als solche zu identifizieren. 

Fall b) Alte Filmliste löschen:
Wenn man einmal verhindert wäre, die Filmliste durchzublättern, bevor sich die Filmliste wieder automatisch aktualisiert, dann wären danach alle ehemaligen Filme ungelesen gelöscht.

**Comment by lookshe** [comment]
Wie soll es ohne regelmäßig automatisches Laden der Filmliste möglich sein, Mediathekview auf einem Headless-System (Homeserver/NAS) zu betreiben, damit einfach automatisiert und regelmäßig bestimmte Abos geladen werden? Es soll Menschen geben, die haben andere Anwendungsfälle, wie bspw. nur die eingerichteten Abos laden und fertig, kein Durchblättern der Filmliste oder ähnliches, sondern einfach nur ihre Abos. Für diese wäre eine solche Option sehr hilfreich, da nicht in regelmäßigen Abständen irgendwo ein Knopf gedrückt werden muss, sondern Mediathekview die Abos einfach so lädt, voll automatisiert und im Hintergrund ohne jegliche Nutzerinteraktion.

**Comment by Nicklas2751** [comment]
Ich stimme da @lookshe zu.

Aktuell lässt sich das mit hilfe von cronjobs bewerkstellingen und dem `-fastauto` Modus. MV so zu erweitern, dass es in zukunft selbständig eine neue Liste zieht halte ich für eine gute Erweiterung die MV wieder ein stück besser macht.

**Comment by Vilem** [comment]
Das ist ein Feature, das ich seit langem vermisse. Ich kann mir nicht vorstellen, wie das mit den Abos von Serien u.ä. überhaupt sinnvoll funktionieren soll, wenn ich dafür einmal am Tag händisch auf den Knopf "Filmliste laden" drücken muss.

**Comment by Kettenknecht** [comment]
+1 für den Featurerequest. Das würde MV so viel besser machen.

**Comment by JonasDralle** [comment]
MV auf einem RPi laufen lassen, Tatort auf NAS speichern, wenn man Zeit hat via Smart TV anschauen....
An sich ein reizvoller Gedanke.

**Comment by sohnkarlsruhe** [comment]
Wäre schön, wenn es realisiert wird

**Comment by derreisende77** [comment]
MV CLI per cron funktioniert. Config file mit filmliste laden auf automatik setzen, MV mit cron regelmäßig starten. Wenn die liste zu alt wird sie aktualisiert ansonsten nicht. Geht bei mir und bekannten schon seit Ewigkeiten.

**Comment by Kettenknecht** [comment]
MV CLI per Cron funktioniert aber nicht, wenn MV GUI bereits läuft. Ich versteh echt nicht, warum es ein Problem ist, eine Option einzubauen, mit der MV GUI automatisch die Filmliste aktualisiert. Wenn die Befuerchtung besteht, dass die Server ueberlastet werden, dann erlaubt man halt nur einen Poll pro Tag.

**Comment by shoeper** [comment]
@Kettenknecht ich denke ein Pull Request ist durchaus willkommen.

**Comment by derreisende77** [comment]
@Kettenknecht und welchen Vorteil bringt ein automatisches neuladen der Liste einmal am Tag ? Und auch dann wirst du MV CLI und GUI nicht parallel betreiben können da die beiden sich dieselben Dateien Teilen. Mal davon abgesehen das es als entweder oder ausgelegt war.
Es ist grundsätzlich kein Problem sowas einzubauen hat aber einfach derzeit keine hohe Priorität...

**Comment by shoeper** [comment]
@derreisende77 er möchte nur MV GUI 24/7 betreiben, dabei werden aber bisher die Listen nicht neu geladen.

**Comment by Vilem** [comment]
Ja, genau so ist es. Wenn man einen dauerhaft (24/7) eingeschalteten Rechner betreibt, sollte die Filmliste einmal täglich automatisch aktualisiert werden, damit Abos funktionieren.

**Comment by Vilem** [comment]
Sehr gut, tausend Dank! Ich hätt's ja selber gemacht, wenn ich Java könnte.

**Comment by Kettenknecht** [comment]
Wooohooo, Dankeschön!

**Comment by Siggi0904** [comment]
Ich hoffe die Kriterien für das automatische aktualisieren sind weitreichender.
Z.B. sollte kein Download laufen und die Abos sollten auch abgeschlossen sein.
