### ISSUE TITLE
Filmliste aktualisieren umbenennen

### ISSUE THREAD

**Issue by Siggi0904** [mediathekview/MediathekView#221]
Besser wäre die Filmliste als Sendungsliste zu benennen.

Das betrifft die Einstellungen und das allgemeine Menü.

**Comment by derreisende77** [comment]
Und wo ist da der Vorteil? Die Liste beinhaltet sowohl Sendungen als auch Filme.
Solche Anmerkungen bitte im Forum stellen, dort werden diese ausführlich behandelt.
