### ISSUE TITLE
Bug Report: Sporadisch erscheinen Abo-Hits nicht im Downloads-Reiter

### ISSUE THREAD

**Issue by zxsd** [mediathekview/MediathekView#223]
Der Rechner hat 4-GB Speicher und x32 BS/Java und MV 13.0.0:

```
C:\>systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 7 Ultimate
OS Version:                6.1.7601 Service Pack 1 Build 7601

C:\>java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) Client VM (build 25.121-b13, mixed mode)
```
---
---

Ab und zu werden Abo-Hits nicht im Downloads-Reiter eingetragen, obwohl sie als solchen identifiziert worden waren.  Ich habe dieses Verhalten nur erlebt, nachdem ich die Filmliste manuell aktualisiert hatte, und MV habe weiterverarbeiten lassen.  Täte ich MV normal herunterfahre, und anschließend neu starten, wird/werden besagte(s) Abo(s) richtig angelegt (und im DL-Reiter angezeigt). Als Workaround kann das (soll) Abo-Hit auch als manueller Download neu angelegt werden; eine Warnung (von einem existierenden DL) wird wie unten abgebildet dann aber nicht gezeigt.

![zdf_abo_erscheint_im_dl-reiter_nicht](https://cloud.githubusercontent.com/assets/23268595/23100361/15a1c872-f64d-11e6-8ea6-07f11b998a54.PNG)

Das Verhalten habe ich ab und zu einige mal in den letzten Wochen erlebt ... und allmählich zur Auffassung gekommen, es als Bug zu melden.  Wenn es vorkommt, kann ich kein Unterschied zu anderen Hits feststellen.  

So schaut's aus (hinsichtlich Warnhinweis) bei einem richtig verarbeitendem Abo-Hit (zeitgleich mit obigem Bild): 

![zdf_abo_erscheint_im_dl-reiter_doch](https://cloud.githubusercontent.com/assets/23268595/23100298/baddd9ae-f64b-11e6-9116-156b09be3ade.PNG)

Die Blacklist ist so eingestellt:

![zdf_abo_erscheint_im_dl-reiter_nicht_blacklist](https://cloud.githubusercontent.com/assets/23268595/23100417/e6411456-f64d-11e6-8590-f01ae2ef6ffb.PNG)

---
---

_{Edit}_ Hier ein SWR-Beispiel vom gleichen Zeitraum; **Notepad++** zeigt downloadAbos.txt:

![swr_abo_erscheint_im_dl-reiter_nicht](https://cloud.githubusercontent.com/assets/23268595/23100842/0ad11c12-f658-11e6-8a55-ef0d69b64954.PNG)

---
---

Könnte ein Zusammenhang mit dem [hier](https://github.com/mediathekview/MediathekView/issues/218) beschriebenem Verhalten vorhanden sein?

**Comment by xaverW** [comment]
Klick auf "Auffrischen" im Tab Download findet die Abos dann? Oder auch nicht und erst nach dem nächsten Programmstart? In den Einstellungen "Abos automatisch suchen" ist aktiv?

**Comment by zxsd** [comment]
> Klick auf "Auffrischen" im Tab Download findet die Abos dann?

Nee.  Mehrmalige Klicks des Knopfes ("Liste der Downloads aktualisieren") bringen auch nichts. Nach dem MV-Neustart ist alles wieder paletti.

> In den Einstellungen "Abos automatisch suchen" ist aktiv?

Ja ... das hätte ich auch erwähnen sollen.

Übrigens sind annähernd 1330 Abos vorhanden.

**Comment by zxsd** [comment]
Dieser Rechner hat 16-GB Speicher, x64 BS/Java und MV 13.0.0:
```
C:\Users\ZxsdUser>systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.14393 N/A Build 14393

C:\Users\ZxsdUser>java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```
---
Im Wesentlichen gleichen alle relevanten Einstellungen von diesem Rechner obigen ... außer zugeteilten Java-Arbeitsspeicher. (Mit diesem heißt es "`-Xms2G -Xmx2G`". Mit dem ersten Rechner lautet es "`-Xms1280M -Xmx1280M`".)

```
.  Programmstart: 19.02.2017 16:28:40
.  ################################################################################
.
.  totalMemory: 2058 MB
.  maxMemory: 2058 MB
.  freeMemory: 1746 MB
.
.  ################################################################################
.
.  MediathekView 13.0.0 [Vers.: 13.0.0]
.
.  ################################################################################
.
.  Java
.  Vendor: Oracle Corporation
.  VMname: Java HotSpot(TM) 64-Bit Server VM
.  Version: 1.8.0_121
.  Runtimeversion: 1.8.0_121-b13
.
.  Programmpfad: C:\Temp\MediathekView\
.  Verzeichnis Einstellungen: C:\Users\ZxsdUser\.mediathek3
```
---
Das Beispiel:

![br_abo_erscheint_im_dl-reiter_nicht_win_10](https://cloud.githubusercontent.com/assets/23268595/23177181/e97c8b18-f833-11e6-8e47-a681be4d97d5.PNG)

**Comment by zxsd** [comment]
Vom neuen Forum ... von einer ausländischen MV-Anwenderin [die schon eine Weile](http://zdfmediathk.sourceforge.net/forum/search.php?st=0&sk=t&sd=d&sr=posts&author=vivi1001&start=40) dabei ist:

* [Abo werden - nur mit Verzögerung angezeigt](https://forum.mediathekview.de/topic/226/abo-werden-nur-mit-verz%C3%B6gerung-angezeigt), 24. Feb. 2017

* [Trotz -angelegtem - Abo erscheint es dort nicht](https://forum.mediathekview.de/topic/212/trotz-angelegtem-abo-erscheint-es-dort-nicht), 22. Feb. 2017

**Comment by zxsd** [comment]
_(Filmliste von 04.03.2017, 08:28 ... PC wie im OP)_ 

Habe eben gemerkt, daß folgende Abo-Hits im DL-Reiter nicht erschienen:

![2 abos die nicht gezeigt werden](https://cloud.githubusercontent.com/assets/23268595/23584334/a3f64f00-012c-11e7-8571-0d3f0d89ff2c.PNG)

Während Folgendes doch gezeigt (und sichtbar schon runtergeladen) wurde:

![1 abo das gezeigt wurde](https://cloud.githubusercontent.com/assets/23268595/23584364/509cfe20-012d-11e7-9122-33f79fc7ee53.PNG)

Der Aufbau von beiden Filmliste-Einträge (ein bißl umformatiert -- damit die Tabulatorzeichen sichtbar sind -- um ein Vergleich zu erleichtern) der _Letzte Spur Berlin_ Sendungen scheinen gleich zu sein ... 

```
163015<Tab>
ZDF<Tab>
03.03.2017<Tab>
<Tab>
Letzte Spur Berlin<Tab>
ZDF-LetzteSpurBerlin<Tab>
Folge 1: Verbrannt - Staffel 6<Tab>
<Tab>
<Tab>
749<Tab>
00:43:31<Tab>
1<Tab>
1<Tab>
Unterweltgröße Nikola Orsic beauftragt Mina, seinen Cousin Vlado zu suchen, der sich mit einem konkurrierenden Clan angelegt zu haben scheint. Orsic macht sich Sorgen - und Mina schöne Augen.<Tab>
21:15:00<Tab>
https://www.zdf.de/serien/letzte-spur-berlin/abgebrannt-104.html<Tab>
<Tab>
<Tab>
<Tab>
<Tab>
<Tab>
1<Tab>
1488572100<Tab>
https://rodlzdf-a.akamaihd.net/none/zdf/17/03/170303_sendung_dls/3/170303_sendung_dls_2328k_p35v13.mp4<Tab>
https://utstreaming.zdf.de/mtt/zdf/17/03/170303_sendung_dls/3/F1011090_hoh_deu_Letzte_Spur_Berlin_Verbrannt_030317.xml<Tab>
86|476k_p9v13.mp4<Tab>
86|3296k_p15v13.mp4<Tab>
mSearch.daten.DatenFilm@d4c513
=========================================================================
163016<Tab>
ZDF<Tab>
10.03.2017<Tab>
<Tab>
Letzte Spur Berlin<Tab>
ZDF-LetzteSpurBerlin<Tab>
Folge 2: Tauschgeschäft - Staffel 6<Tab>
<Tab>
<Tab>
756<Tab>
00:43:43<Tab>
1<Tab>
0<Tab>
Nachdem Mina und ihr Team den Cousin ihres alten Freundes, Nikola Orsic, stellen und für einen Mordanschlag zur Rechenschaft ziehen können, verschwindet das Escort-Girl Vega spurlos.<Tab>
21:15:00<Tab>
https://www.zdf.de/serien/letzte-spur-berlin/tauschgeschaeft-100.html<Tab>
<Tab>
<Tab>
<Tab>
<Tab>
<Tab>
1<Tab>
1489176900<Tab>
https://rodlzdf-a.akamaihd.net/none/zdf/17/03/170310_sendung_dls/2/170310_sendung_dls_2328k_p35v13.mp4<Tab>
<Tab>
86|476k_p9v13.mp4<Tab>
86|3296k_p15v13.mp4<Tab>
mSearch.daten.DatenFilm@a0705e
```

**Comment by Nicklas2751** [comment]
Das ist alles schön und gut aber was steht denn in deiner abo Datei?

**Comment by xaverW** [comment]
danke für die *gute* Beschreibung, habs jetzt endlich mal bei mir nachspielen können werds mir jetzt mal vornehmen, Problem kommt von der Blacklist

**Comment by xaverW** [comment]
Blacklist beim Suchen der Abos verwenden: "Filme in der Zukunft" und "Geo" wird immer ausgewertet, egal ob eingeschaltet

**Comment by zxsd** [comment]
@alex1702 Da soeben "Closed" ... ist diese Version als jüngste Nightly-Version herunterzuladen?

**Comment by xaverW** [comment]
@zxsd über die generelle Einstellung **Blacklist beim Suchen von Abos berücksichtigen** hinaus extra für Geo -> **Geo bei Abos berücksichteigen**??
Wären dann schon etwas viel "zerstückelte" Einstellungen der Blacklist
