### ISSUE TITLE
all java source files are without license headers

### ISSUE THREAD

**Issue by martinkg** [mediathekview/MediathekView#224]
Hi,

I want to build a official package of MediathekView for Fedora Linux.
However, the Packetierung policies do not allow you to packetize files without a license.

All java source files are without license headers. Please can you to confirm the licensing of code and/or content/s and to add license headers.

[FedoraPackagingLicensingGuidelines](https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification)

**Comment by Nicklas2751** [comment]
We have this: https://github.com/mediathekview/MediathekView/blob/master/LICENSE.md
Is this enough or do you really need the license in every file? O.o

**Comment by martinkg** [comment]
We need the license info for each file, because of bundled libraries.

bundled(jcarrierpigeon)
bundled(jtelegraph)
bundled(macwidgets)
bundled(timingframework-classic)
bundled(animation)

**Comment by derreisende77** [comment]
Weil we had/have a debian source Package so i guess there should't be a problem with the current repo. 
Otherwise you can easily find the necessary Info on the net, like:
https://launchpad.net/ubuntu/trusty/+source/mac-widgets/+copyright

**Comment by derreisende77** [comment]
all referenced libraries/classes have been removed from the project with newest merge.
