### ISSUE TITLE
[enhancement] folder res/Icons/Programm/Version-<VERSION>

### ISSUE THREAD

**Issue by Arlon1** [mediathekview/MediathekView#226]
After successfully running through the build process (```./gradlew run```) the folder ```res/Icons/Programm/Version-13.1.0/``` was created. It's containing some PNG files.
I suggest someone adding this path either to ```.gitignore``` or to the versioning system (```git add```)?

This happens both with master (0c4c8212; folder's name is res/Icons/Programm/Version-13.0.1) and develop (52335f61).

**Comment by alex1702** [comment]
yes, i have a fix in a other branch
