### ISSUE TITLE
[enhancement][non-code][Linux] .desktop file

### ISSUE THREAD

**Issue by Arlon1** [mediathekview/MediathekView#228]
I suggest a ```mediathekview.dektop``` file for Linux users.
A Linux could copy this to ```~/.local/share/applications/``` or ```/usr/share/applications/```
```
[Desktop Entry]
Name=MediathekView
Name[de]=MediathekView
Version=13.0.0
Exec=<INSERT_PATH_HERE>/MediathekView/MediathekView.sh
Icon=<INSERT_PATH_HERE>/MediathekView/MediathekView.ico
Terminal=false
Type=Application
StartupNotify=false
Path=
```

**Comment by alex1702** [comment]
this is in the manual https://mediathekview.de/anleitung/#ubuntu-14-04-14-10-15-04
