### ISSUE TITLE
Änderung des Reglers "Zeitraum [Tage]"

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MediathekView#229]
In der vergangenheit hat isch gezeigt, dass es nicht gerade Intuitiv ist, dass beim Regler "Zeitraum [Tage]" das maximale, also Alles vor dem kleinsten kommt. Das vom Nutzer Erwartete Verhalten ist, dass ganz links das minimale ist (also heute) und das maximal mögliche ganz rechts (also "alles").

Wir sollten den Regler so umbauen, dass er diesem Verhalten entspricht.

Aktuelles Beispiel aus dem Forum: https://forum.mediathekview.de/topic/118/wie-lange-kann-ich-r%C3%BCckwirkend-auf-einen-film-zugreifen/13

**Comment by lhaeger** [comment]
Es wäre zudem schön, wenn man min und max gleichzeitig filtern könnte. Spielfilme haben 90 ± 15 Minuten, da würde ich auch gerne die 5-Stunden-Opernmitschnitte auf Arte ausblenden können.

**Comment by styroll** [comment]
> Es wäre zudem schön, wenn man min und max gleichzeitig filtern könnte.

Das kann man (zumindest auf folgendem Weg) schon: Die Minimallänge mit der Blacklist, die Maximallänge in der Seitenleiste (Erweiterte Suche).

**Comment by lhaeger** [comment]
Dannke für den Tipp, aber jedes Mal die Blacklist um zu konfigurieren ist bestenfalls ein hässlicher Workaround.
Ich denke, in der Implementierung hat das schon einen zusammenhang mit dieser Issue: statt den bestehenden Regler umzubauen, wäre es besser, den vorhandenen als "Min" bei zu behalten und einen zusätzlichen "Max" Regler (mit oben beschrieben angepasstem Verhalten) hinzuzufügen:
<img width="227" alt="minmax" src="https://cloud.githubusercontent.com/assets/6388985/23330616/66a81cd0-fb52-11e6-93ff-8a3a36d5b6d6.png">

**Comment by Georg-J** [comment]
> Wir sollten den Regler so umbauen, dass er diesem Verhalten entspricht.

Ich fände es besser, den Regler zu erweitern, dass er diesem Verhalten entspricht. D. h. dass der Zeitraum links von der "1" "alles" bleibt und rechts von der "30" "alles" neu dazukommt.

**Comment by derreisende77** [comment]
Regler wird in 13.1 komplett neu gemacht und ist deutlich intuitiver
