### ISSUE TITLE
Enhancement: MV fehlt ein Feature, um Filme vorzumerken, die man vielleicht später ansehen möchte

### ISSUE THREAD

**Issue by lhaeger** [mediathekview/MediathekView#230]
MV fehlt ein Feature, um Filme vorzumerken, die man nicht gleich ansehen möchte. Das könnte eine Art einfache "Für später merken" Funktion sein, oder auch das Erstellen von selbst definierten Playlists ("Dokus", "Filme", "Kinderfilme", etc.)

**Comment by styroll** [comment]
Ob manuell oder per Abo: Du kannst solche Sendungen in den Downloads-Tab befördern, ohne sie von dort her herunterzuladen. Das Abspielen erfolgt über den Kontextmenü-Befehl "Film (URL) abspielen (vgl. [Thread aus dem alten Forum](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=1&t=1741#p9803)). Bei "manueller" Auswahl im DL-Dialog einfach die Option "Download sofort starten" deaktivieren. Bei abonnierten Sendungen muss in den "Einstellungen –> Erweitert" die Option "Download aus Abos sofort starten" deaktiviert sein (was allerdings die Grundeinstellung ist).

Ich würde es keine gute Idee finden, wenn MV zu einem Player ausgebaut wird. Die Pflege bzw. Aktualisierung der Crawler bindet genug Ressourcen. Eine möglichst aktuelle und vollständige Filmliste ist das Alleinstellungsmerkmal von MV, auf das sollte man sich fokussieren. Für fast alles andere gibt es spezifische und bessere Software.

**Comment by lhaeger** [comment]
Vorab: es geht mir weder darum Alleinstellungsmerkmale aufzugeben, noch einen "Player" aus MV zu machen (wobei  "MediathekView" genau genommen ja bereits ein Synonym zu "Player" ist...).

Sicher kann man die Download-Liste zum taggen interessanter Sendungen  missbrauchen, dazu ist sie aber nicht gedacht und das ganze ist auch recht unintuitiv und - wie oben beschrieben - umständlich Hand zu haben und nicht mit allen Voreinstellungen kompatibel.
Wäre es hingegen möglich Filme mit eigenen Tags zu versehen (und nach diesen Tags filtern/suchen zu können) wäre das weit universeller einsetzbar.

Wenn allerdings die Pflege der Crawler bereits so viele Resourcen bindet, dass so eine relativ überschaubare Erweiterung schon allein deshalb ausgeschlossen wird, sehe ich für MV's Zukunft langfristig schwarz. Natürlich muss man priorisieren, aber ich habe schon zu viele gute Produkte untergehen sehen, weil das Interface vernachlässigt wurde und nicht mit der Zeit ging.

Zum Thema "Für fast alles andere gibt es spezifische und bessere Software": die mag es geben, hilft aber nur weiter, wenn sie entsprechend integriert wird. Das wäre sicher auch eine Option: aus MV heraus auf einfache intuitive Art Playlists in VLC zu befüllen...

**Comment by alex1702** [comment]
Ich finde es eine gute Idee.

**Comment by Nicklas2751** [comment]
Kann man sich als nice to have auf jedenfall mal mit aufnehmen.
