### ISSUE TITLE
Änderung des Reglers "Mindestlänge/Maximallänge"

### ISSUE THREAD

**Issue by lhaeger** [mediathekview/MediathekView#231]
Es wäre wünschenswert, gleichzeitig Minimal- und Maximallänge beschränken zu können.
Ein Weg, dies zu erreichen, bestände darin, den vorhandenen Regler als Min-Regler bei zu behalten und einen zusätzlichen Max-Regler hinzuzufügen, in etwa so:
<img width="227" alt="minmax" src="https://cloud.githubusercontent.com/assets/6388985/23330639/02d8d720-fb53-11e6-8632-6cc29e622987.png">

**Comment by lhaeger** [comment]
PS: dasselbe würde in der Blacklist Sinn machen...

**Comment by styroll** [comment]
> @alex1702 added the enhancement 

Da gibt's schon ein Ticket: https://github.com/mediathekview/MediathekView/issues/195
Deshalb evtl. umbenennen, d.h. auf Blacklist beziehen.

Nur zur Info an die Entwickler: Das kann man (zumindest auf folgendem, eher umständlichen Weg) schon: Die Minimallänge mit der Blacklist, die Maximallänge in der Seitenleiste (Erweiterte Suche).

**Comment by alex1702** [comment]
Oh das hab ich übersehen.
