### ISSUE TITLE
[Enhancement] Download-Server-Namensraum erweitern

### ISSUE THREAD

**Issue by zxsd** [mediathekview/MediathekView#233]
Zur Zeit werden DL-Server (im Sinne folgender Zeile in `MVConfig.java`) ...

`SYSTEM_MAX_1_DOWNLOAD_PRO_SERVER("max1DownloadProServer"), // nur ein Download pro Server - sonst max 2`

... scheinbar nur hinsichtlich der Second-Level-Domain und Top-Level-Domain der URL begutachtet.  Also, von einem beliebigen FQDN (_Fully Qualified Domain Name_, voll qualifizierten Domain-Namen) werden nur die letztere zwei Teilen genommen (z.B., "ORF.AT").

Früher reichte das aus ... wohlgemerkt diese Fähigkeit erst aus MV-User Problem-Meldungen entsprungen war.  Damals schien zwei gleichzeitige DLs bei manchem Sender (beispielsweise ZDF und ARTE.DE) nicht lange, wenn überhaupt, geduldet zu werden.  Zum Teil daraus kam `<maxDownload>`, und eine Weile danach, `<max1DownloadProServer>`.  

Bis die ZDF-Umstellung, hat man gleichzeitig 4 DLs auf einmal laufen lassen können, vorausgesetzt die DL-Geschwindigkeit nicht zu hoch war:
* `http://nrodl.zdf.de/`
* `http://hdvodsrforigin-f.akamaihd.net/`
* `http://media.ndr.de/` (Akamai scheint mindestens seit 2013 hier CDN zu sein.) 
* `http://arte.gl-systemhaus.de/` 

Im laufe der Zeit (nicht mal drei Monaten!) geht so was nicht mehr. Egal wie `<maxDownload>` konfiguriert ist, da kein Default-Wert für `<max1DownloadProServer>` in `mediathek.xml` konfiguriert ist, wird ohne weiteres nur ein DL von den folgenden Servern auf einmal laufen: 
* `https://rodlzdf-a.akamaihd.net/`
* `http://hdvodsrforigin-f.akamaihd.net/`
* `http://mediandr-a.akamaihd.net/`
* `http://arte-a.akamaihd.net/`

Ich schlage vor, der Hostname hinsichtlich der Logik von `<max1DownloadProServer>` auch zu berücksichtigen. Dadurch ermöglicht (wieder) das DL-Verhalten was früher vorhanden war .... und vom Sender/CDN offensichtlich geduldet wurde. Ich nehme an, Sender und CDN (meist Akamai, obgleich 'sichtbar' oder nicht) gemeinsam festlegen, das geduldete Verhalten ... welches vom CDN dann durchgesetzt wird.  

Man könnte den Wert für `<max1DownloadProServer>` auf zwei erhöhen ... meiner Meinung nach aber abzuraten.  Es könnte genauso gut 2 DLs vom gleichen DL-Server (im jetzigen Sinne) ... mit möglichen Gegenmaßnahmen seitens CDN/Sender.

**Comment by zxsd** [comment]
Scheinbar kann man bald vom URL-Präfix `https://rodlzdf-a.akamaihd.net/` Abschied nehmen.  Hoffentlich endgültig ... da man dadurch eventuell viel vom `Ctrl-G` (`Filme als gesehen markieren`) Gebrauch machen müssen.

![zdf_change](https://user-images.githubusercontent.com/23268595/29999597-ba3a2bc2-901c-11e7-8d69-dcc519b0be0e.PNG)

**Comment by derreisende77** [comment]
akamai cdn server werden in 13.3 nicht mehr bei der limit berechnung berücksichtigt.
falls noch andere cdn urls in der filmliste bekannt sind kann ich die gerne ergänzen.
