### ISSUE TITLE
javax.net.ssl.SSLHandshakeException

### ISSUE THREAD

**Issue by almereyda** [mediathekview/MediathekView#234]
```
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	... many more

* Fehlernr: 398001963
* Exception: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
* Fehler(MSearch): ListePsetVorlagen.loadListOfSets
```

Vermutlich betrifft dies die Verwendung von Let's Encrypt Zertifikaten auf https://mediathekview.de/ für den Abruf der Versionsinformationen, da auch ein Fehler über nicht geklappte Überprüfung gemeldet wurde.

Ähnliche Fehler kenne ich von [Hackpad](https://discourse.transformap.co/t/notes-transformap-co/839/4?u=almereyda) und [Hibiscus](http://www.willuhn.de/blog/index.php?/archives/751-Neues-SSL-Zertifikat-fuer-www.willuhn.de-19.01.2017-19.04.2017.html).

**Comment by styroll** [comment]
> @almereyda sagte: Ähnliche Fehler kenne ich von Hackpad und Hibiscus.

Ähnliche Fälle sind bekannt, wenn nicht die aktuellste Java-1.8er-Version oder Java nicht sauber installiert ist, vgl. #207, #205, #191, #201 (alle closed).

**Comment by pidoubleyou** [comment]
Hintergrund der Fehlermeldung ist, dass die JVM dem Zertifikat nicht vertraut. 
Die Aktualisierung von Java kann das Problem lösen, muss aber unter Umständen nicht.

@almereyda Wenn du trotz installierten Java 1.8.0_121 das Problem weiterhin hast, findest du [hier](http://magicmonster.com/kb/prg/java/ssl/pkix_path_building_failed.html), wie du für die JVM ein Zertifikat als vertrauenswürdig hinzufügen kannst.
