### ISSUE TITLE
error: method getUrl in class DatenFilm cannot be applied to given types

### ISSUE THREAD

**Issue by tyrus09** [mediathekview/MediathekView#237]
Hallo.
Unten angefügt ist ein Fehlerlog. Ich habe mir den Stand von mSearch und auch  von mediathekview aus den Git-Repositories ausgecheckt. MSearch lässt sich sauber durchkompilieren. Mediathekview hat aber aktuell ein Compile-Fehler.

Eigende kurze Fehleranalyse:
In MSearch die Klasse DatenFilm hat gar keine Klassenmethode getUrl(DatenFilm f). Es gibt nur eine Methode getUrl(). Also ohne static und ohne Argumentliste.

Daher lässt sich das aktuell nicht mehr kompilieren. Zumindest bei mir. Aber eventuell übersehe ich irgendwas?
Verwendetes System ist Gentoo-Linux. Möchte gerne den Source selber durchkompilieren. Gentoo ist eben eine sourcebasierte Distro. Ein Test mit der Jar basierten vorkompilierten Version von MethiathekView funktioniert. Dabei kann ich auch schon das selber kompilierte MSearch Jar einsetzen und nur noch das ausgelieferte MediathekView.jar einsetzen.

`compile:
    [mkdir] Created dir: /var/tmp/portage/media-tv/mediathekview-9999/work/mediathekview-9999/build/classes
    [javac] Compiling 275 source files to /var/tmp/portage/media-tv/mediathekview-9999/work/mediathekview-9999/build/classes
    [javac] /var/tmp/portage/media-tv/mediathekview-9999/work/mediathekview-9999/src/main/java/mediathek/gui/GuiDebug.java:111: error: method getUrl in class DatenFilm cannot be applied to given types;
    [javac]                     hash.add(DatenFilm.getUrl(f));
    [javac]                                       ^
    [javac]   required: no arguments
    [javac]   found: DatenFilm
    [javac]   reason: actual and formal argument lists differ in length
    [javac] /var/tmp/portage/media-tv/mediathekview-9999/work/mediathekview-9999/src/main/java/mediathek/gui/GuiDebug.java:130: error: method getUrl in class DatenFilm cannot be applied to given types;
    [javac]                 } else if (hash.contains(DatenFilm.getUrl(f))) {
    [javac]                                                   ^
    [javac]   required: no arguments
    [javac]   found: DatenFilm
    [javac]   reason: actual and formal argument lists differ in length
    [javac] /var/tmp/portage/media-tv/mediathekview-9999/work/mediathekview-9999/src/main/java/mediathek/daten/ListePsetVorlagen.java:151: error: cannot find symbol
    [javac]             inReader = new InputStreamReader(conn.getInputStream(), Const.KODIERUNG_UTF);
    [javac]                                                                          ^
    [javac]   symbol:   variable KODIERUNG_UTF
    [javac]   location: class Const
    [javac] /var/tmp/portage/media-tv/mediathekview-9999/work/mediathekview-9999/src/main/java/mediathek/daten/ListePsetVorlagen.java:182: error: cannot find symbol
    [javac]                 return ListePsetVorlagen.importPset(new InputStreamReader(conn.getInputStream(), Const.KODIERUNG_UTF), log);
    [javac]                                                                                                       ^
    [javac]   symbol:   variable KODIERUNG_UTF
    [javac]   location: class Const
    [javac] /var/tmp/portage/media-tv/mediathekview-9999/work/mediathekview-9999/src/main/java/mediathek/daten/ListePsetVorlagen.java:184: error: cannot find symbol
    [javac]                 return ListePsetVorlagen.importPset(new InputStreamReader(new FileInputStream(dateiUrl), Const.KODIERUNG_UTF), log);
    [javac]                                                                                                               ^
    [javac]   symbol:   variable KODIERUNG_UTF
    [javac]   location: class Const
    [javac] /var/tmp/portage/media-tv/mediathekview-9999/work/mediathekview-9999/src/main/java/mediathek/controller/IoXmlLesen.java:51: error: cannot find symbol
    [javac]             try (InputStreamReader in = new InputStreamReader(Files.newInputStream(xmlFilePath), Const.KODIERUNG_UTF)) {
    [javac]                                                                                                       ^
    [javac]   symbol:   variable KODIERUNG_UTF
    [javac]   location: class Const
    [javac] /var/tmp/portage/media-tv/mediathekview-9999/work/mediathekview-9999/src/main/java/mediathek/controller/IoXmlLesen.java:164: error: cannot find symbol
    [javac]             in = new InputStreamReader(new FileInputStream(datei), Const.KODIERUNG_UTF);
    [javac]                                                                         ^
    [javac]   symbol:   variable KODIERUNG_UTF
    [javac]   location: class Const
    [javac] /var/tmp/portage/media-tv/mediathekview-9999/work/mediathekview-9999/src/main/java/mediathek/controller/IoXmlSchreiben.java:120: error: cannot find symbol
    [javac]         out = new OutputStreamWriter(Files.newOutputStream(xmlFilePath), Const.KODIERUNG_UTF);
    [javac]                                                                               ^
    [javac]   symbol:   variable KODIERUNG_UTF
    [javac]   location: class Const
    [javac] /var/tmp/portage/media-tv/mediathekview-9999/work/mediathekview-9999/src/main/java/mediathek/controller/IoXmlSchreiben.java:124: error: cannot find symbol
    [javac]         writer.writeStartDocument(Const.KODIERUNG_UTF, "1.0");
    [javac]                                        ^
    [javac]   symbol:   variable KODIERUNG_UTF
    [javac]   location: class Const
    [javac] /var/tmp/portage/media-tv/mediathekview-9999/work/mediathekview-9999/src/main/java/mediathek/file/GetFile.java:54: error: cannot find symbol
    [javac]         try (InputStreamReader in = new InputStreamReader(getClass().getResource(pfad).openStream(), Const.KODIERUNG_UTF);
    [javac]                                                                                                           ^
    [javac]   symbol:   variable KODIERUNG_UTF
    [javac]   location: class Const
    [javac] /var/tmp/portage/media-tv/mediathekview-9999/work/mediathekview-9999/src/main/java/mediathek/file/GetFile.java:68: error: cannot find symbol
    [javac]             return new InputStreamReader(getClass().getResource(PFAD_PSET_LINUX).openStream(), Const.KODIERUNG_UTF);
    [javac]                                                                                                     ^
    [javac]   symbol:   variable KODIERUNG_UTF
    [javac]   location: class Const
    [javac] /var/tmp/portage/media-tv/mediathekview-9999/work/mediathekview-9999/src/main/java/mediathek/file/GetFile.java:77: error: cannot find symbol
    [javac]             return new InputStreamReader(getClass().getResource(PFAD_PSET_WINDOWS).openStream(), Const.KODIERUNG_UTF);
    [javac]                                                                                                       ^
    [javac]   symbol:   variable KODIERUNG_UTF
    [javac]   location: class Const
    [javac] /var/tmp/portage/media-tv/mediathekview-9999/work/mediathekview-9999/src/main/java/mediathek/file/GetFile.java:86: error: cannot find symbol
    [javac]             return new InputStreamReader(getClass().getResource(PFAD_PSET_MAC).openStream(), Const.KODIERUNG_UTF);
    [javac]                                                                                                   ^
    [javac]   symbol:   variable KODIERUNG_UTF
    [javac]   location: class Const
    [javac] /var/tmp/portage/media-tv/mediathekview-9999/work/mediathekview-9999/src/main/java/mediathek/update/ProgrammUpdateSuchen.java:175: error: cannot find symbol
    [javac]         try (InputStreamReader inReader = new InputStreamReader(connectToServer(), Const.KODIERUNG_UTF)) {
    [javac]                                                                                         ^
    [javac]   symbol:   variable KODIERUNG_UTF
    [javac]   location: class Const
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 14 errors

BUILD FAILED`

**Comment by Nicklas2751** [comment]
Hast du bei beiden den Master branch im Einsatz oder welche Branches hast du Lokal aktuell? Sieht für mich auf die schnelle so aus, als wären da grad zwei unterschiedliche Versionen im Einsatz. Wichtig ist auch, dass du die MSearch Version hast die im MediathekView Gradle angegeben ist.

**Comment by tyrus09** [comment]
Danke das war der Fehler!

Ich hatte in der Tat von beiden den Master branch ausgecheckt. Allerdings braucht der Master branch von Mediathekview den Release 2.1.1 von MSearch. Habs nun korrigiert und es kompiliert sauber durch. :)
