### ISSUE TITLE
Nightlies 13.1 haben defekte filme.json

### ISSUE THREAD

**Issue by Siggi0904** [mediathekview/MediathekView#239]
In den aktuellen Nightlies zur Version 13.1 fehlen die Zeilenumbrüche wodurch alle Daten in einer Zeile stehen.

Bitte für die Kompatibilität korrigieren.

**Comment by derreisende77** [comment]
Das sind keine Defekte sondern Absicht. Pretty Printing ist deaktiviert. Sie sind zum lesen durch die Software gedacht und es spart Platz.  Umformatieren ist aber einfach. 
Und für welche Kompatibilität außer für unsere SW sollen wir sorgen?
