### ISSUE TITLE
Download hängt jedes 2te/3te mal

### ISSUE THREAD

**Issue by manjarooo** [mediathekview/MediathekView#241]
Hallo,
seit dem Update auf Version 13.0 (kurz nach Release) habe ich das Problem, daß immer mal wieder der Download der Filmliste im letzten viertel bzw. kurz vor Ende hängen bleibt.
Ich muß dann das Programm komplett schließen (das kleine "X" zum abbrechen neben dem Fortschrittsbalken funktioniert nicht) und die "filme.json" löschen, danach läuft der Download wieder durch, zumindest bis zum nächsten oder übernächsten Start, dann hängt der Download wieder.

Ich habe auch bereits versucht den kompletten .mediathekview-Ordner mit allen Einstellungen zu löschen, leider mit dem gleichen Ergebnis: Erst läuft der Download fehlerfrei durch, nach dem zweiten oder dritten Programmstart wieder nicht mehr.

Habe das Problem auf mehreren Rechnern, alle mit Manjaro Linux mit dem Kernel 4.4, der neueste Java Version 1.8.0_121, und Cinnamon- bzw. Mate-Desktop. Die aktuell installierte MediathekView Version ist die 13.0.2.
Mit der 12er Version hatte ich dieses Problem übrigens nicht!

Schöne Grüße! :-)

**Comment by styroll** [comment]
> @manjarooo sagte: habe ich das Problem, daß immer mal wieder der Download der Filmliste im letzten viertel bzw. kurz vor Ende hängen bleibt.

Du musst dem Programm bzw. Java mehr RAM zuweisen, vgl. [neues Forum](https://forum.mediathekview.de/post/894) bzw. [Anleitung](https://mediathekview.de/anleitung/#parameter-die-die-einstellungen-der-javavm-ändern) und ausführlich im [alten Forum](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=1&t=2143).

Weitere Fragen bitte im Forum stellen…

**Comment by manjarooo** [comment]
OK, danke, werde mir das mal genauer durchlesen...

Lustigerweise funktioniert der Download, seit dem ich den Original-Post geschrieben hatte, auch nach mehrmaligem Wiederholen auf einmal auf allen Rechnern wieder problemlos. Ich hatte also seitdem keinen einzigen Hänger mehr, obwohl ich zuvor wochenlang auf mehreren Rechnern (darunter auch einer mit viel Arbeitsspeicher) dieses Problem immer wieder hatte. Komisch.
Ist mir ein jetzt auch wenig peinlich ... ;-)

Aber nochmal vielen Dank für den Link und den Hinweis!
