### ISSUE TITLE
Suche in allen Sendern

### ISSUE THREAD

**Issue by maxholgasson** [mediathekview/MediathekView#242]
Hallo,

ist es nicht möglich gleichzeitig in allen Sendern zu suchen? Ich habe beim Filter im Feld "irgendwo" mein Suchbegriff eingegeben, aber bin immer auf den einzelnen Sender beschränkt, oder muss Sender für Sender durchgehen.. was ziemlich mühsam ist. Kann man irgendwie alle Sender auf einmal durchsuchen lassen?

**Comment by styroll** [comment]
Wenn kein Sender selektiert ist, wird auch bei allen Sendern gesucht.

Bitte solche grundlegenden Fragen im Forum stellen.
