### ISSUE TITLE
Blacklist, Reguläre Ausdrücke

### ISSUE THREAD

**Issue by hnebel569** [mediathekview/MediathekView#243]
Erst mal: Tolles Programm. Vielen Dank.
Ich habe gerade die Antwort zu dem o.g. Thema gelesen, habe aber eine Frage.
Lässt sich die Suche mit Regulären Ausdrücken auch auf die Thema-Spalte erweitern?
![grafik](https://cloud.githubusercontent.com/assets/26691226/24332412/73166ce6-1246-11e7-854a-6b659db28050.png)
In der Grafik ist so ein störender Fall, der leider öfter vorkommt und vernünftig nur über die Thema-Spalte zu lösen ist.
Gruß Hans

**Comment by pidoubleyou** [comment]
Du kannst "nur" Titel/ und Thema gleichzeitig mit regulären Ausdrücken filtern, indem du diese in das Feld "Thema oder Titel" einträgst.

Details findest du in der Hilfe zu der Blacklist, die du in den Blacklist-Einstellungen unter dem Button mit dem Rettungsring erreichen kannst:
![grafik](https://cloud.githubusercontent.com/assets/22942659/24335358/aee96de2-127b-11e7-8e90-d99c84680052.png)

Bitte solche grundlegenden Fragen zukünftig im Forum stellen.
