### ISSUE TITLE
Feature Request: automatische Aufnahme des Livestreams

### ISSUE THREAD

**Issue by mithrendal** [mediathekview/MediathekView#244]
Einfache Möglichkeit eine automatische Aufnahme, wie bei einem Videorecorder aus den Livestreams zu programmieren, da nicht alle Sendungen in der Mediathek zur Verfügung gestellt werden.

Eingabeparameter wären:
Sender, Datum, Startzeit, Dauer, Wiederholung (tägliche, wochentäglich, etc.)

Momentan ist das Aufnehmen aus Livestreams nur per manuelles Klicken möglich.

**Comment by derreisende77** [comment]
Werde den request erst mal nicht realisieren, da MV kein online tv recorder werden wird. Wie der Name schon sagt soll mit dem Programm gesehen werden. Für den use case sind sicherlich andere und besser geeignete Tools schon vorhanden.
