### ISSUE TITLE
Bug: Download Regulierung (Anzahl der Downloads und Max. Bandbreite je Download) funktioniert nicht mehr korrekt.

### ISSUE THREAD

**Issue by FL140** [mediathekview/MediathekView#245]
Servus,
Vorweg, danke für die Übernahme und Neuaufstellung des Projekts!

Nach dem Umstieg von 12.x auf 13.0.1 funktioniert die Regulierung der Downloads leider nicht mehr richtig.

In der alten Version wurde die Regulierung direkt im Menü eingestellt und sofort übernommen. Seit dem die Regulierung auf der linken Seite in einem eigenen Frame untergebracht ist wird die Änderung der Download Bandbreite pro Download und die Anzahl der Downloads nicht direkt übernommen. Das ist gerade bei einer ständig schwankenden Internet Verbindung (UMTS/LTE) aber machmal echt wichtig, sonst geht gar nichts mehr.

Bitte um Behebung (funktional so wie es bei der Menü Version war)!
DANKE!

Platform: Linux Debian Testing
MediathekView Version: 13.0.1

**Comment by xaverW** [comment]
bei mir klappt das schon (Version 13.0.1, 13.0.2), eben getestet. sowohl Anzahl als auch Bandbreite. Allerdings werden/wurden bereits gestartete Downloads nicht gestoppt wenn die Anzahl zurückgedreht wird.
