### ISSUE TITLE
ORF-Untertitel haben geändertes Format

### ISSUE THREAD

**Issue by Georg-J** [mediathekview/MediathekView#246]
Sender: ORF
Sendung: Die Millionenshow
Datum: 03.04.2017 20:15
URL: http://api-tvthek.orf.at/uploads/media/subtitles/0008/85/3093fc141c2fc9dfb04610c33431ae0da43b8e41.xml
Fehler: 46231470
Unparseable date: "00:00:00:02"
komplette Zeile: `<p begin="00:00:00:02" end="00:00:01:02" tts:textAlign="right">*</p>`

So wie es aussieht, werden die Zeiten statt wie bisher in Sekunden.Zehntelsekunden nun in hh:mm:ss:ff angegeben. 

Die xml-Datei wurde erfolgreich als ttml-Datei gespeichert. Es wurde daraus keine srt-Datei erstellt. Bei den Systemmeldungen gab es keine Fehlermeldung.

**Comment by zxsd** [comment]
In meiner Erfahrung kommt gelegentlich vor, daß die Ausgangsdateien (also die vom Sender ins Netz gestellte XML- oder TTML-Datei) eine kleine Macke aufweisen, welche die Konvertierung durch MV stört.  

_Randbemerkung: Die MV-Logik wurde meiner Ansicht nach verallgemeinert, um mit den veröffentlichten UT-Dateien von allen gängigen Sendern (darunter SRF, NDR, SWR, BR, usw. ... und ORF) zurechtzukommen._

Wenn ein Problem auftauchen sollte, kann man durch [SubtitleEdit](https://github.com/SubtitleEdit/subtitleedit/releases) immer (meiner Erfahrung nach) selbst eine brauchbare SRT-Datei erzeugen.  Es reicht die TTML-/XML-Datei in SubtitleEdit zu öffnen, und dann diese als SRT-Datei zu speichern (File | Save as...). @Georg-J von Deiner Link habe ich diese Datei runtergeladen (mit `.txt` um diese hier heraufladen zu können):
[3093fc141c2fc9dfb04610c33431ae0da43b8e41.xml.txt](https://github.com/mediathekview/MediathekView/files/904736/3093fc141c2fc9dfb04610c33431ae0da43b8e41.xml.txt)

Mittels SubtitleEdit 3.5.1 als SRT-Datei:
[3093fc141c2fc9dfb04610c33431ae0da43b8e41.srt.txt](https://github.com/mediathekview/MediathekView/files/904738/3093fc141c2fc9dfb04610c33431ae0da43b8e41.srt.txt)

@Georg-J mit umbenannte SRT-Datei geht's? 
 
---
Nach Stichproben von der jungen Zeitspanne kommt MV mit 'konformen' ORF UT-Dateien zurecht:

```
20170324  |  Unterwegs in Österreich_ Die Bilderwelt des Wolfgang Fuchs
20170326  |  Pressestunde mit Umweltminister Andrä Rupprechter (ÖVP)
20170330  |  Die Barbara Karlich Show_ Wir Alten wohnen heute wie die Jun
20170402  |  IM ZENTRUM_ SOS im Mittelmeer - Wie voll ist das europäische
20170404  |  Willkommen Österreich mit Stermann & Grissemann
```

**Comment by Georg-J** [comment]
Danke für den Hinweis auf SubtitleEdit. Auch die aktuelle Version 3.5.2 erzeigt die gleiche srt-Datei. Leider ist die Umrechnung von Frames in Millisekunden "fehlerhaft" - um nicht zu sagen "nicht vorhanden".
Aus `begin="00:30:00:00" end="00:30:01:23"` wird `00:30:00,000 --> 00:30:01,023`, d. h. aus einer Einblendungsdauer von 1 23/25 Sekunden = 1,920 Sekunden werden 1,023 Sekunden. Abgesehen davon funktioniert diese Untertiteldatei.

Da MV mit allen angebotenen UT-Dateien zurechtkommen sollte, wäre eine Erweiterung von TimedTextMarkupLanguageParser wünschenswert, falls ein neues UT-Format dauerhaft verwendet wird. Jetzt warten wir erst einmal die UT der nächsten Millionenshow übermorgen ab.

**Comment by zxsd** [comment]
Wieder was gelernt \<g\>. Ich habe gewagt, ein begründetes Issue beim [SubtitleEdit](https://github.com/SubtitleEdit/subtitleedit/issues/2334) einzureichen.

**Comment by Georg-J** [comment]
Die Nicht-Umrechnung in Millisekunden hatte ich [dort](https://github.com/SubtitleEdit/subtitleedit/issues/2329) schon gemeldet. Tatsächlich liegt dieser Bug an der "zeitlosen" Zeile `<p begin="" end="" />`. Entfernt man diese, wird umgerechnet von 1 23/24 Sekunden zu 1,959 Sekunden. 

In dieser Datei kommt leider kein ':24"' vor, so dass ich einfach die Bildwiederholrate 25 als Maß genommen habe. Damit vermeide ich auch die Gefahr, dass 24/24 zu 1000 Millisekunden werden können und möglicherweise in 0,1000 Sekunden umgerechnet werden.

**Comment by Georg-J** [comment]
Zweifache Entwarnung:
- Meine ORF-UT bis einschließlich vorgestern (Montag) wurden alle von MV automatisch in SRT umgewandelt.
- Die Umwandlung durch SubtitleEdit von :23 in 23/24 wurde ohne gleichnamige Videodatei gemacht. Mit mp4-Video wandelt SubtitleEdit (nun entsprechend der Bildwiederholrate 25) :23 in 23/25 um.
