### ISSUE TITLE
Livestream-Url beider RBB-Streams nicht mehr aktuell

### ISSUE THREAD

**Issue by YggdrasiI** [mediathekview/MediathekView#247]
Hallo, 

auf den jetztigen Links des RBB ist nur noch ein Testbild mit Hinweis auf neuere Urls zu sehen. Wie und ob die neueren Urls lauten konnte ich bisher nicht ermitteln. Vielleicht seid ihr da dank Übung auch schneller ;)

Gruß Yggdrasil

**Comment by pidoubleyou** [comment]
Danke für den Hinweis, werde ich korrigieren.
Ich schließe den Issue, weil ich ihn in der betroffenen MV-Komponente neu erfasst habe.
