### ISSUE TITLE
Sendung zerstückelt - Untertitel identisch

### ISSUE THREAD

**Issue by Georg-J** [mediathekview/MediathekView#248]
Aktuell gibt es zu einer Sendung des ORF (Thema = “Romy 2017 - Der Österreichische Film- und Fernsehpreis”) 15 Stücke mit eigenen Titeln. Zu jedem Titel gibt es eine eigene Untertiteldatei, die aber alle identisch sind und die UT der kompletten Sendung enthalten. Online kann man [dort](http://tvthek.orf.at/profile/Romy-2017/13887132/Romy-2017-Der-Oesterreichische-Film-und-Fernsehpreis/13927243) sehen, dass die UT zum jeweiligen Stück passen.

Gibt es online unterschiedliche UT-Dateien oder gibt es jeweils eine Startzeit, mit der online der richtige Einstieg in die UT gelingt?

Vor zwei Tagen hatte ich obiges schon im [Forum](https://forum.mediathekview.de/topic/359/sendung-zerstückelt-untertitel-identisch) gefragt, aber keine Reaktion erhalten. Da der Link zur Sendung nur noch zwei Tage funktioniert, erlaube ich mir diesen Eintrag hier. 

Ich vermute, dass irgendwo die Startzeit zu den jeweiligen Schnipseln steht. Dann könnte vielleicht VLC den richtigen Einsprung schaffen oder die UT-Datei wäre anzupassen (Info am Dateibeginn oder Filterung und Umrechnung der UT-Zeiten).

**Comment by zxsd** [comment]
Aus Sicht eines hörenden MV-Anwenders ... der Untertitlung (UT) schätzt.

Wenn der ORF-Player Deine Bedürfnisse nicht erfüllt, bis was besseres vorhanden ist, könntest Du [SubtitleEdit](https://github.com/SubtitleEdit/subtitleedit/releases) als Player einsetzen. Einfach eine Kopie der von MV-stammenden SRT-Datei (TTML geht auch) in SubtitleEdit erst öffnen. Die Video-Datei des ersten Schnipsels öffnen, und dann den Anfangspunkt in der Untertitlung suchen.  (Zugegeben, für Hörlosen schwer ...) Die vorherigen Zeilen löschen, und dann der Schnipsel vollständig anschauen. Wiederholen.

(Wichtig "Video --> Un-dock video controls" selektieren! Mit Alt-A und Alt-Eingabe, bzw. Alt-Enter, experimentieren.)

Wenn Du Mac-Anwender bist, geht's leider nicht.  [Die Applikation](http://www.nikse.dk/SubtitleEdit) soll aber auch unter Linux laufen ...

> Subtitle Edit wurde speziell entwickelt, um Sie mit Ihrem vorhandenen Filme ohne verschwenden zu viel Zeit bearbeiten und erstellen Untertitel oder einfach synchronisieren. Die Oberfläche des Programms ist sauber und sehr intuitiv. So können Sie die Start-und Endzeit, Dauer und jede Zeile der Untertitel bearbeiten, fügen Sie einen anderen Untertitel, kopieren Sie ausgewählte Elemente als Text in die Zwischenablage, aufteilen oder zusammenfügen Linien, sowie wie für eine Schreibmaschine oder Karaoke-Effekt, unter anderem . Es ist auch möglich, alle Zeiten einstellen, die Untertitel zu synchronisieren, um die entsprechenden Filme während der Vorschau-Clips in eine integrierte Media-Player, lassen Sie Subtitle Edit automatisch häufige Fehler zu beheben in den ausgewählten Linien übersetzen Text via Google Translate sowie so verwenden Sie die Undo, Redo-und Suchfunktionen. ([Quelle](http://softpicks.com.de/software/Multimedia/Video/Subtitle-Edit_de-359805.htm))

(Anmerkung: Du könntest Schnipsel-eigene UT-Dateien während der Abspielvorgang erzeugen, wenn die Sendung aufzubewahren ist.)

**Comment by Georg-J** [comment]
Den ORF-Player kann ich leider nicht benutzen. Wenn jeder Benutzer das mit SubtitleEdit manuell für die eigenen UT-Dateien macht, ist das insgesamt ein Riesenaufwand verglichen mit dem Programmieraufwand, die vermutlich vorhandene Startzeit-Info auszulesen und an den UT-Link in der Datenbank zu hängen und nach dem Download damit die UT-Datei anzupassen.

Wenn die einzelnen Schnipsel lückenlos sind und man die richtige Reihenfolge kennt, könnte man auch ohne die Startzeit-Info zu einer Lösung kommen:

1. Möglichkeit: Nachträglich die UT-Dateien anpassen. SubtitleEdit 3.5.2 kann das leider nicht. Wenn ich alle 15 Videodateien in die Anwendung ziehe, sagt sie mir leider "Sie können nur eine Datei ablegen". 

1. Möglichkeit: Alle Schnipsel aneinanderhängen.

**Comment by zxsd** [comment]
Wie ich schrieb, kann man mittels SubtitleEdit das Ziel erreichen.  Dazu muß man in der richtigen Weise vorangehen.  Mein Vorschlag die "Video-Datei des ersten Schnipsels öffnen" resultierte irgendwie in das Ziehen "alle 15 Videodateien in die Anwendung."  \<Hunhhh?\> Die Handhabung von SubtitleEdit hat mit MediathekView nichts zu tun ... aber Du wirst das lernen müssen, um Dein Ziel zu erreichen. 

Wenn Du damit auseinandersetzen tätest, würdest Du merken, in SubtitleEdit die restlichen Zeilen automatisch neu durchnummeriert werden wenn einige Zeilen gelöscht werden. Die Zeiten werden eventuell auch angepaßt. 

Deswegen hieß mein Vorschlag:

> Die Video-Datei des ersten Schnipsels öffnen, und dann den Anfangspunkt in der Untertitlung suchen. ... Die vorherigen Zeilen löschen, und dann der Schnipsel vollständig anschauen. Wiederholen.

Nachdem Du `OrfSchnipsel1.mp4` angeschaut hast, könntest Du auch dessen Zeilen ausschneiden, diese in eine neue Datei einfügen, und die Datei als `OrfSchnipsel1.srt` speichern.  Oder sie löschen.  Sobald die Zeilen weg sind, werden die Verbleibenden automatisch durchnummeriert.  Dann `OrfSchnipsel2.mp4` laden, anschauen ... und beliebig oft wiederholen.

---

Mit [avidemux](http://avidemux.sourceforge.net/download.html) könntest Du eventuell alle Schnipsel zusammenfügen ... vorausgesetzt ORF alle in Netz stellt (und die richtig vom ORF geschnitten wurden).  Mit der Sendung _Dancing Stars_ z. B., scheint das nicht der Fall zu sein.  Meiner Meinung nach ist avidemux schwieriger als SubtitleEdit anzuwenden.

---

Als MV-Anwender würde ich aber die Programmierungsaufwand der von Dir gewünschten Funktionalität nicht als geringfügig schätzen.  Als vor etwa zwei Jahren das ORF damit angefangen hat, Sendungen dermaßen zu zerstückeln, wie _Am Schauplatz_ und _Am Schauplatz Gericht_, verzichtete ich einfach darauf.  In letzter Zeit werden diese Sendungen wieder 'ganz' veröffentlicht ... und ich schaue sie ab und zu wieder an.

**Comment by derreisende77** [comment]
Also MV ist ein Hilfsprogramm zum suchen und Downloaden von Filmen aus der Mediathek. Zusätzlich bieten wir noch das Laden der Untertitel an und konvertieren sie in ein Format, damit Anwender mittels VLC damit klar kommen. 
MV ist kein Video- und Untertiteleditor. 
Die geforderte Funktionalität ist keineswegs so trivial wie es hier geschildert wird. Zumal man nicht vergessen darf das das Feature ja auch unter Linux, windows und Mac OS X funktionieren soll. Und das mittels Java. 
Von daher sehe ich absehbar keine reelle Chance den Wunsch zu implementieren. Ich werde auch keine Zeit darauf verwenden. 
Sollte jemand wirklich Interesse an diesem Feature haben kann er gerne einen fertigen pull request einreichen und wir werden das integrieren wenn oben genannte Anforderungen erfüllt sind.

**Comment by Georg-J** [comment]
Es geht erst einmal um die Frage, wie es der ORF macht - siehe 2. Absatz des Eingangsposts.

**Comment by derreisende77** [comment]
Und hier geht es um MediathekView-Fehler und nicht wie ein Sender seine Dateien zerstückelt ;) Und daher mache ich diesen Post erst mal dicht. 
Solche Sachen gehören in das Forum und falls dort niemand antwortet wird wohl keine Hilfe möglich sein.
