### ISSUE TITLE
Bug: ORF-Sendung zerstückelt - MV lädt falsche Untertitel-Datei

### ISSUE THREAD

**Issue by Georg-J** [mediathekview/MediathekView#249]
Sender: ORF
Datum: 30.07.2017
Zeit: 09:00:00
Thema: ZIBB 9:00
Website: http://tvthek.orf.at/profile/ZIB-900/71256/ZIB-900/13928131

Titel 2: EU beschließt Leitlinien für "Brexit"
falsche UT via MV: http://api-tvthek.orf.at/uploads/media/subtitles/0009/94/04fca649e7c130f19a3fdd9149da2b69ed2898ca.xml
richtige UT zum Thema: http://api-tvthek.orf.at/uploads/media/subtitles/0009/94/cbbd2e0f0c9e81d25f2ceb431c79161bca18222b.srt

Titel 3: Hochschulstreit: Orban lenkt nicht ein
falsche UT via MV: http://api-tvthek.orf.at/uploads/media/subtitles/0009/94/04fca649e7c130f19a3fdd9149da2b69ed2898ca.xml
richtige UT zum Thema: http://api-tvthek.orf.at/uploads/media/subtitles/0009/94/779578e44ef9be65e06ec58d7ba5e9c1314b4cc0.srt

Man beachte, dass die URL "falsche UT via MV" bei den unterschiedlichen Titeln identisch ist. "richtige UT zum Thema" haben verschiedene URLs.
Bitte fixen.

**Comment by derreisende77** [comment]
Sollten die Einträge in der Filmliste falsch sein, bitte ein issue bei MServer aufmachen. Dies ist **kein** Fehler von MediathekView.
