### ISSUE TITLE
[enhancement] Please add hirachical categories

### ISSUE THREAD

**Issue by elypter** [mediathekview/MediathekView#250]
the thema drop down menu is pretty convoluted if you just want to browse for example nature documentaries. the best way to implement this would probably be a tagging system and a tree view to group the tags into bigger categories.

**Comment by Nicklas2751** [comment]
And how should we know which Thema we should group under which category? We just read the Thema directly from the TV stations.

I don't see a practicable way to implement this feature.

**Comment by elypter** [comment]
the zdf mediathek for example as Rubriken that groupes shows and videos. unfortunately the new one is much less detailed. it used to have subcategories. maybe this information still exists hidden somewhere

**Comment by elypter** [comment]
why was this closed?

**Comment by derreisende77** [comment]
Because we won‘t implement it. Therefore it does not make sense to keep it open.
