### ISSUE TITLE
[enhancement] please add an add to playlist button

### ISSUE THREAD

**Issue by elypter** [mediathekview/MediathekView#251]
it would be great to have the option to enqueue a video instead of playing it immediately in a second player window

**Comment by derreisende77** [comment]
How would you detect that VLC has finished playing? MV starts the VLC process and then VLC does not shut down after playing the video.
Therefore the second video would never get played as there wouldn´t be any detection of an ending of the first one.

**Comment by Georg-J** [comment]
@elypter You have this option already in VLC. Select "Allow only one instance" and "Enqueue item into playlist in one instance mode".

**Comment by pidoubleyou** [comment]
@elypter you have to modify the VLC parameters used in the set 'Abspielen'. Just add the options `--started-from-file --playlist-enqueue` and all videos are enqueued if a vlc instance is running.

**Comment by elypter** [comment]
@pidoubleyou thanks, it works as intended. it would still be great though to have an additional button for different ways of playing (enque, convert, separate player,...) - a customizable toolbar would be great for this and an official set that can be downloaded from within the application.

@Georg-J while this works fine i think it is better style to use commandline options so people are not forced to change global settings of another application
