### ISSUE TITLE
[Enhancement] Zeitangaben des Aufbauens vom Mediensammlung-Index merken und anzeigen

### ISSUE THREAD

**Issue by zxsd** [mediathekview/MediathekView#252]
Zum Beispiel, wie unten abgebildet:

![mediensammlung001](https://cloud.githubusercontent.com/assets/23268595/25927822/8ed953c8-35c6-11e7-9767-641181781678.PNG)

Wenn mehrere Instanzen von MV gleichzeitig im Betrieb sind, kann vorkommen daß eine Sendung mehrmals aufgenommen wird.  Um so was vorzubeugen, spielt die MediensammlungDB der jeweiligen Instanz eine entscheidende Rolle.  Da die jüngsten Einträge dabei am wichtigsten sind, wäre das Alter der MediensammlungDB wissenswert.

Anmerkung: Das Aufbauen eines neuen Index verbraucht bis 10x soviel Zeit unter Windows als unter Linux; mit MacOS habe ich keine Erfahrung.  (Ich verwende hauptsächlich Windows ... und kann mehrere Instanzen gleichzeitig im Betrieb haben, v.a. um DLs besser steuern zu können.)

**Comment by derreisende77** [comment]
Hmm eigentlich wurde MV nicht dafür programmiert um mehrere Instanzen zu nutzen. Muss mir ein paar Lösungen für die Zukunft einfallen lassen.
Bzgl Performance unter Windows: das ist ein Problem der JVM. Da gibt es mehrere Bug Reports dazu. Da kann ich nicht wirklich viel dagegen machen außer zu testen mit der neuesten Java Version ob sie das Problem zufällig behebt.

**Comment by zxsd** [comment]
Ich hätte präziser schreiben gesollt.  Die MV-Instanzen laufen auf eigenen PCs ...  Ab und zu tue die Dateien (`history.txt` und `downloadAbos.txt`) jedes Rechners manuell verwalten, bzw., zusammenfügen, damit die Dateien meiner Hauptinstanz wieder maßgebend (_authoritative_ auf Englisch) wird.  Eine MV-Instanz wird SRF-Sendungen gewidmet, und hat nur SRF-Abos.  Die anderen haben alle die gleichen Abos; wenn ich nicht aufpasse, werden Abos von letzteren Instanzen nicht nur einmal runtergeladen.

Wenn es möglich wäre, zum Beispiel, mehrere Instanzen wie abgebildet laufen zu lassen, wäre es aus meiner Sicht spitzenmäßig.  (Eine Windows-Instanz ist Hauptinstanz um auf SMB/CIFS hinzudeuten. Bestenfalls dürfte die Hauptinstanz MV-Linux, MV-MacOS, oder MV-Windows sein.)

![mv distributed](https://cloud.githubusercontent.com/assets/23268595/25999800/829607ee-36f4-11e7-99f4-5e6a30f8ef1e.png)

**Comment by derreisende77** [comment]
Mediensammlung wird zukünftig nicht mehr weiterverfolgt
