### ISSUE TITLE
Einfache UND suche ohne RegEx-Kenntnisse in den Suchfeldern.

### ISSUE THREAD

**Issue by alex1702** [mediathekview/MediathekView#253]
Eine einfache Möglichkeit in den Suchfeldern durch ein schlüsselwort oder schlüsselzeichen suchbegriffe per und zu verknüpfen ohne dass man sich erst in RegEx einarbeiten muss.
Eventuell als Schlüsselwort direkt "UND" dies sollte in capslock eher selten in einem Titel oder der Beschreibung einer Sendung vorkommen. Falls es doch schonmal jemand gesehen hat direkt mal hier berichten.

**Comment by zxsd** [comment]
Meiner Erfahrung nach ist MV case-insensitive in der Handhabung.  

![case-insensitive](https://cloud.githubusercontent.com/assets/23268595/26271007/986304fc-3cce-11e7-9f0f-34d31a2956f1.PNG)


Einfacher als gezielt zwischen Groß- und Kleinbuchstaben zu differenzieren, möge `.und.` oder ähnliches sein, wobei  `.nicht.` (und vielleicht `.nah.`) wohl auch zu gebrauchen wären.

**Comment by Kalimbim** [comment]
Operatoren der Google-Suche als Voribld?

- UND als Default
- Minuszeichen als Ausschluss
- Sternchen als Platzhalter/Wildcard für Wortbestandteile oder Worte
- Anführungszeichen für Phrasen

Siehe auch: https://support.google.com/websearch/answer/2466433

**Comment by alex1702** [comment]
Die Idee finde ich gar nicht mal so blöd. Eventuell kann man regex auch als Einstellung machen. Es sind einfache Dinge und man kennt sie von Google oder auch anderen Plattformen dann schon. Und wem das dann zu primitiv ist kann per Einstellung regex aktivieren oder mit einer bestimmten Zeichenkette einleiten oder ähnliches.

**Comment by styroll** [comment]
>@Kalimbim sagte: Operatoren der Google-Suche als Vorbild?

Ja, [der Wunsch ist alt](https://forum.mediathekview.de/post/2048). Das wäre mal ein Änderung, die wirklich einer breiten Masse von Usern zugute käme. Das Rad nicht neu erfinden. UND als Operator braucht es gar nicht, da default eine AND-Suche stattfindet. Wichtig sind dann nur noch die Anführungszeichen (alles andere ist dann schon fortgeschritten, aber trotzdem üblich: OR-Suche, * für Wildcard, - für Exclusions)

**Comment by stefan123t** [comment]
Ich bin prinzipiell auch für RegEx zu begeistern, seit ich mir auf regex101 ein paar Ausdrücken konstruieren kann. Aber Escape Zeichen sind dann auch notwendig. M.E. ist das vor Allem für Abos relevant, aber da funktionieren m.W. auch schon Wildcards wie *, ne c'est pas ?

Auf der Webseite MediathekViewWeb gibt es noch eine weitere Syntax, wie wäre es daher eine gemeinsame und einheitliche Syntax bei beiden Projekten zu verwenden ?
Die Syntax von MVW hätte den Vorteil, dass man im MV Suchfeld direkt Filter für die seit 13.x als separatem Dialog (#446) implementierte Filteranzeige setzen kann. Die dort definierten Selektoren sind einfache Präfixe:

Selektoren
!Sender
#Thema
+Titel
*Beschreibung

**Comment by derreisende77** [comment]
MV 14 wird mittels Lucene eine Suchmöglichkeit abseits von RegEx anbieten, welche ähnlich zu MVW sein sollte. Von daher wird dieses issue vorerst geschlossen.
