### ISSUE TITLE
[Enhancement] Text-Dateien durch Kontext-Menü im Mediensammlungsergebnis-Fenster öffnen lassen

### ISSUE THREAD

**Issue by zxsd** [mediathekview/MediathekView#254]
Auf BS-Ebene werden bestimmte Dateitypen standardmäßig mit dem assoziierten Programm geöffnet, beispielsweise werden MP4-Dateien auf meinem PC mit dem VLC-Player geöffnet.  Unter Java scheint dieses Verhalten (mitsamt Doppel-Klick) nicht übernommen zu werden. 

Zur Zeit werden Text-Dateien vom Medien-Player (fehlerhaft) 'abgespielt,' versuche man sie durch Kontext-Menü im Mediensammlungsergebnis-Fenster zu öffnen.  Wenn diese mit einem Editor geöffnet würden, wäre es rationeller.

Im Bild unten ist ein Beispiel von einer Sendereihe, welche ohne Staffel-Angaben erneut veröffentlicht wurde.  Als Abo-Hit sind 2x Sendungen tatsächlich auf einem anderen PC im DL-Reiter gelandet, und keine Größenangaben waren aufgelistet.  Wenn die Info-Datei hierbei aufzukriegen wäre, wüsste man auf Anhieb es von Wiederholungen handelt, denn die jetzige Beschreibung stimmt mit deren in Infodatei Wortgenau überein. 

![mediensammlung-durchsuchen -vorschlag](https://cloud.githubusercontent.com/assets/23268595/26271934/e7c434e2-3cda-11e7-8f6d-e8821eb22bf8.PNG)

So, oder ähnlich, könnte der Editor im MV vom Anwender eingestellt werden:

![erweiterte-einstellungen](https://cloud.githubusercontent.com/assets/23268595/26271540/34a70f06-3cd5-11e7-8698-c0e358cbd3dd.PNG)

Wenn Doppel-Klick sogar die jeweiligen Default-Aktion hervorrufen würde, wäre es ... Spitze!

**Comment by Georg-J** [comment]
@zxsd > Zur Zeit werden Text-Dateien vom Medien-Player (fehlerhaft) 'abgespielt,' 

Das liegt an der erweiterten Einstellung -> Videoplayer. Fehlt diese, wird die Datei standardmäßig mit dem assoziierten Programm geöffnet.

**Comment by zxsd** [comment]
Danke @Georg-J!
