### ISSUE TITLE
MediathekView auf der Kommandozeile

### ISSUE THREAD

**Issue by bablokb** [mediathekview/MediathekView#255]
Als alter Java-Fan finde ich MediathekView ja sehr gelungen, aber ich wollte es auf meinem kleinen Pi1 zum Laufen bringen und bin gescheitert (zuwenig Speicher, keine X-Oberfläche).

Deshalb habe ich eine schlanke Implementation für die Kommandozeile programmiert: https://github.com/bablokb/mtv_cli

Ziel ist es nicht, den Funktionsumfang des Originals nachzuprogrammieren, sondern ein wichtiges Subset an Funktionen zu bieten.

Gruß, Bernhard

**Comment by derreisende77** [comment]
Hast du MV -auto auf dem RPi verwendet? Habe es damit auf dem RPi2 CLI am laufen

**Comment by bablokb** [comment]
Das war mein erster Versuch. Der Pi1 hat aber nur die Hälfte an Haupspeicher und das scheint zu wenig für Java zu sein. Außerdem bleibt bei -auto das Problem der Filmauswahl ohne grafische Oberfläche. Kann man zwar auf einem anderen Rechner machen und die Konfiguration rüberkopieren, aber ich wollte etwas, was deutlich schlanker und einfacher ist.

**Comment by dessert1** [comment]
Ein CLI sollte (genau wie www.mediathekviewweb.de) auf jeden Fall offiziell mit ins Projekt integriert werden, damit man dieselben Bugs und Features nicht doppelt und dreifach bearbeitet. Das Programm ist per Definition für RPi, Mediaserver und andere headless-Maschinen sehr interessant und der Betrieb per X-Forwarding oft ein Overkill.
Trotzdem, der Vollständigkeit halber: Um Mediathekview auf einer Maschine ohne X-Server zu betreiben, kann man es von einer Maschine mit X-Server mit dem folgenden Befehl starten und das GUI mittels `ssh` X-Forwarding empfangen:

    ssh -X user@host mediathekview

Dazu muss mediathekview natürlich auf dem Server installiert sein – der Startbefehl variiert je nach Installation, hier ein Beispiel für den „direkten” Start von `java`:

    ssh -X user@host 'java -Xms128M -Xmx1G -jar /usr/share/mediathekview/MediathekView.jar'

**Comment by bablokb** [comment]
Ich habe nichts gegen eine Integration in das offizielle Projekt. Das hätte an verschiedenen Stellen seine Vorteile, insbesondere könnte man die Umwandlung der Pseudo-JSON-Filmliste nach SQLite schon zentral erledigen und den Code aus dem CLI entfernen.

Java auf Kleinstrechnern ist nicht nur Overkill, sondern schlicht unmöglich. Ein Parameter wie -Xmx1G macht auf Rechnern mit 512MB einfach keinen Sinn.

Inzwischen hat mein Projekt ja auch einen kleinen Webserver integriert und damit ist die Bedienung extrem einfach und schlank geworden - die CLI dient mir dann zum Skripten ("Abos", siehe Beispielskript mtv_sendinfo).
