### ISSUE TITLE
Filmliste aktualisiert nicht mehr

### ISSUE THREAD

**Issue by luposoft2** [mediathekview/MediathekView#256]
Seit Update auf Version 13.x aktualisiert die Filmliste nicht mehr - es wird nur noch die Version vom 30.04.2017 heruntergeladen. Weiß jemand die Lösung?

**Comment by fipsy1** [comment]
Daran liegt es nicht, das Problem ist bei der Version 12 genauso vorhanden!

**Comment by derreisende77** [comment]
https://forum.mediathekview.de/topic/396/keine-neue-filmliste/16

Das Forum ist für Probleme die erste Wahl. GitHub dient zum melden "echter" Fehler der Software.
