### ISSUE TITLE
Mediathek der ARD völlig unvollständig

### ISSUE THREAD

**Issue by fipsy1** [mediathekview/MediathekView#257]
Wenn man sich die Mediathek der ARD ansieht, so tauchen bei MediathekView im Schnitt nur noch 1-5 neue Sendungen pro Tag auf. Das ist nur ein winziger Bruchteil der tatsächlich in der Mediathek eingestellten Sendungen. Beim ZDF sind es zwar deutlich mehr, aber auch dort fehlen sehr viele Sendungen, die in der Online-Mediathek durchaus enthalten sind. Da ist gewaltig was faul und so ist das Programm unbrauchbar.

Beispiele für Filme, die bei MediathekView fehlen:
https://www.zdf.de/dokumentation/terra-x/unsere-waelder-die-sprache-der-baeume-100.html
http://www.daserste.de/information/reportage-dokumentation/dokus/videos/wie-starb-benno-ohnesorg-video-102.html

**Comment by derreisende77** [comment]
Bitte im Forum das Problem mit den Listen melden. Sollten Sendungen fehlen ist das kein Problem von MediathekView, sondern von dem Server.
