### ISSUE TITLE
Beschreibungsfenster zeigt standardmäßig Ende statt Beginn des Textes

### ISSUE THREAD

**Issue by alex1702** [mediathekview/MediathekView#258]
Zitat von Georg-J aus dem Forum:
> Bei der Auswahl eines Filmes scrollt das Beschreibungsfenster automatisch ans Ende anstatt den Anfang des Beschreibungstextes zu zeigen. Man muss erst manuell hoch scrollen um die Beschreibung von Anfang an lesen zu können. Alternativ könnte man auch die Höhe des Beschreibungsfensters vergrößern, wenn MV dies ermöglichen würde.

https://forum.mediathekview.de/topic/460/beschreibungsfenster-zeigt-standardm%C3%A4%C3%9Fig-ende-statt-beginn-des-textes

**Comment by Georg-J** [comment]
Das beschriebene Verhalten zeigt sich nach Klick auf das Icon **i** auch in der Textarea "Beschreibung" des Popupfensters "Filminformation". Zum Testen das Fenster ggf. schmaler machen, schließen und erneut öffnen.

**Comment by kaiwinter** [comment]
Dort habe ich es jetzt auch behoben.

**Comment by derreisende77** [comment]
Habe es gemerged. Vielen Dank!

**Comment by derreisende77** [comment]
In Filminformationsdialog gefixt, im Beschreibungsfeld wohl untergegangen :( 
Wird in 13.1+ gefixt

**Comment by derreisende77** [comment]
Behoben in 13.1.1
