### ISSUE TITLE
Längenerkennung bei Kika-Heidi funktioniert nicht im Abo

### ISSUE THREAD

**Issue by gr4ssi** [mediathekview/MediathekView#262]
Für die Kids habe ich Heidi abonniert (ZDF.Kika) und die Mindestlänge auf acht Minuten gestellt. Der Abo-Download zeigt aber jetzt aktuell nichts an, da Heidi unabhängig von der Filesize überall nur  "Dauer: 1:44" Min anzeigt in der Film-Datenbank.
Die folgen mit 300-500 MB gehen aber ca. 22 Minuten. Irgendwas stimmt da nicht.
Screenshot:
![image](https://user-images.githubusercontent.com/19840345/27605355-ba9a995a-5b7c-11e7-978d-8a8d6b0dab67.png)

Vorschlag: Nicht nur Mindest-Dauer sondern auch die alternativ die Mindest-Größe selektieren lassen. Die Größe scheint ja zu stimmen.

**Comment by pidoubleyou** [comment]
Danke für den Hinweis, da ist ein Fehler im Crawler für ZDF-Tivi enthalten.

MediathekView ist die falsche Komponente, der MServer ist die betroffene, 
Deshalb schließe ich den Issue. Hier ist der [Link zum Issue in  der richtigen Komponente](https://github.com/mediathekview/MServer/issues/189).
