### ISSUE TITLE
Seit 28.7. kein ZDF mehr?

### ISSUE THREAD

**Issue by chris201708** [mediathekview/MediathekView#265]
Hallo!

Seit 28.7. zeigen die Listen nur noch zdf.tivi, aber keine Sendungen des ZDF mehr. ODer habe ich da was verstellt?

Danke,

C

**Comment by Nicklas2751** [comment]
https://forum.mediathekview.de/topic/592/aktuelle-crawler-probleme-beim-zdf/14
