### ISSUE TITLE
[Enhancement] Add new version check

### ISSUE THREAD

**Issue by locked-fg** [mediathekview/MediathekView#266]
Proactively checking for the most recent version would be great.
If a more recent version is found, just make a little notification somewhere to tell the user he's not running the latest version.
An auto-update would be even cooler. I really don't want to care about updating software any more.

**Comment by zxsd** [comment]
[Programmupdate](https://mediathekview.de/anleitung/#allgemein)

> Ist diese Funktion eingeschaltet, wird die Überprüfung einmal täglich beim ersten Start durchgeführt.

**Comment by derreisende77** [comment]
13.1 will be checking for updates automatically every 24h
