### ISSUE TITLE
[Enhancement] Use Window 10 Info-Center for download-completed-notification

### ISSUE THREAD

**Issue by locked-fg** [mediathekview/MediathekView#267]
I totally appreciate the little notification when a download has been completed. Yet I think at least in Windows 10 the action center / Info-center (seems to have different namings depending on the language) should be used for such kinds of notifications.

**Comment by derreisende77** [comment]
This is a java program and native handling of those windows thingies is almost impossible. There it might happen sometime in the future but it ist not first prio for really a long time.

**Comment by locked-fg** [comment]
"almost impossible"?
https://stackoverflow.com/questions/34490218/how-to-make-a-windows-notification-in-java

**Comment by derreisende77** [comment]
System tray sounds good in the documentation but is fairly unusable and hard to support on all our platforms. That is one of the reasons we don't use it. 
Therefore almost impossible as I don't want to maintain another 3 implementations

**Comment by locked-fg** [comment]
Fair enough. Thanks for explaining.
