### ISSUE TITLE
Do not switch tabs if you navigate in top navigation

### ISSUE THREAD

**Issue by GiantCrocodile** [mediathekview/MediathekView#269]
The tabs on the left shouldn't change if you navigate with your cursor in the top navigation. This reduces the usability a lot and is confusing because stuff changes in the background while you do not click anything.

**Comment by zxsd** [comment]
In my opinion (just an MV-user, and a fan), the 'active' aspect of the MV presentation framework might be less confusing if one keeps to goal in mind ... more rational functionality.  This aspect is only present with respect to the pull-down menus associated with functionality that is only active/meaningful to a specific tab.  After single-clicking one of the drop-down headings that are active, MV changes the tab to correspond to the menu over which the cursor hovers.  Here's a summary of the potential alternatives:

![menuexplained](https://user-images.githubusercontent.com/23268595/29746048-4d308ec6-8a9b-11e7-9dc8-8a9c747e0165.png)

If you're looking at the `Downloads` tab, and activate the pull-down menu for `Abos`, MV presumes you want to exercise `Abos` functionality, and changes the Tab displayed accordingly.  Previous versions displayed the menu -- albeit with greyed out selections -- and the tab focus did not dynamically change.  With these older versions (going back as far version 3), there were complaints about menus.  Some users didn't understand the significance of a grey-out/inactive menu-selection.  Others complained (_meckerte_, in German ... but it doesn't translate well) about how this approach was antiquated.  Any way the project's originator responded to all of the feedback.

A couple of things to note:

- The the dynamic tab-shifting behavior results from the first mouse-click.  If your mouse-over location changes horizontally, such that your cursor is over an adjacent pull-down -- i.e., your cursor hovers over a selection different from that you originally selected -- then MV will change the focus to the proper tab.

- If you mouse-over `Datei`, `Ansicht`, or `Hilfe`, then the displayed tab reverts to that originally displayed when you clicked the mouse.  This results from the fact that the action items in these pull-downs have meaning in all MV-Tabs.

The real developers will read this issue and weigh your comments.  If no change results, I hope this post helps you 'stomach' the behavior easier.

**Comment by derreisende77** [comment]
Automatic tab switching can be turned on/off via settings dialog in 13.1.
Feature already implemented
