### ISSUE TITLE
Filmliste immer vom 30.4.2017 (z.B. am 6.9.2017) - auch "Aktualisieren" ändert nichts

### ISSUE THREAD

**Issue by Niko1953** [mediathekview/MediathekView#270]
Hallo,
Details dazu habe ich im Entwicklerforum als "Niko" mit dem Titel "Filmliste vom 30.4.2017 am 6.9.2017 ?" eingestellt. Hier ein Hardcopy-Ausschnitt dazu: 
![grafik](https://user-images.githubusercontent.com/31710615/30135313-95321c54-935a-11e7-870c-ab2a503bd915.png)

Bitte um Kärung.
M f G
Niko

**Comment by derreisende77** [comment]
Hierzu gibt es zig Lösungsmöglichkeiten im Forum.
