### ISSUE TITLE
howto make and install the new version

### ISSUE THREAD

**Issue by JPRuehmann** [mediathekview/MediathekView#272]
Hello
since today I cant find a build Directory anymore.
And the Readme says nothing about instalation.
How can I install and run?
Thanks,

**Comment by Nicklas2751** [comment]
Look here:
https://mediathekview.de/
and here: 
https://github.com/mediathekview/MediathekView/releases

**Comment by JPRuehmann** [comment]
Tere is no Help for my Problem.
But I have found it on https://github.com/mediathekview/MLib
