### ISSUE TITLE
SHA1 Checksummen durch SHA256 ersetzen

### ISSUE THREAD

**Issue by domrim** [mediathekview/MediathekView#274]
Es wäre schön wenn die Checksums zu den Downloads mindestens zusätzlich - IMHO reicht auch ausschließlich - in SHA256 Angeboten werden, das ist doch wesentlich moderner als das Veraltete SHA1.
Das würde zum Beispiel auch das automatisierte Checksummen-Prüfen von Caskroom (https://caskroom.github.io/) wieder ermöglichen.

**Comment by alex1702** [comment]
Wurden durch SHA-512 ersetzt. =)
