### ISSUE TITLE
arte.tv zickt mal wieder

### ISSUE THREAD

**Issue by Elbrecht** [mediathekview/MediathekView#276]
Hi – 

arte.tv zick mal wieder mit 13.02 & 13.03 – 3sat ist OK. Es poppt sofort "Datei ist schon vorhanden" alert auf – auch nach "Weiter"… immer weiter… 
Irgendein Kurzschluß – arte.tv zuzutrauen…

HE

**Comment by Nicklas2751** [comment]
Das ist ein Fall für das [Forum](https://forum.mediathekview.de/topic/3/anleitung-fehler-melden) bitte wende dich dahin und liefer uns bitte dort auch ein paar mehr Informationen wie z.B. welches Betriebssystem du einsetzt, was du eigentlich machen wolltest und was statdessen passiert ist usw.: [Anleitung - Fehler melden](https://forum.mediathekview.de/topic/3/anleitung-fehler-melden)

**Comment by Nicklas2751** [comment]
Das Thema wird aktuell im Forum aber auch schon diskutiert: https://forum.mediathekview.de/topic/863/kann-download-nicht-fortsetzen/7
