### ISSUE TITLE
Themenfilter funktioniert bei "ss"/"ß" nicht korrekt

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MediathekView#277]
Im [Forum](https://forum.mediathekview.de/topic/882/fehlt-und-fehlt-doch-nicht-problem-mit-thema) wurde gemeldet, dass die Combobox zum Filtern des Themas bei Themen, die mal mit "ss" und mal mit "ß" gelistet sind, nicht funktioniert.

Analyse:

- in der Themenliste wird der Collator für `Locale.GERMANY` verwendet (siehe `ListeFilme.themenLaden`), so dass "ss" und "ß" als gleich angesehen werden.

- bei der Filterung nach Auswahl des Themas wird jedoch mit `String.equalsIgnoreCase` (siehe `Filter.filterAufFilmPruefen`) verglichen, so dass "ss" und "ß" als unterschiedlich angesehen werden.

Damit die Filterung korrekt funktioniert, müssen beide Stellen mit der gleichen Logik vergleichen.

**Comment by kaiwinter** [comment]
Wie/wann landet das eigentlich mal im master Branch und in einer MediathekView Version? :worried:

**Comment by derreisende77** [comment]
Ich arbeite gerade an 13.1 und die wird ein komplett neues Filterpanel enthalten. Das dauert jedoch noch ein bischen. Dort sollte das Problem auch nicht mehr auftreten.
Vorher wird es jedoch kein kleineres Update mehr geben. Ein workaround ist ja im Post auch benannt.
