### ISSUE TITLE
Error: "Filmliste laden war fehlerhaft."

### ISSUE THREAD

**Issue by TimmThaler** [mediathekview/MediathekView#280]
Sorry, mein Fehler...

Lösung gibt's ja schon im Forum 🙈 
https://forum.mediathekview.de/post/2851

**Comment by pidoubleyou** [comment]
Aus der Log-Datei ist nur ersichtlich, dass die Filmliste nicht vom Server geladen werden konnte.
Das kann verschiedene Gründe haben. Diese wurden in diversen Beiträgen im [Forum](https://forum.mediathekview.de/) diskutiert und gelöst. Bitte werfe mal einen Blick hinein.

**Comment by TimmThaler** [comment]
Hat sich erledigt.
Ich habe den Konfigurationsordner ".mediathek3" entfernt und dann Mediathekview neu gestartet. Dann ging wieder alles.
