### ISSUE TITLE
Abo funktioniert nicht korrekt

### ISSUE THREAD

**Issue by KuenzelIT** [mediathekview/MediathekView#281]
Hi,

wenn ich ein Abo mit dem Thema "heute-show" eintrage, erhalte ich jede Menge Downloads von kurzen Ausschnitten aus der Sendung, die komplette Sendung (Länge ~35min) fehlt bei den Downloads jedoch immer.

In der normalen Suche unter "Filme" finde ich mit den gleichen Einstellungen sowohl die ganzen Folgen als auch die Ausschnitte.

Kann mir jemand sagen, warum die vollständigen Sendungen bei den Downloads durch das Abo nicht aufgelistet werden?

Danke!

**Comment by pidoubleyou** [comment]
Prinzipiell ist für solche Fragen das [Forum](https://forum.mediathekview.de) die erste Anlaufstelle.

Hast du eventuell im Abo eine Maximaldauer angegeben?

**Comment by KuenzelIT** [comment]
Mit Mindestdauer habe ich rumgespielt, die entsprechenden Sendungen fehlen trotzdem.

Ich sehe das als einen Bug an, daher habe ich das hier gemeldet (habe alles mögliche ausprobiert).

**Comment by claell** [comment]
Was passiert denn, wenn man über die Mindestdauer die kurzen Ausschnitte rausfiltert? Wird dann gar keine Sendung unter Downloads angezeigt? Screenshots von den entsprechenden Dingen könnten auch helfen.

**Comment by KuenzelIT** [comment]
Hey,
wenn ich die kurzen Ausschnitte rausfiltere, dann bleibt ein einziges längeres Video, aber das ist ein Special, nicht die normale "Heute Show".

Habe hier mal drei Bilder angehängt: das erste Bild zeigt die normale Suche nach "heute-show". Das zweite die daraus übernommene Abo-Einstellung und das dritte die sich aus dem Abo ergebenden Downloads.

Wie man sieht, müssen 9 Sendungen runtergeladen werden, aber es wird in den Downloads nur eine Sendung angezeigt.

Danke für eure Hilfe!

![normalesuche](https://user-images.githubusercontent.com/4572444/32348790-3ad33062-c015-11e7-86cf-274b30bebef9.PNG)

![einstellungenabo](https://user-images.githubusercontent.com/4572444/32348792-3aec9cfa-c015-11e7-8b56-ad9b65211c27.PNG)

![automatischedownloads](https://user-images.githubusercontent.com/4572444/32348789-3aba70ae-c015-11e7-9676-e4a99d367ba3.PNG)

**Comment by pidoubleyou** [comment]
Wenn ich das Abo nach deinen Infos anlege, erscheinen genau die 9 erwarteten Einträge in Downloads.

Hast du über ein anderes Abo die anderen Filme schon mal heruntergeladen bzw. aus Downloads gelöscht? 

Denn MV merkt sich dies, so dass diese bei erneuter Abo-Anlage nicht mehr erscheinen. 

Im Ordner ".mediathek3" im Userprofil gibt es eine "downloadAbos.txt", wenn darin die fehlenden Filme aufgeführt sind, werden sie nicht mehr über ein Abo in Downloads erscheinien.

**Comment by KuenzelIT** [comment]
Hi,

du hast recht, in der downloadAbos.txt waren die Folgen enthalten. Die hatte ich wohl vorher schon gespeichert. Verwirrend für mich ist, dass ich die portable Version benutze und vor der Nutzung der Abos eine neue Version runtergeladen habe. Hier liegt die DownloadAbos.txt unter folgendem Pfad:

```C:\...\MediathekView-13.0.3\Einstellungen\.mediathek3\DownloadAbos.txt```

Irgendwie muss das Programm die Daten aus der alten portablen Version übernommen haben.

Vielen Dank für eure Hilfe!
