### ISSUE TITLE
BR funktioniert nicht mehr

### ISSUE THREAD

**Issue by JuergenWba** [mediathekview/MediathekView#282]
Anscheinend hat der BR am 19.10.2017 seine Seite geändert, seitdem werden keine Videos mehr gefunden.

**Comment by pidoubleyou** [comment]
siehe [Ankündigung im Forum](https://forum.mediathekview.de/topic/879/aktuell-keine-neuen-br-sendungen-folgen)

Der zugehörige [Issue](https://github.com/mediathekview/MServer/issues/241) gehört zu einer anderen MV-Komponente und ist aktuelll noch in Bearbeitung.
