### ISSUE TITLE
Mediathekview kann keine Aktualisierungsprüfung und  keine Sendungen laden

### ISSUE THREAD

**Issue by gitterman** [mediathekview/MediathekView#285]
Ich befinde mich hinter einem Proxy und nutze Mediathekview 13.03 mit Java 8u151.
Ich starte das jar über 
java -jar -Dhttp.proxyHost=... -Dhttp.proxyPort=... MediathekView.jar
Die Senderliste kann geladen werden.
Beim Versuch die Programmversion zu überprüfen kommt ein Fehlerbox. In der Konsole steht 
Fehlernr: 398001963  Exception: connect timed out Fehler(MSearch): ListePsetVorglagen.loadListOfSets
Wenn ich eine Sendung herunterladen will dann erscheint:
java.net.SocketTimeoutException: connect timed out
 ....
Fehlernr: 643298301
Exception: connect timed out
Fehler(MSearch): DirectHttpDownload.getContentLength

Ich habe das mit verschiedenen Sendungen verschiedener Sender überprüft.
Bei manchen Senudngen klappte der Download nach einiger Zeit, bei den meisten aber nicht.
z.B. WISO -> Fehler, ARD Rockpalast -> OK nach wiederholtem Laden, KIKA Pfefferkörner - Fehler, NDR Typisch .. - OK nach wiederholtem Laden, ZDF Filmtrailer - Fehler
Die Wiederholversuche habe ich nicht manuell gestartet sondern die wurden von MV automatisch gemacht.
Da es vor einem halben Jahr noch einwandfrei funktioniert hat, muss sich etwas geändert haben.
Es kam in der Zwischenzeit natürlich mehrere Updates.
Ist eine Lösung bekannt, die das Problem behebt?

**Comment by pidoubleyou** [comment]
In den betroffen Stellen hat sich im Programm mindestens seit der Version 13.0.1 (Release 6.1.2017) nichts relevantes geändert.
Da die Fehler alle einen Timeout der Verbindung betreffen, tippe ich eher auf ein Problem mit dem Proxy.

Hast du schon im [Forum](https://forum.mediathekview.de/) nachgeschaut?
