### ISSUE TITLE
Aufgezeichnete Live-Streams lassen sich nicht abspielen

### ISSUE THREAD

**Issue by SchmidtWolf** [mediathekview/MediathekView#289]
Seit kurzer Zeit lassen sich viele Live-Streams, die ich direkt in MediathekView über die "Film aufzeichnen"-Funktion am Mac aufnehme, anschließend mit keiner App mehr abspielen - auch nicht mit dem VLC-Player. Dort wird das mp4-File u.a. mit einer Laufzeit von 0 angegeben, obwohl es z.B. 1,3 Gb groß ist.
Kennt jemand dieses Problem und weiß eine Lösung?

**Comment by pidoubleyou** [comment]
In solchen Fällen hilft in der Regel ein Blick ins [Forum](https://forum.mediathekview.de)
Vielleicht hilft dir dieser [Beitrag](https://forum.mediathekview.de/topic/287/livestreaming) weiter.
