### ISSUE TITLE
Nach Import in FremdPC-MV-Instanz, haben größere Dateien oft '0' als Dateigröße, obwohl diese in 'externe Medien' korrekt erfaßt wurden

### ISSUE THREAD

**Issue by zxsd** [mediathekview/MediathekView#290]
Um zu ermöglichen, der Inhalt meiner eigentlichen Mediensammlung auf Reise mitzunehmen, versuche ich diese als 'externe Medien' in MV zu erfassen.  Dadurch könnte ich innerhalb der MV-Instanz am Reiselaptop feststellen, ob ich über einer bestimmten Datei verfüge, wenn ich unterwegs bin, und keinerlei Verbindung mit dem Server habe.  Ich befinde mich noch in der Versuchsphase, doch scheint es zu funzen.  (Bis jetzt habe ich in solchen Fällen in einer vom Server exportierten DIR-Liste, die Sendung außerhalb MV gesucht.)

Mir ist aufgefallen, daß größere MP4-Dateien, die in "externe Medien" erfaßt sind, oft keine Größenangabe haben.  (Stichproben haben gezeigt, daß dieses Fehlverhalten scheinbar immer jenseits der 2-GB Grenze vorkommt.)

![externemedien](https://user-images.githubusercontent.com/23268595/33226996-e0614916-d167-11e7-9241-63e1a405fc71.PNG)

MV 13.0.4, JRE 1.8.0_151, Win 10

Bug?  (Die doppelten Einträgen bitte ignorieren.  Sie sind Artefakten meines Versuchens.)

**Comment by zxsd** [comment]
Also ... 5x erneut versucht, wobei 4x richtig gelaufen sind.  Bis ich das besser lokalisieren kann, mache ich das Issue "closed."

**Comment by xaverW** [comment]
ist aus der Beschreibung der Methode die die Dateigröße liest:

>   * @return  The length, in bytes, of the file denoted by this abstract
     *          pathname, or <code>0L</code> if the file does not exist.  Some
     *          operating systems may return <code>0L</code> for pathnames
     *          denoting system-dependent entities such as devices or pipes.

kann es sein, dass das nur bestimmte Pfade betrifft (oder beim Auslesen der Größe das NAS hängt??) ich habs bei mir jetzt zig mal mit Dateien ~ 2 - 4GByte versucht und es hat immer geklappt.

**Comment by zxsd** [comment]
Tut mir leid, @xaverW.  Ich bin erst soeben auf Deine Rückmeldung gestolpert.  

Die Filmgrößen der exportierte Filmliste sind **_immer_** einwandfrei.  

Hapern tut's wenn:

> diese `mediendb.txt` Datei ... dann auf _einen fremden_ Laptop kopiert _wird_, wo sie während der gesamten Urlaubszeit unverändert verwendet wird. (Die Urlaub-Downloads werden lokal gespeichert ... Dieser Pfad ist der einzige Eintrag im ersten Mediensammlung-Tab der Laptop-MV-Instanz.)

Nach dem Laden der exportierten `mediendb.txt` Datei in die MV-Instanz des fremden Laptops, erscheinen erst die null Größen. 

Hier ist eine neue (hoffentlich etwa deutlichere) Version des Bildes vom anderen Thread:

![bulle landei zero length_02](https://user-images.githubusercontent.com/23268595/37252239-16577c54-24f4-11e8-8c3d-b93be9aeb129.png)

---

Da das Problem am fremden Rechner zu finden ist, werde ich in nächster Zeit folgende Usecases anwenden, um vielleicht noch was zu lernen:

| Usecase | BS der exportierenden MV-Instanz | BS der fremden MV-Instanz | 
| --------- | ----------------------- | --------------- |
| 1 |  Win 7  | Win 7 |
| 2 |  Win 7  | Win 10 |
| 3 |  Win 7 | Linux |
| 4 |  Win 10  | Win 7 |
| 5 |  Win 10  | Win 10 |
| 6 |  Win 10  | Linux |

Einige Wochen könnte es werden, bevor ich damit fertig bin ...

**Comment by zxsd** [comment]
Inzwischen habe ich festgestellt, daß das Problem immer gezeigt wird, nachdem ein derartiger Index gebaut worden war, und MV runtergefahren wurde.  Beim nächsten MV-Start, werden die Macken gesehen.

Anders formuliert ... das Laden in neu gestarteter MV-Instanz einer schon gespeicherten `mediadb.txt` Datei zeigt immer eine Größe von null, wenn die jeweilige Datei (um die) 2-GB oder größer ist.
