### ISSUE TITLE
Begrenzung der Downloads

### ISSUE THREAD

**Issue by PAPPIG** [mediathekview/MediathekView#291]
seit der letzten Version lässt sich die Zahl der Downloads nicht mehr erhöhen. - Es bleibt bei 2, welche voreingestellt sind.

**Comment by pidoubleyou** [comment]
Es gibt zusätzlich zu der Anzahl der gleichzeitigen Downloads noch eine Begrenzung der gleichzeitigen Downloads pro Server. Letztere kann in den Einstellungen auf eins reduziert werden, maximal sind im Programm fest zwei hinterlegt.

Bei einem Test konnte ich mehr als zwei Downloads gleichzeitig durchführen.
Ich vermute, dass die Downloads alle vom gleichen Server erfolgen und deshalb nur zwei gleichzeitig laufen.

**Comment by PAPPIG** [comment]
Danke, es scheint, dass ARTE, ARD und die Dritten jetzt auf einem Server liegen. Ich war mir sicher, dass ich früher durchaus mehr Downloads hatte.

Als ich den ARD Download stoppte, begann der ARTE zu laufen.

**Comment by zxsd** [comment]
Vielleicht [von Interesse](https://github.com/mediathekview/MediathekView/issues/233) ...
