### ISSUE TITLE
Suchfunktion für Filmliste?

### ISSUE THREAD

**Issue by Katermerlin** [mediathekview/MediathekView#294]
Bin neuer User und begeistert von der Software...
Nur eines fehlt mir (vielleicht hab ich es aber noch nicht gefunden, bitte dann um Nachsicht):
Eine Suchfunktion für die Filmliste wäre schon schön... Momentan exportiere ich die Liste in Excel, suche nach dem Eintrag und weiß dann unter welcher Nummer der Fim zu finden ist...
Das kann es doch nicht sein, oder?

Schon mal vielen Dank für eure Hilfe

Gruß
Wolfgang

**Comment by alex1702** [comment]
lol entschuldige dass ich da ein wenig schmunzeln muss.
Diese ganze Sektion ist zum Filtern der Filmliste unteranderem auch mehrere Arten in der Filmliste zu suchen.
![auswahl_011](https://user-images.githubusercontent.com/1862815/34381624-0441abb2-eb0a-11e7-8b59-49790115f941.png)
Wenn du einfach suchen willst stellst du auf "irgendwo" und tippst dein Suchbegriff in das Feld darunter.

**Comment by Katermerlin** [comment]
...Oha...
Bei mir war die Filterleiste aus irgendeinem Grund ganz zugeklappt, deshalb hab ich das nicht gesehen...
Hab mir schon gedacht was da links für ein grauer Balken ist...

Vielen Dank für die Lehrstunde... :-)

Gruß
Wolfgang

**Comment by styroll** [comment]
>@Katermerlin sagte: Bei mir war die Filterleiste aus irgendeinem Grund ganz zugeklappt

Selbst dann gibt's immer noch ein Suchfeld "Thema/Titel", mit dem man alles findet…

Bei weiteren Fragen unbedingt [das Forum](https://forum.mediathekview.de) verwenden.

**Comment by Katermerlin** [comment]
Wenn's zugeklappt ist, sieht man das auch nicht:
![fenster nicht sichtbar](https://user-images.githubusercontent.com/34886288/34412650-b34eb40e-ebde-11e7-9d89-b078f52fea7a.gif)

**Comment by vitusson** [comment]
Das klappt sich aber nicht von alleine zu. Und ein Klick auf "HIlfe" oder ein knackiges "F1" hat auch noch nie geschadet. 
Aber Gebrauchsanweisungen lesen gilt komischerweise irgendwie als uncool.

**Comment by styroll** [comment]
>@Katermerlin sagte: Wenn's zugeklappt ist, sieht man das auch nicht:

Das kann man nur reproduzieren, wenn man die Filterliste als Extrafenster anzeigen lässt (welches dann bei dir nicht sichtbar im Hintergrund war). Selbst dann bringt ein Klick auf den Button oben rechts das Suchfeld "Thema/Titel" oder gleich das ganze Filterfenster zum Vorschein.

[Screenshot](https://mediathekview.de/images/anleitung/MV_Suchfeld_Erweitert_Tatort.png)

[Hier geht's zur Anleitung](https://mediathekview.de/anleitung/#anleitung).

**Comment by Katermerlin** [comment]
Danke für alle Hinweise.

Wieso das Fenster zugeklappt war, weiß ich nicht. Ich hab mir auch nicht die Filterliste als Extrafenster anzeigen lassen. Die Hilfe (F1) reagiert bei mir nicht, nur die Onlinehilfe funktioniert.
Aber wir brauchen nicht weiterdiskutieren, ich weiß jetzt Bescheid daß ich zu doof war, das Fenster aufzuklappen. Aber das ist halt so wenn man ein Programm das erste Mal in den Pratzen hat...

Gruß
