### ISSUE TITLE
MediathekView.exe meldet Fehler mit Java 9 RE, obwohl MediathekView.jar problemlos funktioniert.

### ISSUE THREAD

**Issue by Atalanttore** [mediathekview/MediathekView#295]
Hallo

wenn man MediathekView 13 über `MediathekView.exe` unter Windows 10 mit der Java-Laufzeitumgebung 9.0.1 (Java 8 deinstalliert) ausführt, erscheint immer folgende Fehlermeldung, obwohl `MediathekView.jar` problemlos auch mit Java 9 funktioniert.

> This application requires a Java Runtime Environment 1.8.0

Gruß
Atalanttore

**Comment by derreisende77** [comment]
Ja das liegt am .EXE stub. Wenn Du die .Jar direkt startest funktioniert es. Aber ohne Garantie da noch nicht ausführlich getestet.

**Comment by styroll** [comment]
> @Atalanttore sagte: wenn man MediathekView 13 über MediathekView.exe unter Windows 10  Laufzeitumgebung 9.0.1 (Java 8 deinstalliert) ausführt, erscheint immer folgende Fehlermeldung

Das Problem ist bekannt und auch [im Forum beschrieben](https://forum.mediathekview.de/topic/816/aktuelle-probleme-mit-java-9).

Zudem gibt es für den normalen User im Allgemeinen und weiterhin [keinen Anlass](https://forum.mediathekview.de/topic/860/unterstützung-von-java-9/2) Java 9 zu installieren.

**Comment by derreisende77** [comment]
Es ist auch gut das die Warnung auftritt. Ich arbeite gerade an 13.1 und die normalen Jars werden so nicht ohne weiteres mit Java 9 funktionieren.

**Comment by derreisende77** [comment]
Zumal bisher niemand offiziell für Java 9 testet
