### ISSUE TITLE
BR-Untertitel werden falsch heruntergeladen

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MediathekView#296]
Im [Forum](https://forum.mediathekview.de/topic/1117/br-sendungen-mit-untertiteln-beim-download-keine-datei-mit-endung-srt) wurde gemeldet, dass bei BR-Filmen mit Untertitel diese beim Abspielen  nicht angezeigt werden.

Der BR stellt die Untertitel über vtt-Dateien bereit. Beim Download wird die vtt-Endung aktuell durch ttml ersetzt, so dass die Untertitel beim Abspielen nicht angezeigt werden.
Wenn die Datei als vtt vorliegt, funktioniert das Abspielen korrekt.

**Comment by zxsd** [comment]
Serviert werden beim BR sowohl `ttml`-Datei als auch `vtt`-Datei (die Dateiendung ist halt anzupassen).  Im BR-Player findet zur Zeit nur die `vtt`-Datei ggf. Anwendung.  

So viel ich es verstehe, muß laut EBU-Richtlinien eine [EBU-TT konforme ttml-Datei](https://tech.ebu.ch/subtitling) zur Verfügung gestellt werden.  Früher hat das ORF das nicht gemacht; inzwischen schon.  Meiner Meinung nach ist der damalige Vorgang vom @derreisende77 der richtige Weg ... da EBU-Richtlinien immer erfüllt bleiben müssen.   

Zwei Links vom alten Forum die vom Interesse sein mag:

[Wie es war ...](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=2&t=1424&hilit=ttml&start=60)

["ttml" Suche](http://zdfmediathk.sourceforge.net/forum/search.php?keywords=ttml)

**Comment by styroll** [comment]
Ich denke, dass der Fokus auf der Kompatibilität mit den Medienplayern (wie VLC, mpv, MPC HC etc.) gelegt werden sollte. Wenn eh nativ eine vtt-Datei zur Verfügung steht, dann ist es aus meiner Sicht nicht nötig, noch eine ttml-Datei runterzuladen (weder VLC noch mpv z.B. können damit etwas anfangen). Natürlich stört es mich auch nicht, wenn zusätzlich eine ttml-Datei runtergeladen wird (ich benötige selbst eh nie Untertitel).

Die mangelnde Kompatibilität mit dem ttml-Format war ja der Grund, solche Dateien ins populäre SRT-Format zu konvertieren…

**Comment by pidoubleyou** [comment]
@zxsd Danke für die Infos

> die Dateiendung ist halt anzupassen

Da stand ich gestern auf der Leitung, ich dachte, du meinst die heruntergeladene Datei. Das funktioniert natürlich nicht. Aber wenn in der URL der Untertiteldatei die Endung geändert wird, dann erhält man die TTML.

Durch eine etwas geänderte Anfrage beim BR können wir die URL für die TTML auch direkt ermitteln.
Da offensichtlich alle Player bisher mit SRT (konvertiert aus TTML) zurecht gekommen ist, ist mein Vorschlag folgender:

- der Crawler für das BR wird angepasst und liefert für den Untertitel TTML, VTT als Fallback, falls mal keine TTML existieren sollte
- der Fix im MV-Client kommt trotzdem rein, denn es macht keinen Sinn eine VTT-Datei als TTML zu speichern und eine TTML-SRT-Konvertierung durchzuführen
