### ISSUE TITLE
Download von Untertiteln

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MediathekView#298]
Im [Forum](https://forum.mediathekview.de/topic/1123/ndr-sendungen-mit-untertiteln-beim-download-eine-datei-mit-endung-ttml-der-l%C3%A4nge-0) wurde gemeldet, dass NDR-Untertitel nicht korrekt heruntergeladen werden. Die Untertiteldatei ist leer.

Ursache:
beim Download der Untertitel der Statuscode 301 als Antwort kommt. Die Logik für den Download der Untertitel erwartet trotzdem, dass der Content den Untertitel beinhaltet.

Vorschlag: 
bei Statuscode 301 prüfen, ob im Header der Antwort eine alternative URL enthalten ist und diese versuchen herunterzuladen. 

Alternative: Fehler im Meldungsfenster ausgeben.

Anmerkung: das konkrete NDR-Problem wird über einen [Quickfix](https://github.com/mediathekview/MServer/issues/333) im Crawler gelöst.

**Comment by derreisende77** [comment]
gefixt in 13.3. Redirects werden nun verfolgt.
