### ISSUE TITLE
RegExp-Suche übergeht Ergebnisse

### ISSUE THREAD

**Issue by akidee** [mediathekview/MediathekView#299]
Die Suche nach `#:.*bonn.*` und `bonn` sollte genau dieselben Ergebnisse liefern. Dennoch ergibt die RegExp oft weniger Ergebnisse.

Bsp.:
Suche in allem, irgendwo nach `#:.*bonn.*` liefert für den letzten Tag 15 Ergebnisse, für `bonn` 14 - ein BR-Beitrag mit der ID 125822 wird nur bei der normalen Suche mitgeliefert.

Auch bei anderen Suchbegriffe passiert Ähnliches. Es scheint, dass vor allem Beiträge mit relativ langer Beschreibung bei der RegExp-Suche wegfallen.

**Comment by xaverW** [comment]
ich hab mir den Film angesehen:

Sender: "BR"
Thema: "DAS BAYERISCHE JAHRTAUSEND"
Titel: "Ingolstadt - Bayerns erste Uni"
Beschreibung: " ..... Beatrix Schönewald,\n...",

Das Problem liegt daran wie Java Zeilenumbrüche behandelt: das Regex .* passt mit Standardeinstellungen nicht auf Zeilenumbrüche.

Als Lösung seh ich 2 Möglichkeiten:

- Beim Anlegen der Pattern (Pattern.DOTALL anfügen):
`Pattern p = Pattern.compile(filter.substring(2), Pattern.CASE_INSENSITIVE | Pattern.UNICODE_CASE | Pattern.DOTALL);`
- oder die Zeilenumbrüche entfernen. Weiß nicht was da besser ist??

**Comment by akidee** [comment]
Das war auch meine Vermutung, aber ich hatte den Text kopiert und konnte keine Umbrüche finden.

Die erste Lösung wäre die beste.

Temporäre Lösung für mich: `#:(.|\n)*bonn(.|\n)*`

**Comment by derreisende77** [comment]
Lösung 1 wurde für 13.2 eingebaut.
