### ISSUE TITLE
3sat - Filme fehlen

### ISSUE THREAD

**Issue by btreut** [mediathekview/MediathekView#300]
die Suche in der 3sat Mediathek nach "panamericana" findet heute sieben Beiträge, die noch zwei Tage verfügbar sind (http://www.3sat.de/mediathek/?mode=suche&query=panamericana).

Mit Mediathekview gelingt es mir (leider) nicht diese Beiträge zu finden. Habe ich da etwas falsch bedient oder ist das ein Bug?

Ansonsten: Tolles Tool, herzlichen Glückwunsch.

**Comment by Nicklas2751** [comment]
Das ist wad fürs Forum siehe hier: https://forum.mediathekview.de/category/7/fehlende-sendungen bzw. hier: https://forum.mediathekview.de/topic/99/fehlende-sendung-melden

**Comment by Nicklas2751** [comment]
Die Sendungen sind aber so alt, dass da auch nichts mehr kommen wird da der Crawler nicht so weit in der Vergangenheit sucht.

**Comment by btreut** [comment]
Danke.
Kann ich den Crawler zwingen die trotzdem zu holen? Oder soll ich das lieber auch im Forum fragen?
