### ISSUE TITLE
Mehrmalige Meldung über fehlgeschlagenen Download bei ungültiger URL

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MediathekView#304]
Im [Forum](https://forum.mediathekview.de/topic/1252/wenn-die-festplatte-voll-ist-landet-mv-bei-downloads-in-endlosschleife/8) wurde folgendes gemeldet:

Wenn eine URL nicht mehr gültig ist (404), dann wird dennoch versucht, diese n-fach herunterzuladen.
Der Anwender muss dabei n-fach die Fehlermeldung wegklicken, dass der Download nicht möglich war.

Ursache:
MV versucht einen fehlgeschlagenen Download, wenn alle Download abgearbeitet wurden, erneut zu starten (wie oft, kann in der Konfig eingestellt werden). 

Wenn die URL nicht mehr gültig ist, macht das wenig Sinn und ist für den Anwender nur nervig.

Ich vermute, dass die Logik enthalten ist, wenn eine URL kurzzeitig nicht erreichbar ist.
Vielleicht gibt es eine Möglichkeit, dass anwenderfreundlicher zu gestalten, so dass nicht n-fach eine Meldung weggeklickt werden muss.

**Comment by zxsd** [comment]
Über den Jahren haben MV-Anwender immer wieder danach gefragt.  Folgender Thread dürfte repräsentativ sein: [Hängende Downloads: Optimierungsvorschläge](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=2&t=1937). 

Der Xaver hat [darauf reagiert](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=2&t=1763&hilit=Restart%20Downloads&start=39).  Oft wollen MV-Anwender mehr, als eine App ohne erheblichen Aufwand tun könnte. Damals empfand ich im Forum irgendwie Frust seinerseits, im Sinne vom amerikanischen Sprichwort, 'jeder will ins Himmel, aber Sterben will niemand' (_Everyone wants to go to heaven, but no one wants to die._)  

(Irgendein Klugscheißer [meinte damals](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=2&t=1937&hilit=404-Fehler&start=24), "Bei beispielsweise einem 404-Fehler würde bald der Spaß aufhören.")

**Comment by Nicklas2751** [comment]
Wenn die Verbindung nicht geklaptt hat oderä hnliches können wi es ja automatisch neu versuchen wenn aber der HTTP Error code 404 kommt melden wir, dass der Film auf dem Server des Senders nicht gefunden werden konnte. Dabei können wir ja anbieten es erneut zu versuchen wenn der Nutzer mag kann er ja dann auf Ja klicken wenn er nicht will dann halt nicht.

**Comment by Nicklas2751** [comment]
Bzw. wie Alex richtig namerkte isnd Pop-Ups eh zu 99% nervig. Also eher:
Bei fehlgeschlagener Verbindung nochmal probieren.
Bei 404 als fehlgeschlagen makieren und nicht nochmal probieren.

**Comment by zxsd** [comment]
Das gleiche Verhalten empfiehlt sich für 403.  Ein Vorschlag ... ohne jegliche Ahnung wie schwer es zu implementieren wäre:

![httperrors_vorschlag](https://user-images.githubusercontent.com/23268595/37225712-79fcf9a0-23a5-11e8-8315-dfb2dad0f7c1.png)

**Comment by alex1702** [comment]
Würde fast empfehlen es eher in Fortschritt rein zu schreiben, weil die Dateigröße einen anderen Datentyp hat. Denke mal da ist es nicht so einfach zu wechseln. Könnte mich aber auch irren. Trotzdem eher in Fortschritt.

**Comment by ilu33** [comment]
Spammende Popups sind nervig, wenn sie ständig den Fokus stehlen. Die Meldung im Fortschritt wie von zxsd wäre ideal, da sieht man dann übersichtlich was los und kann entscheiden, ob man es manuell nochmal probiert (etwa bei launischen Servern wie ARTE).

**Comment by ilu33** [comment]
Wo finde ich denn eine Version mit dem Fix um das zu testen?  Nightlies scheint es nur von 2017 zu geben ...

**Comment by derreisende77** [comment]
Noch gar nicht. 13.1 ist in Beta und dort wird es gefixt sein. Allerdings funktioniert der build mit build Skript noch nicht.
