### ISSUE TITLE
Kodi AddOn: Basis Infos

### ISSUE THREAD

**Issue by buhtz** [mediathekview/MediathekView#305]
Zum [offiziellen Kodi-AddOn](https://mediathekview.de/news/kodi_add_on/) finde ich zwar den Blog Beitrag und auch das darin verlinkte Forum. Das Forum ist aber nur lesbar.

Ich finde keine Information daüber, für welche Kodi Version das AddOn gedacht ist. Das AddOn selbst hat nicht mal diese Information in seiner addon.xml eingebettet.

Und der offizielle Support-Kanal (Forum, Mailingliste, ...?) zum AddOn ist mir bisher auch unbekannt. Daher poste ich hier und bitte schon mal um Entschuldigung.

**Comment by alex1702** [comment]
Für das Forum brauchst du einen Account um zu schreiben.
Unterforum für das Addon: https://forum.mediathekview.de/category/14/offizieller-client-kodi-add-on
Hier das Repository zum Addon: https://github.com/mediathekview/plugin.video.mediathekview

Das Addon funktioniert mit den aktuellen Versionen von Kodi. Sprich Krypton (17.x) und wurde auch auf Leia (18.x) getestet. 

Installation ist ganz einfach, einfach in der addon rubrik in den offiziellen Repository danach suchen. Oder du installaierst das beta repository wie [hier](https://forum.mediathekview.de/topic/1097/aktuelle-release-ank%C3%BCndigungen) beschrieben und installierst es darüber.

**Comment by buhtz** [comment]
Danke für die Hinweise und Links.
Beim Forum stand aber "gesperrt", trotz Account. Später hatte ich gemerkt, dass man den vorhandenen Account auch nochmal explizit per Mail bestätigen muss. Ungewöhnlich.

**Comment by alex1702** [comment]
Eigentlich bekommt man beim Registrieren direkt eine E-Mail zum bestätigen. Eventuell ist sie bei dir untergegangen oder so.

**Comment by Nicklas2751** [comment]
Der im Blog-Post verlinkte Ankündigungs-Thread ist auch gesperrt. Für Fragen usw. gibt es die von Alex erwähnte Kategorie.
