### ISSUE TITLE
Download-Größe wählen für mehrere Downloads

### ISSUE THREAD

**Issue by bardware** [mediathekview/MediathekView#306]
Hallo,

ich kann in der Filmliste mehrere Sendungen markieren und oben den Download-Button klicken.
Daraufhin erhalte ich einen Dialog, mit dem ich das Zielverzeichnis des Downloads auswähle.

![image](https://user-images.githubusercontent.com/802702/37798248-831b7828-2e1c-11e8-96e6-d14032a5b518.png)

Wenn ich einen einzelnen Film angeklickt habe, kann ich im Dialog auch die Größe des Downloads wählen.
![image](https://user-images.githubusercontent.com/802702/37798310-a68a7912-2e1c-11e8-9871-6aa51ef2d9a6.png)

Gibt es eine vergleichbare Auswahl für den gleichzeitigen Download?

**Comment by pidoubleyou** [comment]
Eine Auswahl der Qualität bei der Auswahl von mehreren Sendungen gibt es aktuell nicht.
Du kannst in den Einstellungen hinterlegen, welche Qualität normalerweise verwendet werden soll. Diese wird dann verwendet.

**Comment by bardware** [comment]
Ich muss zu meiner Schande gestehen, dass ich diese Einstellung nicht gefunden habe :(

**Comment by Pinfeet** [comment]
Moin,
ich habe aktuell das gleiche Problem. Wo kann man das in den Einstellungen definieren?
Ausserdem habe ich es noch nicht geschafft, mehr als einen Film zu laden? Download klappt nur mit Rechtsklick?

**Comment by styroll** [comment]
@Pinfeet: Solche Fragen gehören [ins Forum](https://forum.mediathekview.de)…
