### ISSUE TITLE
Positioning glitch in startup animation on Linux X11 with dual monitors

### ISSUE THREAD

**Issue by 2ion** [mediathekview/MediathekView#307]
* Mediathekview 13.0.6
 * KDE kwin 5.12.3, X11
 * OpenJDK 1.8.0u162

A minor glitch without real usability impact.

When starting MV with a dual-screen setup and laying out the screens next to each other, the startup animation will place itself right in the middle of the combined screens' width, with half of the animation on screen 1 and the other half on screen 2 instead of appearing centered on any of the screens. The position of the startup animation is indepent of on which of the 2 screens the main window gets mapped.

**Comment by derreisende77** [comment]
MV positions dialogs in den center of the screen using Java API. If you are using two screens identifying as one large screen to the system this will happen.
There is no way we can fix this.
