### ISSUE TITLE
MV Mac 13.0.6: Programmstart viel langsamer in macOS 10.13.4 (17E199)

### ISSUE THREAD

**Issue by Thomas-U** [mediathekview/MediathekView#309]
Seit dem macOS update dauert der Programmstart hier wesentlich länger als vorher. 
macOS 10.13.4 (17E199) · MacBookPro (mid 2015) · 16 GB RAM

**Comment by derreisende77** [comment]
Was heisst denn wesentlich länger?

**Comment by derreisende77** [comment]
das liegt an Java. Kann ich leider derzeit nichts dagegen tun.
