### ISSUE TITLE
Filme mit Disclaimer nicht verfügbar

### ISSUE THREAD

**Issue by bjacke** [mediathekview/MediathekView#310]
Es gibt Filme, die nur nach dem Abnicken eines Disclaimers (Altersempfehlung etc.) gezeigt werden, z.B. https://www.arte.tv/de/videos/050167-000-A/das-schwache-geschlecht/ . In MediathekView sind solche Beiträge generell nicht zu finden.

Es wäre schön, wenn es eine Option gäbe, die Beiträge, die einen Disclaimer enthalten, auch zugreifbar machen würden.

**Comment by derreisende77** [comment]
@alex1702 Ist das nicht eher ein issue für den Server?
