### ISSUE TITLE
Provider kappt DSL-Verbindung 

### ISSUE THREAD

**Issue by coastgnu** [mediathekview/MediathekView#311]
Seit Fr,, den 6.Apr.2018 kappt mein Provider (EWE-Tel, Netz Wilhelmshaven) nachweislich die DSL-Verbindung wenn ich Mediathekview oder wget verwende um eine Datei aus der ard/zdf-Mediathek herunter zu laden.

Bei Verwendung von Firefox als Viewer bleibt die DSL-Verbindung bestehen und wird nicht gekappt. Bei Versuch mit dem FF-Plugin Video-Download-Helper die Datei herunter zu laden wird ebenfalls die DSL-Verbindung gekappt.

Ich hab mit wireshark einen Dump im pcapng Format erstellt der dieses Verhalten belegt, er ist allerdings etwas über 350MB gross.

Mediathekview 
  Version 13.0.6
Java 
  Version 1.8.0_162
  Type OpenJDK 64Bit Server VM (Oracle Corporation)

tschüss,
thomas

**Comment by derreisende77** [comment]
Dann ist dies ein Problem von EWE-Tel und nicht von uns. Das Programm läuft bei allen anderen Anbietern ohne Probleme.

**Comment by coastgnu** [comment]
<grummelmodus>
Toll, Das eventuell andere EWE-Tel Kunden auch davon betroffen seien könnten und nur gemeinsam eine Chance darauf besteht dem entgegenzutreten ist den Entwicklern also egal??

Wo kommuniziert man denn Eurer Meinung nach eine Unterbindung der Verwendung von Mediathekview durch einen Provider?

Oder soll deine antwort heissen, "Ist uns doch scheissegal wenn Mediathekview im netz der EWE-Tel abgeblockt wird."? 
</grummelmodus>

**Comment by coastgnu** [comment]
```css
<grummelmodus>
```
Toll, Das eventuell andere EWE-Tel Kunden auch davon betroffen seien könnten und nur gemeinsam eine Chance darauf besteht dem entgegenzutreten ist den Entwicklern also egal??

Wo kommuniziert man denn Eurer Meinung nach eine Unterbindung der Verwendung von Mediathekview durch einen Provider, c't, iX, ... ?

Oder soll deine antwort heissen, "Ist uns doch scheissegal wenn Mediathekview von einem Provider abgeblockt wird."? 
```css
</grummelmodus>
```

**Comment by derreisende77** [comment]
Wie wäre es beim Support von EWE-Tel? Ist es evtl eine technische Störung anstatt einer Verschwörung gegen MediathekView? *Kopfschüttel*
Und ja, mir persönlich ist es wie DU geschrieben hast scheissegal wenn ein Provider angeblich MediathekView sperrt, zumal hierfür das Forum der primäre Ansprechpartner und nicht GitHub. Und bevor hier weitere Ansprüche gestellt werden sollte Mal bitte der Blick auf die Lizenz von MediathekView geworfen werden. 
Und deshalb bleibt dieses issue geschlossen weil es keines ist.
