### ISSUE TITLE
Untertitel zu Weissensee

### ISSUE THREAD

**Issue by mediviewer** [mediathekview/MediathekView#316]
Hallo, es gelingt mir nicht die Untertitel zu "Weissensee" zu laden obwohl UT angegeben ist. Es kommt trotz Anhakens von "Untertitel" im Downloadmenu beim besten Willen keine .srt (und auch keine andere Datei) mit. Rechtsklick im "Film" Menu führt leider auch zu nichts (kein Link). Ein bekanntes Problem ? Einzelschicksal ?  Gegenprobe mit Hard Sun Teil 3 funktioniert (.srt). Was kann ich tun ? Vielen Dank für jede Hilfe. phylynx

**Comment by zxsd** [comment]
>Ein bekanntes Problem ? 

Wurde [im Forum](https://forum.mediathekview.de/topic/1394/weissensee-folge-19-20-ut-link-kaputt) schon gemeldet.

> Einzelschicksal ? 

Keine Ahnung ... aber wohl ein Server- anstatt Client-Issue.

> Was kann ich tun ? 

Dich bei @forum.mediathekview.de@@media_fread bedanken, und die [UT-Datei](https://www.ardmediathek.de/subtitle/230645) herunterladen ... als .ttml-Datei speichern.  Um eine .srt-Datei mit richtigen Zeitangaben daraus zu machen ist [im alten Forum](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=1&t=1988&p=11172#p11172) zu lesen (etwaige Bilder ignorieren) ...

... oder darauf warten, bis die @MV-Entwickler die Sache mal anschauen.

**Comment by mediviewer** [comment]
Danke. Es geht um alle Weissensee-Folgen. Ich finde keine einzige bei der die Untertitel mitkommen.

**Comment by zxsd** [comment]
Siehe [Bug-Report](https://github.com/mediathekview/MServer/issues/365).
