### ISSUE TITLE
ORF Download - Access denied

### ISSUE THREAD

**Issue by GFetka** [mediathekview/MediathekView#317]
Guten Tag,

seit längerer Zeit verweigert der ORF auf sämtlichen Kanälen den Download via MediathekView (siehe Anlage).
Das Mediathek Download-Plugin in Google Chrome funktioniert nach wie vor ohne diese Probleme.

Gibt's für MV schon eine Lösung?

Beste Grüße aus Österreich
Gerhard

![2018-05-23 08_33_36-window](https://user-images.githubusercontent.com/39548275/40407435-b7f0c558-5e64-11e8-8aed-d3c9a10fddb9.png)

**Comment by alex1702** [comment]
Ja, siehe im [Forum](https://forum.mediathekview.de/topic/1337/aktuell-probleme-bei-orf-gel%C3%B6st/2)

**Comment by GFetka** [comment]
Herlichen Dank für die rasante Antwort!

Beste Grüße
Gerhard



Von meinem Samsung Galaxy S9+ gesendet.


-------- Ursprüngliche Nachricht --------
Von: Alexander <notifications@github.com>
Datum: 23.05.18 08:54 (GMT+01:00)
An: mediathekview/MediathekView <MediathekView@noreply.github.com>
Cc: Gerhard Fetka <gerhard@fetka.at>, Author <author@noreply.github.com>
Betreff: Re: [mediathekview/MediathekView] ORF Download - Access denied (#317)


Ja, siehe im Forum<https://forum.mediathekview.de/topic/1337/aktuell-probleme-bei-orf-gel%C3%B6st/2>

-
