### ISSUE TITLE
Fehler bei der Softwareaktualisierung: Aktuelle Version konnte nicht ermittelt werden

### ISSUE THREAD

**Issue by LotharD60** [mediathekview/MediathekView#319]
![180527-0003](https://user-images.githubusercontent.com/39675393/40588079-6ded9072-61d8-11e8-81c7-3ece398f3778.jpg)

MediathekView 13.0.6
=====================================================
Java
Vendor: Oracle Corporation
VMname: Java HotSpot(TM) 64-Bit Server VM
Version: 1.8.0_152
Runtimeversion: 1.8.0_152-b16
=====================================================
Betriebssystem: Mac OS X
Bs-Version:     10.9.5
Bs-Architektur: x86_64

Fehlermeldung bei Programmstart und bei manuellem Test (siehe Screenshot)

**Comment by derreisende77** [comment]
Netzwerk nicht verfügbar?

**Comment by derreisende77** [comment]
Bitte für Hilfe am das Forum wenden

**Comment by LotharD60** [comment]
Netzwerk verfügbar und online
