### ISSUE TITLE
keine ORF downloads möglich - java DNS fehler

### ISSUE THREAD

**Issue by snottyone** [mediathekview/MediathekView#321]
bei downloads von ORF sendungen wirft mediathekview 13.0.6 mehrfach folgende fehlermeldung aus
"java.security.cert.CertificateException: No subject alternative DNS name matching apasfdp.apa.at found,"

**Comment by nikooAtKlu** [comment]
Hi - haette da einen Workaround, git push klappt aber nicht:
remote: Permission to mediathekview/MediathekView.git denied to nikooAtKlu

**Comment by alex1702** [comment]
Bitte forke saß Projekt und packe dein patch in einen Branch. Dann kannst du ein pull request öffnen oder direkt den Branche hier verlinken.

**Comment by nikooAtKlu** [comment]
Hmm. Habe das nach der [Anleitung](https://github.com/mediathekview/MediathekView/wiki/Entwicklung%3A-Ohne-git-flow) gemacht, aber
git push origin 'hotfix/321'
liefert dann wieder denied.

**Comment by nikooAtKlu** [comment]
fork war das Zauberwort... Danke!

**Comment by zxsd** [comment]
Meiner Meinung nach eher ein Server-Problem (https://github.com/mediathekview/MServer/issues/373) ...

**Comment by nikooAtKlu** [comment]
Ja, das ist brandgefährlich und auch nur temporär sinnvoll - deswegen Workaround.

Schöner wäre es natürlich wenn einzelne Ausnahmen schon über die Filmliste beim Client ankommen - es kann ja immer mal passieren, dass ein Zertifikat noch nicht über die jre validierbar ist oder wie beim orf (eventuell absichtlich) das Zertifikat nicht zum Uri passt. 
Die Uris zu modifizieren (z.B. Einfügen von ".sf" an einer bestimmten Stelle) erscheint mir doof, weil das ein Ping-Pong-Spiel werden kann - was passiert, wenn der orf an der Stelle zukünftig ein selbstsigniertes Zertifikat verwendet?

**Comment by derreisende77** [comment]
Also das deaktivieren von SSL werden wir nicht implementieren. Ich persönlich habe da ein großes Problem wenn ein Sender nicht in der Lage ist, sich ein vernünftiges Zertifikat ausstellen zu lassen. Und der Workaround ist nicht nur unsicher und brandgefährlich wie oben ja auch mehrfach beschrieben, sonder ich gehe auch sehr wohl davon aus das der normale User sich nicht darüber im Klaren ist was er eigentlich aktiviert bzw deaktiviert mit dieser option.

Aber versuche doch mal das Zertifikat zu importieren:
`openssl s_client -showcerts -connect apasfpd.apa.at:443 > certs.txt`
dann konvertieren:
`openssl x509 -in certs.txt -out certs.der -outform DER`
Abschließend in die cacert importieren:
`sudo keytool -importcert -file certs.der -keystore <path-to-cacerts> `
Default cacerts passwort ist 'changeit'.

die cacerts datei findest du mit [dem Link](https://stackoverflow.com/questions/11936685/how-to-obtain-the-location-of-cacerts-of-the-default-java-installation)

Sollte die Lösung mit dem globalen Import des Zertifikates bei dir die DL-Probleme lösen, könnte man überlegen, mit MV einen lokalen Keystore mitzuliefern der den Müll des ORF behebt.

**Comment by nikooAtKlu** [comment]
Das kann ich gerne mal ausprobieren, es wird aber nix bringen - das Problem beim orf ist nicht, dass in der Zertifikatskette kein bekannter Trust Anchor gefunden wird.

Problem ist, dass die Verbindung auf den Host-Alias apasfpd.apa.at geht, der in dem Zertifikat nicht erwähnt ist (*.sf.apa.at), und offenbar wird nicht geprüft, ob sich hinter der IP ein DNS-Eintrag mit *.sf.apa.at verbirgt.

**Comment by shoeper** [comment]
Hat denn schon jemand probiert den ORF zu kontaktieren?

**Comment by nikooAtKlu** [comment]
Aber ja, ich unterstelle Absicht - vgl. die Geschichte mit Fehler 403 wenn dem orf der User-Agent nicht passt.

**Comment by xaverW** [comment]
vielleicht wäre es vorerst mal eine tmp. Lösung, das https zu entfernen bis das Zertifikat wieder passt. bei den betroffenen Filmen findet der Crawler auch die Dateigröße nicht.
http geht, mir ist aber beim Testen auch noch aufgefallen, dass der useragent dann auch nicht "MediathekView" sein darf, sonst gehts auch nicht. 
~> vielleicht doch alles beabsichtigt

**Comment by alex1702** [comment]
Werde es mir noch ansehen.

**Comment by zxsd** [comment]
Ich habe es versucht, durchs Editieren der Filmliste.  Mit "hoch" Bildauflösung ginge es, mit "HD" aber nicht.  Ich hatte keinen Erfolg das HD-Offset zu editieren  (sowohl um 3 Zeichen für `.sf`, als auch um 1 für `http`).  

Mit einem Leerzeichen vorne (also, Offset-schönend), `_http`, ginge es auch nicht innerhalb MV.  Solche ORF-URLs (d.h., mit Leerzeichen vorm `http` in der Filmliste) werden erfolgreich im Browser abgespielt (nachdem sie vom MV kopiert worden waren), aber Java scheint damit nicht klar zu kommen.

Wenn etwas vorübergehend implementiert werden sollte, dann sollte die UT-Datei auch behandelt werden.

![2d replacement](https://user-images.githubusercontent.com/23268595/41476946-f68ac3a2-7090-11e8-8973-caf67f9c733d.png)

**Comment by zxsd** [comment]
Ja.  Erst die Filmliste als JSON-Datei exportiert, danach mit Notepad++ editiert, anschließend in MV geladen.  Ich wollte 'an der Quelle' alle ORF DLs auf einmal verbessern.

Die herunterzuladenden ORF-Sendungen im DL-Reiter tue ich nach Doppelklick bearbeiten.  Eich viel Aufwand ist es nicht. \<g\>

Nachdem ich wieder ein bißl dran schaffe, ist mir jetzt klar daß die UT-Dateien so bleiben können, wie sie vom ORF veröffentlicht werden ... im Gegenteil von meinem obigen Beitrag.  Unter Windows 10 scheint die nötige Root-Certificate aber nicht vorhanden zu sein.  Hier ein Bild davon:

![g2rootmissing](https://user-images.githubusercontent.com/23268595/41499966-a42c956e-7157-11e8-8e88-45c5890324a7.PNG)

Ich werde versuchen das GeoTrust G2 Primary-Certificate-Bundle zu installieren, in der Hoffnung es was nutzt.  Um Vergleiche mit Mac/Linux zu ermöglichen, beinhaltet folgende TXT-Datei die OpenSSL-Queries für ORF.AT und APASFPD.APA.AT unter Windows 10:

[openSslResponseForORFCerts.txt](https://github.com/mediathekview/MediathekView/files/2108272/openSslResponseForORFCerts.txt)

**Comment by zxsd** [comment]
Meiner Meinung nach, liegt es an den Certs.

Im ORF-Player sind zwei Server hauptsächlich im Spiel:
```
   -  https://varorfvodw.sf.apa.at
   -  https://apasfiis.sf.apa.at
```
Natürlich funzt alles im ORF-Player selbst, denn das Alias (ohne `sf.`) wird nicht verwendet!  (Im MV-Server Issue tippte ich schon auf Vorsatz seitens ORF.)  Das Versuch mit VLC einer repräsentativen im ORF-Player verwendeten m3u8-Playlist abzuspielen, bringt unter Windows 7 nichts.  So schaut's aus trotz voriger Installation des scheinbar erforderlichen GeoTrust G2 Root-Zertifikats (mangels Bundle, bis jetzt nur mit Root-Zertifikat):

![vlctriestoopenplaylist](https://user-images.githubusercontent.com/23268595/41501374-4bb96b04-7171-11e8-8864-085a56633933.PNG)

Das gleiche (Fehl-)Verhalten sehe ich mit Internet Explorer ... ohne jegliche Änderung.  

---

Hier ist besagtes Zertifikat (als "`-sfapaat.crt`" umbenennen):

[-sfapaat.txt](https://github.com/mediathekview/MediathekView/files/2108439/-sfapaat.txt)

Wenn ich wieder Zeit habe, versuche ich obiger Zertifikat auf BS-Ebene rationell 'zu vertrauen.'

**Comment by novoid** [comment]
FYI: Ich habe mal https://github.com/novoid/mediathekview_change_downloads_to_http programmiert, das alle anstehenden Downloads auf http konvertiert, damit es vorerst mal in der Zwischenzeit ohne manuellem Aufwand funktioniert.

**Comment by shoeper** [comment]
Was passiert denn wenn der crawler am Ende alle Links auf ...sf... umschreibt?

Nach https://www.ssllabs.com/ssltest/analyze.html?d=apasfpd.sf.apa.at&s=185.85.29.131&latest stimmen für die Domains mit sf die Zertifikate und für die ohne nicht.

**Comment by nikooAtKlu** [comment]
2. Versuch - nur den Hostname-Check deaktivieren, und nur bei diesem Fehler "No subject alternative DNS name matching apasfpd.apa.at found."

**Comment by Nicklas2751** [comment]
Das was @shoeper schreibt wird das Zielführende sein. Wenn ich die Zeit finde werde ich mir angucken welche Daten der crawler bekommt und dann entweder den Fehler beheben der dazu führt dass das SF fehlt oder es halt ergänzen lassen. Das ist aber eine Crawler sache und jegliches SSL deaktivieren oder irgend was im client rumpfuschen bringt nichts und ist sehr fraglich.

Da das allg. kein Client thema ist mache ich den Issue hier zu.
