### ISSUE TITLE
13.1.0: Wo sind die Filterprofile?

### ISSUE THREAD

**Issue by akidee** [mediathekview/MediathekView#329]
Ich nutze zum Teil recht komplexe Suchfilter mit RegExps, diese will ich, wie in der Vorversion, auch speichern. Siehe außerdem https://github.com/mediathekview/MediathekView/issues/299

**Comment by zxsd** [comment]
[Abos umbauen und gespeicherte Filter integrieren](https://forum.mediathekview.de/post/8827)

[Der MV-Forum](https://forum.mediathekview.de/recent) ist im Allgemeinen lesenswert ...

**Comment by akidee** [comment]
Danke, das ist hilfreich. Ich wollte weitere Fragen ins Forum posten, aber mich erreicht die nötige Bestätigungsmail nicht. Daher poste ich meine Fragen hier:

* Beim Abofiltern mit den selben Kriterien wie bei einem Filterprofil (in 13.1.0 entfernt) scheinen einige Filme zu fehlen. Es sind nicht bloß die geogeblockten. Welche fehlen?
* Wie kann ich aus der Downloadliste heraus direkt streamen?
* Wie kann ich für einen Download die Qualität individuell bestimmen?

Ich verstehe die Unterteilung in Filme und Downloads nicht. Im Grunde ist eine Liste ja nur eine algorithmische Vorfilterung, die möglicherweise viele false positives enthalten kann. Es wäre besser, einfach eine große Liste zu machen, die mit jedem Listenupdate auch automatisch oder nach Anstoß entsprechend den Abos geupdatet wird. Was ich dann runterlade oder streame, will ich selbst entscheiden.
Abos, wie sie in MV gedacht sind, sind OK, wenn ich eine nur bestimmte Sendungen regelmäßig schaue. Wichtiger als Sendungen bleiben aber bestimmte Themen, folglich die Möglichkeit, alle Daten nach Stichworten zu durchsuchen und dann selbst auszuwählen.
Es wäre gut, eine langdauernde komplexe Suche im Hintergrund auszuführen, und, beginnend bei neueren Einträgen, bereits gefundene Ergebnisse anzuzeigen.
