### ISSUE TITLE
Problems starting 13.1.0 with "-Djava.awt.headless=true" and "-auto"

### ISSUE THREAD

**Issue by holgis** [mediathekview/MediathekView#330]
Starting 13.1.0 with `-Djava.awt.headless=true` and `-auto` does not work for me (openSUSE 15.0 64bit, jre1.8.0_181-b13):

`$ java -Djava.awt.headless=true -jar ./MediathekView.jar -auto "$@"`
`[...]
. Proxy Authentication: not configured
. java.awt.HeadlessException
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  20
  Current serial number in output stream:  21`

Same command on same environment with 13.0.6 is working fine.

**Comment by zxsd** [comment]
In the future, the [Forum](https://forum.mediathekview.de/recent) is likely a good starting point with problems like this.  Here is a link that appears to be relevant:

 [... Server Modus verwenden](https://forum.mediathekview.de/topic/1541/org-h2-jdbc-jdbcsqlexception-server-modus-verwenden)

**Comment by holgis** [comment]
Unfortunately I do not have issues with the database (JdbcSQLException) as the guy on the forum. The error occurring here is: java.awt.HeadlessException with X Error of failed request: BadValue

**Comment by derreisende77** [comment]
Does the program run on console? in Auto or fastauto mode during startung JavaFX exceptions and/or X11 exceptions do occur due to necessary JavaFX initialization. These cannot be prevented but do not harm execution. Just visual annoyance.

**Comment by holgis** [comment]
You closed this issue - what was the resolution?

When running in console the only difference is this message:
`No X11 DISPLAY variable was set, but this program performed an operation which requires it.`
Other than that program sticks forever at:

```
[...]
. Creating SQL indices
. Finished creating SQL indices
. Liste Filme gelesen am: 24.09.2018, 10:18
.   erstellt am: 24.09.2018, 09:15
.   Anzahl Filme: 247925
. Die Filmliste ist 62 Minuten alt
. aktuelle Filmliste verwenden
. ========== ========== ========== ========== ==========
. DURATION 0:  Abo in Filmliste eintragen  [157.00 ms]
.    Klasse:  MediathekAuto.starten
.    Abo in Filmliste eintragen Anzahl: 1   Dauer: 155.00 ms
. ========== ========== ========== ========== ==========
```

**Comment by derreisende77** [comment]
No response after 4 weeks.
#367 provides temporary solution until fix is published.
