### ISSUE TITLE
"Mit Standardeinstellungen starten" ausgegraut [macOS]

### ISSUE THREAD

**Issue by styroll** [mediathekview/MediathekView#334]
Mir ist eben nach der Installation von MV 13.1.1 (App Bundle) unter OS X 10.11.6 aufgefallen, dass beim ersten Start der Button "Mit Standardeinstellungen starten" ausgegraut ist.

![mv_erster_start](https://user-images.githubusercontent.com/24810728/43634984-08799464-970e-11e8-8a4b-5ab49a57c5f9.png)

Wenn man das obige Fenster einfach schliesst, werden keine Standardsets geladen, falls man die Verbindung zum Server "mediathekview.de" via Port 7 nicht zulässt, da dann auch keine Verbindung via Port 443 zu "download.mediathekview.de" zum automatischen Importieren (?) der Sets aufgebaut wird.

Zumindest die "Ausgrauung" war schon bei MV 13.0.6 und MV 13.0.0 (App Bundle) so. Bei der "Zip-Version" (13.0.6) ist das jedoch nicht so (13.1.1 hab ich nicht getestet, da ich diese nur im portablen Modus verwende, wo es ja noch Probleme gibt).

1. Lösungsvorschlag: Der Button sollte (wie bei MV 12) nur ausgegraut sein, wenn VLC noch nicht installiert ist (vgl. [Thread im alten Forum](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=2&t=1983#p11736)).

2. Damit ich das verstehe:  Wozu dient der Verbindungsaufbau via Port 7 (den es bei MV 13.0.6 noch nicht gab)?

EDIT:
 Verbindung via Port 443 zu "download.mediathekview.de" scheint eher nach Updates zu prüfen.

**Comment by alex1702** [comment]
Port 7? wtf?

**Comment by derreisende77** [comment]
JDK InetAddress.isReachable(...) im Update check ist für port 7 verantwortlich:
`Test whether that address is reachable. Best effort is made by the implementation to try to reach the host, but firewalls and server configuration may block requests resulting in a unreachable status while some specific ports may be accessible. A typical implementation will use ICMP ECHO REQUESTs if the privilege can be obtained, otherwise it will try to establish a TCP connection on port 7 (Echo) of the destination host.`
Also von daher ist das gewollt da ich testen muss ob eine Netzwerkverbindung funktioniert.

**Comment by Kasperx** [comment]
Ich habe im Code die Stelle "InetAddress.getByName("res.mediathekview.de");" gefunden. Wenn man da den Port mitgeben würde, sofern die Bib das akzeptiert, würden mehrere Probleme gelöst :)
1 - der Benutzer kann den Port wählen
2 - bei bekannten Firewall-Problemen könnten diese umgangen werden

**Comment by derreisende77** [comment]
Wenn Du im Java-Code lesen kannst weisst Du sicherlich auch wie man an die dazugehlrige javadoc kommt. Dann wäre Dir aufgefallen dass es nicht um InetAddress.getByName() sondern um .isReachable() geht.
Ein Blick in die Doku (dich ich nebenbei zitiert habe oben im Post) zeigt das für reachable das ECHO Protokoll genutzt wird. Und eben dieses ist standardisiert auf Port 7. Daher wird man auch keine Option finden den Port zu ändern, was ja dämlich wäre weil der Empfänger sonst nicht wüsste was der Sender will...
Somit können deine Probleme so nicht gelöst werden weil es
1-keine sind
2-falsche Sachlage
und 
3-fehlerhaft analysiert wurde.

**Comment by alex1702** [comment]
@Kasperx du weißt aber schon was die Funktion macht?
Der Server hat immer die gleiche IP, egal welchen Port du da angibst. und sollte der Port 443 oder 80 gesperrt sein (durch firewall auf dem weg) ist es auch egal welchen Port man beim überprüfen angeben würde.

**Comment by styroll** [comment]
Danke für die Erklärungen zu (2). Kann (1) korrigiert werden?

> @styroll sagte: Lösungsvorschlag: Der Button sollte (wie bei MV 12) nur ausgegraut sein, wenn VLC noch nicht installiert ist (vgl. Thread im alten Forum).

**Comment by derreisende77** [comment]
Habe ich auf der Todo aber nicht für 13.2

**Comment by derreisende77** [comment]
13.3 wird mit Standardeinstellungen starten können wenn das Programm gemäß den Installationsanweisungen der DMG im Programme-Ordner liegt. Ansonsten wird man ffmpeg manuell suchen müssen
