### ISSUE TITLE
Unterschied zwischen MediathekView 13.1.2 Tarball bei Github und der MediathekView-Website?

### ISSUE THREAD

**Issue by ikselven** [mediathekview/MediathekView#338]
Worin besteht der Unterschied zwischen dem vor 4 Tagen [hier auf Github](https://github.com/mediathekview/MediathekView/releases/download/13.1.2/MediathekView-13.1.2.tar.gz) veröffentlichten Tarball und dem heute auf der [MediathekView-Website](https://download.mediathekview.de/stabil/MediathekView-13.1.2.tar.gz) hochgeladenen?

Sollten die nicht beide die gleiche Checksumme haben, da sie das gleiche Release enthalten?

**Comment by derreisende77** [comment]
Vorläufiger Bugfix bis zeitnah neues Update verteilt wird

**Comment by ikselven** [comment]
Danke für die Info!
