### ISSUE TITLE
Use XDG Base Directory Specification

### ISSUE THREAD

**Issue by AGCaesar** [mediathekview/MediathekView#339]
Following a Discussion here https://www.reddit.com/r/linux/comments/971m0z/im_tired_of_folders_littering_my_home_directory/    
I would like to ask for mediathekView to use the XDG Base Directory Specification https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Especially create .mediathek3  inside the .config directory. Thanks a lot :)

**Comment by derreisende77** [comment]
Well actually after reading both the reddit thread and the XDG BDS I don´t see a reason to fix something here in our code.
Rationale: We have documented the default behaviour of our app to save the config directory by default to $HOME on all supported platforms. If people don´t like that location they can change that behaviour ANY TIME by starting the app with a custom directory_location (aka portable mode), which means you can easily configure the app to follow the BDS if you wish to.
we do not provide packages for single linux distributions but our software is intended to be run on various other platforms which do not use the BDS. Therefore you have to spend some time anyways if you wish to modify the default behaviour.

**Comment by Leseratte10** [comment]
The point of the XDG spec (and the default folder of ~/.config) is to not clutter a user's home directory with new config folders for each and every application. It's nice that MediathekView offers a config option, but it's not really viable to add custom launch options for every single application that's writing stuff to the home directory. The point is that `XDG_CONFIG_HOME` is supposed to be the "global" configuration setting (with a default value of `$HOME/.config/` if unset) to act like `directory_location`, just globally for all applications without people having to configure every application independantly. 

Would it be that difficult to change `~/.mediathek3` to `~/.config/mediathek3` by default, or `$XDG_CONFIG_HOME/mediathek3` if set?

**Comment by derreisende77** [comment]
Yes as it breaks compatibility.  And supporting XDG base spec is more than copying the current data to the config, e.g. film list should then be stored in cache dir…
MV (like many other unix ui tools) was created before XDG paper was written. IMHO there is nothing wrong with the current . directory usage since YOU know where all data is stored. 
And MV is still a cross platform solution. This also means you can rely on the fact that you will find your data in all OS under .mediathek3 in your user directory and nit in various split locations. 

If you desperately want to change this set $HOME different for MV. This should be detected by java on startup. Or use portable mode to change the location to a place convenient for you.

**Comment by dvzrv** [comment]
> Yes as it breaks compatibility. And supporting XDG base spec is more than copying the current data to the config, e.g. film list should then be stored in cache dir…

Well, if this ticket wasn't closed, maybe someone would be encouraged to work on this and not have broken compatibility.

> MV (like many other unix ui tools) was created before XDG paper was written. 

The [first version of the basedir spec](https://gitlab.freedesktop.org/xdg/xdg-specs/-/commit/c8475bef1d1f84afcc89c710b6b5b214f11a670f) predates (not that this actually has any relevance when it comes to following a specification, that is widely adopted on the Linux operating system) the [first commit in this repository](https://github.com/mediathekview/MediathekView/commit/00a63e70626453db327a64dedae09f799c08d474) by 9.5 years.

> IMHO there is nothing wrong with the current . directory usage since YOU know where all data is stored.

Well, still seems that users want this (and I would include myself here :) ). Personally, I look up XDG directories before anything else and actually would like to not have a program clutter my $HOME.

> And MV is still a cross platform solution. This also means you can rely on the fact that you will find your data in all OS under .mediathek3 in your user directory and nit in various split locations.

But I am not interested in looking up this data on any other operating system and this ticket is about XDG base dir spec on Linux :)

> Or use portable mode to change the location to a place convenient for you.

Packaging this project for Arch Linux I could of course start adding more workarounds in the startup script, which is required to set some JVM settings already, but if we can have a fully XDG compliant application out of the box instead, I'd much prefer that! :)
