### ISSUE TITLE
No icon for Linux

### ISSUE THREAD

**Issue by joehni** [mediathekview/MediathekView#340]
Since version 13.1.x there's no symbol file for Linux anymore. The desktop files can refer xpm, png, svg and sgvz formats as symbol files. The symbols in xpm, png and svg were delivered in 13.0.x in the Info folder, but that one is no longer in the delivered tar.gz.

**Comment by alex1702** [comment]
i have add the svg https://github.com/mediathekview/MediathekView/blob/master/res/Icons/MediathekView.svg
It will be back in the next release.
