### ISSUE TITLE
Einfügen in Textfelder mit mittlerem Mausbutton unter Linux

### ISSUE THREAD

**Issue by jeriba** [mediathekview/MediathekView#341]
Unter Linux ist es (normalerweise) möglich selektierte Texte mit dem mittleren Mausbutton in Textfelder einzufügen (google: middle click paste). 

Das Suchfeld von MediathekView verlor diese Fähigkeit wohl vor zwei oder drei Versionsnummern. Kann man das wieder aktivieren?

**Comment by Nicklas2751** [comment]
So wie du es beschreibst ist das ja dann ein externes Feature dann sollte sich auch die jeweilige Software die das mitrbringt darum kümmern, dass das geht. Wir bieten ein Standard Textfeld wie wir es von Java zur Verfügung haben. Was dein BS damit macht ist ja nochmal was anderes.

**Comment by jeriba** [comment]
Es hat nichts mit meinem BS zu tun. 

Ich habe die letzte Version gefunden, die den Middle-Paste erlaubt: Version 13.0.6. Ich nehme mal an, dass es sich um die Umstellung auf JavaFX handelt und dass dort die Middle-Mouse-Button-Events nicht automatisch empfangen werden.

**Comment by jeriba** [comment]
Ich habe noch das hier auf [stackoverflow](https://stackoverflow.com/questions/30032290/javafx-mouse-clipboard-does-not-work-in-unix)  gefunden:. Da gibt es einen Beispiel-Code, wie man den den Event abfängt und das Clipboard befragt.

**Comment by derreisende77** [comment]
Wenn du den SO Beitrag zuende gelesen hättest wäre dir aufgefallen dass es sich um einen Java 8 Fehler handelt. Weiterhin wird der als fixed for jdk9 geführt. Leider ist MV bis auf weiteres aber nicht mit Java 9 kompatibel daher kein Versuch das zu fixen. Strg V funktioniert und so...

**Comment by jeriba** [comment]
Und von dort geht's nach [bugs.openjdk.java.net](https://bugs.openjdk.java.net/browse/JDK-8088117]) und im Kommentar dort findet sich: 

> Lowering the priority to P4. I note that this is more of an unimplemented feature than a bug 
> (it has never been supported in FX). We will look at it for JDK 9. 
> Workaround: use copy/paste (CTRL-C / CTRL-V) 

Okay ich seh's ein :-(
