### ISSUE TITLE
Download: Beschränkung der Bandbreite funktioniert nicht

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MediathekView#342]
Aus [Forum](https://forum.mediathekview.de/topic/1636/maximale-bandbreite-funktioniert-nicht-richtig):
Die Beschränkung der Bandbreite pro Download funktioniert seit 13.1.0 nicht mehr korrekt.

Die tatsächliche Bandbreite liegt teilweise weit unter der eingestellten Bandbreite.

Bei meinen Tests ließ sich das Problem mit Downloads in den Abos gut nachstellen.
Manuell erzeugte Downloads hatten selten die eingestellte Bandbreite!

**Comment by Nicklas2751** [comment]
Ist das denn neu? Mir sind solche phänomene schon bekannt seit ich MV nutze. Und mir viel es immer je nach Tageszeit auf usw. Die bisherige Vermutung war, dass es an den Servern der Sender liegt o.ä.
