### ISSUE TITLE
Irgendwo-Suche bei Abos scheint nicht zu funktionieren

### ISSUE THREAD

**Issue by derreisende77** [mediathekview/MediathekView#344]
Reminder

**Comment by bardware** [comment]
Ich habe meine Version gerade mal aktualisiert, ich hing noch an der `13.0.6` und sehe bspw. Verbesserungen in den Einstellungsmöglichkeiten. Den "Irgendwo"-Filter in der Suche vermisse ich aber überhaupt....

**Comment by derreisende77** [comment]
Ist in 13.2 drin. Kommt die tage
