### ISSUE TITLE
MediathekView startet nicht mit OpenJDK 1.8.0_181

### ISSUE THREAD

**Issue by smillies** [mediathekview/MediathekView#345]
Ich habe OpenJDK 1.8.0_181 installiert (in der Distribution von Azul:
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (Zulu 8.31.0.1-win64) (build 1.8.0_181-b02)
OpenJDK 64-Bit Server VM (Zulu 8.31.0.1-win64) (build 25.181-b02, mixed mode)

Meine Pfadvariable enthält das bin-Verzeichnis des JDK (wie in der FAQ beschrieben). Trotzdem startet MediathekView nicht, mit der Meldung: "This application requires a Java Runtime Environment 1.8.0".

-- Sebastian

**Comment by derreisende77** [comment]
starte doch mal das Program direkt mit `java -Xmx1G -jar Mediathekview.jar` und schau ob das geht. Es kann sein dass der EXE-Wrapper Zulu nicht erkennt.
Wobei ich aber schon davon ausgehe das auch das Programm nicht funktionieren wird das AFAIK Azul Zulu kein JavaFX/OpenJFX mitliefert welches von MV benötigt wird.
Sollte dies der Fall sein wirst du unter Windows wohl nicht um Oracle herum kommen.

**Comment by smillies** [comment]
Danke für die schnelle Antwort, es liegt wohl tatsächlich an JavaFX:
C:\Program Files (x86)\MediathekView-13.1.3>java -jar MediathekView.jar
. JavaFX was not found on system.

Man kann versuchen, ohne Oracle auszukommen:
Für OpenJDK 11 gibt es [Early Access Builds](http://jdk.java.net/openjfx/) von OpenJFX .
Für OpenJDK 8 kann man sich OpenJFX selbst bauen. Wird [hier ](https://www.chrisnewland.com/add-javafx-support-to-azul-systems-zulu-jdk-using-openjfx-383 )erklärt.
Man braucht Gradle 3.1 und muss ein Windows SDK installiert haben.

Es gibt auch fertige OpenJFX overlays, z. B. [hier](https://chriswhocodes.com/).
Allerdings funktioniert das anscheinend nicht mit Windows 7, weil neuere core-libs gebraucht werden (z. B. api-ms-win-core-rtlsupport-l1-2-0.dll)

Die MediathekView 13.1.3 bekommt unter Windows 7 dann den Fehler 
Error initializing QuantumRenderer: no suitable pipeline found
Caused by: java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
		
Man sollte also vielleicht einfach dazu schreiben: OpenJDK bisher nicht unterstützt (und wahrscheinlich unter Windows 7 niemals)	.

Diesen Issue kann man dann wohl schließen.

**Comment by tichachm** [comment]
Hallo,
wir haben es gerade ausprobiert, bei dieser OpenJDK Version ist JavaFX dabei (wenn man JavaFX und die Registrierung von .jar Dateien bei der Installation auswählt):
https://github.com/ojdkbuild/ojdkbuild
Achtung: JavaFX ist nur bei der Version 1.8.x dabei.
