### ISSUE TITLE
pc mit wenig Speicher erkennen (islowmemoryenvironmeng)

### ISSUE THREAD

**Issue by Kasperx** [mediathekview/MediathekView#346]
In der Klasse "MemoryUtils" wird der Speicher des PCs analysiert. Der Kommentar beschreibt, dass ein Speicher < 640MB als klein betrachtet wird. (Vielleicht ist ein Hinweis in der Berechnung gut, dass die Methode einen "byte"-Wert zurückgibt...)
Problem 1: Ich glaube, dass der Wert zu niedrig ist. Mein Xubuntu 18 mit 2 GB ram hat bei jedem Programmstart in der Konsole einen Ram-Fehler angezeigt. Dann stürzte das Programm ab.

**Comment by derreisende77** [comment]
Du hast schon gesehen das die Funktion keine Doku besitzt oder? Desweiteren ruft sie genau EINE Funktion auf, die javadoc hat. Daher ist durchaus schnell ersichtlich dass hier mit bytes gearbeitet wird.

Zu Problem 1: Von welcher Version redest du hier? Der Wert ist NICHT zu klein da 13.1 eine Datenbank nutzt und mit ungefähr 350MB RAM auskommen "kann". Schön ist das arbeiten mit 512MB nicht weil alles ewig langsam ist. 

Deine Probleme gehören bitte in das Forum und sind keine Diskussionspunkte für GitHub und auch keine Fehler.
