### ISSUE TITLE
Java Version

### ISSUE THREAD

**Issue by TheRealDarklord** [mediathekview/MediathekView#347]
Hallo liebes Team,

ich kann nicht ganz nachvollziehen, wieso MediathekView 13.0.6 noch mit Java 9 als auch Java 10 funktioniert, aber ab der 13.1.x plötzlich angegeben wird, dass nur explizit Java 8 zugelassen ist.

Ich hatte Java eigentlich immer als _die_ abwärtskompatible Sprache in Erinnerung. Wo liegt denn hier der Hase im Pfeffer?

Ich frage hier nicht mit einem vorwurfsvollen Tonfall, sondern würde gerne besser verstehen warum.

**Comment by styroll** [comment]
> ich kann nicht ganz nachvollziehen, wieso MediathekView 13.0.6 noch mit Java 9 als auch Java 10 funktioniert, aber ab der 13.1.x plötzlich angegeben wird, dass nur explizit Java 8 zugelassen ist.

Eigentlich ist das Forum dazu da, solche Fragen zu stellen. Dort findet sich auch [eine Antwort](https://forum.mediathekview.de/post/6079).

**Comment by TheRealDarklord** [comment]
Ah, danke.
