### ISSUE TITLE
Download Server wirft 503 Fehler

### ISSUE THREAD

**Issue by domrim** [mediathekview/MediathekView#349]
Ist kein direkter Bug, sondern ein Problem in Verbindung mit homebrew auf MacOS.
Wenn ich https://download.mediathekview.de/stabil/ oder auch https://download.mediathekview.de/stabil/MediathekView-13.1.3.dmg direkt aufrufe kriege ich manchmal einen 503 error-code zurück. Mit nem reload hat sich das dann meistens. Nur leider funktioniert daher die Installation über Homebrew Casks nicht, da curl nur den 503er bekommt.

**Comment by alex1702** [comment]
Ich denke mal homebrew-cask macht zu viele Abfragen. Ich hab den Download mit Limits beschränkt. Habe diese jetzt mal erhöht. kannste nochmal testen?

**Comment by domrim** [comment]
Hm, scheint nichts wirklich gebracht zu haben, von 3 versuchen hat einer funktioniert.
Auch das Reload-Verhalten ist immer noch vorhanden. Immer mal wieder werden 503er geworfen.

**Comment by alex1702** [comment]
siehe https://github.com/mediathekview/MediathekViewDE/issues/38
