### ISSUE TITLE
zweifaches Laden der Filmliste bei auskommentierten performUpdateCheck

### ISSUE THREAD

**Issue by alex1702** [mediathekview/MediathekView#351]
Wird in der FilmeLaden.java die Zeilen 200 und 201 auskommentiert, behebt das den Fehler in Issue #350 aber der Client lädt in Folge dessen die Filmliste 2 mal herunter.

**Comment by alex1702** [comment]
Nachtrag:

es hat nix mit der Methode zu tun. Jetzt ohne die filmliste.id auf dem Server lädt er bei jedem start 2 mal die FIlmliste herunter.

**Comment by derreisende77** [comment]
ist normal wenn Filmliste älter als 5Stunden
