### ISSUE TITLE
startet nicht unter openSUSE 42.3

### ISSUE THREAD

**Issue by 15knots** [mediathekview/MediathekView#352]
Erstmal Dank an die Autoren für die viele Mühe mit Mediathekview!

OS: openSUSE 42.3
JVM: OpenJDK 1.8.0_171 / 1.8.0_181

Die ersten 13.x Versionen hatten den Crash nicht, aber seit 3 Wochen crasht es.
MV crasht im native code, eine Web-Suche brachte da nix Erhellendes (in Form von JVM Optionen als Workaround) --> attachment [MVcrash.log](https://github.com/mediathekview/MediathekView/files/2325364/MVcrash.log)

Wenn ich das Verzeichnis `~/.mediathek3`lösche, erscheint kurz der initiale Einstellungsdialog, der aber ohne weiteres Zutun ebenfalls mit einem Crash endet --> 
[MVcrash-fiststart.log](https://github.com/mediathekview/MediathekView/files/2325380/MVcrash-fiststart.log)

In der Datei` hs_err_pid*.log` steht auch nix Erhellendes.

Ich vermute, dass MV eine Funktion in Java-FX aufruft, die noch nicht vollständig auf allen Plattformen getestet ist. Im bugzilla von openJDK ist jendefalls kein solcher Bug zu finden.

**Comment by derreisende77** [comment]
Versuche Mal Oracle jdk zu installieren und schau ob das stabil funktioniert. Openjdk hatte je nach Plattform eine gute Zeit lang Probleme und brauchte diverse Updates bis es stabil lief.

**Comment by 15knots** [comment]
Oracle jdk? Aber nur testweise, die haben immer noch die cryptograghy-export-restritions, was bei meinen Projecten immer für Issues sorgt.
Zusätzlich werde ich noch prüfen, welche Altversion von MV noch läuft, damit man bei openJDK Bescheid sagen kann.

**Comment by derreisende77** [comment]
Ich hatte bei Ubuntu 18.04 knapp 4 Wochen massive Probleme mit openjdk. Letztendlich habe ich Oracle jdk installiert. Die Probleme mit openjdk werden wohl noch eine Weile andauern. Zumal die Unterstützung von JavaFX derzeit da echt nicht gut aussieht. Das soll sich mit Java 11 bessern aber ich wage das erst Mal zu bezweifeln. MV benutzt bei Threads und so keine Besonderheiten

**Comment by 15knots** [comment]
https://github.com/mediathekview/MediathekView/issues/352#issuecomment-416349894
Oracle JRE  1.8.0_181-b13 mit MediathekView 13.1.3 unter openSUSE 42.3 funktioniert.
Scheint also eine Macke/Regression in openJDK/icedtea zu sein; schließlich ist das ja die Basis fpr Oracle JRE..

Aber Oracle JRE sehe ich **nicht** als Option/Workaround für Endbenutzer, das Ding klnkt sich ja nicht mal in `path` ein und ist für den update-alternatives-Mechanismus unsichtbar (mit dem kann mann mehrere JRE parallel installieren und den System-Default festlegen). Und für Oracle möchte ich mein System nicht verstrubbeln.

Werde mal MV 13.2 ausprobieren, vllt. hat sich das Problem dann erledigt.

BTW, es gibt auch RPMs mit MV für openSUSE: https://build.opensuse.org/package/show/home:syntron:MediathekView/MediathekView1306

**Comment by derreisende77** [comment]
Das jdk klinkt sich in path ein nicht das jre. Das ist richtig. 
Es gibt aber diverse Java Apps die von der Nutzung von openjdk abraten eben weil es nicht richtig funktioniert. Und da Open jdk bis vor kurzen nicht auf allen Plattformen verfügbar war ist es für MV bisher der Standard. 
Mit openjdk 11 wird sich das ändern und es wird der Standard für die Entwicklung. Bis dahin muss Oracle genutzt werden.
