### ISSUE TITLE
MediathekView mac 13.2 bundle identifier

### ISSUE THREAD

**Issue by core-code** [mediathekview/MediathekView#353]
hi there

in MediathekView 13.2 the bundle identifier ("CFBundleIdentifier" in the Info.plist file)
changed from
org.mediathek.MediathekView 
which sounds good and which it has 'always' been to
com.install4j.2884-1958-5872-3865.59
which sounds like a mistake.

is this on purpose or a bug?

**Comment by derreisende77** [comment]
Purpose.  We had to change the way we build the app and now it is done using intellij install4j.

**Comment by core-code** [comment]
ok thanks. 
will it now stay 'com.install4j.2884-1958-5872-3865.59' or be different for each release?

**Comment by derreisende77** [comment]
Good question. I don't know yet since this is the first release. But I try to keep it

**Comment by core-code** [comment]
perfect, thanks
