### ISSUE TITLE
MediathekView auf Snap

### ISSUE THREAD

**Issue by media233** [mediathekview/MediathekView#356]
Hallo,

wäre es möglich MediathekView im [Snapcraft](https://docs.snapcraft.io/build-snaps/java) Store zu veröffentlichen? Dann wäre es für Linux einfacher das Programm zu installieren.

**Comment by styroll** [comment]
Nur zur Info: Im Forum gab es eine [Diskussion in Sache AppImage](https://forum.mediathekview.de/post/1562).

**Comment by derreisende77** [comment]
Und bitte die Frage im Forum stellen...
