### ISSUE TITLE
Falsche Zeichen im User-Agent "blockien" alle Downloads | Incorrect characters in the user-agent "block" all downloads

### ISSUE THREAD

**Issue by DJCrashdummy** [mediathekview/MediathekView#360]
Wegen den ORF-Problemen habe ich vor längerer Zeit den User-Agent auf `Gebührenzahler` geändert und alles funktionierte wieder wie gewollt.
Selbiges habe ich noch einmal machen müssen nach dem Update auf 13.1.x...
_--> btw: Es wäre nett gewesen irgendwo zu erwähnen, dass der User-Agent beim Update auf 13.1.x nicht übernommen wird (das hätte einige Stunden an Recherche erspart)!_
...und jetzt funktioniert auf einmal (keine Ahnung seit welchem Update genau - verwende momentan 13.2.0) kein einziger Download, egal von welchem Sender!

Nach einigem herumprobieren ist klar, dass das `ü` im User-Agent den Start jedes Downloads verhindert/blockiert. Auch `"Gebührenzahler"` und `'Gebührenzahler'` funktioniert nicht. Einzig mit `Gebuehrenzahler` war ein Downloaden wieder möglich.
Interessant an der ganzen Geschichte - und was mich darin bestärkt, dass es ein Bug ist - ist, dass das Abspielen im VLC mit dem Zusatz `http-user-agent="Gebührenzahler"` sowohl vor als auch mit 13.1.x  und 13.2.0 funktioniert.

---

Because of the ORF problems, I changed the user agent to `"Gebührenzahler"` a long time ago and everything worked again as intended.
I had to do the same thing again after the update to 13.1.x ...
_-> btw: It would have been nice to mention somewhere that the user agent is not kept after the update to 13.1.x (that would have spared some hours of research)!_
...and now (no idea since which update exactly - i use currently 13.2.0) not a single download works, no matter what channel!

After some experimenting it is clear that the `ü` in the user agent prevents/blocks the start of each download. Also `"Gebührenzahler"` and `'Gebührenzahler'` does not work. Only with `Gebuehrenzahler` a download was possible again.
Interesting in the whole story - and what reinforces me that it is a bug - is, that playing in the VLC with the addition `http-user-agent="Gebührenzahler"` worked before and with 13.1.x and 13.2.0.

**Comment by alex1702** [comment]
In einen UserAgent gehören auch nur ASCII Zeichen. Schreib einfach ue anstatt ü. Sehe das jetzt nicht als wichtig hier an.

**Comment by alex1702** [comment]
Eventuell kommt ein kleiner Hinweis einfach oder eine Überprüfung. Werden wir im Team noch besprechen.

**Comment by DJCrashdummy** [comment]
> In einen UserAgent gehören auch nur ASCII Zeichen.

Ja, aber die Inkonsistenz zu den früheren Versionen macht das ganze ziemlich irritierend.

Und wenn die technische Beschränkung beabsichtigt bzw. by (Java-)Design ist, wäre ein Check oder zumindest ein Hinweis sehr hilfreich, anstatt einfach jeglichen Download kommentarlos zu verweigern.

> Sehe das jetzt nicht als wichtig hier an.

Da es mit alten Versionen funktionierte (habe es damals extra getestet) und auch immer noch mit VLC aus MediathekView heraus, sehe ich es als Regression bzw. Bug an, daher der Bugreport hier.
Über die Wichtigkeit bzw. die Prioritäten der in der Entwicklung zu entscheiden maße ich mir nicht an... sonst würde vermutlich jeder Reporter den Fix zu seinem Bug als wichtigsten überhaupt einstufen. :wink:

**Comment by shoeper** [comment]
ISO-8859-1 ist valide für die meisten HTTP Header, für Host auf jeden Fall (neue Header sollen auf US-ASCII beschränkt werden). (Diskussion dazu gibt's u.a. unter https://github.com/rack/rack/issues/764 (Englisch))

Damit ist `Gebührenzahler` zumindest nach den Standards gültig. Ob man das in diesem Fall für den Client braucht sei dahingestellt.

**Comment by derreisende77** [comment]
Die Behandlung des User Agent hat sich nicht geändert. Sie wird wie bisher bei allen Versionen einfach an den Empfänger weiter gereicht. Das einzig neue ist das es konfigurierbar ist. 
Und ich widerspreche dem Empfänger das es nett gewesen wäre auf die Änderung hinzuweisen. Früher war es eine system Einstellung die nicht User konfigurierbar war. Nun ist sie es. Sämtliche Änderungen davor waren rein system intern zu nutzen.

**Comment by DJCrashdummy** [comment]
> Die Behandlung des User Agent hat sich nicht geändert.

@derreisende77 ich kann mich (leider) nur auf das Ergebnis beziehen... und das hat sich definitiv geändert: :confused: 
Unter 13.0.x waren Downloads mit `Gebührenzahler` problemlos möglich, aber unter 13.1.x und 13.2.0 wird kein einziger (egal von welchem Sender) gestartet!

> Und ich widerspreche dem Ersteller das es nett gewesen wäre auf die Änderung hinzuweisen.

Naja... 1) **Nett** wäre es auf jeden Fall gewesen.
2) Ob bzw. in welcher Form es **nötig** gewesen wäre, kann man diskutieren...
3) Es hätte nicht unbedingt das Erste in den [Release Notes](https://mediathekview.de/changelog/13-1-0/) sein müssen, auch wenn es IMHO dort beim Punkt _"Der User-Agent für Downloads kann nun in den Einstellungen konfiguriert werden."_ recht gut gepasst und Keinem weh getan hätte.
4) Aber zumindest bei der bzw. den Anleitungen im Forum ([[1]](https://forum.mediathekview.de/topic/1337/aktuell-probleme-bei-orf-gel%C3%B6st), [[2]](https://forum.mediathekview.de/topic/1602/13-1-1-kann-in-%C3%B6sterreich-orf-nicht-downloaden) und [[3]](https://forum.mediathekview.de/topic/1508/orf-film-abspielen-mit-vlc-funtkioniert-nicht)) zu den Umstellungen (für 13.0.6) wäre eine Anmerkung absolut sinnvoll.

_--> btw: Dass eine Forum-Suche erst nach einer Anmeldung möglich ist, ist doch recht ungewöhnlich und kontraproduktiv!_ :slightly_frowning_face:  

> Früher war es eine system Einstellung die nicht User konfigurierbar war. Nun ist sie es.

Ja, ganz abgesehen von den Diskussionen um Kaisers Bart, zeigt sich aber leider auch da der Kern des Bugs: Wenn ein "Casual User" MV neu herunter lädt, installiert und diverse Einstellungen vornimmt (und dabei auch ein Umlaut im User-Agent landet) funktioniert zunächst alles wunderbar... Aber wenn er MV eine Woche später wieder verwenden will geht gar nichts mehr - ohne jeglicher Fehlermeldung oder auch nur Hinweis! Ein "Casual User" wird vermutlich nicht als erstes an den User-Agent denken, wenn er den Fehler überhaupt finden will und nicht gleich wieder MV frustriert deinstalliert.

**Comment by vitusson** [comment]
Und "Casual User" sind die, die als erstes den User Agent ändern, weil sie ihre infantile Anti-ÖR-Agenda verbreiten wollen, ist klar.

**Comment by pidoubleyou** [comment]
siehe https://github.com/square/okhttp/issues/4008
