### ISSUE TITLE
zu viele Debug-Ausgaben

### ISSUE THREAD

**Issue by buzo-ffm** [mediathekview/MediathekView#365]
_MediathekView_ (auf Linux) schreibt extrem viele Debug-Ausgaben nach _stdout_. Kann man das unterdrücken oder abschalten? Ich denke es wäre sinnvoll, wenn das explizit eingeschaltet werden müsste, wenn man es haben möchte (als Entwickler statt als Nutzer).

**Comment by buzo-ffm** [comment]
Klar kann ich das nach /dev/null umleiten, mache ich ja auch, aber erwartet ihr von jedem Anwender, dass er sich ein Wrapper-Skript bastelt, was das macht?
Ihr liefert doch schon ein Shell-Skript mit aus, könnt ihr das dort nicht einfach einbauen?

**Comment by derreisende77** [comment]
Viele Leute wollen/müssen die Ausgabe lesen und nur wenige nicht. Aber einer Anpassung des Skriptes durch dich steht ja nichts im Weg. Und es handelt sich nicht um debug messages sondern um Informationen was das Programm macht.
