### ISSUE TITLE
[Dokumentation/Feature-Request] Java-Kompatibilität

### ISSUE THREAD

**Issue by m-ueberall** [mediathekview/MediathekView#368]
Es wäre nett, wenn an zentraler Stelle eine kurze Erklärung hinterlegt würde, warum MediathekView ab Version 1.3.1.0 die Einschränkung "_Hinweis: MediathekView ist NICHT mit Java 9 und höher kompatibel! Es wird zwingend Java 8 vorausgesetzt._" erhielt, wenn Version 1.3.0.6 unter Ubuntu 18.04 – zumindest für alle von mir bislang durchgeführten Interaktionen mit dem Programm – problemlos mit _java full version "10.0.2+13"_ (via `ppa:linuxuprising/java`) funktioniert. Zunächst einmal sieht das nach einem wesentlichen Rückschritt aus, was die Kompatibilität anbelangt.

Eine "Wiederherstellung" der Kompatibilität wäre "noch netter".

**Comment by derreisende77** [comment]
Ist im Forum ausführlich erklärt worden. Es liegt an den genutzten Versionen einiger Java libs die nicht Java 9+ kompatibel sind. Das es geht ist dann insofern Zufall weil sie unter Linux nicht verwendet werden. Und wie du selbst festgestellt hast gilt das an 13.1.0 weil sich da vieles im vgl zu 13.0.6 geändert hat.
Und nein Rückschritt ist es nicht. Du darfst aber gerne deinen Dank an Ora le schicken für die ganzen Modifikationen bei Java 9.

**Comment by derreisende77** [comment]
Und es wird eine 13.3 geben die Java 9/10 tauglich ist. Java 11 ist derzeit explizit ausgenommen weil es dort wieder gravierende Änderungen gab die einige Teile nicht zuverlässig laufen lassen. Das können wir aber erst sehen wenn es raus ist und evtl die libs angepasst wurden.
