### ISSUE TITLE
Live Streams werden in Version 13.2.1 nicht angezeigt

### ISSUE THREAD

**Issue by RedirectCleaner** [mediathekview/MediathekView#371]
In der aktuellen Version (13.2.1) werden keine Live Streams mehr angezeigt auch wenn man nur nach Live Stream filtert werden keine Einträge angezeigt.

**Comment by pidoubleyou** [comment]
Bei mir sind die Livestreams vorhanden. Hast du irgendwelche anderen Filter wie Mindestlänge o.ä. aktiv?

Bitte solche Fragen das nächste Mal im [Forum](https://forum.mediathekview.de) stellen.

**Comment by RedirectCleaner** [comment]
stimmt, jetzt gehts, wäre super wenn live streams trotz der mindestlänge angezeigt werden würden. 

>Bitte solche Fragen das nächste Mal im Forum stellen. 

Wird gemacht

**Comment by derreisende77** [comment]
Das konterkariert aber das Filterpanel. Das ist ja dazu alles zu filtern was Du eingestellt hast. Da kann es dann schon vorkommen das Einträge verschwinden.
Es wäre besser die Livestreams aus dem Tab zu entfernen und separat darzustellen.
