### ISSUE TITLE
Mediathekview aus Terminal

### ISSUE THREAD

**Issue by f2818331** [mediathekview/MediathekView#372]
Ich benutze Programme gerne in einem Terminal. Damit ich Mediathek-View (MV) auch so bedienen kann, hätte ich einen Feature-Requests:

**Liste aller Videos in der Mediathek speichern**: Ich habe gelernt, dass irgendwo ein `json` mit genau diesen Daten aktualisiert wird. Ich würde MV gerne so starten, dass nur dieses `json` aktualisiert wird.
Ohne GUI Interaktion. Am besten noch an einem von mir (per Parameter) definierten Ort.

Das wäre alles. Das Features wäre toll, um MV wiederum in anderen Skripten zu verwenden.

**Comment by alex1702** [comment]
sollte mit -auto und dann angabe des Profilpfades am Ende funktionieren.
Siehe:
https://mediathekview.de/anleitung/#starten-im-portablen-modus-mediathekview-portable
und: 
https://mediathekview.de/anleitung/#auto
