### ISSUE TITLE
Dateiname aus Thema + Titel generieren

### ISSUE THREAD

**Issue by commaender** [mediathekview/MediathekView#373]
Ich würde mir eine (optionale) Option wünschen, dass der Download die Dateien direkt anhand des Thema + Titels benennen könnte, ohne die kryptischen Dateinamens-Angaben wie es jetzt ist. Das würde einiges an Suche (wenn mehrere ähnliche Folgen geladen werden) und manuelle Umbenennungen ersparen.

Also Beispielsweise Benennung als "Kabarett Comedy - Olaf Schubert. Sexy forever.mp4" statt jetzt "Kabarett _ Comedy-Olaf Schubert_ Sexy forever-180930_3satfestival2018_olaf_schubert_kabarett_232.mp4".

Sinnvoll wäre (u.U. je nach Abo getrennt) eine Benennungregel mit Variablen (etwa als "{thema} - {titel}" der "{sender} {titel}", sowie eine Ersetzungsregel für nicht-erlaubte Sonderzeichen (Schrägstriche, Doppelpunkte, etc.).

**Comment by derreisende77** [comment]
Gibt es schon.[Handbuch](https://mediathekview.de/anleitung/#eigene-aufnahme-und-abspielsets-einrichten-f%C3%BCr-fortgeschrittene-benutzer)
