### ISSUE TITLE
fehlende Buttons im Filmtab

### ISSUE THREAD

**Issue by flaun** [mediathekview/MediathekView#375]
Hallo,
habe heute auf die aktuelle Version 13.2.1 aktualisiert.
Im Tab Filme fehlt bei mir die Anzeige sämtlicher Buttons (siehe Fotos). 
In den Tabs Downloads und Abos werden alle Buttons richtig angezeigt. Ist dieses Problem bekannt? Workaround?

Ubuntu 16.04 32bit
![mediathekview 13 2 1 - fehlende buttons](https://user-images.githubusercontent.com/28860284/46730379-4466b380-cc88-11e8-8e41-45bad672ebf3.png)

Vielen Dank für die Hilfe

**Comment by derreisende77** [comment]
In der Regel liegt das daran das Java 8 nicht installiert ist bzw nicht genutzt wird. 
Was sagt denn 'java -version' als Ausgabe?

**Comment by flaun** [comment]
`openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
OpenJDK Server VM (build 25.181-b13, mixed mode)`

vielen Dank für die schnelle Hilfe

**Comment by derreisende77** [comment]
Funktioniert es jetzt?

**Comment by flaun** [comment]
Immer noch alles gleich!
Hab ja nichts geändert und nur die Ausgabe von 'java -version' gepostet

**Comment by derreisende77** [comment]
Kannst du den Inhalt von MediathekView.log Posten? Evtl sieht man da Fehler drin

Von meinem iPhone gesendet

**Comment by derreisende77** [comment]
Da keine Fehler drin stehen bleibt eigentlich nur zu testen ob es mit Oracle Java funktioniert. Openjdk macht bisher immer wieder unsinnige Fehler die mit Oracle nicht da sind.

Wenn du das Programm aus dem Terminal startest kommen da evtl irgendwelche exceptions?

**Comment by flaun** [comment]
Das ist die Ausgabe des Terminals beim Programmstart:

> . Portable Mode: false
. Proxy Authentication: not configured
. Programmstart: 15.10.2018 12:46:45
. maxMemory: 943 MB
. Version: MediathekView 13.2.1
. Java:
. Vendor: Oracle Corporation
. VMname: OpenJDK Server VM
. Version: 1.8.0_181
. Runtimeversion: 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13
. Programmpfad: /opt/MediathekView/
. Verzeichnis Einstellungen: /home/florian/.mediathek3
. 
. 
. 
. ========== ========== ========== ========== ==========
. DURATION 0:  Start  [972,00 ms]
.    Klasse:  Main.getPlatformWindow
. ========== ========== ========== ========== ==========
.  
.  =======================================
.  Systemparameter
.  -----------------
.  Download-Timeout [s]: 250
.  max. Download-Restart: 5
.  max. Download-Restart-Http: 10
.  Download weiterführen in [s]: 60
.  Download Fehlermeldung anzeigen [s]: 120
.  Downoadprogress anzeigen: true
.  User-Agent: MediathekView
.  =======================================
.  
. Konfig wurde gelesen!
. ========== ========== ========== ========== ==========
. DURATION 1:  Start Gui  [958,00 ms]
.    Klasse:  Main.getPlatformWindow
. ========== ========== ========== ========== ==========
. initializeDatabase()
. initializeDatabase() done.
. ========== ========== ========== ========== ==========
. DURATION 2:  Init GUI  [12,53 s]
.    Klasse:  Main.getPlatformWindow
. ========== ========== ========== ========== ==========
. ========== ========== ========== ========== ==========
. DURATION 3:  Gui steht!  [1,01 s]
.    Klasse:  Main.getPlatformWindow
. ========== ========== ========== ========== ==========


Sehe da jetzt auch keinen Fehler! Dachte es wäre vielleicht einfach, aber ansonsten komme ich schon auch klar....
Vielen Danke
