### ISSUE TITLE
MV 13.2.1 merkt sich Fensterposition nicht korrekt

### ISSUE THREAD

**Issue by LigH-de** [mediathekview/MediathekView#376]
Wenn ich MV 13.2.1 nicht maximiert, sondern als normales Fenster (z.B. “nebeneinander angeordnet” fast über den ganzen Desktop) beende, wird beim nächsten Öffnen die linke obere Ecke des Fensters etwa in der Mitte des Desktops positioniert, danach die Größe wiederhergestellt - mit dem Ergebnis, dass das Fenster rechts unten aus dem Desktop herausragt.

![mv_quit](https://user-images.githubusercontent.com/5917225/46864936-10bc9280-ce1c-11e8-952f-92f9f2da0fa0.jpg)
![mv_open](https://user-images.githubusercontent.com/5917225/46864946-17e3a080-ce1c-11e8-9296-d106116143b6.jpg)

Schließe ich das Programm maximiert, startet es auch wieder maximiert; wenn ich dann das Fenster “verkleinere”, schrumpft es zu einem winzigen Fensterchen in der Mitte des Desktops.

![mv_tiny](https://user-images.githubusercontent.com/5917225/46865063-79a40a80-ce1c-11e8-9e90-6e89290def59.jpg)

**Comment by derreisende77** [comment]
im nächsten release gefixt, ab morgen in den nightlies vorhanden
