### ISSUE TITLE
Ubuntu 18.04, MediathekView 13.2.1: java.lang.UnsupportedOperationException: Unable to open DISPLAY

### ISSUE THREAD

**Issue by kuehnelbs** [mediathekview/MediathekView#379]
Bei mir die gleiche Fehlermeldung wie bei #367, GUI startet nicht
- Ubuntu 18.04.1 LTS 64Bit
- Open-jdk 1.8.0_181
- Speicher 15,6 GB
- Prozessor: i5-7200U
- Grafik: Intel HD Graphics 620 (KabyLake GT2)
- Gnome 3.28.2

Zuvor werwendete Version 13.0.6 (aus offiziellem RePo)

___  ___         _ _       _   _          _    _   _ _               
|  \/  |        | (_)     | | | |        | |  | | | (_)              
| .  . | ___  __| |_  __ _| |_| |__   ___| | _| | | |_  _____      __
| |\/| |/ _ \/ _` | |/ _` | __| '_ \ / _ \ |/ / | | | |/ _ \ \ /\ / /
| |  | |  __/ (_| | | (_| | |_| | | |  __/   <\ \_/ / |  __/\ V  V / 
\_|  |_/\___|\__,_|_|\__,_|\__|_| |_|\___|_|\_\\___/|_|\___| \_/\_/  

. Portable Mode: false
. Proxy Authentication: not configured
. Headless environment detected but -auto was not specified.
MediathekView wurde nicht als Kommandozeilenprogramm gestartet.
Startmodus wurde auf -auto ge?ndert.

. java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
. Programmstart: 14.10.2018 12:06:40
. maxMemory: 954 MB
. Version: MediathekView 13.2.1
. Java:
. Vendor: Oracle Corporation
. VMname: OpenJDK 64-Bit Server VM
. Version: 1.8.0_181
. Runtimeversion: 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13
. Programmpfad: /home/torsten/MediathekView-13.2.1/
. Verzeichnis Einstellungen: /home/torsten/.mediathek3
. 
. 
. 
. Einstellungen laden: /home/torsten/.mediathek3/mediathek.xml
.  
.  =======================================
.  Systemparameter
.  -----------------
.  Download-Timeout [s]: 250
.  max. Download-Restart: 5
.  max. Download-Restart-Http: 10
.  Download weiterf?hren in [s]: 60
.  Download Fehlermeldung anzeigen [s]: 120
.  Downoadprogress anzeigen: true
Exception in thread "DummyFXApp Thread" java.lang.UnsupportedOperationException: Unable to open DISPLAY
	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:68)
	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at com.sun.glass.ui.Application.run(Application.java:146)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:257)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
.  User-Agent: MediathekView
.  =======================================
.  
. Liste Filme lesen von: /home/torsten/.mediathek3/filme.json
. initializeDatabase()
. initializeDatabase() done.
. Creating SQL indices
. Finished creating SQL indices
. Liste Filme gelesen am: 14.10.2018, 12:06
.   erstellt am: 14.10.2018, 11:15
.   Anzahl Filme: 249936
. Die Filmliste ist 50 Minuten alt
. aktuelle Filmliste verwenden
. ========== ========== ========== ========== ==========
. DURATION 0:  Abo in Filmliste eintragen  [4.77 s]
.    Klasse:  MediathekAuto.starten
.    Abo in Filmliste eintragen Anzahl: 1   Dauer: 4.77 s
. ========== ========== ========== ========== ==========

Ab hier geht's nicht mehr weiter (Abbruch mit Strg+C)

Ich habe dann wie beschrieben die Version auf Dropbox versucht:

___  ___         _ _       _   _          _    _   _ _               
|  \/  |        | (_)     | | | |        | |  | | | (_)              
| .  . | ___  __| |_  __ _| |_| |__   ___| | _| | | |_  _____      __
| |\/| |/ _ \/ _` | |/ _` | __| '_ \ / _ \ |/ / | | | |/ _ \ \ /\ / /
| |  | |  __/ (_| | | (_| | |_| | | |  __/   <\ \_/ / |  __/\ V  V / 
\_|  |_/\___|\__,_|_|\__,_|\__|_| |_|\___|_|\_\\___/|_|\___| \_/\_/  

. Portable Mode: false
. Proxy Authentication: not configured
. Headless environment detected but -auto was not specified.
MediathekView wurde nicht als Kommandozeilenprogramm gestartet.
Startmodus wurde auf -auto ge?ndert.

. java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
. Programmstart: 14.10.2018 12:14:02
. maxMemory: 954 MB
. Version: MediathekView 13.2.1
. Java:
. Vendor: Oracle Corporation
. VMname: OpenJDK 64-Bit Server VM
. Version: 1.8.0_181
. Runtimeversion: 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13
. Programmpfad: /home/torsten/MediathekView-13.2.1/
. Verzeichnis Einstellungen: /home/torsten/.mediathek3
. 
. 
. 
. Einstellungen laden: /home/torsten/.mediathek3/mediathek.xml
.  
.  =======================================
.  Systemparameter
.  -----------------
.  Download-Timeout [s]: 250
.  max. Download-Restart: 5
.  max. Download-Restart-Http: 10
.  Download weiterf?hren in [s]: 60
.  Download Fehlermeldung anzeigen [s]: 120
.  Downoadprogress anzeigen: true
Exception in thread "DummyFXApp Thread" java.lang.UnsupportedOperationException: Unable to open DISPLAY
	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:68)
	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at com.sun.glass.ui.Application.run(Application.java:146)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:257)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
.  User-Agent: MediathekView
.  =======================================
.  
. Liste Filme lesen von: /home/torsten/.mediathek3/filme.json
. initializeDatabase()
. initializeDatabase() done.
. Creating SQL indices
. Finished creating SQL indices
. Liste Filme gelesen am: 14.10.2018, 12:14
.   erstellt am: 14.10.2018, 11:15
.   Anzahl Filme: 249936
. Die Filmliste ist 58 Minuten alt
. aktuelle Filmliste verwenden
. ========== ========== ========== ========== ==========
. DURATION 0:  Abo in Filmliste eintragen  [5.62 s]
.    Klasse:  MediathekAuto.starten
.    Abo in Filmliste eintragen Anzahl: 1   Dauer: 5.62 s
. ========== ========== ========== ========== ==========
. ========== ========== ========== ========== ==========
. DURATION 1:  Blacklist filtern  [119.00 ms]
.    Klasse:  MediathekAuto.starten
.    Blacklist filtern Anzahl: 1   Dauer: 118.00 ms
. ========== ========== ========== ========== ==========
. Filme in Downloads eintragen
. 0 Filme zum Laden
. 
. ################################################################################
. -------------------------------------------------------
. Einstellungen sichern
. Einstellungen wurden heute schon gesichert
. -------------------------------------------------------
. Daten Schreiben nach: /home/torsten/.mediathek3/mediathek.xml
. Config Schreiben nach: /home/torsten/.mediathek3/mediathek.xml startet
. Config Schreiben beendet
. 
. 
. 
. 
.  
.  ################################################################################
.   Keine Fehler :)
.  ################################################################################
. 
. 
. ################################################################################
.    --> Beginn: 14.10.2018 12:14:02
.    --> Fertig: 14.10.2018 12:14:28
.    --> Dauer[Min]: <1
. ################################################################################

Danach Rückkehr zur Konsole.

**Comment by derreisende77** [comment]
Wenn du es ohne GUI betreiben willst musst du die passenden Parameter verwenden:
'java -Xmx1G -jar XXX.jar -auto'

**Comment by derreisende77** [comment]
Und offensichtlich hat die Dropbox Version sich regulär beendet weil keine Downloads da waren. Vorher wurde Liste aktualisiert. Ist also kein Fehler erkennbar sondern alles normal.

**Comment by kuehnelbs** [comment]
Danke. Meine irrige Annahme war, dass ich mit Aufruf des Shell-Scriptes das Programm mit GUI von der Konsole aus starten kann. Habe jetzt einen Starter erstellt und es funzt.
