### ISSUE TITLE
Synchroner Auto Modus

### ISSUE THREAD

**Issue by g3723387** [mediathekview/MediathekView#383]
Ich verwende MV in der Regel im `-auto` modus; das vor allem unter Windows (falls es einen Unterschied macht).

Dabei ist mir aufgefallen, dass mein Aufruf
```
MediathekView.exe tmp -auto
```
immer sofort fertig ist, MV dann aber "asynchron" (vermutlich in einem Fork) das eigentliche Update im Hintergrund durchführt. Wenn man das per Hand in der Konsole macht, sieht man zB die Log-Meldungen aus dem Hintergrund.

Gibt es einen Weg, MV mit synchronem `-auto` zu starten? D.h. ich würde gerne MV so starten, dass der MV Prozess erst beendet wird, wenn das Update auch tatsächlich fertig ist. Falls nein, wäre das ein Feature-request.

**Comment by derreisende77** [comment]
Da es keinen Maintainer für die CLI Version mehr gibt ist ab 13.3 kein CLI Modus erstmal mehr verfügbar. Evtl wird es zukünftig wieder eine getrennte CLI Version geben.
