### ISSUE TITLE
Keine Neuen ORF Daten seit 19.10.2018 12:00

### ISSUE THREAD

**Issue by AlbertMaria** [mediathekview/MediathekView#384]
Seit obigen Datum sind keine neuen Einträge vom ORF vorhanden.
Welchen Grund kann es dafür geben?

Liebe Grüße

**Comment by pidoubleyou** [comment]
siehe https://forum.mediathekview.de/topic/1882/filmlistenprobleme-behoben-und-aktuell-kein-orf

Details in diesem [Github-Ticket](https://github.com/mediathekview/MServer/issues/427)

**Comment by AlbertMaria** [comment]
Danke, haben den Eintrag nicht gesehen.
Schönen Abend.
