### ISSUE TITLE
alte GUI war in Teilen besser

### ISSUE THREAD

**Issue by scytho** [mediathekview/MediathekView#385]
Hallo,

es ist inzwischen ein wenig unübersichtlich geworden, wo man nun Verbesserungsvorschläge für die GUI anbringen soll, deswegen schreibe ich es hier, wo ich einen Account habe.

Ich fand die alte GUI besser, was die Filterung in der Liste der Filme (Reiter/Tab Filme) angeht. Da hatte man am linken Rand alles zur Hand. Jetzt (13.2.1) muß man auf dieses seltsame Symbol oben rechts klicken, um in einem Popup nach Sendern usw. zu filtern. Das macht das Suchen deutlich umständlicher und unübersichtlicher.

Außerdem gab es früher bei der Downloadliste einen Schieberegler für die Downloadgeschwindigkeit. Warum schafft man soetwas ab? Jetzt hat man nur noch die Möglichkeit in ein Textfeld zuklicken, mit der Hand zur Tastatur zu wechseln, Zahlen einzugeben und auf Enter zu drücken. Das ist viel umständlicher und dauert viel länger.

**Comment by Nicklas2751** [comment]
Das Thema wurde 1000 Fach im [Forum](https://forum.mediathekview.de) besprochen.
