### ISSUE TITLE
ORF: "%N" (Originaldateiname des Films) liefert immer nur "playlist.m3u8"

### ISSUE THREAD

**Issue by novoid** [mediathekview/MediathekView#388]
Hi,

Bug original [bei MServer eingelastst](https://github.com/mediathekview/MServer/issues/436) und dann hierher kopiert.

## Problembeschreibung

Wenn ich mit meinem MV 13.2.1 (Debian GNU/Linux) als Zieldateiname der Downloads `%DT%d %s - %t - %T -ORIGINAL- %N.mp4` angebe, dann wird `%N` nicht mit einem sinnvollen Originaldateinamen, sondern immer nur mit dem konstanten String `playlist.m3u8` ersetzt.

Die anderen Ersetzungen aus meinem Dateinamen-String funktionieren wie gehabt.

### Womit das Problem auftauchte

Womit/wann das entstanden ist, kann ich nicht sagen, da ich im Zuge der aktuellsten ORF-Probleme auch von MV 10.x auf MV 13 umgestiegen bin und ich mir damit zumindest eine Sache eingehandelt habe, die MV 13 leider nicht out-of-the-box korrekt mitbringt und schon länger _irgendwo_ gelöst worden ist (#435).

Dass sich ein simpler User schwer tut, zu Problemen im Forum die passenden News und Workarounds  zu finden, ist eine andere Geschichte. 😞

### Eine unqualifizierte Schätzung

Von Seiten des Forums wie [diese da](https://forum.mediathekview.de/topic/1887/orf-hat-wieder-umgestellt/25?page=2) leite ich ohne tiefere Kenntnis der Vorgänge ab, dass beispielsweise 
`https://apasfiis.sf.apa.at/ipad/cms-worldwide/2018-10-22_1402_tl_02_Schmeckt-perfek_Paul-Ivicherz__13992854__o__1037693653__s14383895_5__ORF2HD_14021514P_14140102P_Q8C.mp4/playlist.m3u8` 
durch den letzten Bindestrich "falsch aufgelöst" wird. Also zumindest ohne der Detailinformation, die im Pfad aber nicht im letzten Dateinamen zu finden ist.

Das deutet IMHO darauf hin, dass `%N` besser mit dem String zwischen den beiden letzten Schrägstrichen befüllt werden sollte, denn das sieht ganz nach dem String aus, den ich bis vor einer Woche mit MV v10 für `%N` erhalten habe: 
`2018-10-22_1402_tl_02_Schmeckt-perfek_Paul-Ivicherz__13992854__o__1037693653__s14383895_5__ORF2HD_14021514P_14140102P_Q8C.mp4`

## Warum %N sehr relevant ist

Zitate sind von [hier](https://github.com/mediathekview/MServer/issues/436#issuecomment-435012357) übernommen.

### Mehrwert von %N

> %N liefert selten einen Mehrwert gegenüber "Titel und Thema"

Au contraire: `%N` war die einzig verbliebene Möglichkeit, die einzelnen Beiträge mehrteiliger Sendungen (zB: ZIB) in ihre originale Reihenfolge zu bringen, dachdem auch diese MV-spezifische Indexnummer aus mir unverständlichen Gründen aus den Variablen gestrichen wurde: [MServer issue 361](https://github.com/mediathekview/MServer/issues/361)

Von meinem Beispiel oben: `2018-10-22_1402_tl_02_Schmeckt-perfek_Paul-Ivicherz__13992854__o__1037693653__s14383895_5__ORF2HD_14021514P_14140102P_Q8C`

Hier kann man schön rausparsen, dass die Sendung exakt um 14 Uhr 2 Minuten und 15 Sekunden begonnen hat und um 14 Uhr 14 Minuten und eine Sekunde fertig war. MIt Tools wie [guessfilename](https://github.com/novoid/guess-filename.py) kann man dann wirklich sinnvolle Dateinamen nachträglich bauen lassen.

### Beispiel zur Veranschaulichung

Mit der MV-Einstellung `%DT%d %s - %t - %T -ORIGINALhd- %N.mp4` erzeugte ich mittels funktionierendem `%N` Dateinamen wie `20180510T090000 ORF - ZIB - Signation -ORIGINAL- 2018-05-10_0900_tl_02_ZIB-9-00_Signation__13976423__o__1368225677__s14297692_2__WEB03HD_09000305P_09001400P_Q4A.mp4` die dann mittels [guessfilename](https://github.com/novoid/guess-filename.py) in brauchbaren Dateinamen wie `2018-05-10T09.00.03 ORF - ZIB - Signation -- lowquality.mp4` endeten. Die sind human-readable und bringen die einzelnen ZIB-Beiträge in ihre _ursprüngliche Reihenfolge_, wenn man die Dateien nach deren alphabetischer Reihenfolge abspielt. Wie man hier auch sieht, stimmt die Startzeit mittels `%d` keinesfalls mit der wirklichen Startzeit im Originaldateinamen überein: alle Beiträge der ZIB teilen sich die identen `%d`. Damit geht der _Verlust der Reihenfolge_ einher.

### %N ist nicht entfernt worden und sollte IMHO sinnvoll verwendet werden

> deshalb wurde %N vor einigen MV-Versionen auch aus dem Default-Set entfernt.

Mein MV listet nach wie vor in der Hilfe die `%N`-Variable - sie ist also in den Binaries noch nicht entfernt worden. Meine Bitte ist nun, sie wieder gemäß der Hilfeseite mit dem Originaldateinamen zu befüllen. Wenn der ORF beschlossen hat, den Originaldateinamen nicht als Dateiname sondern als Pfadbestandteil zu listen, so sollte MV so flexibel sein, und für den ORF den Originaldateinamen aus dem Pfad herausparsen und per `%N` zur Verfügung stellen. Schlußendlich beinhaltet dieser Originaldateiname durchaus sehr viel Information, die man ansonsten nirgends mehr rausbekommt. Man muss sich nur ein wenig mit dem Reverse-Engineering von der "kryptischen Zeichenfolge" beschäftigen und Sender-spezifisch doch Sinnvolles rausbekommen.

### Fazit

Der Originaldateiname ist die einzig verbliebene Möglichkeit, beim ORF die Reihenfolge bzw. die tatsächlichen Beginnzeiten zu rekonstruieren. Daher ist meiner Meinung nach ein "semantisch funktionierender" Originaldateiname per `%N` unerlässlich.

## Alternativvorschlag

Alternativ kann MV als **zusätzliche** Variable Zugriff auf einen sanitized original URL (beispielsweise `%U`) geben, damit ich mir die notwendigen Infos notfalls selber aus dem vollständigen Pfad, der die Detailinformationen beinhaltet, parsen kann.

**Comment by styroll** [comment]
Hier auch nochmals folgender Hinweis aus dem geschlossenen Thread:

Das Problem liegt auch bei SRF-Sendungen vor, welche auch FFmpeg benötigen bzw. bei welchen die Playlist-URLs ähnliche Syntax aufweisen:
`…myschool_20161018_090020_v_webcast_h264_,q40,q10,q20,q30,.mp4.csmil/index_0_av.m3u`
Dort resultiert auch nur:
[index_0_av.m3u](url)

**Comment by derreisende77** [comment]
wird in 13.3 behoben sein und dem Vorschlag entsprehend den namen davor liefern ohne Extension
