### ISSUE TITLE
Download Phoenixsee

### ISSUE THREAD

**Issue by Seth-Gecko** [mediathekview/MediathekView#389]
Der Download der Serie **Phoenixsee** bricht für alle Episoden leer ab (aus der **WDR**-Mediathek). Die ARD-Downloads funktionieren. Die Episoden direkt abspielen über den Play-Button funktioniert.

Getestet mit 13.0.1 aus dem Debian Repository und einem git-build, den ich vorhin aus github gezogen habe.

Außerdem wird "Phoenixsee (6/6)" noch nicht in der Liste angezeigt, obwohl in der ARD-Mediathek abrufbar. Ich vermute, dass ich hier noch auf eine Aktualisierung der Filmliste warten muss.

Cooles Tool, funktioniert insgesamt sehr gut! :)

**Comment by Nicklas2751** [comment]
Solche Themen gehören ins Forum. Dort wird dieses auch bereits behandelt: https://forum.mediathekview.de/topic/1947/phoenixsee-folge-6/13

**Comment by Nicklas2751** [comment]
Solche Themen gehören ins Forum. Dort wird dieses auch bereits behandelt: https://forum.mediathekview.de/topic/1947/phoenixsee-folge-6/13
