### ISSUE TITLE
Download mit Proxy funktioniert nicht mit Release 13.2.1 

### ISSUE THREAD

**Issue by Sethur** [mediathekview/MediathekView#390]
Hallo,

mit Release Version 13.2.1 funktionert der Download einzelner Videos über einen Proxy nicht mehr, der Download der Filmliste klappt hingegen. Bei Version 13.0.6 funktionierte noch alles einwandfrei. Ich vermute, dass zum Download der Filme eine andere Subroutine angestoßen wird, an die der Proxy nicht weitergegeben wird.

Im Gegensatz zur älteren Version kann man bei 13.2.1 den Proxy auch direkt in den Einstellungen angeben, oder aber man verwendet die Kommandozeile und startet mittels `java -DproxySet=true -DproxyHost=x.x.x.x -DproxyPort=xxxx -jar ./MediathekView.jar`. Bei mir macht das aber keinen Unterschied, der Filmdownload hängt so oder so, auch wenn man beides auf einmal angibt.

**Comment by habazut** [comment]
Bei mir funktioniert es _teilweise_:

Was funktioniert:
  * http und "Film aufzeichnen"

Was nicht funktioniert (tcpdump zeigt mir das nicht alle Pakete zum Proxy gehen):
 * http und "Film abspielen"
 * https (weder aufzeichnen noch abspielen)

Ich habe mit wget verifiziert dass mein Proxy für die angegebenen URLs funktioniert.

Ich habe den Proxy sowohl in den Einstellungen als auch auf der Kommandozeile angegeben.

Mfg,
Harald.

**Comment by derreisende77** [comment]
Es werden an VLC keine Proxy Informationen übergeben. Diese können aber über die pset eingetragen werden

**Comment by habazut** [comment]
An VLC könnte man mit --http-proxy=IP:PORT diese Information weiter geben. Wenn das nicht gemacht wird dann erklärt das warum "Abspielen" nicht geht.

Das erklärt aber nicht warum der Download bei http funktioniert, bei https aber nicht.

Mfg,
Harald.

**Comment by derreisende77** [comment]
Die Parameter für http sind http.proxyPort bzw http proxyHost. Gut HTTPS sind statt http. https. Zu verwenden. Dies bezieht sich auf MV und hat nichts mit VLC zu tun. Warum HTTP funktioniert und HTTPS nicht liegt Ana Java da es zwei verschiedene Parametersätze verwendet. In der nächsten Version verwenden wir eine andere Bibliothek die besser mit Proxy harmonieren sollte

**Comment by habazut** [comment]
Ich glaube ich habe verstanden was du meinst. Wenn man MV so (siehe unten) startet dann funktioniert der eingebaute Proxy der Javalib für Download sowohl für http als auch für https:

PROXYHOST=1.2.3.4
PROXYPORT=8080
java -jar \
    -Dhttp.proxyHost=$PROXYHOST \
    -Dhttp.proxyPort=$PROXYPORT \
    -Dhttps.proxyHost=$PROXYHOST \
    -Dhttps.proxyPort=$PROXYPORT \
     ./MediathekView.jar

Wenn man in den Einstellungen einen HTTP(S) Proxy parameter anbietet dann muss man überlegen ob man das für http und https gemeinsam oder seperat macht und wie man es an Programme die von MV aufgerufen werden wenn notwendig weitergibt.

Mfg,
Harald.

**Comment by derreisende77** [comment]
Also in den Einstellungen ist von HTTP-Proxy die Rede, nicht von HTTPS. In 13.3 wird eine andere Netzwerkbibliothek verwendet dann sollte das Problem beseitigt sein.
Da die PSet durch den Nutzer konfigurierbar sind was die verwendeten Programme anbetrifft ist eine Übergabe von Proxy Parametern nicht realisierbar da das Programm kein Hellseher sein kann. Wenn man schon einen Proxy oder eine sonstige exotische Konfiguration nutzt muss man schon ein wenig Eigeninitiative leisten damit es erfolgreich funktioniert. Das wird einem auch keine andere Software abnehmen.

**Comment by habazut** [comment]
> In 13.3 wird eine andere Netzwerkbibliothek verwendet dann sollte das Problem beseitigt sein.

Na dann.

> Da die PSet durch den Nutzer konfigurierbar sind

Sind sie. Aber im GUI steht "Vlc". Also kann man einen vlc mit Parameter --http-proxy erwarten. Den braucht man ja sowieso nur auszugeben wenn ein HTTP Proxy konfigurieret ist. Auch mpv unterstützt seit kurzem --http-proxy.

Ob ein sogenannter "HTTP Proxy" für http oder für http und https zuständig ist, darüber wird man sowieso keinen weltweiten Konsensus finden. Siehe z.B. wget (verschiedene Parameter) und vlc (ein Parameter für alles).

Mfg,
Harald.

PS: Vielleicht wird auch dem einen oder anderen mit "exotischer Konfiguration" dieser Thread helfen.
;-)
