### ISSUE TITLE
MV lädt zuerst die komplette Filmliste um dann festzustellen dass sie zu alt ist

### ISSUE THREAD

**Issue by scubasunny** [mediathekview/MediathekView#391]
Beim Start lädt MV erst die komplette Filmlist (aktuell ca. 150kB) um dann festzustellen dass die Liste zu alt ist, dann erfolgt der Download um dann wieder neu eingelesen zu werden.

Das dauert natürlich etwas lange (natürlich abhängig vom Computer ;-)

Wäre es nicht logischer den Zeitstempel der Filmliste zuerst zu überprüfen, dann gegebenenfalls die neue Liste zu downloaden um dann erst in MV einzulesen?

**Comment by derreisende77** [comment]
Das ist grundsätzlich richtig aber es werden noch ein paar Informationen mehr daraus geladen die im Anschluss benötigt werden. Daher ist es schon sinnvoll diese zu nutzen
