### ISSUE TITLE
[INFO] macOS: IINA statt VLC

### ISSUE THREAD

**Issue by JayBrown** [mediathekview/MediathekView#392]
Statt VLC kann man auch den Media-Player **[IINA](https://github.com/lhc70000/iina)** für das Set "Mac abspielen" verwenden, z.B. mit dem Pfad `/Applications/IINA.app/Contents/MacOS/iina-cli`. Wichtig ist, dass `iina-cli` als Executable benutzt wird.

Es wäre also eigentlich vernünftig, in den MV-Preferences unter "Programme" nicht den String "Vlc", sondern "Media-Player" zu benutzen.

PS: warum eigentlich "Vlc", und nicht "VLC"?

**Comment by styroll** [comment]
> @JayBrown sagte: Es wäre also eigentlich vernünftig, in den MV-Preferences unter "Programme" nicht den String "Vlc", sondern "Media-Player" zu benutzen.

Das wäre überhaupt nicht hilfreich: MV ist vorkonfiguriert (Set Abspielen und Set Speichern) für die Benützung von VLC, welchen es auf macOS, Linux und Windows gibt. Für andere Medienplayer brauchst du andere Sets bzw. andere Schaltereinstellungen. Das schöne ist doch, dass MV so flexibel ist, auch andere Medienplayer zuzulassen. Dazu erstellt man einfach ein eigenes Set.

Immerhin scheint der IINA-Player ein interessantes Projekt zu sein. Ich benutze selbst mpv, auf dem dieser Player ja basiert.
