### ISSUE TITLE
ORF downloads not working at all

### ISSUE THREAD

**Issue by AlexVienna** [mediathekview/MediathekView#394]
With version 13.2.1 complete new fresh install no ORF download is working any more. See attached log file please. 
[mediathekview.log](https://github.com/mediathekview/MediathekView/files/2590737/mediathekview.log)

**Comment by pidoubleyou** [comment]
siehe [Forum](https://forum.mediathekview.de/topic/1602/probleme-beim-download-und-abspielen-von-orf-sendungen/3)
