### ISSUE TITLE
Documentation for Ubuntu Linux 18.04LTS  is incorrect

### ISSUE THREAD

**Issue by StephanEggermont** [mediathekview/MediathekView#395]
Ubuntu needs a Java 8 with JavaFX. This  can only be found out by going through the closed issues. 

The default apt install default-jre installs at the moment a java 11 without openjfx, so I had to install that and openjdk-8-jre-headless before being able to switch by update-alternatives --config java and selecting the  
right java.

**Comment by styroll** [comment]
>@StephanEggermont sagte:  Documentation for Ubuntu Linux 18.04LTS is incorrect

Das Problem der nicht mehr aktuellen Anleitung ist [bekannt](
https://github.com/mediathekview/MediathekViewDE/issues/40#issuecomment-434055062).

Diese Issue gehört eigentlich in [dieses Repo](https://github.com/mediathekview/MediathekViewDE).
