### ISSUE TITLE
SailfishOS client

### ISSUE THREAD

**Issue by zwieberl** [mediathekview/MediathekView#397]
Hi,
ich schreibe gerade eine App für mein SailfishOS-Handy, welche als Client für euren Service fungieren soll zum Durchsuchen der Mediatheken.
Wäre es für euch ok, diese im sailfish-store zu veröffentlichen?
Die App ist (und bleibt) open source. Credits würde ich euch ebenfalls gerne geben.

**Comment by alex1702** [comment]
Hast du Ahnung wie man etwas im sailfish-store veröffentlicht? gerne können wir das zusammen machen. Bedingung ist aber, dass du Maintainer bleibst. So weit ich weiß hat keiner von uns Sailfish Erfahrung.

**Comment by zwieberl** [comment]
Nein, das wäre meine erste App im Harbour. 
Gibt aber Doku dazu: https://sailfishos.org/wiki/Application_Development#Harbour
Sollte hoffentlich kein Problem sein. 

Die App ist aktuell eh nur eine Suche. Videostreams kann ich aufgrund von Harbour-Einschränkungen aktuell nicht machen (Video-API von Sailfish ist noch nicht als stabil erklärt worden, daher dürfen Apps die noch nicht verwenden).
Daher beschränkt sich das momentan auf "Suche zusammenbauen", "Ein GET-call", "Ergebnisse anzeigen" und "URLs kopieren".

**Comment by zwieberl** [comment]
Addendum: Wäre natürlich auch nicht als "offizielle Mediathekview-App" gedacht, sondern als "hab ich als Privatmensch geschrieben und nutzt mit freundlicher Genehmigung mediathekview", wie die meisten Apps im Harbour

**Comment by alex1702** [comment]
nutzt du matrix? Dann kontaktiere mich mal direkt unter https://matrix.to/#/@alex:matrix.elaon.de

**Comment by alex1702** [comment]
geht in Ordnung.
