### ISSUE TITLE
Falsche Fehlermeldung

### ISSUE THREAD

**Issue by Latz** [mediathekview/MediathekView#398]
Ist kein Speicherplatz auf der Platte vorhanden, um den Film zu speichern, erscheint als Fehler:
"Der Film "X" existiert bereits". und der Film wird als bereits heruntergeladen markiert.

Ein vorheriger Check, ob ausreichend Speicherplatz vorhanden ist und eine entsprechende Fehlermeldung wäre an dieser Stelle hilfreich.

**Comment by derreisende77** [comment]
Funktioniert aber nicht bei Filmen, bei denen die Länge im Vorfeld nicht bekannt ist. 
Von daher sollte primär der Nutzer sicherstellen dass genügend Speicherplatz vorhanden. Zumal das Erkennen von Speicher mit Java insofern problematisch ist das Verhalten der Meldung des freien Speichers von Betriebsystem zu Betriebssystem unterschiedlich ist und Java an sich keine gute Möglichkeit bietet das vernünftig zu erkennen.
