### ISSUE TITLE
Blacklist Menüeinträge überarbeiten

### ISSUE THREAD

**Issue by alex1702** [mediathekview/MediathekView#404]
Unter Einstellungen kann das Farbenspiel für die Blacklist Option weg. Der Text sollte so gewählt sein, dass man erkennt, dass es sich um die Blacklist handelt. Eventuell einfach nur "Blacklist" mit einem Info Icon daneben zur weiteren Funktionserläuterung oder erklärenden Text direkt daneben. Sollte Designbewusst entschieden werden.

Des Weiteren sollte im Filme Tab beim Kontextmenü die beiden Einstellungen zum An/Abschalten der Blacklist entfernt werden.

![auswahl_001](https://user-images.githubusercontent.com/1862815/51383964-317f3d00-1b1b-11e9-8c26-9d822ac86939.png)

![menu_002](https://user-images.githubusercontent.com/1862815/51383974-35ab5a80-1b1b-11e9-8f94-614a5675e7b4.png)

**Comment by derreisende77** [comment]
fixed
