### ISSUE TITLE
X Window System error

### ISSUE THREAD

**Issue by dipohl** [mediathekview/MediathekView#405]
MediathekView 13.2.1 on Fedora 29 with
```
  java-1.8.0-openjdk-1:1.8.0.191.b13-0.fc29.x86_64                              
  java-1.8.0-openjdk-headless-1:1.8.0.191.b13-0.fc29.x86_64                     
  java-1.8.0-openjdk-openjfx-1:1.8.0.191.b13-0.fc29.x86_64                      
```
The application crashes e.g. after choosing the download directory for "Film aufzeichnen"

Output is:
```
Available monitors: 1
Work Area: x:0, y:0, w:1920, h:1054
convert monitor[0] -> glass Screen
[x: 0 y: 0 w: 1920 h: 1080]

(java:8100): Gdk-ERROR **: 00:18:24.212: The program 'java' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 71078 error_code 3 request_code 20 minor_code 0)

```
Possibly this is not an error on your side as I found the following info 

> For the segfaults with MediathekView, please fill a new bug report. I'm investigating on that and it seems that is libglassgtk2.so the source of the problem. There is a bug when JavaFX and Swing are mixed, I see also these segfaults with javafx apps launched with icedtea-web (javaws)

in this Fedora Bugreport: https://bugzilla.redhat.com/show_bug.cgi?id=1657636

fyi und danke für MediathekView!

**Comment by derreisende77** [comment]
Yes JavaFX 8 has tons of problems with JavaFX. Some of them received some love with JavaFX 9. 
Unfortunately we cannot fix these in the program. 
You may want to try Java 11 on your system and build MV from GitHub develop Branch. This version only relies on Java 11 and packages JavaFX internally. It should work a lot better on your system and release of this Branch is planned soon. This way you might be able to use the program and it has some new features. BUT it is a develop Branch that will change...

**Comment by derreisende77** [comment]
going to close this here as we can´t do much against it and hopefully the java 11 version will not be affected

**Comment by dipohl** [comment]
fyi: the issue has been fixed in openjfx in Fedora distribution :-)
https://bugzilla.redhat.com/show_bug.cgi?id=1667675
