### ISSUE TITLE
Mediatelk startet nicht on ubuntu 18.4

### ISSUE THREAD

**Issue by elchgucker** [mediathekview/MediathekView#406]
A fatal error has been detected by the Java Runtime Environment:

  Internal Error (nativeInst_x86.cpp:165), pid=9294, tid=0x00007f25fb3c3700
  guarantee(disp == (intptr_t)(jint)disp) failed: must be 32-bit offset

 JRE version: OpenJDK Runtime Environment (8.0_191-b12) (build 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)
 Java VM: OpenJDK 64-Bit Server VM (25.191-b12 mixed mode linux-amd64 compressed oops)

**Comment by elchgucker** [comment]
He says Liste Filme lesen von: /pfad....
followed by a crash

e.g also this one here
`# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f6f5b9ace7d, pid=9338, tid=0x00007f6f51f8c700
#
# JRE version: OpenJDK Runtime Environment (8.0_191-b12) (build 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.191-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x639e7d]
`

**Comment by elchgucker** [comment]
`#
`# A fatal error has been detected by the Java Runtime Environment:
`#
`#  SIGSEGV (0xb) at pc=0x00007f358457ee20, pid=9382, tid=0x00007f358016e700
`#
`# JRE version: OpenJDK Runtime Environment (8.0_191-b12) (build 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)
`# Java VM: OpenJDK 64-Bit Server VM (25.191-b12 mixed mode linux-amd64 compressed oops)
`# Problematic frame:
`# V  [libjvm.so+0x62ee20]
`

**Comment by derreisende77** [comment]
This is a problem with Java on your system. Maybe http://forum.mediathekview.de can help here.
Since no problem with the app this issue will be closed.
