### ISSUE TITLE
Filterfenster bekommt keinen Mausklicks

### ISSUE THREAD

**Issue by gprints** [mediathekview/MediathekView#408]
Wenn ich auf das Trichter-Icon klicke und das Fenster mit Sendern, etc. aufgeht, kann ich dort nichts anklicken. Maus-Klicks gehen durch das Fenster hindurch auf die Liste dahinter und das Fenster ist nach dem Klick weg. Es gibt keine Fehlermeldungen auf der Console. Ich kann mit der Tastatur die Checkboxen highlighten (hoch- und runter-Tasten), kann sie aber auch nicht auswählen. Drücke ich die Leertaste, landet ein Leerzeichen in dem Suchfeld rechts neben dem Trichter-Icon.

Ich verwende
mediathekview-13.2.1
openjdk8-8.202.8
Window-Manager icewm-1.3.8 mit click-to-focus, kein Compositing-Manager
xorg-server-1.18.4_10,1

**Comment by derreisende77** [comment]
das ist leider ein Problem mit manchen window managern und Java, ich hoffe das Problem mit 13.3 behoben zu haben. Mit Java 13.2 wird man da nichts gewinnen können.
