### ISSUE TITLE
Medithekview startet nicht mehr

### ISSUE THREAD

**Issue by hitam4450** [mediathekview/MediathekView#411]
Hallo,
vor 2 Tagen habe ich unter UBUNTU 18.04 ein Major Update gestartet und durchgeführt um das System zu aktualisieren. Jetzt wollte ich meine medithekview Anwendung starten und es erscheint nur das logo ganz kurz und das war es !

Das folgende
![Bildschirmfoto vom 2019-04-18 18-05-27](https://user-images.githubusercontent.com/9738727/56374991-ad655000-6204-11e9-99a1-abc4c7289248.png)

zeigt die Fehlermeldung,

der folgende Screenshot welche Version von openjfx  installiert ist:

![Bildschirmfoto vom 2019-04-18 18-06-06](https://user-images.githubusercontent.com/9738727/56375025-c3731080-6204-11e9-9b08-0ebb6127e767.png)

Wie bekomme ich Mediathekview schnellstmöglich wieder zum funktionieren ?

Vielen Dank im Voraus, hitam4450

**Comment by Nicklas2751** [comment]
Wie die Fehlermeldung schon sagt, läuft die entsprechende MediathekView Version nur mit Java 8. Dein Screenshot zeigt aber, dass du Java 11 installiert hast.

Du hast jetzt zwei Optionen:
1. Downgrade auf Java 8
2. Du verwendest die letzte nigthly Version von MediathekView. Aber Achtung hierbei handelt es sich um eine unstabile Entwickler Version! https://download.mediathekview.de/unstabil/

**Comment by hitam4450** [comment]
Danke für den Hinweis!

Habe jav11 übewr den paketmanager deinstalliert und  aus den UBUNTU rep heruntergeladen und will es mit gdebi installieren. das funktioniert aber nicht!   ????? 
LG; hitam4450

**Comment by Nicklas2751** [comment]
Hier steht wies geht: https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-on-ubuntu-18-04

**Comment by hitam4450** [comment]
Danke Dir !

**Comment by knmkuriq** [comment]
Das funktioniert nicht wirklich. OpenJFX8 kann gar nicht installiert werden. Man kann zwar OpenJDK8 installieren und auch systemweit aktivieren, bringt aber nichts, da OpenJFX8 einfach nicht existent ist:

https://github.com/mediathekview/MediathekView/issues/416

**Comment by alex1702** [comment]
Ich hab mir mal die Arbeit gemacht das [AppImage](https://download.mediathekview.de/stabil/MediathekViewFull-13.2.1-x86_64.AppImage) lokal zu erzeugen. Ihr Könnt unter Ubuntu 18.04, darauf aufbauende Distributionen oder neueren Ubuntu Version diese Version nutzen. Sie bringt Java 8 schon mit.

Download [hier](https://download.mediathekview.de/stabil/MediathekViewFull-13.2.1-x86_64.AppImage)

Dieses muss nur ausführbar gemacht werden und kann dann aufgerufen werden.
