### ISSUE TITLE
Download der Filmliste nicht in Ansicht/Bandbreitennutzung

### ISSUE THREAD

**Issue by jjvbsag** [mediathekview/MediathekView#413]
Es wäre schön, wenn auch der Download der Filmliste in die Anzeige aufgenommen würde.
Dann könnte man sich dort schon ein Bild über die Internetgeschwindigkeit machen...

**Comment by derreisende77** [comment]
Und was wäre der vorteil? Die Anzeige wäre verfälscht da die Liste während des Download direkt verarbeitet wird und dadurch sich je nach Leistung des Rechner kein Rückschluss auf die Bandbreite erzielen lässt
