### ISSUE TITLE
Filmliste ist nicht auf dem Letzten Stand

### ISSUE THREAD

**Issue by Kostenzer** [mediathekview/MediathekView#415]
Ich suchte auf Lotta &

Auf [https://www.zdf.de/suche?q=lotta&synth=true&sender=Gesamtes+Angebot&from=&to=&attrs=&abName=abtest-2019-04-23&abGroup=gruppe-a](url) stehen 8 Episoden.

Im MediathekView finde ich nur 2.
Zeitraum und Mindestlänge stehen auf alles.

Mache ich was Falsch?

**Comment by Nicklas2751** [comment]
Solche Fragen gehören in das Forum: https://forum.mediathekview.de/category/7/fehlende-sendungen
