### ISSUE TITLE
[Usability] Merken der gewünschten Auflösung

### ISSUE THREAD

**Issue by uhafner** [mediathekview/MediathekView#418]
Wenn man einen Download startet, kommt zunächst der "Film Speichern" Dialog. Dort sind immer die gleichen Defaults eingestellt. Es wäre prima, wenn sich der Dialog die letzten Einstellungen merken könnte. Sonst muss ich immer den HD Radiobutton neu wählen. 

(Alternativ wäre es schön, dies zumindest in den Einstellungen irgendwo festlegen zu können.)

**Comment by derreisende77** [comment]
Eine Lösung zu dem Problem findest Du im [Forum](http://forum.mediathekview.de).
Aber das Programm merkt sich jetzt schon die Einstellungen wenn Du sie entsprechend in den PSets bearbeitest. Dies findest Du im Einstellungen-Menü unter "Set bearbeiten". Dort das PSet für Speichern auswählen und den Reiter "Download" auswählen. Dann ist alles da.

**Comment by styroll** [comment]
> @uhafner sagte: Alternativ wäre es schön, dies zumindest in den Einstellungen irgendwo festlegen zu können

Bitte für solche Anliegen das Forum benutzen bzw. zuerst die FAQs bemühen (dort ist das [explizit erklärt](https://mediathekview.de/faq/#wie-kann-man-bei-abos-die-hd-auflösung-wählen))…

**Comment by uhafner** [comment]
Ich habe mich wohl vom Titel im FAQ täuschen lassen, denn der referenziert Abos, die ich noch nie benutzt habe. Danke für das schnelle Feedback!
