### ISSUE TITLE
FFMPEG aktualisieren

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MediathekView#419]
Mit den ausgelieferten FFMPEG-Versionen funktionieren die ORF-Downloads nicht mehr.

Laut [Forum](https://forum.mediathekview.de/topic/2427/bei-mir-bei-sendungen-seit-12-5/) behebt Version 4.1.3 das Problem. Die ausgelieferten Versionen für alle Plattform müssen aktualisiert werden.

**Comment by styroll** [comment]
> @pidoubleyou sagte: Laut Forum behebt Version 4.1.3 das Problem.

Gut, wenn du das hier anmerkst. Ich bin eigentlich davon ausgegangen, dass der @derreisende77 das eh macht, da unter macOS das Problem schon seit mehr als einem halben Jahr existiert und im Rahmen des Release von 13.3 auch ein Update für Win erfolgt.

Ich hab gerade keine Win-Kiste in der Nähe, aber anhand der Dateigrösse für ffmpeg.exe im aktuellsten Nightly (59.3 MB) vs. jener in der aktuellen Version 13.2.1 (35.9 MB) dürfte bereits jetzt eine 4er-Version von ffmpeg.exe gepackt sein…

Man müsste auch die Dateien ffmpeg.txt und ReadMe.txt im MV-Programmverzeichnis auf den neusten Stand bringen (wenn ich den Nightly-Build vom 15. Mai 2019 für Win anschaue)

**Comment by derreisende77** [comment]
Also ich maintaine die MacOS Version und bei jedem Release dort wird von mir ffmpeg aktualisiert. Ich gestehe das ich mich nicht um Windows binaries kümmere da ich es nicht nutze.

**Comment by styroll** [comment]
> @derreisende77 sagte: Also ich maintaine die MacOS Version und bei jedem Release dort wird von mir ffmpeg aktualisiert.

Zumindest in der aktuellen Release (13.2.1) ist im AppBundle die fast 2a alte 3.3.4-Version von FFmpeg. Deshalb ist ja das Problem im Zusammenhang mit ORF-Sendungen auch aufgefallen. Das ist bloss eine Feststellung, sicher kein Vorwurf. Wichtig ist nur, dass in der 13.3 eine aktuelle Version gepackt sein wird (und das ist ja offenbar der Fall). Besten Dank an dieser Stelle für deinen unermüdlichen Einsatz.

PS: Gibt's in den Nightlies auch ein AppBundle, dass man testen könnte. Ich hab da nur Versionen mit der jar-Datei gefunden?

**Comment by derreisende77** [comment]
Nein das bundle muss manuell erzeugt und digital signiert werden.

**Comment by derreisende77** [comment]
Kann sein das ich bei 13.2.1 ein älteres stable verwendet habe. Werde es für 13.3 dann nochmal prüfen. Leider gibt es keinen stabilen Download Link von dem man regelmäßig laden könnte.  Aber ich mache mir Mal ein issue das man dies evtl zukünftig einbauen sollte.

**Comment by styroll** [comment]
>@derreisende77 sagte: Leider gibt es keinen stabilen Download Link von dem man regelmäßig laden könnte.

Damit sollte es klappen (mit [Download-API](https://evermeet.cx/ffmpeg/#api)):
https://evermeet.cx/ffmpeg/getrelease (für 7z-DL des Stable Static Builds)
https://evermeet.cx/ffmpeg/getrelease/sig (Signierung)
https://evermeet.cx/ffmpeg/getrelease/dmg (für DMG-DL des Stable Static Builds)

>@derreisende77 sagte: Nein das bundle muss manuell erzeugt und digital signiert werden.

Alles klar, danke für die Info.

**Comment by bst2002git** [comment]
In Windows einfach bin/ffmpeg.exe mit dem Build von https://ffmpeg.zeranoe.com/builds/ ersetzen.
Funktioniert unter der Version 13.2.1

**Comment by styroll** [comment]
>@bst2002git sagte: In Windows einfach bin/ffmpeg.exe mit dem Build von https://ffmpeg.zeranoe.com/builds/ ersetzen.

Es geht hier nicht darum, wo es ein Static Binary von FFmpeg gibt…

> @bst2002git sagte: Funktioniert unter der Version 13.2.1

Das ist bekannt wie auch dass jenes aus der besagten Quelle [funktioniert](https://forum.mediathekview.de/post/14713).

**Comment by alex1702** [comment]
> > Nein das bundle muss manuell erzeugt und digital signiert werden.
> 
> Kann man das nicht automatisieren? Besteht das Problem speziell nur für den signierungsvorgang?

Da es sein Account auf seinem Entwickler Rechner ist, kann man da aktuell nix automatisieren.

**Comment by derreisende77** [comment]
> > Nein das bundle muss manuell erzeugt und digital signiert werden.
> 
> Kann man das nicht automatisieren? Besteht das Problem speziell nur für den signierungsvorgang?

Nein das kann man nicht automatisieren. Das Problem ist das jpackager aus java bisher entfernt wurde und somit keine Apps mehr erzeugt werden können. Weiterhin müssen binaries in den "Resources"-Ordner einer App gemäß Apple-Richtlinien kopiert werden. jpackager und andere java app creator erlauben dies nicht. Und im Anschluss muss das bundle signiert werden. Dies ist der unkritischte Schritt an der ganzen Sache. Aber er ist mit jeder neuen macOS Version immer wichtiger da Apple ansonsten den Zugriff auf Funktionen verweigert bzw. jedes Mal Nachfragen an den Nutzer stellt.

**Comment by yannicklamprecht** [comment]
> > > Nein das bundle muss manuell erzeugt und digital signiert werden.
> > 
> > 
> > Kann man das nicht automatisieren? Besteht das Problem speziell nur für den signierungsvorgang?
> 
> Da es sein Account auf seinem Entwickler Rechner ist, kann man da aktuell nix automatisieren.

Aber es wäre möglich den bundle build und Sign Prozess in die cli zu bringen um diesen bei einem lokalen build mit aufzurufen. Über gesetzte Environment variablen könnte erkannt werden, dass ein Mac OS build getätigt werden darf.

**Comment by derreisende77** [comment]
Wenn jpackager Mal wieder in Java integriert wurde vielleicht. Bis dahin nutzen wir eine kommerzielle Lizenz einer Software und das wird nicht ins Netz gehen.

**Comment by bagbag** [comment]
Und wenn wir das in einem privaten repository mit privaten CI machen?

**Comment by Nicklas2751** [comment]
Das open source Projekt PDFSam baut (Teile?) seiner dmg mit maven. Ob der travis den sie einsetzen das dann auch mit baut konnte ich gerade nicht herausfinden. Wir sollten uns das jedenfalls mal ansehen da wir besimmt nicht die ersten sind die ihr Java Projekt zu dmg automatisiert bauen wollen.
https://github.com/torakiki/pdfsam/blob/master/pdfsam-basic/pom.xml

So weit ich das von @yannicklamprecht genannte maven Plugin richtig überblicke nutzen es den jpackager nicht oder übersehe ich da was?

Auch interessant: https://www.infoq.com/news/2019/03/jep-343-jpackage/

**Comment by derreisende77** [comment]
Das maven plugin von federkasten funktioniert nur bis Java 8. Danach ist Sense wie in den issues mehrfach erwähnt.

**Comment by derreisende77** [comment]
in 13.3 wieder aktualisiert
