### ISSUE TITLE
Illegal reflective access by mediathek.Main (file:/usr/share/mediathekview/MediathekView.jar) to field sun.awt.X11.XToolkit.awtAppClassName

### ISSUE THREAD

**Issue by WarpinWolf** [mediathekview/MediathekView#422]
Hopefully not doing anything wrong by reporting it here.....

`user@computer:~$ java -jar /usr/share/mediathekview/MediathekView.jar

___  ___         _ _       _   _          _    _   _ _               
|  \/  |        | (_)     | | | |        | |  | | | (_)              
| .  . | ___  __| |_  __ _| |_| |__   ___| | _| | | |_  _____      __
| |\/| |/ _ \/ _` | |/ _` | __| '_ \ / _ \ |/ / | | | |/ _ \ \ /\ / /
| |  | |  __/ (_| | | (_| | |_| | | |  __/   <\ \_/ / |  __/\ V  V / 
\_|  |_/\___|\__,_|_|\__,_|\__|_| |_|\___|_|\_\\___/|_|\___| \_/\_/  

. Portable Mode: false
. Proxy Authentication: not configured
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by mediathek.Main (file:/usr/share/mediathekview/MediathekView.jar) to field sun.awt.X11.XToolkit.awtAppClassName
WARNING: Please consider reporting this to the maintainers of mediathek.Main
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
. Programmstart: 09.06.2019 12:40:27
. maxMemory: 721 MB
. Version: MediathekView 13.2.1
. Java:
. Vendor: Ubuntu
. VMname: OpenJDK 64-Bit Server VM
. Version: 11.0.3
. Runtimeversion: 11.0.3+7-Ubuntu-1ubuntu219.04.1
. Programmpfad: /usr/share/mediathekview/
. Verzeichnis Einstellungen: /home/user/.mediathek3
`

**Comment by styroll** [comment]
> @WarpinWolf sagte: . Version: MediathekView 13.2.1
. Java:
. Vendor: Ubuntu
. VMname: OpenJDK 64-Bit Server VM
. Version: 11.0.3

MV 13.2.1. benötigt Java 8, für weitere Hilfe vgl. Forum.

**Comment by WarpinWolf** [comment]
Ooops. Thanks!
