### ISSUE TITLE
Menü Schriftgröße 2560x1440 

### ISSUE THREAD

**Issue by Hermann12** [mediathekview/MediathekView#423]
Die Schriftgröße des Menüs ist micr. Wo kann man das größer stellen, damit man kein Vergrößerungsglas benötigt. Habe schon versucht in Win10 das App Verhalten zu ändern, ohne Erfolg. Die Listen Sprache konnte ich leicht vergrößern.

**Comment by styroll** [comment]
Für solche Fragen ist das Forum da. Dort gibt's entsprechende Threads. Bzw. stell die Frage dort.
