### ISSUE TITLE
film list download doesn't appear in download list

### ISSUE THREAD

**Issue by traumschule** [mediathekview/MediathekView#425]
Downloading the list of films can take some time. The status bar shows '1 Download' but the tab Downloads doesn't show it.

Please add this for more clarity.

**Comment by derreisende77** [comment]
The "1 download" is not related in any way to filmlist download. While a fmlist is loading it makes perfect sense that no downloads are shown in the tab. Further information on all your questions can be found in the official forum and it is no big.
