### ISSUE TITLE
Integration of Joyn

### ISSUE THREAD

**Issue by dannykorpan** [mediathekview/MediathekView#426]
Hi,

it would bei great If there is any possibility to integrate "Joyn Mediathek" https://www.joyn.de/

Kind Regards,
Danny

**Comment by bagbag** [comment]
Hi,

take a look at [https://www.joyn.de/nutzungsbedingungen](https://www.joyn.de/nutzungsbedingungen). They don't allow that and they obviously don't want to loose their revenue from ads.

> Eine Nutzung für geschäftliche und andere hier nicht genannte Zwecke ist unzulässig

MediathekView is not really "geschäftlich", but also not private.

So unfortunately, we can't add joyn, like all the other private Mediatheken.
