### ISSUE TITLE
AppImage auf Downloadseite verlinken

### ISSUE THREAD

**Issue by probonopd** [mediathekview/MediathekView#427]
Bitte das AppImage auf der Downloadseite verlinken, danke.

**Comment by CarstenMeyer** [comment]
Die aktuelle Version 13.3 wird nicht als AppImage bereitgestellt. Version 13.2.1 ist noch zu finden.

**Comment by probonopd** [comment]
Warum gibt es denn kein AppImage mehr? Das war so praktisch

**Comment by Nicklas2751** [comment]
Das letzte wurde von Alex per Hand erstellt. An einer Automatisierung arbeiten wir noch

**Comment by probonopd** [comment]
Wenn ich helfen kann, super gern. Mit AppImage kenne ich mich zum Glück aus 👍 

Vielleicht mit dieser Methode?
https://github.com/AppImage/AppImageKit/wiki/Bundling-Java-apps#bundling-a-subset-of-java-using-adoptopenjdk-openj9-jlink

**Comment by alex1702** [comment]
Vielen Dank für den Hinweis. Muss mein Skript dafür dann anpassen. Bzw. das gebaute tar.gz aktuell hat ja auch schon eine jre mit drin. Denke das sollte ich hinbekommen in den nächsten Tagen.

**Comment by Nicklas2751** [comment]
@probonopd 
Ich habe da mal was angefangen: https://github.com/mediathekview/MediathekView/tree/feature/AppImage/scripte/appimage

Wie ich sehe bist du bei AppImage recht aktiv. Evtl. kannst du mir helfen.
Aktuell erhalte ich folgenden Fehler wenn ich versuche das AppImage (siehe Branch) zu bauen:

Befehl: `./pkg2appimage-with-docker MediathekView.yml`

Fehler: 
```sh
+ mkdir -p ../out/
mkdir: cannot create directory '../out/': Permission denied
+ true
+ mv MediathekView-.glibc2.4-x86_64.AppImage ../out/
mv: cannot move 'MediathekView-.glibc2.4-x86_64.AppImage' to '../out/': Not a directory
```

**Comment by alex1702** [comment]
AppImage Build Skript wurde hinterlegt.

**Comment by probonopd** [comment]
Ist Docker wirklich nötig?

**Comment by alex1702** [comment]
Docker wurde entfernt und bauen wurde ja jetzt korrigiert. Es fehlt aktuell nur noch das richtige deployen, dass habe ich gestern nicht mehr geschafft. ^^

**Comment by Nicklas2751** [comment]
Ist nun auch in den nighlys zu finden: https://download.mediathekview.de/unstabil/

**Comment by CarstenMeyer** [comment]
13.5.0 von heute als AppImage habe ich erfolgreich gestartet. Danke! :-)
