### ISSUE TITLE
Allowing to control Finder

### ISSUE THREAD

**Issue by vivalamovie** [mediathekview/MediathekView#428]
In the Catalina beta everytime MediathekView is writing a downloaded file this window appears ("Full Disk Access" and "Files an Folders" in "Security & Privacy SysPref both are checked for the app):
<img width="420" alt="Screenshot 2019-07-01 at 23 01 37" src="https://user-images.githubusercontent.com/1328231/60466726-c2268100-9c54-11e9-9ccd-52d1a6d41553.png">
(sorry for Dark Mode)

**Comment by derreisende77** [comment]
You should check Automation as well. This is a known problem with Mojave and newer. Hopefully 13.3 will fix this as the official binaries will be signed then.

**Comment by vivalamovie** [comment]
But Finder Automation also is checked.

**Comment by derreisende77** [comment]
Then you need to disable writing spotlight comments in settings/pset.

**Comment by vivalamovie** [comment]
Yes, working now. Thank you.
