### ISSUE TITLE
Umlaute lassen sich unter Linux nicht per Compose-Taste eingeben

### ISSUE THREAD

**Issue by hupfdule** [mediathekview/MediathekView#429]
Das Problem ist ein Bug im OpenJDK < 10: https://bugs.openjdk.java.net/browse/JDK-8185792

JavaFX-Komponenten in einer Swing-Anwendung zeigen dieses Verhalten. Das Problem wurde erst mit JavaFX 10 gefixt.

MediathekView setzt leider Java 8 voraus, also kein JavaFX 10. 
Als mögliche Lösung sehe ich eigentlich nur die Anwendung tauglich für Java > 8 zu machen oder (falls das überhaupt möglich ist) ein aktuelleres OpenJFX mit auszuliefern.

**Comment by alex1702** [comment]
Aktuell ist die Entwicklerversion noch nicht für ein Release bereit, diese ist aber schon Java 11 kompatibel, bzw. setzt das vor raus. Die Snapshots kann man hier https://download.mediathekview.de/unstabil/ finden.
Bitte gerne mal testen ob das Problem damit behoben ist.

**Comment by derreisende77** [comment]
Die nightly build nutzen openjfx 13 early access gerade um einen Bug mit KDE zu umschiffen. Feedback wäre Willkommen ob dein Problem damit beseitigt ist.

**Comment by hupfdule** [comment]
Ja, im aktuellen nightly build tritt das Problem nicht auf!

**Comment by derreisende77** [comment]
Dann empfehle ich die Nutzung des nightly vorerst. Der ist schon sehr stabil und ein Release der Version Pläne ich für ende des Monats. 
Ich würde das issue damit schliessen.
