### ISSUE TITLE
flvstreamer aus Speichern-Set entfernen

### ISSUE THREAD

**Issue by styroll** [mediathekview/MediathekView#434]
Im App-Bundle für macOS ist das Binary "flvstreamer" – im Unterschied zurWindows-Version (ZIP-Datei-Download) – nicht mehr enthalten. Das ist wohl beabsichtigt, da unter dem kommenden macOS "Catalina" 32-bit-Programme eh nicht mehr lauffähig sind.

Unschön ist, dass jetzt die Prüfung der Pfade in den Einstellungen zu einem Fehler führt:

<img width="741" alt="flvstreamer_falscher_Pfad" src="https://user-images.githubusercontent.com/24810728/62793989-3addf000-bad3-11e9-8e95-7fb877999733.png">

… bzw. umgekehrt, dass im aktuellen Speicher-Set das Subset "flvstreamer" immer noch vorhanden ist.

Ich schlage vor, mit der nächsten MV-Version das Subset "flvstreamer" und das Binary dazu für alle Plattformen zu entfernen, da in der Praxis auch keine Flash-Videos bei den ÖR-Sendern zu finden sind.

**Comment by alex1702** [comment]
Ja, hatte ich für diesen Release auch schon gedacht. War mir aber nicht sicher, ob alle Mediatheken den Quark nicht mehr brauchen. Und wäre kein mal eben Ausbau mehr gewesen. Aber danke für den Hinweis.

**Comment by styroll** [comment]
>@alex1702 sagte: War mir aber nicht sicher, ob alle Mediatheken den Quark nicht mehr brauchen.

Zumindest gibt es in der aktuelllen Filmliste 0 Einträge mit der URL "rtmp://…". Vor zwei Jahren gab's da allenfalls noch einige Leichen (uralte Filme).
