### ISSUE TITLE
13.3.0: Keine Downloadliste inklusive Abos möglich

### ISSUE THREAD

**Issue by akidee** [mediathekview/MediathekView#436]
13.3.0 (unter Mac OS 10.11.6) hängt sich auf, wenn ich meine Aboliste nach Update der Datenbank anzeigen lasse (Klick auf "Aktualisieren" mit Anzeigen "alles" im Tab "Downloads"), während die Liste in 13.0.6 bereits nach mehreren Sekunden angezeigt wird.
Mir bleibt nichts anderes übrig als die Applikation zu beenden und weiter 13.0.6 zu nutzen.

**Comment by derreisende77** [comment]
Welche Fehler stehen im Log?

**Comment by derreisende77** [comment]
Hast Du in den Einstellungen unter Erweitert "Downloads automatisch aktualisieren" aktiviert?

**Comment by akidee** [comment]
> Welche Fehler stehen im Log?

Die Liste ist dann doch erschienen, aber erst nach mehreren Minuten. Unter Mac OS steht in /App/Contents/Resources/app/error.log nur eine Zeile - nichts Relevantes. Ich nutze jetzt einfach die Sortierung nach "Abo" in der Liste im Tab "Filme". 

> Hast Du in den Einstellungen unter Erweitert "Downloads automatisch aktualisieren" aktiviert?

Diese Einstellung gibt es nicht. Die Option "Abos automatisch suchen" zu wählen ändert nichts.

_Hilfreich wäre sicher bei allen aus der DB generierten Listen im UI ein Cursor, sodass intern nicht die ganze (Abo-)Liste vorgeladen wird, sondern meiner Sortierung gemäß immer nur die nächsten n Einträge. (Ähnlich wie jede Webapp das macht.) Das würde die Performance des UI stark verbessern. Eine separate Abo-DB wäre auch nicht schlecht, sodass das "Abos eintragen" nur für neue Film-IDs oder nach Abo-Änderungen neu getriggert wird._

**Comment by derreisende77** [comment]
Das logfile liegt unter ~/.mediathek3/mediathekview.log. error.log ist das error log des macOS launcher wrapper.

**Comment by derreisende77** [comment]
Interessant ist aber, dass sich die Abo-Verwaltung außer der UI-Kosmetik überhaupt nicht verändert hat gegenüber 13.2.1. Auf allen Testsystemen funktioniert das ohne größere Probleme und benötigt auch keine mehrere Minuten.
Gibt es einen Grund weshalb Du OS X 10.11 verwendest?

**Comment by akidee** [comment]
Derzeit: "never change a running system" - vor allem in Hinblick auf spezielle Apps wie z. B. Lightroom.

Dass es so lange dauert, kann auch an meinen speziellen Filtern liegen, die fast 10 % der ganzen Liste auswählen. Aber warum die Downloadliste dann viel langsamer geworden ist, erklärt das noch nicht.
