### ISSUE TITLE
"Java 11 ist nun Minimumvoraussetzung"

### ISSUE THREAD

**Issue by BenWagener** [mediathekview/MediathekView#439]
Könnt ihr mal sagen wie Otto Windows-Normaluser diese Minimumvoraussetzung erfüllen soll? Euch ist schon klar, dass Java 11 nicht mehr als System-weite JRE für Windows angeboten wird, sondern eigentlich erwartet wird, dass die Elemente der JRE welche die App braucht modular mit in die App gepackt werden? Sollen jetzt wirklich alle Anwender von MediathekView das Java SE Development Kit installieren um Eure Minimalvoraussetzungen zu erfüllen?

**Comment by derreisende77** [comment]
Ja, weil es auch nicht weh tut. Abansonsten [tut es das auch](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.4%2B11/OpenJDK11U-jre_x64_windows_hotspot_11.0.4_11.msi)

**Comment by BenWagener** [comment]
Okay, wenig Anwenderfreundlich. Der TV-Browser läuft unter Windows 10 mit Java 11 auch prima, ohne dass man extra eine JRE installieren muss. Dann werde ich wohl lieber auf MediatheView verzichten und unter Windows 10 "Meine Mediatheken" nutzen. Trotzdem Danke für Eure Arbeit!

**Comment by davidkopp** [comment]
Wäre es nicht sinnvoller, die Anwendung inkl. JRE bereitzustellen? Hierfür existiert das Tool `jlink`, welches die Anwendung zusammen mit den benötigten Abhängigkeiten zu einem Paket zusammenschnürt.
Laut Oracle ist das ja auch der Weg, den man heute gehen sollte:

> As client application development continues to shift from the old “plugin” world to modern deployment, the need for a standalone Java Runtime Environment (JRE) that is installed centrally, separately from Java applications has diminished.  Using the ‘jlink’ tool introduced with JDK 9 will make it even easier for application developers to package and deploy dedicated runtimes rather than relying on a pre-installed system JRE.  Oracle will begin transitioning from the standalone architecture later next year in what will be a multi-year effort.
https://blogs.oracle.com/java-platform-group/faster-and-easier-use-and-redistribution-of-java-se

**Comment by derreisende77** [comment]
https://forum.mediathekview.de/topic/2653/aufruf-mv-installer

**Comment by BenWagener** [comment]
@davidkopp https://forum.mediathekview.de/topic/2650/roadmap-f%C3%BCr-mediathekview-oder-tsch%C3%BCss-windows-und-linux

**Comment by davidkopp** [comment]
> @davidkopp https://forum.mediathekview.de/topic/2650/roadmap-f%C3%BCr-mediathekview-oder-tsch%C3%BCss-windows-und-linux

Danke für den Link! Ich muss gestehen, dass ich hier komplett neu bin und das überhaupt nicht mitbekommen hatte.
Deswegen hatte ich auch nur durch die GitHub Issues durchgeschaut und blöderweise nicht im MediathekView-Forum, wo zu dem Thema JRE 11 ja schon einiges drin steht.

**Comment by derreisende77** [comment]
Es wird Installer für Windows und Linux geben. Diese befinden sich gerade in der finalen Phase des Testings. Mehr dazu in meinem Link.
