### ISSUE TITLE
[Enhancement] In the download window, when deleting a file, then also remove the item

### ISSUE THREAD

**Issue by Wikinaut** [mediathekview/MediathekView#44]
In the download window, two different methods exist:
- delete the item from the download list (a downloaded file stays untouched)
- delete the file (accessible only through right-click context menu)

In the first case (when wiping the file from the list only) I propose to add a new dialog "Do you also want to delete the downloaded file?"

In the second case, the list item remains. In my view, here the file deletion should also remove the item from the list.

**Comment by xaverW** [comment]
first case:
I will put it on my toDo

second case:
I don't think so, that's also for downloads
didn't work to restart them after the deletion.




Am Wed, 05 Aug 2015 06:00:10 -0700
schrieb Wikinaut <notifications@github.com>:

**Comment by patzi** [comment]
Second case is for me also not very practicable as you sometimes want to delete a file an re download it i.e.

First case could be possible but I think only a part of users would use this, the others, like me, would be quiet disturbed by always have to click no on the delete file question. So if this would be implemented there must be something like: "remember my decision and don't ask again" added to the dialog.
