### ISSUE TITLE
Missing backend/scraper code?

### ISSUE THREAD

**Issue by thackel** [mediathekview/MediathekView#444]
Hi there,

any idea where is the code for the backend and the scrapers?

The blocked arte scraping and "too late for sunday Tatort" update forces me to setup my own schedule.

Thanks!

**Comment by alex1702** [comment]
See MServer

**Comment by thackel** [comment]
omg. thanks. it was just not promoted enough on the main account landing page.
Should have been pinned.

Thanks!
