### ISSUE TITLE
Regression - Speichern im Pfad nicht möglich bei Netzwerk Laufwerken

### ISSUE THREAD

**Issue by pimhoff72** [mediathekview/MediathekView#445]
In Klasse GuiFunktionenProgramme wird in checkPathWriteable Files.isWritable(path) aufgerufen. Diese Methode liefert auf Windows Systemen leider nicht immer die korrekte Antwort.
Entfernt man den Aufruf, funktioniert es z.B. wieder mit Netzwerklaufwerken auf synology-Diskstation

**Comment by derreisende77** [comment]
Wenn du dir das auf dem master branch angesehen hast ist das korrekt. In Develop würde das schon gefixt.

**Comment by pimhoff72** [comment]
Ah, ok. Das habe ich gestern dort noch nicht gesehen

**Comment by pimhoff72** [comment]
Damit hat sich das dann erledigt
