### ISSUE TITLE
Position und Grösse des Filterfensters merken

### ISSUE THREAD

**Issue by styroll** [mediathekview/MediathekView#446]
13.3.0 ist ein massiver Fortschritt in Bezug auf die Versionen 13.1 und jünger. Tolle Arbeit und besten Dank.

Der Grund, weshalb ich immer noch mit 13.0.6 "arbeite", ist **nicht** der leicht schnellere Programmstart (11 sec) gegenüber der aktuellen Version (16 sec bis alles parat, für mich nicht relevant), sondern die im Hauptfenster integrierte Filterleiste.

Der schwebende Dialog von 13.3.0 hat nun viele Nachteile des bisherigen Filter-Popups nicht mehr und erlaubt nun fast ein Nachbilden des 13.0.6-GUI.

Wenn sich MV die Position und Grösse des Filterfensters beim Beenden des Programms (analog zu jener des Hauptfensters) merken könnte, wäre das eine tolle Sache.
Natürlich nur, wenn das für andere Nutzerszenarien keine neuen Nachteile/Probleme mit sich bringt.

Hier meine konfigurierte Darstellung der 2 Fenster auf die Breite des Bildschirms:

<img width="1440" alt="MV_Position_Filterfenster_positioniert" src="https://user-images.githubusercontent.com/24810728/63639419-0ea99e00-c693-11e9-971e-bc7891fd05f6.png">

Und so sieht's aus nach einem Neustart von MV (Grösse und Position des Filterfensters verändert):

<img width="1440" alt="MV_Position_Filterfenster_nach_Restart" src="https://user-images.githubusercontent.com/24810728/63639430-339e1100-c693-11e9-854b-4e3d9c52cef3.png">

Schön wäre es, wenn man die Grösse und Position des Filterfensters nicht erneut anpassen müsste. Für das Filter-Popup gab's auch schon mal eine [entsprechende Idee](https://github.com/mediathekview/MediathekView/issues/343).

**Comment by derreisende77** [comment]
Sowohl die Positionierung des Hauptfenster als auch die Positionierung des Filterdialog sind von ir gerade gefixt worden und im develop branch ab jetzt verfügbar.
Beim nightly wird es wohl erst ab morgen verfügbar sein.
Ansonsten ist es in der nächsten Version beides verfügbar.

**Comment by derreisende77** [comment]
Da es sich um neue Konfigurationsparameter handelt müssen diese leider natürlich erneut eingestellt werden. Danach sollte es keine weiteren Probleme mehr geben.

**Comment by styroll** [comment]
> @derreisende77 sagte: Beim Filterdialog merkt sich das Programm nun auch ob er offen war als es beendet wurde und stellt ihn auch wieder her.

Noch besser. Besten Dank.
Wird auch die Grösse des Filterfensters gespeichert? Auf dem Laptop hab ich das nur so breit wie nötig (vgl. Screenshot 1 oben).

**Comment by derreisende77** [comment]
Ja Breite Höhe und x y Position des Filter als auch des Hauptfenster wurden korrigiert. Sollte also nach einmaliger Einstellung nach beenden und Neustart alles so sein wie vorher. Alles andere wäre ein Bug. Habe das gerade auf allen Systemen getestet und es funktioniert so weit bei mir

**Comment by stefan123t** [comment]
Hallo Christian,
ich nutze MV auch seit laengerem und habe heute von 13.0.6 auf 13.3.0 upgedatet.
Auch ich war durch den neuen Filterdialog der einen guten Teil des Hauptfensters ueberdeckt ernsthaft irritiert. Frueher konnte man einfach die Filtereinstellungen aendern und in den Ergebnissen per Cursor-Tasten scrollen, ohne den Maus-Focus auf einen zweiten Dialog bzw. das Hauptfenster zu wechseln.
Es ist ein bisschen wie der Unterschied zwischen PS und GIMP =^)
Gibt es eine Moeglichkeit den Filterdialog an das Hauptfenster anzudocken ?
Mit besten Gruessen,
Stefan
