### ISSUE TITLE
-auto startet grafisch und beendet sich nicht nach dem Download der Abos

### ISSUE THREAD

**Issue by novoid** [mediathekview/MediathekView#447]
Hi,

Wenn ich MediathekView so starte, kommt entgegen der Doku auf https://mediathekview.de/anleitung/#starten-mit-zus%C3%A4tzlichen-parametern ein X-Fenster. Nach dem Download der neuen Abo-Dateien beendet es sich auch nicht mehr.

Startkommando: `java -jar ./MediathekView.jar -auto ~/.mediathek3_abos`

Das selbe passiert, wenn ich `-Xmx1G` dazugebe oder `-fastauto`verwende oder die alternative Konfiguration weglasse.

-------------------------

MediathekView 13.3.0, Debian GNU/Linux 9 (stretch), openjdk version "11.0.4" 2019-07-16, OpenJDK Runtime Environment (build 11.0.4+11-post-Debian-1bpo91)

------------------------

_Erwartetes Verhalten_ wäre, dass nach dem Startkommando kein X-Fenster erscheint, die neuen Abodateien heruntergeladen werden und sich der MediathekView-Prozeß danach beendet.

_Tatsächliches Verhalten_: was auch immer ich angebe (`-fastauto` oder `-auto`), es startet immer nur MediathekView normal grafisch, ohne sich zu beenden.

**Comment by styroll** [comment]
> @novoid sagte: Tatsächliches Verhalten: was auch immer ich angebe (-fastauto oder -auto), es startet immer nur MediathekView normal grafisch, ohne sich zu beenden.

Das CLI wurde entfernt, [vgl. Forum](https://forum.mediathekview.de/post/16474) bzw. Change Log.

**Comment by novoid** [comment]
Aha. Ich habe das auch nicht mit CLI in Verbindung gebracht.

Blieb es in der Doku weil das Feature wiederkommen wird oder weil es zu wenige freiwillige Mitarbeiter dafür gibt?

**Comment by derreisende77** [comment]
Zu wenig weitere Helfer.
