### ISSUE TITLE
MediathekView.exe does not find/accept JDK 12

### ISSUE THREAD

**Issue by FriedrichFroebel** [mediathekview/MediathekView#448]
I just updated the portable ZIP installation folder on my Windows 8.1 device using the archive for MV 13.3.0 after some time. Java is installed with the JDK in version 12.0.2 provided [here](http://jdk.java.net/12/) and works for regular Java development stuff.

Whenever I click on one of the EXE files, an error stating "This application requires a Java Runtime Environment 11" is thrown. The same applies to the 11.0.2 builds available in the [OpenJDK Release Archive](http://jdk.java.net/archive/) (which claim to be not suitable for production anyways). According to the [changelog](https://mediathekview.de/changelog/13-3-0/), it should work with both of them. Executing `java -jar MediathekView.jar` from the terminal works, but is not very convenient.

According to an [issue comment](https://github.com/mediathekview/MediathekView/issues/439#issuecomment-522322364), there will be installers for MV in the future bundling the JRE. This might solve the problem (but not at the current state, only with a future update), but I prefer portable solutions with a simple ZIP and cluttering my hard drive with yet another Java/JRE does not sound very satisfying to me.

**Comment by Nicklas2751** [comment]
Do you have more Java versions installed as the acutal? How ever there hast to be something wrong in your Java configuration. Either uninstall all Java versions and install this JDK: https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot or try this (Yes there are Installers but also a Zip which includes a working Java and Exe files which uses it): https://forum.mediathekview.de/topic/2653/aufruf-mv-installer

**Comment by FriedrichFroebel** [comment]
No, I uninstalled all older Java versions, but nevertheless I would have expected that adding the `bin` directory to the `PATH` variable and setting `JAVA_HOME` to the right folder would work as it does for regular Java (development) stuff.

I must have missed the ZIP versions before.
