### ISSUE TITLE
[Vorschlag] Seperater download von Untertiteln

### ISSUE THREAD

**Issue by SebiderSushi** [mediathekview/MediathekView#450]
Manchmal kann es vorkommen, dass man einen Film bereits heruntergeladen hat, allerdings keine Untertitel. Eventuell, weil man vergessen hat das nötige Häkchen zu setzen, eine Version des Films ohne Untertitel erwischt hat oder man den Film schon länger heruntergeladen hat und er nun mit Untertiteln in die Mediathek gekommen ist.

In solchen Fällen wäre es nützlich, nur die Untertitel herunterladen zu können, um sie dann frei mit der bereits vorhandenen Datei kombinieren zu können, falls beides aufeinander passt.

Um es generisch und für mehrere Anwendungszwecke offen zu halten, könnte dieses Feature als Option implementiert werden, beim Download die Filmdatei einfach wegzulassen. Möglicherweise bei der Qualitätsauswahl als zusätzliche Option "Keine [0 MB]" (natürlich etwas undurchsichtig) oder als Häkchen, etwa "Download der Filmdatei überspringen".

**Comment by tylus** [comment]
Ich bin dafür.

Letzte Woche hat mein Cronjob die Heuteshow im Abo zunächst ohne Untertitel heruntergeladen und einen Tag später nochmal mit Untertiteln. Anscheinend sind die erst später (vielleicht in Zusammenhang mit einer Wiederholung?) in den Metadaten sichtbar geworden.

Ich bin nicht sicher, wie das am besten zu handhaben ist ... ich stelle mir eher eine zentrale Einstellung "ich will eigentlich immer Untertitel" vor, und vielleicht könnte dann auch bei nicht-Abos Mtv nachträglich automatisch erkennen, dass jetzt Untertitel verfügbar geworden sind? Das ist natürlich eine sehr große Änderung, nur so'ne Phantasie.

Das manuelle nachladen "ohne Film" wie von @SebiderSushi beschrieben wäre schon ein toller Anfang.

**Comment by SebiderSushi** [comment]
Ich habe mir das nachladen ohne Film jetzt mal als Downloadset zusammengebastelt.

Man kann ein Set anlegen (ich habe einfach mein Standardset kopiert) und unter dem Tab "Download" die beiden Felder für "direkt speichern" leeren und dann unter dem Tab "Hilfsprogramme" einen einzelnen dummy-Eintrag einrichten. Als Programm also etwa `/urs/bin/echo` eintragen. Solange im Feld "Schalter" einmal die zwei Sternchen (`**`) vorkommen, für die MV dann den Zieldateipfad einsetzt sollte das funktionieren.

Ist jetzt zwar nicht die feine Art, aber wenn man damit leben kann, dass jeder Download als Fehlerhaft endet und man alles in Handarbeit zusammenfügen muss tut es seinen Zweck.

Dieses Kostrukt habe ich jetzt erstmal noch nicht auf meine bestehende Sammlung losgelassen und stattdessen in einen leeren Ordner laufen lassen. Wer weiß, ob da nicht noch etwas gehörig schief gehen kann.

**Comment by styroll** [comment]
>@tylus sagte: Ich bin nicht sicher, wie das am besten zu handhaben ist ... ich stelle mir eher eine zentrale Einstellung "ich will eigentlich immer Untertitel" vor

Eine solche Einstellung [gibt es bereits](https://forum.mediathekview.de/post/4605).

**Comment by derreisende77** [comment]
@SebiderSushi Ich könnte in das Kontextmenü eines Filmeintrages implementieren, dass man dort nur die Untertitel downloaded. Das würde dann sofort geschehen und man müsste den Downloadpfad angeben, es umgeht also die Psets aber führt direkt zum Ziel.
@tylus Also eine nachträgliche Suche und Verwaltung welche Filme keine Untertitel haben und diese nachzuladen sehe ich nicht als zielführend an. Eigentlich sind wir keine Medienverwaltung sondern ein Suchmittel. Weiterhin selbst wenn ich es implementieren würde hättest Du keinen Erfolg damit das die aktuellen MV Versionen keine CLI-Variante mehr bereit stellen und somit dein CRON-job nicht unbedingt erfolgreich wäre damit.

**Comment by SebiderSushi** [comment]
#### @derreisende77:
Die Variante mit dem Kontextmenü würde für meine Zwecke reichen. Sicherzustellen wäre jedoch, dass sich die Option auf mehrere ausgewählte Filme anwenden lässt. Dies wäre z.B. der Fall
- beim von mir beschriebenen Häkchen in den "Alle Downloads starten" oder "Film speichern" Dialogen
- beim hinzufügen eines weiteren Buttons in der Leiste mit dem Suchfeld
- bei einer Option unter dem Reiter "Filme" im Fenstermenü
- bei der Möglichkeit, mehrere ausgewählte Filme mit der rechten Maustaste zu klicken.

Bei letzterem bin ich mir nicht sicher, ob es dazu eine Option gibt, es ein Plattformabhängiger Eingabefehler, ein Gestaltungsfehler in MediathekView oder schlichtweg so gewollt ist, weil sich einige Optionen des Kontextmenüs nicht ohne weiteres auf mehrere Einträge gleichzeitig anwenden lassen. Jedenfalls verhält es sich bei mir unter Ubuntu 16.04 so, dass nach dem Auswählen mehrerer Filme durch einen Rechtsklick die Auswahl ausschließlich auf den geklicken Film umspringt. Das lässt sich zwar mit etwas Gewohnheit umschiffen, war für mich mindestens am Anfang aber sehr unintuitiv und führt bis heute hin und wieder dazu, dass ich mein Geklicke zum Auswählen der Filme wiederholen muss.
(Falls sinnvoll wäre ist das aber auch wieder Material für ein weiteres Ticket, oder?)

#### Zu den Vorschlägen von @tylus:
Generell ist auch mein Idealbild von MediathekView, dass man einen "Soll Zustand" festlegt und dieser dann nach Möglichkeit erreicht wird.
Wenn also beim ersten Download z.B. wie besprochen Untertitel nicht vorhanden waren oder nur eine niedrigere Auflösung als die gewünschte, diese aber später in der Mediathek auftauchen, würde das MediathekView in der idealen Version automatisch erkennen und zumindest bei Abos die aktuelle vollständigere oder bessere Version eines Films zum download anbieten, selbst wenn zu einem früheren Zeitpunkt bereits eine vom Soll Zustand abweichende Ausführung dieses Films geladen wurde.

Natürlich ist das nur ein Idealbild und wenn ihr Entwickler sagt, dass das nicht euer Ziel ist kann ich das völlig verstehen. Neben der Alternative, sich eigenständig zu behelfen oder auf eine komplett andere Lösung umzusteigen: Wärt ihr bereit, einem dementsprechenden Pull-Request zuzustimmen oder wäre das für euch eine zu große Verkomplizierung während am Ende vermutlich der Pflegeaufwand an euch hängen bleiben könnte?
