### ISSUE TITLE
Alte Filmliste laden via URL funktioniert nicht mehr

### ISSUE THREAD

**Issue by styroll** [mediathekview/MediathekView#457]
Hab eben festgestellt, dass bei mir unter macOS Mojave und mit MV 13.5.0 nicht mehr möglich ist, eine archivierte Filmliste via URL zu laden. Es passiert ohne Fehlermeldung nichts:

<img width="1247" alt="MV_Einstellungen_Filmliste-via-URL" src="https://user-images.githubusercontent.com/24810728/66635581-cf69e900-ec0f-11e9-9c80-e3f1937f82e4.png">

Die gleiche Filmliste lässt sich jedoch mit MV 13.0.6 laden. Wenn man die Liste zuerst runterlädt (xz-Datei) und dann lokal lädt, dann klappt's auch bei MV 13.5.0.

Was mir auch noch aufgefallen ist, dass in der Statusleiste der alte Zeitstempel bleibt, auch wenn man eine ältere Liste geladen hat:

<img width="360" alt="MV_Filmliste_Timestamp_alte_liste" src="https://user-images.githubusercontent.com/24810728/66635670-fcb69700-ec0f-11e9-9b97-af2d3cc8f82f.png">

Und dann wieder die aktuelle Liste lädt:

<img width="378" alt="MV_Filmliste_Timestamp_neue_liste" src="https://user-images.githubusercontent.com/24810728/66635725-1ce65600-ec10-11e9-9d77-47f0a6d55dce.png">

Die Zeitangabe wird erst aktualisiert/korrigiert, wenn man erneut einen Eintrag in der Liste anklickt. Das war in bisherigen Versionen von MV nicht so (bei 13.3 bin ich mir nicht sicher, hatte ich nur kurz im Einsatz).

**Comment by styroll** [comment]
Update: Sehr merkwürdig: jetzt funktioniert's wieder. 

Das zweite kleine Problem bleibt bestehen.

**Comment by derreisende77** [comment]
hmm ich glaube das nicht aktualisieren kann ich erklären. in dem release notes steht drinnen das um die cpu last zu reduzieren die altersanzeige etc deaktiviert wird wenn das programm in den hintergrund geht sprich das fenster deaktiviert wird. 
das hauptfenster wird jedoch auch deaktiviert wenn ein dialog geöffnet wird. daher sollte es während der lade dialog offen ist keine updates des alters geben. erst beim schließen.
