### ISSUE TITLE
Spamming syslog

### ISSUE THREAD

**Issue by hanfried** [mediathekview/MediathekView#458]
My SSD run full after MediathekView was writing a lot of messages to a total of 72GB in syslog with:
```
...
Oct 11 17:54:08 hanfried-ideacentre install4j_a303jh-MediathekView.desktop[8829]:   >> ERRORSTREAM [37]: [00007f986801ba60] vdpau_chroma filter error
: video mixer attributes failure: An invalid handle value was provided.                
Oct 11 17:54:08 hanfried-ideacentre install4j_a303jh-MediathekView.desktop[8829]:   >> ERRORSTREAM [37]: [00007f986801ba60] vdpau_chroma filter error
: video mixer rendering failure: An invalid handle value was provided.                 
Oct 11 17:54:08 hanfried-ideacentre install4j_a303jh-MediathekView.desktop[8829]:   >> ERRORSTREAM [37]: [00007f986801ba60] vdpau_chroma filter error
: video mixer features failure: An invalid handle value was provided.       
Oct 11 17:54:08 hanfried-ideacentre install4j_a303jh-MediathekView.desktop[8829]:   >> ERRORSTREAM [37]: [00007f986801ba60] vdpau_chroma filter error
: video mixer attributes failure: An invalid handle value was provided.                 
Oct 11 17:54:08 hanfried-ideacentre install4j_a303jh-MediathekView.desktop[8829]:   >> ERRORSTREAM [37]: [00007f986801ba60] vdpau_chroma filter error
: video mixer rendering failure: An invalid handle value was provided.           
Oct 11 17:54:08 hanfried-ideacentre install4j_a303jh-MediathekView.desktop[8829]:   >> ERRORSTREAM [37]: [00007f986801ba60] vdpau_chroma filter error
: video mixer features failure: An invalid handle value was provided.            
Oct 11 17:54:08 hanfried-ideacentre install4j_a303jh-MediathekView.desktop[8829]:   >> ERRORSTREAM [37]: [00007f986801ba60] vdpau_chroma filter error
: video mixer attributes failure: An invalid handle value was provided.        
Oct 11 17:54:08 hanfried-ideacentre install4j_a303jh-MediathekView.desktop[8829]:   >> ERRORSTREAM [37]: [00007f986801ba60] vdpau_chroma filter error
: video mixer rendering failure: An invalid handle value was provided. 
```
I'm using Mediathekview 13.5.0 installed with the package from the Download-Section for Ubuntu 18.

What's even worse, I could not find an option to avoid logging. Is there at least an env variable I can set for? Edit: Of course, I can run something like `sudo bash -c 'sed -i "/.*Mediathekview.*//d' /var/log/syslog` (untested) as a cronjob to clean it up regulary, but I don't think that's the intended usage and certainly a disaster for the usual linux user, isn't it? (and it also might allow some race conditions on writing the syslog, doesn't it)

A bit disappointing, I can't give more details from the log , as I run already `sudo truncate -s 0 /var/log/syslog`. The above output is coming from a `tail`.

**Comment by derreisende77** [comment]
Your ffmpeg or whatever alternative is malfunctioning. The error stream is used to parse progress. Deactivation is not possible

**Comment by hanfried** [comment]
Well, videos are showing, that's in the end all I care as end user (BTW, if MediathekView can spot an error, why not **show** it to the user once instead of silently logging it far away). Progress of the video is easy to see, I'd never look into syslog (unless I'm doing DevOps stuff). I can understand it might be useful for debugging, but debug messages should always be deactivatable. Also, the error messages don't show any progress. They are the same, probably for every frame, what's not helpful at any all, even for debugging (that's one of the best options of Sentry that it helps to get away of multiple same messages, unless explicitly warranted).

What does it mean it's impossible to deactivate? Does the error logging come from MediathekView? In case, could you point me to the line or class where it is coming from? I'm pretty sure, I could make a PR in case with an option to switch it off in case.

**Comment by hanfried** [comment]
If I understand correctly, all we would need to do is to make the log level configurable (e.g. by an env variable) in this line: https://github.com/mediathekview/MediathekView/blob/ee41a58ccb9b80be2db0cd2ddacd36d5cc1472e4/src/main/java/mediathek/Main.java#L110 - wouldn't we already get rid of too verbose logging. Shouldn't it on error or fatal for deploying to end users anyway. I usually deactivate DEBUG already on staging area (the main part of logging after development is to get enough information to reproduce the problem on a development computer, not to understand the problem without a development computer).

Also, this line below makes me nervous, too: https://github.com/mediathekview/MediathekView/blob/master/src/main/java/mediathek/Main.java#L130 (but I'm not a Java Developer, so I guess, it's not a file logger and root of the syslog problems).

**Comment by derreisende77** [comment]
TRACE level on root logger is necessary as we provide finegrained logging to console via cmd line options. normal users see INFO and WARn... on console. However as many users are not capable of describing their problems we log DEBUG by default to file. That´s where thresholdfilter comes into play. From that point of view it is perfectly valid to log error output to log file. 
I do agree that log file rotation might be a valid use case for another version. But at first it is your system which is at fault.
The easiest fix for your problem is to fix the problems either of your ffmpeg or your VLC error. in case of vdpau_chroma filter error deactivate hardware acceleration. No error, no log entry.

**Comment by derreisende77** [comment]
And btw if you have the code cloned anyway you can easily build a custom version of MV for yourself without logging. you found the places in the code so uncomment the functions or change the warn levels.

**Comment by derreisende77** [comment]
13.5.1 will contain parameter `-f` or `--disable-file-logging`to deactivate log output written to file. Note that then NOTHING will be written.
