### ISSUE TITLE
Releases on github

### ISSUE THREAD

**Issue by baztian** [mediathekview/MediathekView#462]
Can you please provide the built artifacts as [github releases](https://github.com/mediathekview/MediathekView/releases) again? download.mediathekview.de is way to slow.
BTW: It might be a good idea to also use [github actions](https://github.com/features/actions). They allow you to automatically build your artifacts.

**Comment by alex1702** [comment]
I'm sorry, what? How many times do you download MediathekView that it's too slow for you?
Currently we use travis and don't want to get involved in github actions.
