### ISSUE TITLE
Infos zu Abos

### ISSUE THREAD

**Issue by seldonha** [mediathekview/MediathekView#465]
Unter "Abos verwalten" könnte

- die Anzahl der Filme zu diesem Abo
- das Datum des letzter Films zu diesem Abo

in einer Spalte angezeigt werden.

**Comment by derreisende77** [comment]
Das Datum wird im Abo verwalten Dialog in der Spalte "letztes Abo" angezeigt, eine Anzahl der Filme für ein Abo lässt sich im Download-Dialog ermitteln und hat IMHO keine Notwendigkeit im Verwalten-Dialog.
