### ISSUE TITLE
Fehlerhafte RegEx in Abos führen zum Abbruch des Ladens der Filmliste

### ISSUE THREAD

**Issue by t0rge** [mediathekview/MediathekView#466]
Das Laden der Filmliste bei Start von MediathekView wird abgebrochen, wenn eine RegEx in irgendeinem Abo **grundlegend** fehlerhaft ist:

- Die Filmliste bleibt leer. 

- Es erscheinen keinerlei Abo-Filme im Download-Bereich, auch nicht von anderen Abos. 

- Erneutes manuelles Laden der Filmliste verändern nichts - die Liste bleibt weiterhin leer

In diesem Fall, fehlte eine ")".
Das Problem ist seit Version 13.3.0 vorhanden, zumindest unter macOS. 13.2.1 funktionierte hingegen noch einwandfrei.

**Comment by t0rge** [comment]
Das Problem ist weiterhin in 13.5.0 und 13.5.1 präsent. Ein fehlerhafter Regulärer Ausdruck (RegEx) in irgendeinem Abo stoppt jegliches Laden der Filmliste in Reiter "Filme". Die Anzeige bleib leer. Da keine Filmliste geladen wird ist auch keinerlei Download möglich. Beispiel für fehlerhafte RegEx die zum Abbruch führen sind

- `#:(Eins|Zwei|*Drei)(?!.*(Hörfassung|deskription)).*` -- vor dem 1. "*" fehlt "."
- `#:(Eins|Zwei|.*Drei)(?!.*(Hörfassung|deskription).*` -- hinter "description" fehlt ")"

**Comment by derreisende77** [comment]
Ja ist vollkommen richtig. Derzeit ist noch keine Überprüfung eingebaut. Wenn das erfolgt wird es hier einen dementsprechenden commit geben. 
Bis dahin muss der Nutzer sicher stellen dass seine regex korrekt sind. Dafür gibt es ja auch genügend Websites die das zulassen.

**Comment by t0rge** [comment]
Ich denke es liegt ein Missverständnis vor. Das eigentliche Problem liegt woanders. Der Check war noch nie eingebaut, und ist aus meiner Sicht auch nicht notwendig.
Hintergrund: In 13.3.0 (oder 13.5.0) wurde offensichtlich die Initialisierung von MV überarbeitet. Beim Starten werden nach dem Laden der Filme die Abo ausgewertet. Hat jetzt ein Abo eine fehlerhaft RegEx bricht die Initialisierung ab und es werden **überhaupt keine** Filme irgendwo angezeigt.
Bis 13.2.1 wurde die Initialisierung korrekt beendet. Eine fehlerhaft RegEx eines Abos hat lediglich keine Downloads generiert. Aber die Auswertung der verbliebenen Abos ging weiter, und am Ende erscheint eine Liste aller Filme der Mediatheken und die Downloads der korrekten Abos. Jetzt ist alles einfach nur leer und man kann gar nicht machen. Neu laden ändert nichts. 
Es hat ewig gedauert bis ich eine fehlerhaft RegEx als Ursache der "totalen Arbeitsverweigerung" von MV aus gemacht hatte.
