### ISSUE TITLE
Add Categories field to Linux desktop files.

### ISSUE THREAD

**Issue by jnphilipp** [mediathekview/MediathekView#469]
The linux .desktop files should contain a Categories field. Should be something like this `Categories=Network;FileTransfer`.
https://specifications.freedesktop.org/menu-spec/latest/apa.html

**Comment by derreisende77** [comment]
@alex1702 oder @Nicklas2751 Wurde das hinzugefügt im Installer?

**Comment by Nicklas2751** [comment]
Bisher nicht

**Comment by Nicklas2751** [comment]
Mit commit 729bb141 umgesetzt. Wird mit 13.6 kommen. Mit Raspberry Pi 4 und Raspbian getestet
