### ISSUE TITLE
Update-Prüfung blockiert UI

### ISSUE THREAD

**Issue by jpstotz** [mediathekview/MediathekView#470]
In den letzten Minuten war die Webseite https://mediathekview.de nicht verfügbar. Dies hat dazu geführt, dass jede automatische oder manuelle Ausführung der Funktion "Nach Update Suchen" in MediathekView die UI für mehrere Minuten einfrieren ließ.

Kann es sein, dass die Updateprüfunktion aus Versehen auf dem Main-UI-Thread ausgeführt wird und wenn dieser in einen Time-Out läuft das ganze Programm blockiert?

Edit: Wenn ich mich nicht irre ist das tatsächlich so. `ProgrammUpdateSuchen.checkVersion` und damit auch der HTTP-Abruf in `retrieveProgramInformation` wird sowohl beim automatischen, als auch beim manuellen Check aus dem UI-Thread aufgerufen und blockiert diesen damit. Wäre es nicht besser das alles in einen Hintergrund-Thread zu verfrachten?

**Comment by derreisende77** [comment]
Ja das wird in den nächsten Versionen kommen.
