### ISSUE TITLE
Replace Mac OS X splash string with macOS 

### ISSUE THREAD

**Issue by derreisende77** [mediathekview/MediathekView#472]
When running on macOS

**Comment by supervisitor** [comment]
the change of this string is the second bugfix in the list of changelog, seems it is a important thing... but since this, the welcome screen looks nice:

![Screen Shot 2020-02-19 at 10 44 10](https://user-images.githubusercontent.com/10810886/74822448-6e60c900-5305-11ea-9cc4-adfce70cbfa0.png)

**Comment by supervisitor** [comment]
... still the same with Catalina 10.15 (19G73) + Java SE 14.0.2 and now MediathekView 13.6:
![Screen-Shot-2020-08-26-at-12 48](https://user-images.githubusercontent.com/10810886/91297725-136dca00-e79f-11ea-96da-ff033a514902.jpg)
and both (macOS + JRE) are official supported versions!

**Comment by thetrial** [comment]
Maybe this is art?
