### ISSUE TITLE
macOS: Fenster lässt sich nicht schließen

### ISSUE THREAD

**Issue by yannickkirschen** [mediathekview/MediathekView#475]
Hallo zusammen,

unter macOS lässt sich das Hauptfenster bei mir nicht über den "normalen" roten Button schließen. Es passiert einfach nichts. Auch eine Neuinstallation hat das Problem nicht behoben. Wenn ich über `command + q` gehe, schließt sich das Fenster aber ordnungsgemäß.

macOS: 10.15.1 (Catalina)
MediathekView: 13.5.0

Ist dies bereits bekannt?
Es würde mich sehr freuen, wenn der Fehler gefunden und behoben werden kann 👍.

**Comment by derreisende77** [comment]
Ja der Fehler ist bekannt und wird in 13.5.1 behoben. Fix dafür ist schon fertig. Release sollte zeitnah erfolgen.
