### ISSUE TITLE
Sender Radio Bremen aufnehmen

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MediathekView#477]
In der ARD-Mediathek ist mit "Radio Bremen" ein weiteres drittes Programm vorhanden. Der Sender soll zur Filterung neu aufgenommen werden.

Als Senderbezeichnung wird in der Filmliste folgendes verwendet: Radio.Bremen

Link für Icon: https://de.wikipedia.org/wiki/Radio_Bremen#/media/Datei:Logo_Radio_Bremen.svg

**Comment by derreisende77** [comment]
„rbtv“ sollte als Abkürzung in der Liste verwendet werden. Dies ist auch die offizielle Abkürzung im dvb-t.
