### ISSUE TITLE
Hang of MediathekView, had to force quit it

### ISSUE THREAD

**Issue by IOOI-SqAR** [mediathekview/MediathekView#478]
MdeiathekView did hang (rainbow wheel of dead) and consuming 900-something percent of my processors time so I had to force kill it. Here is a crash report of this situation (see attached file):

[CrashReport_MediathekView_hang_2019-12-11.txt](https://github.com/mediathekview/MediathekView/files/3952746/CrashReport_MediathekView_hang_2019-12-11.txt)

**Comment by eleph-hub** [comment]
same for me. with v13.5 on mac osx. 
also: Search box didn't work. couldn't even enter characters.
