### ISSUE TITLE
possible concurrency problem with Daten.getListeFilme()

### ISSUE THREAD

**Issue by me-like-cookies** [mediathekview/MediathekView#479]
as posted [in the forum](https://forum.mediathekview.de/topic/3013/orf-kein-abspielen-mehr-mit-unter-windows-7/21) in reply to [a user's stack trace](https://forum.mediathekview.de/topic/3013/orf-kein-abspielen-mehr-mit-unter-windows-7/20) 
there _might_ be a problem with Daten.getListeFilme() and concurrency.

See [here](https://github.com/mediathekview/MediathekView/blob/master/src/main/java/mediathek/filmlisten/FilmeLaden.java) (L266-L269).

The content of _the_ ListeFilme instance is modified (list is added to and sorted).
There are a couple of calls of getListeFilme() throughout the MV code. It am **not** certain that this code is actually called concurrently to any e.g. iterating through _the_ ListeFilme instance. I only _guess_ so due to the post linked to above quoting a java.util.ConcurrentModificationException.

Consider my playground test file  [ListConcurrencyTest.java](https://github.com/me-like-cookies/TestStuff/blob/master/src/container/ListConcurrencyTest.java)

I ran this a couple of times, and often it passed through, but sometimes crashed, with a java.util.ConcurrentModificationException

I think, in case the above mentioned actually is a concurrency problem, which is not positively clear: one possible solution might be to
- add to and sort another instance of the Container (pointing to the same data) (L31)
- swap the old container and the new instance after sorting (L33)
- not calling the getter of the list for each loop body, but only once before the loop (L40)
line references see [ListConcurrencyTest2](https://github.com/me-like-cookies/TestStuff/blob/master/src/container/ListConcurrencyTest2.java)

drawback:
- What can and -i think will- happen then, is, that the iteration is not through the most up to date container instance

As mentioned from the start:
there well may be reasons why the current code has no concurrency problem at the mentioned place. I did not get through all of it. Please consider this issue null and void if you know better.

Cheers, and thanks for the great work!

**Comment by me-like-cookies** [comment]
I had second thoughts about that one even before posting

> not calling the getter of the list for each loop body, but only once before the loop (L40)
line references see ListConcurrencyTest2

with the only benefit of that "solution" being least invasive to existing code. Basically, I never really liked that suggestion as it only will work well _**if all**_ programmers **_always_** regard this rule when iterating through the list.

In this concurrent situation, I'd rather remove direct access to the container and provide functions for indirect access to e.g. 
- get size, 
- for adding to the list and also 
- for iterating, calling a given "functor" / functional interface, like e.g. a `java.util.function.Consumer`

see [ListConcurrencyTest3.java](https://github.com/me-like-cookies/TestStuff/blob/master/src/container/ListConcurrencyTest3.java), used by [ListConcurrencyTest3User.java](https://github.com/me-like-cookies/TestStuff/blob/master/src/container/ListConcurrencyTest3User.java)

As I have a clone for MV repo and as it's my suggestion, I'm willing to provide a preview in my MV clone how this suggestion could look applied to MV 'Daten.getListFilme()' - but would only do so if official MV maintainers approve of the modification

**Comment by derreisende77** [comment]
I will give a detailed answer after Christmas. Currently I am quite busy with other things but this topic is not forgotten.

**Comment by me-like-cookies** [comment]
Of course, no problem. Take your time.

>I will give a detailed answer [...]

Appreciate it, thanks. But I will perfectly accept a _really_ brief answer, too. No need to steal your time. ;-)

**Comment by me-like-cookies** [comment]
[Eine Meldung im Forum](https://forum.mediathekview.de/topic/3229/fehlende-sendung-wieder-einmal-orf) enthält folgenden Stacktrace:

```
Exception in thread “AWT-EventQueue-0” java.lang.NullPointerException
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
...
at mediathek.daten.ListeFilme.countNewFilms(ListeFilme.java:272) (MV 13.5.0)
```

also [dieser Code](https://github.com/mediathekview/MediathekView/blob/13.5.0/src/main/java/mediathek/daten/ListeFilme.java)
```
271 public synchronized long countNewFilms() {
272        return stream().filter(DatenFilm::isNew).count();
273 }

```

Ich hab es zugegeben nicht detailliert angeschaut. Für mich sieht es so aus, als ob nebenläufig zum hier durchgeführten Filtern des ArrayList.strea() ggfs. ein anderer Thread den Inhalt der ArrayList ändert, ggfs. eine reallocation wg. ArrayList.add(e) o.ä..

Besteht hier Eurer Einschätzung nach ein Problem / Handlungsbedarf?

**Comment by me-like-cookies** [comment]
Problem ist bei mir nicht mehr aufgetreten, auch im Forum keine einschlägige Meldung mehr.
