### ISSUE TITLE
ORF playlist.m3u8 --> chunklist.m3u8 --> media_{0-8}.ts

### ISSUE THREAD

**Issue by drandreaskrueger** [mediathekview/MediathekView#480]
Film Nr 539396 (ORF)

--> 

https://apasfiis.sf.apa.at/ipad/cms-worldwide/2019-12-13_1800_tl_01_ZIB-18_-Fridays-for-Fu__14034926__o__1535712861__s14607331_1__BCK1HD_18061722P_18074209P_Q8C.mp4/playlist.m3u8

--> 

https://apasfiis.sf.apa.at/ipad/cms-worldwide/2019-12-13_1800_tl_01_ZIB-18_-Fridays-for-Fu__14034926__o__1535712861__s14607331_1__BCK1HD_18061722P_18074209P_Q8C.mp4/chunklist.m3u8

--> 

https://apasfiis.sf.apa.at/ipad/cms-worldwide/2019-12-13_1800_tl_01_ZIB-18_-Fridays-for-Fu__14034926__o__1535712861__s14607331_1__BCK1HD_18061722P_18074209P_Q8C.mp4/media_0.ts

to 

https://apasfiis.sf.apa.at/ipad/cms-worldwide/2019-12-13_1800_tl_01_ZIB-18_-Fridays-for-Fu__14034926__o__1535712861__s14607331_1__BCK1HD_18061722P_18074209P_Q8C.mp4/media_8.ts

**Comment by derreisende77** [comment]
This is an issue on the server and patch has already been issued. Waiting to be merged soon
