### ISSUE TITLE
Add a quality flag into "Abo" list (enhancement)

### ISSUE THREAD

**Issue by o0oooooRayooooo0o** [mediathekview/MediathekView#481]
Hi team,

can you please add a quality flag for each Abo list entry that the automatic generated download list has a presetting for each new video (with selected quality). After this enhancement you can still decide on your own, if you want to switch the quality before you sownload. UseCase in example: I want to download each video of the Abo "daily news" in "middle" quality (definition in Abo entry) and each new episode of series "XYZ" in "higest" quality. Then the Download-Lists already have this flag stored and in the Download list contains different predefined qualities. "daily news" as "middle and "XYZ" as "high". 

I really appreciate your work and continues updates! Like!

Best regards,
Ray

**Comment by derreisende77** [comment]
This feature is already implemented. You can define different Programm sets which specify what resolution you want to download. These Psets can be set in the abo later on to achieve exactly your use-case.

**Comment by o0oooooRayooooo0o** [comment]
Thank you for answering so fast! I was not aware of this feature and with your hint I created different presets. Exactly, what I had in mind.

Thanks a lot!

Best regards,
Ray
