### ISSUE TITLE
13.5.1 AppImage + /snap/bin/vlc: >> ERRORSTREAM [1]: cannot open path...

### ISSUE THREAD

**Issue by wgoetz** [mediathekview/MediathekView#484]
The AppImage is not able to play using /snap/bin/vlc

The debian Package works as expected!

ubuntu 18.04LTS

log: (search for ERRRSTREAM...)

 . [Film abspielen, URL: https://rbbmediapmdp-a.akamaihd.net/content/7d/c0/7dc053bb-871c-46dd-a361-f5686d892302/2fa7ee71-fd65-4dbc-a23f-4babea357506_1800k.mp4, Startzeit: 21:35:35, Programmaufruf: /snap/bin/vlc https://rbbmediapmdp-a.akamaihd.net/content/7d/c0/7dc053bb-871c-46dd-a361-f5686d892302/2fa7ee71-fd65-4dbc-a23f-4babea357506_1800k.mp4 --play-and-exit, Programmaufruf[]: /snap/bin/vlc<>https://rbbmediapmdp-a.akamaihd.net/content/7d/c0/7dc053bb-871c-46dd-a361-f5686d892302/2fa7ee71-fd65-4dbc-a23f-4babea357506_1800k.mp4<>--play-and-exit]
. =====================
. Starte Array: 
.  -> /snap/bin/vlc<>https://rbbmediapmdp-a.akamaihd.net/content/7d/c0/7dc053bb-871c-46dd-a361-f5686d892302/2fa7ee71-fd65-4dbc-a23f-4babea357506_1800k.mp4<>--play-and-exit
. =====================
  >> ERRORSTREAM [1]: cannot open path of the current working directory: Permission denied
. Fehler beim Löschen: /tmp/.mount_mediat6h7oac/usr/bin
. [Film fertig, Startzeit: 21:35:35, Endzeit: 21:35:37, Restarts: 0, Dauer: 2 s, Dauer: <1 Min., URL: https://rbbmediapmdp-a.akamaihd.net/content/7d/c0/7dc053bb-871c-46dd-a361-f5686d892302/2fa7ee71-fd65-4dbc-a23f-4babea357506_1800k.mp4, Programmaufruf: /snap/bin/vlc https://rbbmediapmdp-a.akamaihd.net/content/7d/c0/7dc053bb-871c-46dd-a361-f5686d892302/2fa7ee71-fd65-4dbc-a23f-4babea357506_1800k.mp4 --play-and-exit, Programmaufruf[]: /snap/bin/vlc<>https://rbbmediapmdp-a.akamaihd.net/content/7d/c0/7dc053bb-871c-46dd-a361-f5686d892302/2fa7ee71-fd65-4dbc-a23f-4babea357506_1800k.mp4<>--play-and-exit]

**Comment by alex1702** [comment]
https://askubuntu.com/questions/930437/permission-denied-error-when-running-apps-installed-as-snap-packages-ubuntu-17

Try this.

**Comment by Andreas-ddl** [comment]
I have the same behavior with version 13.8. It seems to be linked to the parameters transferred. Before and after the URL there is "<>" instead of " ". May be the creator of the AppImage can correct this. To check see the log of the running AppImage, copy it and use the command with/without the replacement in another command shell.

The path for deb and AppImage in my case was the same: /snap/bin/vlc.
