### ISSUE TITLE
Anbindung an mysql Datenbank

### ISSUE THREAD

**Issue by Uatschitchun** [mediathekview/MediathekView#487]
Hi ... tolle Arbeit, die ihr hier macht!

Frage, habe das mv addon in kodi mit drin und aktualisiere meine DB mittels mvupdate auf meinem Server gegen eine Mysql DB, um die Listen auf allen Clients parat zu haben. 

Nun liegt ja die Filmliste bereits als DB vor... könnte man nicht MV dazu bringen, diese DB mitzubenutzen, anstatt die Listen separat zu laden?!

**Comment by derreisende77** [comment]
Nein, da MV und Kodi zwei völlig unterschiedliche Baustellen sind.

**Comment by Uatschitchun** [comment]
Auch die Datenbanken vom MV-Addon und MV selbst sind komplett verschieden?! Dachte, man könnte hier ggf. Bandbreite, etc. einsparen...

**Comment by bagbag** [comment]
Ja, sind sie. MV erwartet ein JSON-artige Datei für den Import und macht dann ein eigenes Ding draus.

**Comment by Uatschitchun** [comment]
Ah ok, schade. Wäre ja zu schön gewesen ;)
