### ISSUE TITLE
Einstellungsoption "Downloads aus Abos sofort starten" bezieht sich auch auf manuell angelegte Downloads

### ISSUE THREAD

**Issue by styroll** [mediathekview/MediathekView#488]
Ein User [im Forum](https://forum.mediathekview.de/post/20324) beklagte sich, dass manuell angelegte Downloads nach Neuladen der Filmliste (manuell ausgelöst oder automatisch z.B. bei Neustart von MV) sofort heruntergeladen werden.

Wie ein Test von mir und einem weiteren User ergab, hat die Option “Downloads aus Abos sofort starten” in den Einstellungen die gleiche Auswirkung auf manuell angelegte Downloads wie auf durch Abos angelegte DLs.

![MV_Einstellungen_Erweitert_DL-aus-Abos.png](https://forum.mediathekview.de/assets/uploads/files/1581264866296-mv_einstellungen_erweitert_dl-aus-abos.png)

Ich sehe nun 2 Möglichkeiten (die erste Variante wäre die sinnvollere):

1. Die Bezeichnung "Downloads aus Abos sofort starten" bleibt so, bezieht sich aber in Zukunft nicht mehr auf manuell angelegte Downloads (aus meiner Sicht ist es auch kein Use-Case, einen DL bewusst nicht starten zu lassen und diesen dann beim nächsten Neustart von MV – unbeabsichtigt aber automatisch – starten zu lassen).
2.  Die Option bleibt funktionell so, wird jedoch umbenannt zu “Manuell angelegte Downloads und Downloads aus Abos sofort starten”.

**Comment by derreisende77** [comment]
wird in 13.8 behoben sein.
