### ISSUE TITLE
Filter unbrauchbar

### ISSUE THREAD

**Issue by emdete** [mediathekview/MediathekView#491]
Es mag daran liegen, dass ich Linux-Nutzer bin oder dass ich einen tiling Windowmanager benutze. Die Möglichkeit, so hübsch wie früher mit den Filtern Filme zu selektieren, ist in der aktuellen Version nicht mehr gegeben (warum ist der Filter überhaupt in einen separates Fenster gewandert, das war doch prima).

Das Fenster öffnet sich mit riesigem Font, Es enthält keinen Button, es wieder zu schliessen (und reagiert nicht auf <Esc>) und zeigt vermutlich nicht den vollständigen Inhalt (da es größer als der Bildschirm ist - der angefügte Screenshot ist auf ein Viertel skaliert).

![s](https://user-images.githubusercontent.com/3251523/74605591-cd39fe80-50c9-11ea-9512-e677dafe165b.png)

Wenn ich versuche, das Fenster zu "draggen" ändert sich plötzlich das Layout und statt dem Pfeil-Oben erscheint oben links ein Knopf mit einem "X" im Kreis. Der schliesst das Fenster dann zuverlässig.

Früher gabs auch mal 4 Knöpfe mit voreingestellten Filtern - die sind auch nicht mehr zu finden.

**Comment by styroll** [comment]
Im Forum bist du mit solchen Fragen bzw. Problemen besser aufgehoben, zumindest wenn du die notwendigen Informationen lieferst. Du sagst ja nicht mal, welche MV-Version du benutzst…

>warum ist der Filter überhaupt in einen separates Fenster gewandert, das war doch prima).

Das haben sich schon viele gefragt. Immerhin hat sich diesen Fenster seit MV 13.3 soweit verändert, dass man optisch wie funktionell wieder die Möglichkeiten von MV 13.0.6 hat (okay mit gewissen Desktop-Systemen unter Linux vielleicht nicht…).

>Früher gabs auch mal 4 Knöpfe mit voreingestellten Filtern

Die sind seit dem Wechsel von Java 8 auf Java 11 verschwunden, sollen aber wieder kommen…
