### ISSUE TITLE
Unterstützung für ZDF HDR-Content

### ISSUE THREAD

**Issue by sphr2k** [mediathekview/MediathekView#492]
Wäre es möglich, HDR-Inhalte des ZDF zu unterstützen? Ich weiß leider nicht, ob die irgendwie systematisch auffindbar sind - aktuell findet man (nur via HbbTV) _Bad Banks_ in HDR als eine Art Promo auf der Startleiste, aber nicht über die Suche.

![image](https://user-images.githubusercontent.com/1213706/74659785-3cc8f000-5195-11ea-91fe-83400ff2b5e5.png)

([http://hbbtv.zdf.de/zdfstart/idesigner/index.php?id=Bad%20Banks%202%20neu](HbbTV-URL))

Die Download-URLs sehen ganz normal aus, z.B. für Bad Banks S02E01 "Schöne neue Welt":

http://tvdl.zdf.de/de/zdf/diverse/200208_2145_sendung_hdr_bad_2628k_p1112v12.mp4

Weitere Beispiele, u.A. _Bergdoktor_ und _Terra X_ findet man, wie ich gerade gesehen habe, in diesem Thread: https://www.loewe-friends.de/viewtopic.php?f=7&t=9112

**Comment by derreisende77** [comment]
@pidoubleyou Das wäre doch was für dich oder?

**Comment by derreisende77** [comment]
Die Funktion steht auf der TODO Liste für den Crawler. Der MV Client hat an sich damit nichts zu tun und ich habe es an die Verantwortlichen weiter gegeben. Ich schließe daher hier erst mal das issue.

**Comment by Voidi** [comment]
> Die Download-URLs sehen ganz normal aus, z.B. für Bad Banks S02E01 "Schöne neue Welt":
> 
> http://tvdl.zdf.de/de/zdf/diverse/200208_2145_sendung_hdr_bad_2628k_p1112v12.mp4
> 
Wie bist du denn an die konkrete Download URL gekommen? Ich suche gerade eine Möglichkeit wie ich die HDR-Version mit Audiodeskription komme

**Comment by sphr2k** [comment]
> Wie bist du denn an die konkrete Download URL gekommen? Ich suche gerade eine Möglichkeit wie ich die HDR-Version mit Audiodeskription komme

AFAIR mit einem Browser-Plugin für HbbTV.

**Comment by Voidi** [comment]
Über [http://hbbtv.zdf.de/zdfm3/index.php](http://hbbtv.zdf.de/zdfm3/index.php) wird die HDR Version nicht ausgeben
und über [http://hbbtv.zdf.de/zdfstart/idesigner/index.php?id=Bad%20Banks%202%20neu](http://hbbtv.zdf.de/zdfstart/idesigner/index.php?id=Bad%20Banks%202%20neu) bekomme ich zwar den Link, habe aber keine Möglichkeit die Version Audiodeskription/Hörfassung auszuwählen

**Comment by sphr2k** [comment]
Vielleicht gibt es keine Version mit HDR und Audiodeskription. Dann bliebe nur, Standard + Deskription und HDR runterzuladen und neu zu muxen.
