### ISSUE TITLE
Dialog "Gesicherte Einstellungen laden?" von Splash-Screen verdeckt

### ISSUE THREAD

**Issue by me-like-cookies** [mediathekview/MediathekView#493]
Mir ist bei Tests (unter Win10 Pro x64) bzgl. MV Einstellungen aufgefallen, dass bei MV 13.5.1+ beim Start der Splash-Screen den Dialog "Gesicherte Einstellungen laden?" teil verdeckt. Bei mir ist dann nur noch der untere teil des Dialogs zu sehen, mit zwei Schaltflächen "Ja" "Nein", s.u.. Betrifft auch das 13.6.0 nightly vom 12.2.2020

MV 13.5.0 ist nicht betroffen, da sehe ich den Dialog noch komplett.

![Anmerkung 2020-02-26 120800](https://user-images.githubusercontent.com/55579396/75358121-a68e7b80-58b2-11ea-8b3a-716ffd15a2cc.png)

**Comment by derreisende77** [comment]
Das Problem sollte im nächsten nightly behoben sein.

**Comment by me-like-cookies** [comment]
Ein nächstes nightly ist im Moment noch nicht veröffentlicht.

Mit Eclipse bekomme ich develop nicht mehr übersetzt. (wg. kotlin)

Mal kurz das mir fremde IntelliJ angetestet. Aber es sind zu viele mir derzeit unbekannte Technologien im Einsatz, als dass ich eine Aussage treffen könnte, warum MV 13.6 im Fall eines fehlenden config File bei mir hängen bleibt oder sich beim Start sofort beendet und dabei abstürzt (log4j). 
1x insgesamt (intakte config) hatte ich die MV GUI gesehen, aber da sehr viele Fehlermeldungen in der Console wg. illegal access in RangeSliderBehaviour oder so.

Anders gesagt verwendet MV 13.6 inzwischen Technologien, die ich derzeit noch nicht mal verwenden kann, mir auch nicht selbst behelfen kann, geschweige denn dazu ansatzweise hilfreiches Feedback geben. Derzeit möchte ich keine Zeit investieren, mich in diese Technologien einzulesen.

**Comment by derreisende77** [comment]
Wenn du jdk installiert hast kannst du das aktuelle MV jederzeit so ohne Probleme auch unabhängig einer IDE bauen:
./mvnw clean install
cd target
java -jar MedithekView.jar

Es muss nichts weiteres installiert sein.

**Comment by me-like-cookies** [comment]
Auch hier mit Probleme. Der Aufruf

mvnw clean install
im src Verezichnis
baut bei mir kein ./target/MediathekView.jar
Stattdessen Test Failure in mediathek.tool.dns.DnsSelectorTest
(lookup:16 expected <0> but was: <1>
mündet insgesamt in build failure.

**Comment by derreisende77** [comment]
Auf welchem OS? Hat diese maschine keine internetanbindung? Der selektortest macht eine abfrage in das internet. Man kann die Tests aber auch ausfallen lassen indem man mvnw -DskipTests clean install ausführt.

**Comment by me-like-cookies** [comment]
> Auf welchem OS?

Win 10 Pro x64 2004

> Hat diese maschine keine internetanbindung?

Es ist diejenige Maschine, mit welcher ich diesen und den vorigen Beitrag verfasst habe.

> `mvnw -DskipTests clean install`

Danke. Damit war das Bauen ohne IDE erfolgreich.
Ich kann MV nun starten mit dem Befehl
`C:\OpenJDK\bellsoft-jdk14.0.1+8-windows-amd64-full\bin"\java.exe --add-exports javafx.controls/com.sun.javafx.scene.control.inputmap=ALL-UNNAMED -jar MediathekView.jar` 

Mit vorhandener Datei `mediathek.xml` erscheint die GUI. (Test abgebrochen)

Benenne ich die Datei um nach `mediathek_test.xml` und belasse die `mediathek_copy1.xml` etc. stehen , dann verschwindet der Splash-Screen und der Dialog  "Gesicherte Einstellungen laden?" ist vollständig sichtbar.

Klicke ich an der Stelle auf "Nein", gelange ich in den Dialog "Erster Start" (und breche den Test ab).

Klicke ich an der Stelle aber auf "Ja", erscheint noch "Konfig wurde gelesen" in der Console und im log File. Nichts weiter. Der java-Prozess bleibt dann mit 0% CPU Last stehen. Eine GUI erscheint nicht.

Ich werde ganz einfach einen workaround anwenden und die `mediathek_copy.xml` Dateien ebenfalls verschieben. Danke.
