### ISSUE TITLE
Zustand der Filter anzeigen

### ISSUE THREAD

**Issue by tsfg** [mediathekview/MediathekView#494]
Gute Idee aus dem Forum (https://forum.mediathekview.de/topic/3217/zustand-der-filter-anzeigen):
Das Filter Symbol (Button) vor dem Eingabefeld der Suche sollte eine Farbe annehmen, wenn ein Filter gesetzt ist.
Übersichtlich wäre es sicher, wenn der Platz vor dem Filter-Button genutzt werden könnte, um mit Symbolen oder Text anzuzeigen, aus welchem Bereich (Sender(Antenne/Sendeturm), Länge(Stoppuhr), Thema(Blatt), Zeitraum(DoppelPfeil)) oder welche der oberen Optionen gesetzt ist. (Vorschläge für Symbole dafür (in der Reihenfolge der Optionen von oben nach unten): HD, UT, 12-zackiger Stern in dunkelgrau (ggf. mit der Inschrift “NEW”, wenn das erkennbar bleibt) , GrünerPunkt, durchgestrichenes Auge, Hand oder besser durchgestrichenes Ohr, Filmklappe (ist zwar schon das Logo von MV aber ggf. kann man ja eine einfache Strich-Umfangs-Skizze davon nehmen), Ohr mit schwarzem Hintergrund)
Die Piktogramme sollten jeweils nur sichtbar sein, wenn ein entsprechender Filter gesetzt ist.
Gerne bin ich auch mit Piktogrammen behilflich.

**Comment by alex1702** [comment]
Die Idee finde ich nicht schlecht, aber es könnte auch User verwirren, die meinen, man könnte dann mit klick darauf den Zustand ändern.

**Comment by tsfg** [comment]
Ggf. könnte es hier helfen, die Symbole mit schwarzem Hintergrundfeld hinterlegen, das es wie ein Display aussieht?

**Comment by alex1702** [comment]
Wäre eine Idee. Muss mal der Gui Spezialist @derreisende77  was zu sagen.

**Comment by derreisende77** [comment]
Wie im thread schon geschrieben wurde kann der geneigte User in der Fußzeile erkennen das Filter oder Blacklist gesetzt sind. Ich kann jetzt nicht so ganz erkennen worin der Vorteil liegen soll mit 12 icons anzuzeigen das irgendetwas gesetzt ist oder nicht. Anhand der icons wird das keiner auf die Schnelle erkennen können. Somit muss er mit der Maus über das Icon fahren, auf den tooltip warten und lesen was es bedeutet. In der Zeit hat er zig mal auf den Filter Button klicken und den Dialog öffnen können. Dann sieht er genau was gesetzt ist - wenn er den Dialog nicht eh die ganze Zeit offen hat.
Mal davon abgesehen das auf kleinen Laptopgrößen nicht unendlich Platz da ist um noch zig icons darzustellen. Dies würde dann gnädigerweise dazu führen das ich zwar sehe das Filter gesetzt sind - aber dummerweise das Suchfeld ausgeblendet werden muss weil kein Platz mehr da ist. Ich bin mir nicht sicher was besser ist...
Alternative wäre eine Implementierung im Stil einer binär blinkenden Matrixansicht. So 60er Jahre Retrostyle. Sähe sicherlich cool aus, ist nicht unwesentlich Arbeit und bringt auch nix.
Andere Frage: wie sollte denn dann schnell und übersichtlich dargestellt werden das der Filter für die Filmlänge aktiv ist zwischen z.B. 20 und 40 Minuten?

Wie ihr aus dem etwas ironisch gehaltenen Text seht halte ich von der Idee an sich und auch den Argumenten hier und im Forumsfred nicht wirklich viel.
