### ISSUE TITLE
Skalierung hdpi

### ISSUE THREAD

**Issue by FranzFelberer** [mediathekview/MediathekView#497]
Die Schrift und Graphikelemente sind unter Linux (Ubuntu 19.10) auf hdpi displays nicht skaliert. Die Schrift lässt sich auch nicht (mehr ?) im Programm einstellen.

**Comment by alex1702** [comment]
Hast du schon folgende Einstellungen probiert: https://mediathekview.de/anleitung/#starten

**Comment by FranzFelberer** [comment]
Danke!
In meinem Fall:
```
# Öffnen mit
sudoedit /opt/MediathekView/MediathekView.vmoptions
#  falls es wo anders installiert ist 
sudo / find -name MediathekView
# Einfügen
-Dsun.java2d.uiScale=2.0
```
