### ISSUE TITLE
Abos auf Network Drive legt rekursiv Directory an

### ISSUE THREAD

**Issue by erwinmars** [mediathekview/MediathekView#498]
Meine Downloads werden auf der Directory "\\\\MYCLOUD\Public\Shared Videos" abgelegt. Diesen Pfad habe ich gemapped auf B:\. Ich habe darunter z.B. Directory ARD und ZDF angelegt, wo die jeweilige MP4 Files abgelegt werden. Das funnktioniert auch gut und die Dateien liegen an der richtigen Stelle. 

Wenn ich aber in einem Abo so einen Pfad angebe, dann wird das Video an einem falschen Ort abgelegt:

Dialog Abos verwalten:	\\MyCloud\Public\Shared Videos\RBB\Abo\Chez Krömer 
abgelegt in 		B:\Shared Videos\Abos\MyCloud\Public\Shared Videos\RBB\Abo\Chez Krömer

Dialog Abos verwalten:	B:\Shared Videos\3Sat\Abo
abgelegt in:  		B:\Shared Videos\Abos\B_\Shared Videos\3Sat\Abo

**Comment by DaDirnbocher** [comment]
1. Mit solchen Frage bist Du im Forum wohl besser aufgehoben (https://forum.mediathekview.de/)
2. Angaben zum System (Version, BS, etc.) wären hilfreich.
3. Wenn bei Dir in den Einstellungen im Speichern-Set im Zielpfad b:\Shared Videos\Abo steht, funktioniert alles richtig. Pfadangaben im Abo sind relativ zum Zielpfad im Speichern-Set.

**Comment by erwinmars** [comment]
MV 13.5.1
Windows 10 64 bit
Ich denke, MV könnte da ein bißchen inteligenter sein. Wenn der relative Pfad kein relativer Pfad ist, könnte er das auch als absoluten Pfad behandeln. Erkennen kann man das am Beginn \\ oder Laufwerksbuchstaben. 
Das wäre Windows. Wie das auf Linux gehen könnte weiß ich leider nicht sicher.

**Comment by DaDirnbocher** [comment]
Seit wann ist unter Windows "\" am Beginn ein Kennzeichen eines absoluten Pfades?

**Comment by derreisende77** [comment]
Da MV aber auf drei Plattformen läuft und mit entsprechender Konfiguration funktioniert sehr ich keinen Grund das das Programm intelligenter werden müsste. Und auch keinen Fehler.

**Comment by erwinmars** [comment]
Entschuldigung ich meinte natürlich \\\\

**Comment by Kasperx** [comment]
Sofern ich das richtig verstehe sehe ich 2 Denkfehler:
#1 Mac ist im Grunde Linux (Openbsd), daher ist das System nicht sehr weit von Linux entfernt, Pfade fangen also auch da an mit "/...".
#2 Das Programm läuft mit Java und somit plattformunabhänging. Da wir vom zugrunde liegenden System reden (Mac, windoof, linux) gibt es Bibliotheken, die dieses Problem korrigieren können.

Ist grob geraten, da ich das Backend nicht ausreichend kenne :(

**Comment by derreisende77** [comment]
@Kasperx wenn Du nur rätst, solltest Du bitte Kommentare unterlassen. Weiterhin solltest Du dich mal mit Linus Torvalds oder den anderen Linux-Kernelentwickler mit Deiner Aussage #1 auseindandersetzen. Wäre gespannt wie lange es dauert bis Du gesteinigt wirst. Fakt ist dass Linux-Kernel und macOS GAR NICHTS miteinander zu tun haben. macOS basiert auf mach-Mikrokernel mit BSD-Oberbau (FreeBSD nicht OpenBSD), Linux ist ein eigener Kernel ( LINUX = Linux is NOT UNIX). Über POSIX Interfaces sind die zwar einigermaßen kompatibel, aber haben sonst gar nichts miteinander gemein.
Du magst Java für Platformunabhängig halten, aber auch das hat seine Grenzen. Nämlich dann wenn sich die Betriebssysteme unterschiedlich verhalten. Wenn Du dir den Code - spaßeshalber wie Du geschrieben hast - genauer ansiehst wirst Du feststellen dass es an doch recht vielen Stellen Funktionen etc gibt, die sich - trotz plattformunabhängigkeit - damit beschäftigen, corner cases der einzelnen Betriebssysteme abzufangen.
Solltest Du anderer Meinung sein, dann stelle hier bitte keine leeren Behauptungen nach existieren Bibliotheken auf die das können (und auch dann in MV erledigen) sondern liefere harte Fakten.
