### ISSUE TITLE
ZDF info Sendung nicht gelistet

### ISSUE THREAD

**Issue by bjacke** [mediathekview/MediathekView#500]
diese Doku hier wird von Mediathekview aus irgend einem Grung nicht gefunden:

https://www.zdf.de/dokumentation/zdfinfo-doku/-notre-dame-brennt-12-stunden-im-flammenmeer-100.html

Länge    43 min
Datum:    11.04.2020
Video verfügbar bis 11.05.2020, in Deutschland

**Comment by styroll** [comment]
> @bjacke sagte: diese Doku hier wird von Mediathekview aus irgend einem Grung nicht gefunden:

Hier ist das Entwicklerforum der App MediathekView. Die Filmliste und damit fehlende Sendungen haben nichts direkt damit zu tun.

Solche Fragen gehören ins [Forum](https://forum.mediathekview.de).
