### ISSUE TITLE
Programmsets auf Server noch mit veraltetem Pfad für ffmpeg [macOS]

### ISSUE THREAD

**Issue by styroll** [mediathekview/MediathekView#501]
Im Zusammenhang mit [dieser Frage im Forum](https://forum.mediathekview.de/post/21564) (Audio-only-Set) realisierte ich, dass in den für macOS zur Verfügung gestellten Sets (also nicht nur beim Set "nur Ton"), die man vom Server importieren kann, noch nicht berücksichtigt ist, dass MediathekView.app seit einigen Versionen in einem Unterordner zu finden ist:

Falsch ist:
`/Applications/MediathekView.app/Contents/Resources/ffmpeg`

Richtig wäre:
`/Applications/MediathekView/MediathekView.app/Contents/Resources/ffmpeg`

Das wäre vielleicht auch der Moment, die Sets generell (auch dir für Linux und Win) mal wieder auf Aktualität zu kontrollieren.

**Comment by derreisende77** [comment]
@alex1702 passt du die config Dateien mal bitte an?

**Comment by alex1702** [comment]
Laut Überprüfung stimmen bei den 3 Sets für MAC die Pfade.
https://res.mediathekview.de/programmgruppen13/pset_mac.xml
https://res.mediathekview.de/programmgruppen13/pset_mac_nurTon.xml
https://res.mediathekview.de/programmgruppen13/pset_mac_klein.xml

**Comment by alex1702** [comment]
@derreisende77 Verrate mir mal lieber, wieso MV scheinbar die aus programmgruppen11 nimmt?!

**Comment by alex1702** [comment]
Wird mit dem nächsten Release gefixt.

**Comment by styroll** [comment]
Die Mac-Version funktioniert auch bei einer Erstinstallation von MV 13.7  nicht, wenn FFmpeg ins Spiel kommt, da der FFmpeg-Pfad falsch eingetragen ist (mir ist klar, dass bei bestehenden Installationen der Pfad manuell angepasst werden muss, wie das auch im Changelog steht). 

Falsch ist:
`/Applications/MediathekView/MediathekView.app/Contents/Resources/ffmpeg`

Richtig wäre:
`bin/ffmpeg`

Toll ist jetzt allerdings, dass nun offenbar auch in der Mac-Version relative Pfade möglich sind, also der absolute Pfad (/Applications/MediathekView.app/Contents/Resources/bin/ffmpeg) nicht mehr nötig ist und das Programm – theoretisch –auch von irgendwoher gestartet werden kann (hab's nicht getestet).

Ein Import der Standardsets bringt nichts, da auch auf diesem Weg klar wird, dass auch die Standardsets auf dem Server nicht aktuell sind:

<img width="913" alt="Screenshot_ 2020-12-21 at 16 41 22" src="https://user-images.githubusercontent.com/24810728/102795980-d8c31980-43ad-11eb-94da-6781acc8ecc0.png">

**Comment by derreisende77** [comment]
Das pset auf dem server wird noch korrigiert.
