### ISSUE TITLE
mediathekview main GUI broken: shrinked to minimum size

### ISSUE THREAD

**Issue by thkoch2001** [mediathekview/MediathekView#502]
Forwarded from https://bugs.debian.org/956608

Version: 13.2.1-4

I use xmonad as window manager, but that should hopefully not be a problem.
The app starts fullscreen, but the GUI elements only occupy the minimal
possible amount of space. As a result, the app can not be used.
Also menus are rendered far away from the top menu.

I tested Java 9, 13 and 15.

See screenshot:

![mediathekview_rendering](https://user-images.githubusercontent.com/94641/79135687-06cc7480-7db0-11ea-878a-87f037f38867.png)

-- System Information:
Architecture: amd64 (x86_64)
Foreign Architectures: i386

Kernel: Linux 5.2.17-1-amd64 (SMP w/8 CPU cores)
Kernel taint flags: TAINT_WARN, TAINT_OOT_MODULE
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8), LANGUAGE=en_US.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /usr/bin/bash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages mediathekview depends on:
ii  java-wrappers                   0.3
ii  libcommons-compress-java        1.18-3
ii  libcommons-configuration2-java  2.2-1
ii  libcommons-dbcp2-java           2.7.0-1
ii  libcommons-lang3-java           3.8-2
ii  libcommons-pool2-java           2.6.2-1
ii  libcontrolsfx-java              9.0.0+hg20181001-1
ii  libguava-java                   19.0-1+build2
ii  libh2-java                      1.4.197-4
ii  libjackson2-core-java           2.10.1-1
ii  libjchart2d-java                3.2.2+dfsg2-2
ii  libjiconfont-font-awesome-java  4.7.0.0-1
ii  libjiconfont-java               1.0.0-1
ii  libjiconfont-swing-java         1.0.1-1
ii  libjide-oss-java                3.7.6+dfsg-1
ii  liblog4j2-java                  2.11.2-1
ii  libmbassador-java               1.3.1-1
ii  libmiglayout-java               5.1-2
ii  libokhttp-java                  3.13.1-1
ii  libopenjfx-java                 11.0.2+1-1+build2
ii  libswingx-java                  1:1.6.2-4
ii  libxz-java                      1.8-2
ii  openjdk-15-jre [java9-runtime]  15~11-1

**Comment by derreisende77** [comment]
There are tons of problems with Java if the window manager is not KDE or GNOME. Unfortunately I can’t be of much help to fix your problems here aside from using GNOME or KDE.

**Comment by thkoch2001** [comment]
Solution found:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=956608#27
