### ISSUE TITLE
Quellcode-größe unerwartet groß

### ISSUE THREAD

**Issue by Kasperx** [mediathekview/MediathekView#503]
Hallo,

ich habe mir den Spaß erlaubt, das Projekt per git zu laden. Vllt kann ich bei der Entwicklung helfen, dazu später mehr.
Aufgefallen ist, dass der Quellcode fast 400MB ist, was dank Versionierungssystem sehr ungewöhnlich ist. Hat das einen speziellen Grund?

VG
kasper

**Comment by alex1702** [comment]
Hast du mal einen screenshot?

**Comment by alex1702** [comment]
Das liegt daran, dass früher auch binarys drin waren und auch aktuell auch noch ffmpeg (wobei das ausgelagert ist mit git-lfs) aber die alten versionen davon sind halt noch da.

**Comment by derreisende77** [comment]
und es existiert nicht erst seit gestern...
