### ISSUE TITLE
git clone (master) hat Änderungen bei frischer Kopie

### ISSUE THREAD

**Issue by Kasperx** [mediathekview/MediathekView#504]
Hallo,

ich habe mir den Spaß erlaubt, das Projekt per git zu laden. Vllt kann ich bei der Entwicklung helfen, dazu später mehr.
Nach laden, Ordner-eintritt und Befehl "git status" zeigt die Konsole viele Änderungen. Laut meines Verständnisses sollte das im Master nicht vorkommen.
Habe ich etwas übersehen?

VG
kasperx

**Comment by alex1702** [comment]
Hast du mal einen Screenshot?

**Comment by Kasperx** [comment]
ja
(die gesamte Meldung ist sehr viel, deswegen hier Anfang und Ende)

![mv_github_gitclone_status1](https://user-images.githubusercontent.com/10506030/79244598-5fb31000-7e77-11ea-8b25-f749db65670c.jpg)
![mv_github_gitclone_status2](https://user-images.githubusercontent.com/10506030/79244613-63df2d80-7e77-11ea-88c8-5796aea2cb48.jpg)

**Comment by derreisende77** [comment]
```
git clone https://github.com/mediathekview/MediathekView.git
Klone nach 'MediathekView' ...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 47215 (delta 4), reused 8 (delta 3), pack-reused 47206
Empfange Objekte: 100% (47215/47215), 399.58 MiB | 11.55 MiB/s, Fertig.
Löse Unterschiede auf: 100% (35062/35062), Fertig.
```

Funktioniert ohne Probleme. Sowohl unter macOS als auch windows als auch linux.

**Comment by derreisende77** [comment]
```
XXX@YYY-Pro test % cd MediathekView
XXX@YYY-Pro MediathekView % git status
Auf Branch master
Ihr Branch ist auf demselben Stand wie 'origin/master'.

nichts zu committen, Arbeitsverzeichnis unverändert
XXX@YYY-Pro MediathekView %
```

**Comment by Kasperx** [comment]
Oh
Jetzt bei mir auch, ich muss es nur 5 mal machen... 2 mal reicht nicht O.o
Klingt lustig, ist aber leider so
Downloadfehler vllt

**Comment by Kasperx** [comment]
Danke für eure Mühen
