### ISSUE TITLE
Unnötige Aktionen beim Startup

### ISSUE THREAD

**Issue by codingPF** [mediathekview/MediathekView#507]
Hallo,

es sieht so aus, als ob der fap.themaBox.setOnAction listener beim startup der Appl. zwei mal feuert. Einmal mit NULL und einmal mit leer String.
Das hat zur folge, dass die Filmliste refresht wird (obwohl es dafür keinen Grund gibt).
Somit wird die Filmliste drei mal sortiert / gefiltert wärend die App. started.

Das macht das ganze ein wenig träge und ist wahrscheinlich nicht nötig.

**Comment by derreisende77** [comment]
was für eine HW hast Du damit du da einen Unterschied bemerkst? Bei mir fällt das eigentlich überhaupt nicht auf. Werde es für die nächste Version aber beheben.

**Comment by codingPF** [comment]
Das macht bei mir keinen großen Unterschied. Ich hatte dazu einen Thread im Forum gelesen (Programm verbraucht viel....) und dann mal reingeschaut. Dabei ist mir das aufgefallen.

PS. Deine Lösung verhindert aber nur einen von zwei reloads :-)

PPS. Das Problem geht auch noch weiter wenn man einen Sender auswählt. Dadurch wird die ThemaBox neu generiert und wieder ein event gefeuert. D.h. da hat man dann auch zwei reload (Sender ARD > Reload > Thema box "" > Reload). Ohne sich den Inhalt der Themabox wegzuspeichern wird das schwierig...

**Comment by derreisende77** [comment]
das hat aber nichts mit dem Speicherverbrauch zu tun und performancetechnisch ist es auch vernachlässigbar. Der Reload ist notwendig da sich die Liste ändert nach den Aktionen. Das ändert aber nur das Table model und nicht die Filmliste ansich, allokiert also wenig Speicher. Kann man im Profiler sehen.
Alternative ist keine Filtermöglichkeit. Oder die Themabox bietet immer ALLE Themen an und nicht wie gerade eine gefilterte Ansicht der gerade zur Verfügung stehenden Filme...

**Comment by codingPF** [comment]
Kein Filter ist natürlich auch nicht schön....wahrscheinlich ist der Ansatz sich um den Sort zu kümmern und damit das Thema zu entschärfen, der beste
