### ISSUE TITLE
Kopieren in „Clipboard“ nicht möglich

### ISSUE THREAD

**Issue by DirkSchmitt** [mediathekview/MediathekView#508]
Aus dem Beschreibung Fenster (und anderen) ist ein selektieren von Text und nachfolgendes Kopieren in „Clipboard“ nicht möglich.

Dies ist hinderlich wenn ich im Webbrowser oder anderem nach einem Film suchen möchte.

Die Umgebung ist Linux mit OpenJDK 11.

**Comment by derreisende77** [comment]
in der Beschreibung kann man per Rechtsklick ein Kontextmenü anzeigen und den Text komplett in das Clipboard kopieren oder über "Beschreibung ändern" an Teile des Textes an sich heran kommen.

**Comment by DirkSchmitt** [comment]
Der beschriebene Weg über „Beschreibung ändern“ ist zwar ein Umweg den beschriebenen Fehler/Mangel zu umgehen, aber auch vergleichsweise mühsam.

Der Weg über „In Zwischenablage kopieren“ ist nicht hilfreich, da hier nicht nur der benötigte Titel, sondern auch der Sender mit kopiert wird.

Ich bitte freundlich darum diesen Fehlerbericht offen zu lassen.
