### ISSUE TITLE
Filterfenster nicht sichtbar über Remote Desktop Protokoll

### ISSUE THREAD

**Issue by riemy** [mediathekview/MediathekView#509]
Hallo zusammen,

Mir ist aufgefallen, dass das Filterfenster sich nicht öffnen lässt, wenn ich das Programm unter Windows 10 über eine Remote Desktop Verbindung (Windows-eigene RDP-Implementierung) öffne. Bei direkter Nutzung am Rechner funktioniert es natürlich.

Getestet mit 13.5.1 und 13.5.0.

~~In den Logfiles steht nichts dazu, es gibt auch keine Fehlermeldung in der Anwendung. Es passiert nur einfach nichts nach dem Knopfdruck.~~

~~Ich hatte mal ein ähnliches Problem bei einem anderen Programm (Homebank). Da lag es an einem Fehler in der GUI-Bibliothek (GTK). Ich bin dem aber damals nicht weiter nachgegangen, und inzwischen funktioniert es bei den aktuellen Versionen der Software wieder.~~

~~Irgendwelchse Tests die ich noch durchführen könnte?~~

Edit: Korrektur der Fehlermeldung, s.u.

Viele Grüße,
riemy

**Comment by riemy** [comment]
Korrektur:

Es ist nicht das von mir gedachte Verhalten. Es handelt sich um ein Fensterpositionsproblem. 

Ausgangssituation: Am Desktop mit zwei Bildschirmen wird das Filterfenster auf dem Seitenbildschirm geschoben. Das Programm wird geschlossen. Später, über eine Remote-Desktop-Sitzung, die nur die Auflösung des Hauptmonitors überträgt, kann das Filterfenster nicht gesehen werden, weil es vermutlich noch im nicht verfügbaren Bildschirmbereich an der Seite liegt.

Ich sehe aktuell keine Möglichkeit, dieses unsichtbare Fenster in den Sichtbereich zu bringen. Gibt es da Möglichkeiten?

Idealerweise würde die GUI selbst merken, dass die Auflösung sich geändert hat und seine Fensterpositionen anpassen.

**Comment by derreisende77** [comment]
13.6 wird die Position des Filterdialogs in die sichtbare Fläche zurücksetzen. Es wird aber nicht unterschieden in unterschiedliche Anwendungsfälle ein screen, zwei screens etc. Es wird nur sichergestellt dass das Fenster sichtbar ist.

**Comment by derreisende77** [comment]
Korrektur: Der fix funktioniert nicht unter macOS mit Sidecar. Dort verhindert er beim Start die Wiederherstellung der korrekten Fensterposition.
@riemy Bist Du sicher das der Remote Desktop richtig konfiguriert ist? Zumindest unter macOS ist es so dass Fenster nur maximal auf dem Bildschirm erzeugt werden auch wenn die Koordinaten außerhalb der Sichtfläche liegen. 
Mangels Remote Desktop Umgebung mache ich den Fix erst mal rückgängig.

**Comment by riemy** [comment]
Danke für den Korrekturversuch @derreisende77!

Ich habe den Durchlauf nochmal getestet und kann mein bisher beobachtetes Verhalten bestätigen:

Vorbedingung: Bei einem lokalen Start wird das Filterfenster auf dem Zweitbildschirm platziert, und verbleibt dort bis zum Ende des Programmdurchlaufs.

1. Aufruf des Rechners per Remote-Desktop mit nur einem Bildschirm. Die Auflösung des entfernten Rechners wird an die des anzeigenden Rechners angepasst.

2. MediathekView öffnen. Kein Filterfenster sichtbar und auch nicht aufrufbar.

3. Remote Desktop Sitzung bei laufendem MediathekView beenden.

4. Lokale Sitzung weitermachen. Die Auflösung ist wieder auf zwei Bildschirme zurückgesprungen. Das Filterfenster ist sichtbar an der Stelle des zweiten Monitors, wo sie in der Vorbedingung verblieben ist.

Wenn deine Korrektur zu anderen unangenehmen Fehlern führt, dann hilft mir im Moment ja auch das wissen, dass ich das Filterfenster einfach nicht in dem Bildschirmbereich verbleiben lasse, um das ganze zu umgehen. Für mich eine akzeptable Umschiffung durch Vermeidung der Vorbedingung.

Windows Remote Desktop hat sehr wenige Einstellmöglichkeiten. Was ich gefunden habe ist lediglich eine Möglichkeit, die Auflösung noch weiter manuell runterzuschrauben, oder aber mehrere Bildschirme zu übertragen, was aber auch nur funktioniert, wenn das anzeigenden System tatsächlich mehrere Bildschirme besitzt, was in meinem Anwendungsfall leider nicht so ist.

Das hier scheint wirklich ein Randproblem zu sein und ich habe für mich eine einigermaßen akzeptable Umgehung, so dass ich keinen Schmerz hiermit habe.

**Comment by derreisende77** [comment]
Kennst du dich mit Java aus? Sprich ein eigenes jar von Hand starten? Ich bräuchte mit einem Testprogramm unter dem Remote Desktop und normal mal Informationen wie sich die Bildschirmkonstellation für das Programm darstellt.
Alternativ könnte ich einen Parameter für die anbieten der wenn gesetzt die Positionierung des Filterfensters Anhand der Einstellungen verhindert.
