### ISSUE TITLE
Mehrfach-Selektion mit STRG

### ISSUE THREAD

**Issue by Winneone** [mediathekview/MediathekView#511]
Wenn man sich nur die HD-Releases anzeigen läßt und dann mit STRG mehrere Downloads markiert und anschließend auf den Download-Button (oben auf der Menüleiste) klickt, werden die SD-Releases geladen.

**Comment by derreisende77** [comment]
Der Filter zeigt nur an, **das** es HQ-Versionen eines Eintrages gibt. Die Filter haben keine Auswirkungen auf die Download-Einstellungen, welche in den PSets definiert werden. Dort kann vorselektiert werden, welche Version standardmäßig geladen werden soll.
Bei einem Einzeldownload kann man das im Dialog ja anpassen, bei Mehrfachselektionen erhält die Einstellung des Pset Vorrang.
