### ISSUE TITLE
Start mit Proxy der nicht antwortet schwer.

### ISSUE THREAD

**Issue by habazut** [mediathekview/MediathekView#512]
Wenn ich einen Proxy definiert habe, der aber nicht antwortet, dann bekommt man zwar einen Netzwerk-Timeout, das Program speit aber auch Java exceptions und es taucht _kein_ Fenster auf in dem man das Problem beheben könnte. Man muss also den Proxy manuell aus dem settings.xml mit Editor der Wahl rausnehmen um weiterzukommen. Ich denke das ist nicht jedermans Sache.

Linux mit 13.5.1.

Grüße,
Harald.

**Comment by derreisende77** [comment]
Das stimmt so aber nicht. Wenn die Konfiguration eines Proxy komplett falsch ist brechen Downloads mit Fehlermeldung(en) ab. Das ist soweit gewünschtes Verhalten.
Wenn der server nicht antwortet MUSS das Programm den Timeout abwarten und liefert dann Fehlermeldung(en) zurück. Auch das ist gewollt.
Die Exceptions auf der Console sind ein Hinweis für das Logfile und stören nicht den Programmablauf.

Man muss den Proxy nicht manuell aus den settings.xml herausnehmen. Im Einstellungen-Dialog (der ist nach den Fehlermeldungen immer noch erreichbar) kann man die Proxy-Konfiguration ändern. Neustart ist notwendig (steht dort auch).

Also von daher besteht hier kein Handlungsbedarf.

**Comment by habazut** [comment]
> Das stimmt so aber nicht.

Wie meinen? Das ich zu blöd bin zu sehen ob da ein Fenster auftaucht oder nicht? Dann erzähl mir mal wie lange man warten muss bis ein Fenster auftaucht. Ok, in Zukunft mache ich auch noch einen check mit xlswins (siehe unten) aber das kann man ja von einem normalen user nicht erwarten, oder?

> Man muss den Proxy nicht manuell aus den settings.xml herausnehmen.

So wie hätte ich es sonst lösen sollen ohne Fenster?
Natürlich, rm settings.xml ist auch eine Lösung.

Es wäre fein wenn man nicht gleich als Idiot hingestellt wird nur weil das Program sich vielleicht nicht ganz genau so wie erwartet. Es _kann_ natürlich auch sein dass das Fenster sich außerhalb der sichtbaren Arbeitsfläche positioniert hat, siehe issue/513, das hab ich jetzt nicht mit xlswins kontrolliert, weil sowas hab ich wirklich nicht erwartet. Ich weiss nur dass nachdem ich den Proxy händisch aus dem xml file getilgt hatte, da hatte ich wieder ein Fenster.

Also lieber reisende77, auf sowas kann man anders reagieren. "Kann ich leider nicht nachvollziehen" oder "nach einem Timeout von X sollte trotzdem ein Fenster auftauchen" sind ganz gute Sätze für so eine Situatiuon und falls du jemals in die Verlegenheit kommen wirst für Geld bei irgend einem Support zu arbeiten leg ich dir das mal zu Herzen.

Grüße,
Harald.

**Comment by derreisende77** [comment]
Jetzt pass mal auf, Mimöschen. 
In keinem Satz habe ich geschrieben das Du zu blöd bist (ob das bei der Konfiguration der Proxy-Settings zutrifft darfst Du entscheiden). Man kann sich „Beleidigungen“ auch brav einbilden.

Ich habe dir geschrieben was meine Tests hier ergeben haben, basierend auf den dünnen Informationen deinerseits (auch durch andere verifiziert). Nämlich das das Programm ohne Probleme hochfährt auch mit fehlerhaften Einstellungen. Die Proxy Einstellungen haben bis zum Start eines Downloads keine Auswirkungen.
Und beim manuellen Start eines Film-Downloads erscheinen nach Ablauf des Netzwerk-Timeouts Fehlermeldungen das der DL fehl geschlagen ist. Wenn man die alle weg klickt (es sind in der Regel mehrere) kann man sehr wohl auf den Einstellungen-Dialog klicken und die Proxy-Settings verändern. 
Das habe ich unter macOS, Linux (Kubuntu) und Windows 10 getestet.

Wenn das Verhalten bei dir anders ist wäre es ggf. clever gewesen, ETWAS mehr Angaben zu liefern (z.B. deine settings.xml) um Dein beschriebenes Verhalten nachvollziehen zu können. Auch wären ein paar Information mehr außer „Linux“ interessant gewesen da es bei diversen esoterischen WM durchaus Probleme geben kann.

Ach ja, abschließend noch etwas: Ratschläge für meine Arbeit kannst Du dir gerne kneifen, ich bin bestens für die Zukunft ausgerichtet und muss bei keinem Support arbeiten.
