### ISSUE TITLE
Retagging von 13.5.1

### ISSUE THREAD

**Issue by dvzrv** [mediathekview/MediathekView#517]
Hi! Ich maintaine mediathekview fuer Arch Linux.

Mir ist grad aufgrund eines rebuilds aufgefallen, dass version 13.5.1 retagged wurde.

Ich habe am `2020-04-30` den source tarball der version 13.5.1 heruntergeladen: https://github.com/mediathekview/MediathekView/archive/13.5.1.tar.gz

Dieser unterscheidet sich allerdings nun von dem jetzt herunterladbaren:

```
8e46259eb0ecc4f378d01fa378cf3f52d9e419194e9d6b37668bb07a9c3f6590dbd60a08ff4feff1d475c1266eb852279db37e11c76c32d39aa5ca02c7ae6daa  old-mediathekview-13.5.1.tar.gz
```

```
6c2d8e9d3f7d030de4c3b1efb8355c008ab066abe5642e17b963ce28d41696400d809f2097267540d3219dc8b0545d853560621e48f70fa83dc6a1921937343d  mediathekview-13.5.1.tar.gz
```

Der Unterschied ist die ffmpeg.exe:

```
diff -ruN a b
Binary files a/res/bin/ffmpeg.exe and b/res/bin/ffmpeg.exe differ
```

Es ist keine gute Praxis einfach einen tag zu ueberschreiben. Das bricht alle (reproduzierbaren) builds Downstream und mindert das generelle Vertrauen in einen Upstream. Bitte einfach einen neuen Tag anlegen in Zukunft!

Zudem waere es auch super Binaerdateien wie unter [res/bin/](https://github.com/mediathekview/MediathekView/tree/master/res/bin) zu finden nicht in dieses Repo einzuchecken sondern zu einem Windows spezifischen (oder Build spezifischen) Artefakt hinzuzufuegen (per build pipeline), da git ohne lfs nicht wirklich gut mit binaerdateien umgeht und dieses Repository dadurch staetig waechst.
Da kann man ganz einfach [einen der folgenden Downloads](https://ffmpeg.zeranoe.com/builds/) teil der Build Pipeline machen und *nur* wenn die Applikation gebaut wird diese Executable hinzufuegen. Das kann dann auch reproduzierbar mit Downloadlink und checksum passieren. Meines Erachtens nach macht es nicht wirklich Sinn diese Datei in diesem Repository mitzutragen.

**Comment by derreisende77** [comment]
@alex1702 wir nutzen doch git-lfs mittlerweile? Schau dir das doch mal bitte an.
