### ISSUE TITLE
Subtitle is not downloaded from ARD Mediathek

### ISSUE THREAD

**Issue by zgyarmati** [mediathekview/MediathekView#518]
I'm downloading the serie Babylon Berlin, which apparently has subtitle on the ARD web interface (see for example:  https://www.ardmediathek.de/ard/video/babylon-berlin/babylon-berlin-s01-e01/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2JhYnlsb24tYmVybGluLzYwMzk5MTBlLTBhZDAtNDg1Ni04OWRkLWQxODdjZmZiNmMxYw/ ), but unfortunately MediathekView doesn't download it, and the subtitle URL from the context menu (for the eposide above: https://www.ardmediathek.de/subtitle/258167) gives 404 error. I would guess that the URL scheme has been changed on the server side, but i couldn't figure out the correct URL. 

Version: 13.5.1
OS: KDE Neon Testing (aka Ubuntu 18.04)
java version "1.8.0_201"

**Comment by derreisende77** [comment]
this is a problem with the [Server component](https://github.com/mediathekview/MServer) and should be fixed by now for furture runs.
