### ISSUE TITLE
Run script after download completed

### ISSUE THREAD

**Issue by stueja** [mediathekview/MediathekView#519]
I'd wish for a possibility to run a script on a file mediathekview has just downloaded.
Config options in MV could be `script path`. MV could call the `script path` with at least the saved file's name. So MV would call e. g. `/usr/local/bin/mvcomplete.sh /home/user/videos/downloadedfile.mp4`.

There are a lot of flexibility for all kinds of usecases. My usecase currently is to move a file from my laptop to my NAS after it downloaded successfully.

**Comment by DaDirnbocher** [comment]
> There are a lot of flexibility for all kinds of usecases.

You can define your own "Speichern-Set" running your script.
