### ISSUE TITLE
[Test] Windows 32bit

### ISSUE THREAD

**Issue by me-like-cookies** [mediathekview/MediathekView#520]
Antwort auf https://forum.mediathekview.de/topic/3524/test-windows-32bit

@Nicklas2751 Danke, dass Du Dich der Sache angenommen und Zeit investiert hast

Ich habe eine VM
Windows 10 Pro N 2004 (19041.329), 32-Bit-Betriebssystem, x64-basierter Prozessor, 4GB RAM zugewiesen.

mit dieser habe ich folgende Rückmeldung.

### zur beigelegten ffmpeg.exe:
`C:\Program Files\MediathekView_Test32\bin>ffmpeg.exe`
`Die Version von C:\Program Files\MediathekView_Test32\bin\ffmpeg.exe ist mit der ausgeführten Windows-Version nicht kompatibel. Überprüfen Sie die Systeminformationen des Computers, und wenden Sie sich anschließend an den Herausgeber der Software.` 
Sieht nicht gut aus. Ist das 32-bit executable beigelegt?

### zum beigelegten JRE:
`C:\Program Files\MediathekView_Test32\jre\bin>java -version`
`openjdk version "14.0.1" 2020-04-14`
`OpenJDK Runtime Environment (build 14.0.1+8)`
`OpenJDK Client VM (build 14.0.1+8, mixed mode)`
Passt

### zu Mediathekview.exe:
`C:\Programs\MediathekView_Test32>MediathekView.exe
`
C:\Programs\MediathekView_Test32>`
(Beobachtung in Worten: keine Konsolenausgabe, kein Fenster öffnet sich, mediathekview.log wird nicht angelegt. In der Windows-Computerverwaltung in den Ereignisprotokollen finde ich auf die Schnelle keine passenden Fehler-Einträge. Wo könnte ein error-File stehen?)
Sieht nicht gut aus.

### zu Mediathekview.jar:
startet mit den für Win32 [genannten](https://github.com/mediathekview/MediathekView/issues/483#issuecomment-577315805) und bekannten Java-Parametern einwandfrei.

Für ausführliche Tests fehlt mir jetzt die Zeit. Meine eigenen Tests mit Liberica damals haben für die 32bit Windows Version ansonsten kein abweichendes Verhalten zur 64bit Windows Version gezeigt.

Ab Sonntag hab ich wieder Zeit für weitere Tests, oder um Fragen zu beantworten, die ich hier übersehen habe.

**Comment by Nicklas2751** [comment]
Ah ja, hab bei dem Launcher die —add-export usw. vergessen. Guck ich später dann mal. Ja die ffmpeg muss ich dafür auch noch anpassen.

**Comment by derreisende77** [comment]
@Nicklas2751 starte MV dann bitte mit -e für extended logging. ansonsten sieht man nicht so viel zum Testen

**Comment by Nicklas2751** [comment]
Das Startproblem sollte behoben sein und es die durch `-e` aktivierten zusatz logs sollten erscheinen.

Neue Dateien hier: https://p.elaon.de/m-2W4/

**Comment by me-like-cookies** [comment]
ich habe diese Dateien von o.g. Pfad gezogen:
MediathekView_windows-x32_13_6_0-SNAPSHOT.zip SHA-512 1b51349ab222f07ed86d597a53d580bcf421098bcb29d6239f98cddd1fe23e0f5e2dcae97bc2f0855529e886e1698d8c5b9ba395ee5e5fc735c30ec7cccf0bfd 
MediathekView_windows-x32_13_6_0-SNAPSHOT.exe SHA-512 9000164fe24e542d5e3ced4d85e4dabc63bd11d38b26539387282fb4f6205501c41cb97a5e3e0ecb69a536ae58968d98cf03829772989c8ae8550a1d6cbf3519

zu ffmpeg.exe aus diesen Archiven: SHA-512 fb7b93d9e095432b4b4af55917f656f60c159202d69f59f985e88c7dc32ceae1992d3516a218326cd6b3f82fdd30cff0f041992b31651c0539b24f9e8a7889a2

siehe erster Beitrag.

zu MediathekView.exe aus diesen Archiven: SHA-512 e5a08449fce58e3777b9b3ccaea9b31884d0b181eea9428e0051bab8f1855abd84feb021f4d8734b864f2afd7d5fa6cc33db46031bf97ebf21261944fb94eeb3 

siehe erster Beitrag.

**Comment by Nicklas2751** [comment]
Hmm ich kann gerade sie sha nicht überprüfen aber guck doch mal bitte was in der Konsole ausgegeben wird. Ffmpeg ist unverändert, das passt aber die MediathekVie exe muss sich geändert haben. Hab ihr u.a. das add-exports verpasst.

**Comment by Nicklas2751** [comment]
Laut deinem Screenshot ist die Mediathekview.exe von 14:51 Uhr. Erstellt habe ich  das neue aber erst um 16:54 Uhr. 

Am besten einen neuen Ordner nehmen und in diesen das zip entpacken. ;)

**Comment by me-like-cookies** [comment]
Tut mir leid. Ich hab die zip Datei eben von einem *anderen* Rechner aus nochmal und nochmal geholt, um sicher zu gehen, dass nicht bei mir irgendwo ein Cache dazwischenfunkt.

Ich bekomme beim Download:
MediathekView_windows-x32_13_6_0-SNAPSHOT.zip
SHA-512
1b51349ab222f07ed86d597a53d580bcf421098bcb29d6239f98cddd1fe23e0f5e2dcae97bc2f0855529e886e1698d8c5b9ba395ee5e5fc735c30ec7cccf0bfd 

Und ich diskutiere hier weiter, wenn der SHA oder ein anderer Hash bestätigt oder als falsch bezeichnet wird und statt dessen ein anderer SHA Wert oder etwas Ähnliches zur Verifikation / Falsifikation Geeignetes Instrumentarium genannt wird, gegen den ich vergleichen soll.

Falls der o.g. SHA der der aktuellen Testdatei ist, dann bitte ich, das zip Archiv zu öffnen und im Unterordner "MediathekView" das Änderungsdatum der MediathekView.exe zu lesen. Es ist in dem Archinv mit obigem SHA folgendes Datum für MediathekView.exe: 2020-06-26 14:51

Das zip Archiv MediathekView_windows-x32_13_6_0-SNAPSHOT.zip mit diesen Inhalten wurde dagegen um 16:54 Uhr erstellt.

Ich habe zwar keinen Snapshot der VM von vor dem ersten Test heute, auf den ich zurückkehren hätte können. Aber ich habe vor meinem Post von 20:44 Uhr das zip Archiv in einen frischen Ordner entpackt, um genau das auszuschließen...
...wobei ich heute Morgen um 8:56 Uhr kaum eine Datei von 14:51 Uhr selben Tages hatte testen können, glaube ich...

daher: zur Vermeidung von weiteren Mißverständnissen teste ich *nach Nennung von SHA*, ab Montag, gerne weiter.

**Comment by Nicklas2751** [comment]
Um auch ein cache Problem bei mir auszuschließen habe ich es erneut gebaut.

Hier der Download: https://p.elaon.de/m-FWzJZV/
Das Zip hat die SHA256 9c98a7c7ca813306ba1bd558f4053d289ef4e6d92df5f4f09174e8da96651589
und die MediathekView.exe darin hat: SHA256 d1535e6493f59f51f39943e6251e91364d2a1315acb585114880a6b16e180a89

**Comment by me-like-cookies** [comment]
Danke. Muss gleich los darum kurz:

Empfangen habe ich Dateien mit identischen SHA256 Werten, die Du oben nennst
MediathekView_windows-x32_13_6_0-SNAPSHOT.zip
9c98a7c7ca813306ba1bd558f4053d289ef4e6d92df5f4f09174e8da96651589

MediathekView.exe
d1535e6493f59f51f39943e6251e91364d2a1315acb585114880a6b16e180a89

Leider ist es wiederum so, dass beim Àufruf in der Console weder auf dem 64-bit host noch in der 32-bit VM etwas passiert.
Es tut mir leide, dass ich hier erneut nur die vageste aller Fehlermeldungen geben kann: "es passiert nichts."

`C:\temp\MediathekView_windows-x32_13_6_0-SNAPSHOT\MediathekView>MediathekView.exe -e`

`C:\temp\MediathekView_windows-x32_13_6_0-SNAPSHOT\MediathekView>`

Hast Du ein 64-bit Windows verfügbar? Und verhält es sich bei Dir ebenso, oder kriegst Du MV damit gestartet?


Morgen hab ich mehr Zeit.
Kannst Du eine Code-Stelle oder irgendein Werkzeug nennen, mit dem ich analysieren kann, was in der Zeit zwischen Programmaufruf und dem Wiederholen des Prompt in der Console passiert?

**Comment by Nicklas2751** [comment]
Ich habe mir eine Windows 7 32bit VM besorgt und es dort ausprobiert. Wie du sagst tut es leider garnichts. Außer man startet es via `jre\bin\java -Xmx2G -jar MediathekView.jar` dann bekommt man, den Fehler, dass er dem Teil nicht genug RAM geben kann. Mit `Xmx1G` funktionierts. 

Daher hier nun mit standard 1GB: https://p.elaon.de/m-yWVG5/

Witzigerweise schafft mein Raspberry Pi 4 mit 32bit Raspbian auch 2GB. Warum Win7 32 das nicht mag ist mir ein Rätsel.

**Comment by me-like-cookies** [comment]
Zuerst zu MediathekView_windows-x32_13_6_0-SNAPSHOT.zip
SHA-256: 119444d7619d8749f6527fc5fb0deab97c608f7f977f22f0774ed5bb571e691a

Aufruf 
`C:\Programs\MediathekView_windows-x32_13_6_0-SNAPSHOT\MediathekView>MediathekView.exe -e`
führt auch bei mir in der Win32 VM auf Anhieb zu einem erfolgreichen Programmstart. Es wird ein log File erzeugt (s.u.). Und die mir bekannte Ausnahme beim Erzeugen der Widgets im Filter Dialog ist auch nicht da. In anderen Worten ist der Slider für Mindest- und Maximallänge vorhanden. - Weiter habe ich nicht getestet.

[mediathekview.log](https://github.com/mediathekview/MediathekView/files/4842842/mediathekview.log)

Auch wenn ich das MediathekView_windows-x32_13_6_0-SNAPSHOT.exe
SHA-256: b1c2c50e93b0c45e81854f4ed553dfd2f5cf40d337f345797b42f1dcdeba57ab
über die bestehende MV Installation drüber installiere, startet das MediathekView.exe auf Doppelklick erforlgreich und die GUI öffnet sich.


Dann noch zu der anderen Geschichte. Tut mir leid, hätte ich diesen Parameterwert von 2 GB schon am Freitag gekannt, hätte ich mir das ganze SHA-Mimimi geschenkt und Du und ich hätten Zeit sparen können.

Ich war zum einen bei meinem damaligen Startskript für meinen inoffiziellen 13.5.1 Build für Win32 schon mit 1,5 GB auf die Nase gefallen. Das klappte mal, mal nicht...
Zum anderen hab ich persönlich aus Altersgründen schon vor etlichen Jahren mal in C++ einen blutige-Nase-Moment gehabt, wo Win32 beim Allokieren von großen Arrays aussteigt:

`BYTE *array = new BYTE[1<<30 + 1<<29]; // wirft exception...`

Aber kurz Suchmaschine benutzen [erklärt das Rätsel auch](https://www.oracle.com/java/technologies/hotspotfaq.html#gc_heap_32bit)

Start Parameter -Xmx1280m sollte laut dem Artikel noch drin sein.
 -Xmx1408m dagegen könnte schon in Bereich "Glückssache" gehen.

Grundsätzlich finde ich für die allermeisten Nutzer das MediathekView.exe sehr praktisch. Es hat aber einen fiesen Nachteil und Ich persönlich verwende das MediathekView.exe wegen dem grundsätzlich nicht mehr. Hab nur für diesen Test ne Ausnahme gemacht. Als ich mich zuletzt gefreut hatte "Schön, endlich ist bei mir mal volle CPU Auslastung bei "stillem" MV, kann ich gleich mal kucken, welchen Thread da noch läuft, muß nur mal kurz VisualVM star... Nö.

Hast Du zum 32-Bit Programm noch Fragen an mich?

P.S.: ffpmeg.exe bitness ...
