### ISSUE TITLE
[Enhancement]  Mehrere Filter

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MediathekView#523]
Wiedereinführung von mehreren Filtern, abspeichern dieser und wieder laden.

- Es muss mindestens ein Filter vorhanden sein
- Filter müssen angelegt und gelöscht werden können

**Comment by DaDirnbocher** [comment]
Wow. Das schaut spitze aus.

**Comment by derreisende77** [comment]
In 13.6 drin
