### ISSUE TITLE
--auto Modus?

### ISSUE THREAD

**Issue by JPRuehmann** [mediathekview/MediathekView#525]
Wird es irgendwann wieder eine möglichkeit geben seine Abos an der Komandozeile scriptgesteuert herunterzuladen?
Oder Bleibt Mediathekview unverwendbar?

**Comment by alex1702** [comment]
Die Antwort bleibt die gleiche: wenn es jemand einbaut

**Comment by JPRuehmann** [comment]
Es wahr drinn und hat funktioniert!
Warum wurde es entfernt?

**Comment by Nicklas2751** [comment]
Weil es ein extra Teil war der die Entwicklung des Clients ausgebremst hat. Noch dazu hat der Client Anforderungen an das Betriebssystem die gegen einen solchen Einsatz sprechen. Z.b. Dass eine Grafischeoberfläche vorhanden sein Muss.

Deshalb wurde es aus dem Client entfernt wird aber als eigener Client zurückkehren. Nur wann ist noch ungewiss.

BTW. Mit Forderungen erreichst du hier nichts. Keiner von uns ist dir irgendwas schuldig.

**Comment by JPRuehmann** [comment]
Ich fordere garnichts.
Ich habe nur gefragt wann das Programm wieder Nutzbar wird.

**Comment by JPRuehmann** [comment]
Der start des Programmes mit grafischem Frontend dauert mehrere Minuten, verbraucht mindestens 4GB Speicher und stürzt nach maximal 15Minuten kommentarlos ab verbraucht laut htop zwischen 200% und 400% Leistung (start über die Kommandozeile). Außerdem kann ich dann keine anderen Anwendungen mehr starten. Als Befehl via Chrontab gibt es diese Probleme alle nicht(128MB 1% und keine abstürze).

**Comment by OrbitingOcelot** [comment]
> Deshalb wurde es aus dem Client entfernt wird aber als eigener Client zurückkehren. Nur wann ist noch ungewiss.

Ist dieser Plan immer noch aktuell? Eine Command-Line Version fände ich sehr nützlich.
