### ISSUE TITLE
13.6.0 benoetigt "preview features"

### ISSUE THREAD

**Issue by dvzrv** [mediathekview/MediathekView#528]
Seit 13.6.0 benoetigt der Start von Mediathekview den zusaetzlichen `--enable-preview` parameter fuer `java` um "preview features" zu aktivieren (siehe [man page](https://jlk.fjfi.cvut.cz/arch/manpages/man/java-openjdk14.1#STANDARD_OPTIONS_FOR_JAVA)) beim Start mit OpenJDK14.

Zu dieser notwendigen Aenderung sehe ich aber nichts in der [Release Note](https://mediathekview.de/news/mediathekview-13-6/).

**Comment by alex1702** [comment]
Das stimmt. Startest du MediathekView manuell?

**Comment by dvzrv** [comment]
Ich package mediathekview fuer Arch Linux. Im package wird das folgende script (z.B. per XDG desktop file) genutzt um die Applikation zu starten:
https://github.com/archlinux/svntogit-community/blob/packages/mediathekview/trunk/mediathekview.sh

**Comment by derreisende77** [comment]
@dvzrv Es ist besser folgendes zu machen:
`java —enable-preview -jar ...`

**Comment by derreisende77** [comment]
@dvzrv Ich weiß nicht ob/wie bei Arch dependencies gemanaged werden aber da ich nun native Benachrichtigungen unter Linux unterstütze sollte - falls möglich - eine dependency zu libnotify hinzugefügt werden.

**Comment by dvzrv** [comment]
> @dvzrv Es ist besser folgendes zu machen:
> `java —enable-preview -jar ...`

Das ist vermutlich richtig (werd ich beim naechsten Update aendern). So funktioniert es allerdings auch.

> @dvzrv Ich weiß nicht ob/wie bei Arch dependencies gemanaged werden aber da ich nun native Benachrichtigungen unter Linux unterstütze sollte - falls möglich - eine dependency zu libnotify hinzugefügt werden.

Ist das optional oder eine harte dependency? Kann ich in jedem Fall hinzufuegen.

**Comment by derreisende77** [comment]
ein optional sollte reichen.

**Comment by stueja** [comment]
Ich belebe dieses Issue neu. Wenn das nicht gewünscht ist, dann mache ich auch gerne ein neues auf.

Seit dem letzten Systemupdate (Arch Linux) startet mediathekview (13.7.1) nicht mehr. Beim Systemupdate wurde als auf den ersten Blick einziger möglicher Schuldiger Java aktualisiert (von 15.0.3 auf 16.0.1). Seitdem gibt mediathekview beim Start über die Konsole nur noch das aus:

```
/usr/lib/jvm/java-16-openjdk/bin/java --enable-preview -jar /usr/share/java/mediathekview/MediathekView.jar
Error: LinkageError occurred while loading main class mediathek.Main
	java.lang.UnsupportedClassVersionError: mediathek/Main (class file version 59.65535) was compiled with preview features that are unsupported. This version of the Java Runtime only recognizes preview features for class file version 60.65535
```

Was kann ich tun, um mv wieder zum Leben zu erwecken?

**Comment by derreisende77** [comment]
Lade am besten die aktuelle nightly von 13.8 und nutze diese. Sie ist fast fertig lediglich die 32 bit variante hat noch Probleme so dass Du sie schon nutzen kannst.
