### ISSUE TITLE
Ausstrahlungsdatum älter als 01.01.1970 wird verworfen

### ISSUE THREAD

**Issue by HolgerAusB** [mediathekview/MediathekView#529]
Alle Sendungen die älter sind als 1. Januar 1970 haben in MV 13.6.0 und früher derzeit KEIN Datum. Dadurch wirkt auch der Zeitraum-Filter nicht.

Da die ARD-Sender am 27 Oktober 2020 alle non-fiktionalen Beiträge von vor 1966 in ihre Mediatheken fluten wollen, sollte MV auch Datumsangaben von vor 1970 verarbeiten können. Als Workaround notfalls eine Checkbox, dass Sendungen ohne Datum ausgeblendet werden.

Ich fürchte eben, dass Suchvorgänge und auch Abo-Durchläufe sonst nach dem 27. Oktober deutlich länger dauern könnten.

Siehe auch meinen schon älteren [Beitrag im Forum](https://forum.mediathekview.de/topic/3515/ard-will-sendungen-aus-der-zeit-vor-1966-dauerhaft-online-stellen?_=1597907253372).

**Comment by derreisende77** [comment]
Das Ticket für MV client ist falsch da dieser die Filme korrekt darstellen wird. Wie im Forum verlinkt ist das entsprechende Ticket für den server noch offen: [Ticket](https://github.com/mediathekview/MLib/issues/119)
Deshalb schließe ich das hier und @pidoubleyou sollte das sich noch einmal ins Gedächtnis rufen ;)

**Comment by HolgerAusB** [comment]
oh sorry. das hab ich übersehen
