### ISSUE TITLE
Packaging von mediathekview.ico

### ISSUE THREAD

**Issue by me-like-cookies** [mediathekview/MediathekView#532]
Mir ist auf Windows 10 x64 Pro 2004 beim Verwenden der vom MV 13.6.0 Win64 Installer eingespielten Datei mediathekview.ico für ein Desktop-Symbol aufgefallen, dass das MV Symbol nicht dargestellt wird. 

Folgende Informationen helfen ggfs. das Problem nachzuvollziehen:
im git Repository (master) hat die Datei eine Größe von 15.086 Byte
SHA256 b2e4797a3f2e1dd6d24455d78fa3b908211ffe265b3b7b8fcbaeb6d476e2948b
SHA512 089b0e2407d70e510c6adf58eed0e83011159369229eb5d8ae5a1cb61b18f2784d570823987e04f2ad500e2c681631d7b62ef96c9fd0054dbbd34928905680b9

die bei mir vom MV 13.6.0 Win64 installer eingespielte Version hat eine Größe von 23.329 Byte,
SHA256 3205669b2812994a432dba9e446af15a53c05053370a0d3d92904d175b1f955e
SHA512 ddc0ebdf0f49e91076b7ba27dcb2ccf06c4626de8e9054959fe33d20cd87590c3f65ec64f8473680eb3b08ad200a752bae1554984973fde85372664b0e27c9dd
dies gilt auch für die vom MV 13.6.0 Win32 installert auf Win 10 Pro x86 2004

Meine Erwartung: bitweise Übereinstimmung der git-Version mit der installierten Version bei identischer Dateigröße

**Comment by derreisende77** [comment]
@Nicklas2751 kannst Du da was zu sagen?

**Comment by Nicklas2751** [comment]
Guck ich mal drauf bei Gelegenheit. Evtl passt der Pfad in der install4j Datei nicht oder so.
