### ISSUE TITLE
macOS splash string

### ISSUE THREAD

**Issue by supervisitor** [mediathekview/MediathekView#534]
... still the same with Catalina 10.15 (19G73) + Java SE 14.0.2 and now MediathekView 13.6:
![Screen-Shot-2020-08-26-at-12 48](https://user-images.githubusercontent.com/10810886/91297725-136dca00-e79f-11ea-96da-ff033a514902.jpg)
and both (macOS + JRE) are official supported versions!

_Originally posted by @supervisitor in https://github.com/mediathekview/MediathekView/issues/472#issuecomment-680820256_

**Comment by supervisitor** [comment]
more important could be the name of the font you use on the splash screen and the versions the user have installed?
when I trace the fonts used by MV, then I see this list:
`
/Library/Fonts/ACaslonPro-Bold.otf
/Library/Fonts/ACaslonPro-BoldItalic.otf
/Library/Fonts/ACaslonPro-Italic.otf
/Library/Fonts/ACaslonPro-Regular.otf
/Library/Fonts/ACaslonPro-Semibold.otf
/Library/Fonts/ACaslonPro-SemiboldItalic.otf
/Library/Fonts/AGaramondPro-Bold.otf
/Library/Fonts/AGaramondPro-BoldItalic.otf
/Library/Fonts/AGaramondPro-Italic.otf
/Library/Fonts/AGaramondPro-Regular.otf
/Library/Fonts/AmericanTypewriter.ttc
/Library/Fonts/Andale Mono.ttf
/Library/Fonts/Apple Chancery.ttf
/Library/Fonts/Arial Black.ttf
/Library/Fonts/Arial Bold Italic.ttf
/Library/Fonts/Arial Bold.ttf
/Library/Fonts/Arial Italic.ttf
/Library/Fonts/Arial Narrow Bold Italic.ttf
/Library/Fonts/Arial Narrow Bold.ttf
/Library/Fonts/Arial Narrow Italic.ttf
/Library/Fonts/Arial Narrow.ttf
/Library/Fonts/Arial Rounded Bold.ttf
/Library/Fonts/Arial.ttf
/Library/Fonts/Athelas.ttc
/Library/Fonts/Baskerville.ttc
/Library/Fonts/BigCaslon.ttf
/Library/Fonts/Brush Script.ttf
/Library/Fonts/Capitals.dfont
/Library/Fonts/ChaparralPro-Bold.otf
/Library/Fonts/ChaparralPro-BoldIt.otf
/Library/Fonts/ChaparralPro-Italic.otf
/Library/Fonts/ChaparralPro-Regular.otf
/Library/Fonts/CharlemagneStd-Bold.otf
/Library/Fonts/Charter.ttc
/Library/Fonts/Cochin.ttc
/Library/Fonts/Comic Sans MS Bold.ttf
/Library/Fonts/Comic Sans MS.ttf
/Library/Fonts/CooperBlackStd-Italic.otf
/Library/Fonts/CooperBlackStd.otf
/Library/Fonts/Copperplate.ttc
/Library/Fonts/Courier New Bold Italic.ttf
/Library/Fonts/Courier New Bold.ttf
/Library/Fonts/Courier New Italic.ttf
/Library/Fonts/Courier New.ttf
/Library/Fonts/Didot.ttc
/Library/Fonts/DIN Alternate Bold.ttf
/Library/Fonts/DIN Condensed Bold.ttf
/Library/Fonts/Futura.ttc
/Library/Fonts/Georgia Bold Italic.ttf
/Library/Fonts/Georgia Bold.ttf
/Library/Fonts/Georgia Italic.ttf
/Library/Fonts/Georgia.ttf
/Library/Fonts/GillSans.ttc
/Library/Fonts/Impact.ttf
/Library/Fonts/Iowan Old Style.ttc
/Library/Fonts/LithosPro-Black.otf
/Library/Fonts/LithosPro-Regular.otf
/Library/Fonts/Luminari.ttf
/Library/Fonts/Marion.ttc
/Library/Fonts/Microsoft Sans Serif.ttf
/Library/Fonts/MinionPro-Bold.otf
/Library/Fonts/MinionPro-BoldCn.otf
/Library/Fonts/MinionPro-BoldCnIt.otf
/Library/Fonts/MinionPro-BoldIt.otf
/Library/Fonts/MinionPro-It.otf
/Library/Fonts/MinionPro-Medium.otf
/Library/Fonts/MinionPro-MediumIt.otf
/Library/Fonts/MinionPro-Regular.otf
/Library/Fonts/MinionPro-Semibold.otf
/Library/Fonts/MinionPro-SemiboldIt.otf
/Library/Fonts/MyriadPro-Bold.otf
/Library/Fonts/MyriadPro-BoldCond.otf
/Library/Fonts/MyriadPro-BoldCondIt.otf
/Library/Fonts/MyriadPro-BoldIt.otf
/Library/Fonts/MyriadPro-Cond.otf
/Library/Fonts/MyriadPro-CondIt.otf
/Library/Fonts/MyriadPro-It.otf
/Library/Fonts/MyriadPro-Regular.otf
/Library/Fonts/MyriadPro-Semibold.otf
/Library/Fonts/MyriadPro-SemiboldIt.otf
/Library/Fonts/NuevaStd-BoldCond.otf
/Library/Fonts/NuevaStd-BoldCondItalic.otf
/Library/Fonts/NuevaStd-Cond.otf
/Library/Fonts/NuevaStd-CondItalic.otf
/Library/Fonts/OCRAStd.otf
/Library/Fonts/OratorStd-Slanted.otf
/Library/Fonts/OratorStd.otf
/Library/Fonts/Papyrus.ttc
/Library/Fonts/Phosphate.ttc
/Library/Fonts/PrestigeEliteStd-Bd.otf
/Library/Fonts/RosewoodStd-Regular.otf
/Library/Fonts/Savoye LET.ttc
/Library/Fonts/Seravek.ttc
/Library/Fonts/SignPainter.otf
/Library/Fonts/Skia.ttf
/Library/Fonts/SnellRoundhand.ttc
/Library/Fonts/Songti.ttc
/Library/Fonts/StencilStd.otf
/Library/Fonts/SuperClarendon.ttc
/Library/Fonts/Tahoma Bold.ttf
/Library/Fonts/Tahoma.ttf
/Library/Fonts/TektonPro-Bold.otf
/Library/Fonts/TektonPro-BoldCond.otf
/Library/Fonts/TektonPro-BoldExt.otf
/Library/Fonts/TektonPro-BoldObl.otf
/Library/Fonts/Times New Roman Bold Italic.ttf
/Library/Fonts/Times New Roman Bold.ttf
/Library/Fonts/Times New Roman Italic.ttf
/Library/Fonts/Times New Roman.ttf
/Library/Fonts/TrajanPro-Bold.otf
/Library/Fonts/TrajanPro-Regular.otf
/Library/Fonts/Trebuchet MS Bold Italic.ttf
/Library/Fonts/Trebuchet MS Bold.ttf
/Library/Fonts/Trebuchet MS Italic.ttf
/Library/Fonts/Trebuchet MS.ttf
/Library/Fonts/Verdana Bold Italic.ttf
/Library/Fonts/Verdana Bold.ttf
/Library/Fonts/Verdana Italic.ttf
/Library/Fonts/Verdana.ttf
/Library/Fonts/Webdings.ttf
/Library/Fonts/Zapfino.ttf
/System/Library/Fonts/Apple Braille Outline 6 Dot.ttf
/System/Library/Fonts/Apple Braille Outline 8 Dot.ttf
/System/Library/Fonts/Apple Braille Pinpoint 6 Dot.ttf
/System/Library/Fonts/Apple Braille Pinpoint 8 Dot.ttf
/System/Library/Fonts/Apple Braille.ttf
/System/Library/Fonts/Apple Color Emoji.ttf
/System/Library/Fonts/Apple Symbols.ttc
/System/Library/Fonts/AppleSDGothicNeo.ttc
/System/Library/Fonts/ArialHB.ttc
/System/Library/Fonts/Avenir Next Condensed.ttc
/System/Library/Fonts/Avenir Next.ttc
/System/Library/Fonts/Avenir.ttc
/System/Library/Fonts/Courier.dfont
/System/Library/Fonts/GeezaPro.ttc
/System/Library/Fonts/Geneva.dfont
/System/Library/Fonts/Helvetica.dfont
/System/Library/Fonts/HelveticaNeue.dfont
/System/Library/Fonts/Hiragino Sans GB W3.ttc
/System/Library/Fonts/Hiragino Sans GB W6.ttc
/System/Library/Fonts/Kohinoor.ttc
/System/Library/Fonts/KohinoorBangla.ttc
/System/Library/Fonts/KohinoorTelugu.ttc
/System/Library/Fonts/LucidaGrande.ttc
/System/Library/Fonts/MarkerFelt.ttc
/System/Library/Fonts/Menlo.ttc
/System/Library/Fonts/Monaco.dfont
/System/Library/Fonts/Noteworthy.ttc
/System/Library/Fonts/Optima.ttc
/System/Library/Fonts/Palatino.ttc
/System/Library/Fonts/PingFang.ttc
/System/Library/Fonts/SFNSDisplay-Bold.otf
/System/Library/Fonts/SFNSDisplay-Regular.otf
/System/Library/Fonts/SFNSText-Bold.otf
/System/Library/Fonts/SFNSText-BoldItalic.otf
/System/Library/Fonts/SFNSText-Regular.otf
/System/Library/Fonts/SFNSText-RegularItalic.otf
/System/Library/Fonts/STHeiti Light.ttc
/System/Library/Fonts/STHeiti Medium.ttc
/System/Library/Fonts/Symbol.ttf
/System/Library/Fonts/Thonburi.ttc
/System/Library/Fonts/Times.dfont
/System/Library/Fonts/ZapfDingbats.ttf
`
the fonts on my mac are all fine and checked... but could be that MV is one missing, because I manage all of this manually.
(could it be better to combine the app name as graphic with black background?)

**Comment by supervisitor** [comment]
... now I found in your code, you don't define a font anywhere. so an other solution to fix this (instead of pasting the name as graphic file) could be to define at `src/main/resources/mediathek/res/css/splashscreen.css` for `#appName`  (or on higher level, because it is "inherit") something like this:
`-fx-font-family: "sans-serif";`
but remember: `JavaFX CSS does not support comma-separated series of font family names in the -fx-font-family property.` ([JavaFX CSS Ref. Guide](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/doc-files/cssref.html) & [Limitations](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/doc-files/cssref.html#introlimitations))

**Comment by derreisende77** [comment]
as you seem to be able to modify the code and the css file, the question: Does your suggested solution **fix** the display problem on your machine? Not specifying the font family for a javafx label simply means "use the default provided font" and works for all of the other used strings.

**Comment by supervisitor** [comment]
I'm as surprised as you are, because it works fine for all other texts without any specification?!
But there are probably still more than I where the error also occurs. ([#472 @thetrial](https://github.com/mediathekview/MediathekView/issues/472#issuecomment-678314735)) I think most people don't report it, because it doesn't annoy them. (like me! 😎)

Now I check both: `-fx-font-family: "sans-serif";` and `-fx-font-family: "Helvetica";`, No differences between the two or without?!
But there are still some font files inside the jar where I can't analyze how they interact with the OS fonts at the moment or if they are fine or not.

**Comment by derreisende77** [comment]
The fonts are loaded by JavaFX via their native routines. They query all available system fonts and do some magic to make them available to JavaFX. There are reported bugs in the font handling (one I reported several months ago related to the inability to draw bold text - they haven´t fixed it yet :-( )
So far all reports have been from macOS only and I am more thinking that this might be some graphics driver bug on apple´s side as the FXML used for the dialog is valid. All the Macs I have available do not experience this behaviour.
Therefore I am currently not really eager trying to find a workaround for it besides updating the JavaFX runtime whenever updates are available. If you can find a workaround I will happily look at a pull request and maybe we can integrate it.

**Comment by supervisitor** [comment]
Then you can probably just create a picture of the text or call it modern art. 😇

**Comment by derreisende77** [comment]
I´ll call it modern art and hopefully a fix will be provided by JavaFX in the future. Currently we don´t plan on using an image here but maybe this may change. For now I am going to close this.
