### ISSUE TITLE
Doppelte Einträge verschiedener Sender vermeiden

### ISSUE THREAD

**Issue by Matthias84** [mediathekview/MediathekView#539]
Hi, ich habe den MTV jetzt wiederentdeckt, hätte aber einen Wunsch, um die Nützlichkeit meiner RSS-Abos noch zu erhöhen.
Sucht man etwa nach ["Rostock"](https://mediathekviewweb.de/#query=Rostock), sind die meisten Einträge doppelt und gleichnamig sowohl beim NDR, als auch ARD gelistet.

Könnte man eine Möglichkeit schaffen, um gleichnamige Einträge zusammenzuführen? Also z.B. das die Regionalprogramme der Öffentlich Rechtlichen vlt. erhalten bleiben, aber ARD / ZDF dann versteckt werden?

**Comment by DaDirnbocher** [comment]
Wenn Du von RSS Abso sprichst, meinst Du wohl mediathekviewweb, hier gehts um die Desktopapplikation Mediathekview.

issues zu mediathekviewweb gibts [hier](https://github.com/mediathekview/mediathekviewweb).

Die Doppellistung ARD/Regionalsender war ein Wunsch der USer im [Forum](https://forum.mediathekview.de/).

Du kannst aber in mediathekviewweb nach sender filtern, auch nach mehreren gleichzeitig. D.h. Du könntest nur ARD oder nur die Regionalen filtern.
