### ISSUE TITLE
Suche mit zu ignorierbaren Stichwörtern

### ISSUE THREAD

**Issue by Matthias84** [mediathekview/MediathekView#540]
Ich mag den MTV und verfolge verschiedene Themen per RSS. Mir ist bei der Zusammenstellung aber aufgefallen, dass man nicht wie bei Suchmaschienen etc. auch Wörter aus den Suchergebnissen ausschließen kann. So könnte die Suche nach[ rostock -sport](https://mediathekviewweb.de/#query=Rostock%20-sport) alle Einträge listen, welche "Rostock" enthalten, aber nicht zusammen mit "sport"?

**Comment by DaDirnbocher** [comment]
Auch hier: Du bist für mediathekviewweb hier falsch, und Dein Wunsch wurde vom Programmierer bereits zugesagt. https://github.com/mediathekview/mediathekviewweb/issues/91 Die Frage ist nur wann.

**Comment by Matthias84** [comment]
Danke für die schnelle Reaktion. Ich hatte vermutet, dass dies feature zunächst im core berücksichtigt werden muss. Ich schaue mal bei MVV, danke! :smile:
