### ISSUE TITLE
Filtersettings während der Aktualisierung der Filmlistentabelle

### ISSUE THREAD

**Issue by DaDirnbocher** [mediathekview/MediathekView#541]
Eine der Änderungen der 13.6.:

* BUGFIX: Filtersettings können während Aktualisierung der Filmlistentabelle nicht mehr geändert werden um inkosistenten Zustand zu vermeiden.

Es wäre ein **nice-to-have**, wenn es (irgend)ein optisches Feedback für den Zeitraum gäbe, für den die Filtersettings gesperrt sind (Filterdialog grau oder im Fenstertitel sowas wie "Filter busy").

Hintergrund: 
* Auf schwächeren Rechnern kann die Aktualisierung durchaus "etwas" dauern, da könnte man glauben, dass MV hängt (hatte ich schon, bis mir diese Änderung einfiel - insbesondere bei Filtern mit ARD-Beteiligung) 
* Es ist immer noch möglich, vermeintlich inkonsistente Zustände per Screenshot zu dokumentieren, wenn man den richtigen (oder falschen - je nach Sichtweise) Zeitpunkt erwischt.

**Comment by derreisende77** [comment]
Eigentlich "sollte" dies schon die ganze Zeit der Fall sein.
Ich habe in develop nun explizit nochmals code drin welcher den Filterdialog deaktivieren soll. Hoffe das hilft in Zukunft.

**Comment by derreisende77** [comment]
Aufgrund der Art wie das Datenupdate implementiert ist kann ich leider **nicht** ein optisches Feedback hierzu geben. Um das einzubauen müsste die komplette Ansicht neu programmiert werden :( 
Dies wird erst später erfolgen wenn sie im Rahmen des Umbaus eh ersetzt werden muß
