### ISSUE TITLE
Schalter für automatische Programmbeendigung implementieren

### ISSUE THREAD

**Issue by derreisende77** [mediathekview/MediathekView#543]
Funktion:
wenn gesetzt, Starte Programm, lade alle Abos, beende Programm.
siehe hierzu [Forum](https://forum.mediathekview.de/topic/3663/kommandozeilenversion/7?page=1)

**Comment by toby63** [comment]
Interessant wäre in diesem Zusammenhang eventuell noch eine Funktion den Computer herunterzufahren.

**Comment by OrbitingOcelot** [comment]
Fände so eine Funktion auch toll.

Anwendungsszenario:
PC bootet, User loggt sich ein
MV startet via Autostart
MV holt die Filmliste+erstellt Downloadliste+arbeitet Abo Liste ab
MV zeigt Meldung in Statuszeile und wartet 60 Sekunden
MV beendet sich selbst

**Comment by OrbitingOcelot** [comment]
Hatte mir schon Hoffnungen gemacht, aber leider hat es das Ticket wohl nicht in 13.8 geschafft. Gibt es evt. eine Chance, das in Version 14 oder eine der darauffolgenden aufzunehmen? Vielen Dank!

**Comment by derreisende77** [comment]
In 14 nicht da es nicht ganz so einfach ist das feature zu integrieren. Dafür müssten für Downloads sämtliche GUI-Dialog die auftreten können deaktiviert werden was nicht sinnvoll ist.
Ein separates Programm ist hierfür aus meiner Sicht sinnvoller welches nur downloadet. Das wird aber noch einige Zeit benötigen.

**Comment by OrbitingOcelot** [comment]
Okay, vielen Dank für die Rückmeldung/Einschätzung!

**Comment by derreisende77** [comment]
Ist ab 14.0.1 als Parameter verfügbar.

**Comment by dgottstein** [comment]
Gibt es schon Pläne, wann die v14.0.1 released wird?

**Comment by derreisende77** [comment]
in ca. 14 Tagen ggf. Aber es ist schon via nightlies verfügbar.

**Comment by dadidadit** [comment]
Die Funktion gibt es doch schon seit mindestens Version  13.7.1 :

**Downloads > Alle Downloads zeitversetzt starten**.

Für das Laden von Abos ist es notwendig, dass mindestens 1 Download  bereits in der Liste vorhanden ist, sonst wird das Programm sofort wieder beendet. Dazu könnte man z. B. eine fehlerhafte Dummy-URL nutzen, den dabei angezeigte Fehler einfach mit "Weiter" übergehen. Die Zeitverzögerung könnte dazu genutzt werden, die aktuelle Filmliste zu laden, die Abos zu ermitteln und nach Herunterladen aller Downloads das Programm automatisch beenden zu lassen und evtl. sogar den Rechner herunterfzufahren.
Und falls man unbedingt inen Scheduler nutzten möchte (mit nircmd die zeitversetzte Option starten), kann man das Programm soohl starten als auch per Batch beenden. Unter Windows einfach mal HELP in der Konsole eingeben und unter dem Buchstaben "T" findet man auch den passenden Befehl.
Lesen bildet, in den Kontexmenus und in den Aleitungen ...

**Comment by dadidadit** [comment]
Die Funktion gibt es doch schon seit mindestens Version 13.7.1 :

Downloads > Alle Downloads zeitversetzt starten.

Für das Laden von Abos ist es notwendig, dass mindestens 1 Download bereits in der Liste vorhanden ist, sonst wird das Programm sofort wieder beendet. Dazu könnte man z. B. eine fehlerhafte Dummy-URL nutzen, den dabei angezeigte Fehler einfach mit "Weiter" übergehen. Die Zeitverzögerung könnte dazu genutzt werden, die aktuelle Filmliste zu laden, die Abos zu ermitteln und nach Herunterladen aller Downloads das Programm automatisch beenden zu lassen und evtl. sogar den Rechner herunterfzufahren.
Und falls man unbedingt inen Scheduler nutzten möchte (mit nircmd die zeitversetzte Option starten), kann man das Programm soohl starten als auch per Batch beenden. Unter Windows einfach mal HELP in der Konsole eingeben und unter dem Buchstaben "T" findet man auch den passenden Befehl.
Lesen bildet, in den Kontexmenus und in den Anleitungen ...

**Comment by dadidadit** [comment]
Die Funktion gibt es doch schon seit mindestens Version 13.7.1 :

**Downloads > Alle Downloads zeitversetzt starten**

Für das Laden von Abos ist es notwendig, dass mindestens 1 Download bereits in der Liste vorhanden ist, sonst wird das Programm sofort wieder beendet. Dazu könnte man z. B. eine fehlerhafte Dummy-URL nutzen, den dabei angezeigten Fehler einfach mit "Weiter" übergehen. Die Zeitverzögerung könnte dazu genutzt werden, die aktuelle Filmliste zu laden, die Abos zu ermitteln und nach Herunterladen aller Downloads das Programm automatisch beenden zu lassen und evtl. sogar den Rechner herunterfzufahren.
Und falls man unbedingt einen Scheduler zum Starten nutzen möchte (mit nircmd die zeitversetzte Option starten), kann man Mediathekview sowohl starten als auch per Batch beenden.
Unter Windows einfach mal HELP in der Konsole eingeben und unter dem Buchstaben "T" findet man dann auch den passenden Befehl. Und eigentlich wird die neue Option "-dp" damit auch überflüssig.

Lesen bildet, in den Kontexmenus und in den Anleitungen ...
