### ISSUE TITLE
Build Anleitung aktualisieren

### ISSUE THREAD

**Issue by Wonno** [mediathekview/MediathekView#547]
Eine detaillierte Anleitung wie lokal gebaut und gestartet und gedebuggt werden kann wäre wünschenswert.

Was mir konkret fehlt sind die Startparameter für die JVM um das jar mit Java 14 starten und debuggen zu können.

Die Konsole nach dem Start mit Exceptions geflutet:
`Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: jdk/swing/interop/SwingInterOpUtils`

Derzeit von mir verwendete Startup Optionen:
```java --module-path C:\tools\javafx-sdk-11.0.2\lib
--add-exports=javafx.base/com.sun.javafx.logging=ALL-UNNAMED
--add-exports=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED
--add-exports=javafx.graphics/com.sun.javafx.embed=ALL-UNNAMED
--add-exports=javafx.graphics/com.sun.javafx.css=ALL-UNNAMED
--add-exports=javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED
--add-exports=javafx.graphics/com.sun.javafx.stage=ALL-UNNAMED
--add-exports=javafx.graphics/com.sun.javafx.scene=ALL-UNNAMED
--add-exports=javafx.base/com.sun.javafx.event=ALL-UNNAMED
--add-exports=javafx.graphics/com.sun.javafx.cursor=ALL-UNNAMED
--add-exports=javafx.graphics/com.sun.javafx.util=ALL-UNNAMED
%CLASSPATH% mediathek.Main --debug
```

**Comment by derreisende77** [comment]
git clone....
mvn clean install
cd target
java —enable-preview -jar MediathekView.jar ...

steht im Wiki und man braucht keine add-exports

**Comment by Nicklas2751** [comment]
Intellij öffnen, Projekt als Maven dings importieren. Mit Maven bauen und zum testen und debuggen die Main Klasse mit InelliJ ausführen bzw. Debuggen. 

Bei eclipse das ganze nur halt mit eclipse.

**Comment by Wonno** [comment]
Fehler gefunden:  
Anstatt `OpenJDK Runtime Environment AdoptOpenJDK  14 ` muss das `OpenJDK 14` verwendet werden.

**Comment by derreisende77** [comment]
@Wonno hast du nen Link? dann muss man nicht ewig suchen
