### ISSUE TITLE
Start program in tray

### ISSUE THREAD

**Issue by RealVegOs** [mediathekview/MediathekView#550]
Es wäre zumindest für mich schön, wenn sie das Programm per Autostart zum Trayicon minimiert starten ließe. Ich habe es mit devilspie2 nicht hinbekommen. Und selbst wenn, besser wäre, wenn MediathekView das selber könnte. Danke! - Wenn alle meine Programme aus dem Autostart maximiert starten würden, bekäme ich eine Meise.

**Comment by derreisende77** [comment]
Man kann in den Einstellungen das Programm so konfigurieren dass es sich in das Tray minimiert. Wenn man unter Windows dann MV mittels x "beendet" verschwindet das Fenster in das Tray. Das kann man mittels nircmd und dem senden entsprechender Befehle an MV wohl erreichen. Dazu gab es im Forum diverse Anleitungen wie man nircmd anwenden kann.

**Comment by RealVegOs** [comment]
nircmd hab ich unter LInux eben nicht... Wäre also schön, wenn das Programm minimiert starten könnte. devilspie kann das wohl mit Java-Progarammen nicht. Deshalb mein featrue request.

**Comment by derreisende77** [comment]
Naja, Du hast nicht geschrieben welches Linux und welche Desktop Umgebung du verwendest...Eine explizite Funktion zum minimierten Starten werde ich nicht einbauen, da die von Java angebotene Tray-Funktionalität asbach-uralt-Technologie ist und halt "gerade noch" funktioniert. Es gibt seit Jahren Wünsche das zu verbessern aber Oracle hat da wohl auch kein Interesse daran. Eine kurze Google Suche hat mir diverse Links ausgespuckt wie man das unter KDE ab Version 4 wohl realisieren kann und bei anderen wohl auch ([Beispiel](https://www.google.com/search?q=linux+start+app+minimized&oq=linux+start+app+minimized&aqs=chrome..69i57.14243j0j1&sourceid=chrome&ie=UTF-8).

**Comment by RealVegOs** [comment]
Ich hatte schon selber rumgelesen und Diverses probiert, hab ja auch Internet! War alles nicht so, wie ich es haben wollte. Schade, daß Java nichts brauchbares auf Lager hat, so daß es das Programm selber kann. Im Prinzip geht es mir ja nur um das relative lange Laden des Programmes, wiewohl das jetzt deutlich schneller geworden ist. Wäre es evtl. möglich, das Programm per Autostart ohne GUI im Hintergrund zu starten, quasi als daemon process, so daß bei Bedarf nur noch die Grafik starten muß? Gibt Java dafür was her?

**Comment by RealVegOs** [comment]
Finde ich nicht gut, das issue zu schließen! Desktop spielt keine Rolle, jeder Desktop muß das handhaben können. Hatte außerdem jahrelang gar keinen. Benutze kein Betriebssystem aus dem Suppentüte. Aber wenn's interessiert: Debian Buster mit Mate. Tschüß, ich frage nix mehr!

**Comment by derreisende77** [comment]
Issues sind dazu da, Fehler zu melden oder Feature requests zu stellen. Ich habe dir geschrieben weshalb ich es nicht umsetzen werde. Von daher besteht keine Notwendigkeit das issue offen zu halten. Dies ist der Lauf der Dinge von issues. Das mag Dir gefallen oder nicht, ist aber so. 
Es gibt wmcontrol, xdotools etc mit denen man so etwas erreichen kann. Für Fragen in dieser Richtung ist auch eher das Forum angebracht, dort gibt es diverse Linux User die Gefallen an solchen Fragen finden.

MediathekView ist eine GUI Applikation, sie besteht nicht aus einem daemon und einer separaten UI. Von daher besteht auch keine Möglichkeit dies im Hintergrund laufen zu lassen. Das war nie der Zweck der Applikation als sie 2008 ins Leben gerufen wurde.
13.6.1 ist auch so modifiziert worden dass der splash screen in den Hintergrund geklickt werden kann so dass er nicht mehr dauerhaft stören wird. Mehr ist nicht drin.
