### ISSUE TITLE
13.6.0: Löschen eines Abos löscht falsches Abo

### ISSUE THREAD

**Issue by MuenchenSued** [mediathekview/MediathekView#552]
Wie in https://forum.mediathekview.de/topic/3672/abo-verwalten-senderselektion/5 beschrieben, gibt es ein Fehlverhalten beim löschen von Abos. Wenn man “Abos” verwalten" auswählt und dann nach Sender filtert, wird nicht die Zeile dieses Senders sondern die an der gleichen Position in der Komplettliste gelöscht. Wird also ZDF gefiltert und die erste ZDF-Zeile soll gelöscht werden, dann wird die allererste Zeile aller Abos gelöscht. Auf die Weise kann man sich seine ganzen Abos verunstalten.

**Comment by MuenchenSued** [comment]
Die Abo Edit-Funktion ist auch von diesem Bug betroffen. Wird beispielsweise bei 10 Abos nach ZDF gefiltert und bleiben die Nummern 1 und 9 übrig, dann führt das Editieren von Abo 9 dazu, dass Abo 2 bearbeitet wird.

**Comment by derreisende77** [comment]
@MuenchenSued Im aktuellen develop ist ein fix dafür nun enthalten. ACHTUNG: Bitte history.txt vorher sichern da diese nun in eine DB migriert wird und nach Erfolg gelöscht wird. Sofern Du zurück gehen möchtest musst Du diese wieder hinein kopieren UND dann history.db löschen.

**Comment by MuenchenSued** [comment]
Der Fix wirkt nicht beim Löschen sondern nur beim Ändern. Beim Löschen von 9 (wie im obigen Bild) wird weiterhin 2 gelöscht

![Bildschirmfoto vom 2020-11-02 14-16-34](https://user-images.githubusercontent.com/71550657/97872382-3a53f980-1d16-11eb-829c-2e63736c8d30.png)

**Comment by derreisende77** [comment]
Okay, ich habe gerade einen weiteren commit gemacht der das Löschen nun beheben sollte. Dies sowohl beim Löschen eines Eintrages als auch bei mehreren.
