### ISSUE TITLE
java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by bardware** [mediathekview/MediathekView#553]
Ich hatte mir kürzlich MediathekView 13.6 als ZIP geladen und starte das Programm immer über die Kommandozeile. Ich habe zuletzt JDK 14 von AdoptOpenJDK genutzt.
`D:\JAVA\jdk-14.0.2+12\bin\java.exe --enable-preview -Xmx1G -jar MediathekView.jar`
Da JDK 14 EOL war und JDK 15 kam, wollte ich heute darauf wechseln.
Leider erhielt ich eine Fehlermeldung

```
D:\JAVA\jdk-15+36\bin\java.exe --enable-preview -Xmx1G -jar MediathekView.jar
Fehler: Beim Laden der Klasse mediathek.Main ist ein LinkageError aufgetreten
        java.lang.UnsupportedClassVersionError: mediathek/Main (class file version 58.65535) was compiled with preview features that are unsupported. This version of the Java Runtime only recognizes preview features for class file version 59.65535
```

Heißt das, dass ich sinnigerweise bei JAVA 14 bleibe?

**Comment by Nicklas2751** [comment]
Im ZIP ist bereits die passende JRE/JDK enthalten.

________________________________
Von: Bernhard Döbler <notifications@github.com>
Gesendet: Saturday, September 19, 2020 8:35:02 PM
An: mediathekview/MediathekView <MediathekView@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [mediathekview/MediathekView] java.lang.UnsupportedClassVersionError (#553)


Ich hatte mir kürzlich MediathekView 13.6 als ZIP geladen und starte das Programm immer über die Kommandozeile. Ich habe zuletzt JDK 14 von AdoptOpenJDK genutzt.
D:\JAVA\jdk-14.0.2+12\bin\java.exe --enable-preview -Xmx1G -jar MediathekView.jar
Da JDK 14 EOL war und JDK 15 kam, wollte ich heute darauf wechseln.
Leider erhielt ich eine Fehlermeldung

D:\JAVA\jdk-15+36\bin\java.exe --enable-preview -Xmx1G -jar MediathekView.jar

Fehler: Beim Laden der Klasse mediathek.Main ist ein LinkageError aufgetreten

        java.lang.UnsupportedClassVersionError: mediathek/Main (class file version 58.65535) was compiled with preview features that are unsupported. This version of the Java Runtime only recognizes preview features for class file version 59.65535



Heißt das, dass ich sinnigerweise bei JAVA 14 bleibe?

**Comment by derreisende77** [comment]
Ja, derzeit unterstützen wir nur Java 14.
