### ISSUE TITLE
Option to disable startup splash screen

### ISSUE THREAD

**Issue by Marrib** [mediathekview/MediathekView#554]
**Current situation**
MediathekView needs some time to start up -- up to a minute or so on slower computers or when installed on a regular HDD drive instead on a SSD. Even on faster computers with SSD the startup takes some time.
During the whole startup process a huge splash screen logo/image is dispayed in the center on the screen, covering all other applications and makes the computer completely unusable for the time it takes for MV to start up. This is frustrating, because it interrupts the user and it is impossible to have MV start in the background.

**Feature request / enhacement**
Please implement an option (for example an on/off toggle in the MV settings) to disable the splash screen. Or if that's not wanted by the developers, then please change the splash screen so that other windows can be brought to the foreground and that the splash does not cover other windows.

**Benefits**
• Splash screen does not cover other windows and applications on the screen
• Instead of waiting for MV to start up, users can work on other things in the foreground while MV starts in the background

**Comment by derreisende77** [comment]
splash screen will no longer be always on top of other windows

**Comment by Marrib** [comment]
Thank you!!!

**Comment by strangezuffi** [comment]
Can it be that this behaviour reappeared? In version 14.1.0 , the splash screen again covers every other program and doesn't fall to the background when it loses the focus.
