### ISSUE TITLE
Write video information as nfo file

### ISSUE THREAD

**Issue by Lonerider2010** [mediathekview/MediathekView#558]
For Kodi users it is very useful to get the information about a movie, tv show, documentation etc as an .nfo file instead of a .txt file. Are there plans to implement this?

**Comment by derreisende77** [comment]
No there hasn´t been any request for this feature yet. According to [this kodi spec](https://kodi.wiki/view/NFO_files/TV_shows) a quick scan shows that only a movie nfo might be usable for MediathekView. And with that you will only get a title, a uniqueid type "MediathekView" and a year. 
Therefore I do not see much benefit in here. But please correct me if I am wrong and hint me to more benefits.
