### ISSUE TITLE
Weiterführen eines abgeschlossenen Downloads startet diesen von vorne

### ISSUE THREAD

**Issue by almereyda** [mediathekview/MediathekView#559]
Wenn eine Datei in der Downloadliste vollständig geladen wurde, wird diese erneut heruntergeladen, wenn die Funktion *Alle Downloads starten* genutzt wird. Darauf wird nicht explizit hingewiesen.

Diese Schritte lassen den Effekt auftreten:

1. Downloadliste mit Downloads füllen und einige herunterladen.
2. Fehlerhafte Downloads vorhalten und neue hinzufügen.
3. *Alle Downloads starten* anwählen
4. Hinweis auf bereits heruntergeladene Dateien auch zu starten bestätigen.
5. Bei existierenden Dateien erscheint das Wiederaufnehmen Fenster, welches es auch erlaubt den Download unter neuem Namen fortzuführen. Das Wiederaufnehmen ist zu wählen.
6. Die Datei wird nun nicht von dort fortgesetzt, wo sie zuletzt beendet wurde (100 %), sondern wird neu von vorne begonnen.

Es wäre wünschenswert, dass der Dialog in (4.) darauf hinweist, dass bereits abgeschlossene Downloads neu von vorn gestartet werden, oder dass die Wiederaufnahme aus (5.) erkennt, dass eine Datei zu 100 % vorhanden ist, und nicht fortgesetzt zu werden braucht.

Eine deutlichere Benennung der Konsequenzen kann hier helfen kleine Irritationen zu vermeiden.

**Comment by DaDirnbocher** [comment]
> 

> Wenn eine Datei in der Downloadliste vollständig geladen wurde, wird diese erneut heruntergeladen, wenn die Funktion _Alle Downloads starten_ genutzt wird. Darauf wird nicht explizit hingewiesen.

Die Funktion heisst "alle Downloads starten" und nicht "alle noch nicht runtergeladenen Downloads starten. Insofern tut sie ihren Namen entsprechend genau das, was sie soll.

Man kann ja, bevor man diese Fuktion ausführt, die Downloadliste säubern, dann gibts auch keine Doppeldownloads.

**Comment by almereyda** [comment]
Danke für den Hinweis. Ich hatte versucht anzumerken, dass an dieser Stelle das Wording etwas expliziter sein könnte, damit Mißverständnisse im vorhinein begegnet werden kann. Ich habe gerade aber auch keinen besseren Gegenvorschlag.

Lässt sich mein Punkt zumindest nachvollziehen, und kann sich da wer anschließen?

**Comment by DaDirnbocher** [comment]
> Danke für den Hinweis. Ich hatte versucht anzumerken, dass an dieser Stelle das Wording etwas expliziter sein könnte, damit Mißverständnisse im vorhinein begegnet werden kann. Ich habe gerade aber auch keinen besseren Gegenvorschlag.

Was soll man noch klarer formulieren als "alle Downloads starten"? Etwa "alle Downloads starten (Aber Achtung alle heißt auch wirklich alle)"?

Im Grunde willst Du - Vermutung! -  kein klareres Wording, sondern eine andere Funktionalität, nämlich "offene Downloads starten". Stell einen Featurerequest und dann wirst ja sehen, ob das umgesetzt wird.

**Comment by almereyda** [comment]
Ja, wir haben hier vermutlich ein semantisches Problem. Vermutlich suche ich nach etwas wie

> Alle unfertigen Downloads starten

anstatt

> Alle Downloads starten und abgeschlossene neu beginnen

In meinem Verständnis lassen sich abgeschlossene Downloads nicht wieder starten, da sie ja komplett sind. MediathekView ist hier anderer Meinung als ich. (:

**Comment by DaDirnbocher** [comment]
> n meinem Verständnis lassen sich abgeschlossene Downloads nicht wieder starten, da sie ja komplett sind.

So verstehen wir halt beide einiges nicht.

Und ich verstehe nicht, warum man fertige Downloads in der Downloadliste belässt, wenn man sie eh gar nicht noch einmal laden möchte.

Und ich verstehe auch nicht, warum man zuerst einzelne Downloads offensichtlich manuell startet und danach "alle Downloads" starten will.  Oder wie kommts sonst zu fertigen Downloads wo man danach "alle starten" machen möchte?

**Comment by derreisende77** [comment]
Ich sehe das ganze wie @DaDirnbocher und halte Änderungen an einer Funktionalität, mit der bisher 99,999% der User klargekommen sind für nicht zielführend. Der OP hat nach dem Auswählen der Funktion 2x mindestens jeweils Dialoge bestätigen/klicken müssen um darauf zu kommen was nun passieren wird. Man muß einem nicht alles vorbeten und ein wenig geistige Eigenleistung (z.B. in Form Frage im Forum oder Lesen der Anleitung) kann man dem geneigten Nutzer schon zumuten.
