### ISSUE TITLE
4k Text Skalierung 150% funktioniert nicht

### ISSUE THREAD

**Issue by dreambox** [mediathekview/MediathekView#560]
13.6.0
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)

32" 3840 x 2160 150% Windows 10

Test wird in den Tabellen und Tabs sowie diversen Steuerelementen nicht skaliert und ist extrem klein, kaum zu lesen

**Comment by DaDirnbocher** [comment]
Siehe [Anleitung](https://mediathekview.de/anleitung/#starten) Stichwort: `-Dsun.java2d.uiScale=XXX`

**Comment by dreambox** [comment]
Super, hat funktiniert, danke DaDirnbocher
