### ISSUE TITLE
Historische Beiträge nur teilweise auffindbar

### ISSUE THREAD

**Issue by m-ad** [mediathekview/MediathekView#561]
Einige sehr alte Mediathek-Einträge aus dem SWR-Archiv sind über die Suche nicht auffindbar, zum Beispiel dieser Beitrag von 1960:
https://www.ardmediathek.de/ard/video/abendschau/karlsruhe-modernisierung-der-altstadt/swr-de/Y3JpZDovL3N3ci5kZS9hZXgvbzExOTc3NDM/

Zumindest konnt ich es weder in MediathekView noch MediathekViewWeb mit diversen Sucheingaben finden.

Ein weiteres nicht auffindbares Beispiel von 1965:
https://www.ardmediathek.de/ard/video/abendschau/letzte-fahrt-der-alten-turmbergbahn-in-karlsruhe/swr-de/Y3JpZDovL3N3ci5kZS9hZXgvbzExNTcwNjg/

Das gilt aber nicht generell für alle historischen Beiträge. Zum Beispiel eine [Suche](https://mediathekviewweb.de/#query=abendschau%20karlsruhe&everywhere=true&future=true) nach "Abendschau Karlsruhe" liefert u.a. einen Treffer von 1965: https://www.ardmediathek.de/ard/video/abendschau/politesse-schreibt-strafzettel/swr-de/Y3JpZDovL3N3ci5kZS9hZXgvbzExNTY2Nzc/

Auch aus 1962 lassen sich mit einer [Suche](https://mediathekviewweb.de/#query=abendschau%201962&everywhere=true) Beiträge finden, aber gemessen am [Angebot in der Mediathek](https://www.ardmediathek.de/ard/sendung/abendschau/Y3JpZDovL3N3ci5kZS8yNDEwMzE1Ng/) dann doch recht wenig.

Warum sind nicht alle historischen Beiträge auffindbar?

**Comment by Nicklas2751** [comment]
Solche und ähnliche Fragen sollten im [Forum](https://forum.mediathekview.de) gestellt werden.

Aber kurz gesagt: der Crawler sucht nicht so weit in die Vergangenheit zurück wenn die Folgen nicht über die Api neu ausgeliefert werden tauchen Sie auch nicht in der Film Liste auf.
