### ISSUE TITLE
"Download sofort starten" nur auf aktuellen FIlm anwenden - Einstellungen bereinigen

### ISSUE THREAD

**Issue by MuenchenSued** [mediathekview/MediathekView#563]
Wie in https://forum.mediathekview.de/topic/3598/einstellungen-bereinigen beschrieben fände ich es gut, wenn beim Download eines Filmes der Button "Download sofort starten" nur auf den aktuellen Film angewendet wird und nicht für alle folgenden. Ähnlich wie für den Button "Infodatei anlegen" sollte das generelle Verhalten über einen eigenen Eintrag in den Einstellungen erfolgen.

**Comment by derreisende77** [comment]
nicht mehr in 13.6.1, die ist fast fertig

**Comment by blubber-temp** [comment]
Wenn man gewünschte (mehrere) Downloads markiert und dann mit **d** startet, hat man doch die Möglichkeit, die Einstellungen einzeln zu aktivieren/deaktivieren. Vielleicht könntest du dir damit helfen?

**Comment by derreisende77** [comment]
Also das Feature existiert so seit 2016 und es gab bisher keine Beschwerden. Von daher gesehen wird es in diesem Dialog nicht geändert werden.
Da der Dialog an sich zu einem späteren Zeitpunkt zur Überarbeitung ansteht wird es dann ggf. zu Anpassungen der Funktionalität kommen. Bis dahin mache ich das issue zu
