### ISSUE TITLE
Export history.db in lesbares Format

### ISSUE THREAD

**Issue by blubber-temp** [mediathekview/MediathekView#564]
13.6.1: Wünschenswert wäre eine Export-Funktion, mit der die history.db wieder lesbar und durchsuchbar wäre. In der Nightly z., Zt nicht vorhanden.

**Comment by derreisende77** [comment]
Ist eine sqlite db. Das heisst sie kann mit den offiziell dazugehörigen tools geöffnet gelesen und modifiziert werden. Und also auch exportiert. Gib zig GUIs dafür für Windows,linux und Mac. 
Ansonsten wird es aus vorher genannten Gründen keine Exportfunktion geben.

**Comment by blubber-temp** [comment]
Hi,
danke für die prompte Antwort. Eigentlich hätte ich darauf selbst kommen können, sorry, ist heute nicht mein Tag. :-)

Ansonsten Top Programmversion, wirklich gut gelungen und sehr schnell. Danke dafür.

Gruß und schönes Wochenende.
