### ISSUE TITLE
[Feature Request] Automatically add new episodes to thetvdb

### ISSUE THREAD

**Issue by jwillmer** [mediathekview/MediathekView#565]
Automatically add new episodes to https://www.thetvdb.com

Plex, Kodi and other media management apps are using thetvdb.com to get additional information about media files. The most important information is the season and episode number. For German TV shows the information is not complete and some poor guy needs to update it every time he wants correct information displayed in his media management app. Could MediathekView not allow us to automatically add the information to thetvdb.com? Since at the time of downloading the episode we have all the necessary information and could really improve the episode lookup for German TV shows.

**Comment by Nicklas2751** [comment]
MediathekView doesn’t know the season or episode number. It even doesn’t know if a video is a single film or a series.

**Comment by jwillmer** [comment]
Episode number doesn't matter since thetvdb uses the (first) aired date to define the position. 

I know it won't work for all TV shows and maybe we need to still use some manual work but even if it only works for a couple predefined TV shows it would be a great improvement.

**Comment by derreisende77** [comment]
Well we will not spend time on integration data upload to thtvdb. First it won´t have any benefit for MediathekView. Second, you have to register to upload data. Third - and this is the showstopper from my side: If you upload data and/or images to thetvdb you *"[..]expressly grant us a license to use[...]"* (see [this link](https://www.thetvdb.com/api-information)). This is something I will not do as the description content belongs to the respective sender and **I will not** seek permission to upload the respective sender´s data to thetvdb.
If you don´t care about the possible legal implications, our data is freely available in different formats and you could write an uploader for thetvdb yourself, with all the risk on your side.

**Comment by vitusson** [comment]
Eine schöne Schnapsidee.
Selbst wenn es so eine Schnittstelle zu tvdb.cm gäbe, wären die "Informationen" die die ÖR-Mediatheken zu Serien liefern absolut nicht geeignet dort irgendetwas sinnvolles einzutragen. Jeder Sender braut bei der Benamung sein eigenes Süppchen, Staffel und Episodennummern werden nach Lust und Laune mitgeliefert oder auch nicht, sinnlose Zusätze eingestreut.
Greade eben beim ZDF, 6 Folgen einer Serie, und jede Folge hat exakt hat den gleichen Titel "They Were Ten - Französische Thrillerserie - Deutsche Erstausstrahlung", ohne Nummern. Viel Spaß damit so etwas bei tvdb einzutragen…
