### ISSUE TITLE
datei ohne Bytes

### ISSUE THREAD

**Issue by evusoft** [mediathekview/MediathekView#569]
Bares für Rares-Bares für Rares vom 15. Dezember 2020 - Die Trödel-Show mit Horst Lichter-062203.mp4 hat 0 Bytes zum Downloaden

**Comment by derreisende77** [comment]
Es kommt manchmal vor das URLs der Sender nicht funktionstüchtig sind. Mittlerweile ist in der Filmliste ein funktionierender Link enthalten.

Fehlerhafte oder fehlende Sendungen werden bitte im [Forum](https://forum.mediathekview.de) gemeldet. Hier werden in der Regel nur Fehler des Programms aufgenommen.
