### ISSUE TITLE
Zusätzlicher Filtereintrag für die Blacklist

### ISSUE THREAD

**Issue by ghost** [mediathekview/MediathekView#570]
Folgende Erweiterungsmöglichkeit der neuen Filtersteinstellungen mit mehreren Filtern  halte ich für überlegenswert:

Wenn man mit einem Filter alles abschalten kann, was eine vollständige Suche evtl. behindert, wäre auch die Abschaltung der Blacklist mit einer im Filter enthaltenen Checkbox ideal . Dann könnte man bei Bedarf mit **einem** Filterwechsel auf auf einmal alles aus- und wiedereinschalten. Damit sollte man dann eigentlich auch alles finden (können).

**Comment by derreisende77** [comment]
Das An- und Abschalten der Blacklist hat noch weitere Seiteneffekte und ggf. Auswirkungen auf die angelegten Abos. Weiterhin ist die Basisintention des Filters das einzugrenzen was nach der Blacklist übrig ist. 
Die gewünschte Änderung wird in Anbetracht der bisherigen Funktion der Blacklist nur zur Verwirrung der meisten Nutzer führen, daher werde ich den Vorschlag in dieser Programmreihe nicht umsetzen.
