### ISSUE TITLE
Test Readme.md

### ISSUE THREAD

**Issue by blubber-temp** [mediathekview/MediathekView#571]
Test Readme.md ergänzt

**Comment by blubber-temp** [comment]
Jetzt muss ich nur noch raus bekommen, wie ich die vergleichen kann.

Derzeit werden die Mediatheken der folgenden Sender unterstützt:

- ARD (Das Erste)
   - BR (Bayerischer Rundfunk)
   - HR (Hessischer Rundfunk)
   - MDR (Mitteldeutscher Rundfunk)
   - NDR (Norddeutscher Rundfunk)
   - Radio Bremen TV
   - RBB (Rundfunk Berlin-Brandenburg)
   - SR (Saarländischer Rundfunk)
   - SWR (Südwestrundfunk)
   - WDR (Westdeutscher Rundfunk)
   - ONE
   - ARD alpha
   - tagesschau24
   - Phoenix  (Gemeinschaft ARD und ZDF)
   - Arte Gemeinschaft ARD und ZDF (deutsch und französisch)
- ZDF (Zweites Deutsches Fernsehen) inkl.  ZDFneo, ZDFInfo und Tivi
   - Phoenix (Gemeinschaft ARD und ZDF)
   - Kika (Kinderkanal von ARD und ZDF)
   - 3Sat
   - Arte Gemeinschaft ARD und ZDF (deutsch und französisch)
- DW TV (Deutsche Welle)
- ORF (Österreichischer Rundfunk)
- SRF (Schweizer Rundfunk) inkl. Podcasts

**Comment by alex1702** [comment]
DU verwirrst mich, was genau machst du hier?

**Comment by blubber-temp** [comment]
Ich habe mir die DE Repo auf nach lokal kopiert und die Anleitung und die FAQ ergänzt (lokal!) Nun sollte ich einen Branch erstellen und die beiden Versionen einen Pullrequest vergleichen, dazu einen Issue aufmachen. Leider habe ich den aus Versehen hier im Repro erstellt und nicht gewusst, wie ich den wieder wegkriege. Die Anleitung und die FAQ sind fertig. Kannst du mir bitte helfen?

**Comment by alex1702** [comment]
erst mal musst du dieses repo hier über github forken, dann checkst du deinen fork lokal aus. Du kannst aber auch die änderungen eventuell mit der Web-IDE machen.
Wenn du lokal entwickelt hast, dann pushed du den oder die commits und danach kannst du in deinem fork einen pull request gegenüber unser repo machen.

**Comment by alex1702** [comment]
Eventuell hilft dir ja folgendes Video: https://www.youtube.com/watch?v=hSbJaIdqwKg

**Comment by blubber-temp** [comment]
Nein, ich habe nur statt im DE Repo den Issue hier aufgemacht und kriege den nicht wieder weg. Ich weiß ja, wo's hin soll. Nicht Hier. Kannst du den Issue evtl. einfach killen?
