### ISSUE TITLE
"Programminfos anzeigen" via Menü "Hilfe" funktioniert nicht

### ISSUE THREAD

**Issue by styroll** [mediathekview/MediathekView#575]
Beim Anklicken der Menüeintrags "Programminfos anzeigen" im Menü "Hilfe" passiert nichts (macOS 10.14.6 Mojave und MV 13.7). [Gemäss Forum](https://forum.mediathekview.de/post/25274) funktioniert das auch unter Linux nicht.

**Comment by derreisende77** [comment]
Ja weil es derzeit keine Programminfos gibt. Dann erscheint auch kein Dialog

**Comment by styroll** [comment]
>@derreisende77 sagte: Ja weil es derzeit keine Programminfos gibt. Dann erscheint auch kein Dialog

In der Zwischenzeit gibt es ja eine Meldung. Bei Befehlen mit "Bla bla…" also mit den 3 Punkten sollte immer ein Fenster erscheinen, auch wenn dann dort bloss "Keine aktuellen Infos" steht.

Beim Befehl darüber, also bei "Nach Update suchen…" erscheint auch nicht einfach nichts, wenn keine neuere Programmversion vorliegt, sondern es erscheint auch eine entsprechende (sinnvolle) Mitteilung:

<img width="271" alt="MV_Update-Suche" src="https://user-images.githubusercontent.com/24810728/103039816-11abeb80-4572-11eb-8641-683ba6e3c167.png">
