### ISSUE TITLE
"URL kopieren" im Kontextmenü lässt bei Playlists (SRF, ORF…) keine Auswahl der Qualität zu

### ISSUE THREAD

**Issue by styroll** [mediathekview/MediathekView#576]
Wenn man via Rechtsklick auf einen Film die "URL kopieren" will, kann man bei Playlists (SRF, ORF…) keine Auswahl der Qualität mehr selektieren ([vgl. Forum](https://forum.mediathekview.de/topic/3883/film-url-kopieren)).
Über den Download-Dialog ist das weiterhin möglich.

Ich gehe davon aus, dass dieses Verhalten ein unbeabsichtigtes Verhalten aus der Korrektur des folgenden Bugfix ist:

>BUGFIX: Im Kontextmenü des Tab Film wurde der Eintrag “Film-URL kopieren” in “URL kopieren” umbenannt. Gleichzeitig wird nun geprüft ob es sich um einen regulären Film mit mehreren URLs handelt oder um eine PlayList. Dementsprechend wird die Auswahl nun korrekt angeboten.

**Comment by pidoubleyou** [comment]
der Crawler ermittelt bei m3u8-Dateien bereits qualitätsspezifische Urls, so dass in der Filmliste zwar m3u8-Dateien aufgeführt sind, aber für jede Qualität eine eigene.

in 13.6 wurden die verschiedenen Urls korrekt angezeigt, sollte auch in 13.7 so gemacht werden.

**Comment by derreisende77** [comment]
Wird dann in der nächsten version gefixt. Meine Einträge hatten immer identische URLs.
