### ISSUE TITLE
Function "Add to JDownloader" should also parse the title to JDownloader, not just the URL; functional redundancy to "Copy URL to clipboard"

### ISSUE THREAD

**Issue by Marrib** [mediathekview/MediathekView#577]
The "Add to JDownloader" context menu function is a great new functionality.

However, only the URL is parsed to JDownloader, not the title. That's why users have to manually rename the file and enter the title in JDownloader. It would be a great time saver if MediathekView would also parse the title to JDownloader automatically.

Additionally, the current situation is redundant, because MediathekView has two context menu functions built in: "Copy URL to clipboard" and "Add to JDownloader", which do basically the same:

Parsing the _URL only without the title_ to JDownloader does not need this separate "Add to JDownloader" function. Because the same thing can be achieved by using the function "Copy URL to clipboard" and setting JDownloader to monitor the clipboard. The separate  "Add to JDownloader" function would make more sense if it had additional benefits to just parsing the URL, for example parsing the title, too.

**Comment by derreisende77** [comment]
There is no API to send title to JDownloader.

**Comment by pat-richter** [comment]
@derreisende77 but it can be configured via packagizer settings. Maybe this can be added as a hint.

After I've found [this thread](https://github.com/mediathekview/mediathekviewweb/issues/125) via search, I've created a small [gist](https://gist.github.com/pat-richter/387b927e9ff44294dc2d3dcda0948e5f) which could be executed via DevTools. There is also a comment how to use it in combination with JDownloader (keeping file names).

**Comment by derreisende77** [comment]
Your mixing MVW which is javascript with MV which is Java. Otherwise i would be interested how you‘d call JS from Java

**Comment by pat-richter** [comment]
@derreisende77 sure. I just mentioned it here as an example how one could implement this feature. 

Sorry, I've missed to say that part earlier ;-)

**Comment by styroll** [comment]
>@Marrib sagte: The separate "Add to JDownloader" function would make more sense if it had additional benefits to just parsing the URL, for example parsing the title, too.

Wenn man – wie [hier im Forum beschrieben](https://forum.mediathekview.de/post/25621) – direkt die URL der Webseite zur Sendung an JD (also nicht die Video-URL) weitergeben könnte, dann hätte man das Problem mit dem Titel gar nicht und dafür zusätzlich folgende Vorteile:

- Zugriff auf Videos in anderen Sprachen und/oder Untertiteln (z.B. bei ARTE)
- weitere Auflösungen, die MV nicht anbietet
- aktuelle funktionierende DL-Möglichkeit für den Fall, wo die Video-URL gewechselt, aber der Crawler das nicht mitgekriegt hat (geschieht beim ZDF immer wieder) – für mich der wichtigste Punkt

Wenn das möglich wäre, würde ich allerdings weiterhin JD über ein separates Aufnahme-Set (Übergabe an einen externen DL-Manager) aufrufen, da man via Kontextmenü JD selber bereits gestartet haben muss.
