### ISSUE TITLE
[Feature request] Buttons bar should be customizable

### ISSUE THREAD

**Issue by Marrib** [mediathekview/MediathekView#578]
MediathekView has a button bar at the top, in the "Movies" tab and in the "Downloads" tab. Those buttons provide quick access to useful main functions, which is great.

However, many useful functions are only accessible via the context menu or the (sub)menus bar at the very top.

I think the buttons bar should be customizable so that every user can add/create buttons for functions he uses frequently and remove buttons of functions that he does not need (very often).

**Comment by derreisende77** [comment]
Yeah they should be customizable, however this functionality is not provided by the UI framework and would be very time-consuming for implementation. Therefore I will not implement this in the near future.
