### ISSUE TITLE
13.7.0: Blacklist - Zeile löschen löscht falsche Zeile

### ISSUE THREAD

**Issue by MuenchenSued** [mediathekview/MediathekView#579]
Wie im [Forum](https://forum.mediathekview.de/topic/3932/blacklist-zeile-l%C3%B6schen-l%C3%B6scht-falsche-zeile) beschrieben, wird beim Löschen von Zeilen in der Blacklist ab dem zweiten Löschvorgang die falsche Zeile entfernt.
Das Verhalten konnte ich bestätigen.

**Comment by derreisende77** [comment]
Ja dafür ist #566 schon offen

**Comment by MuenchenSued** [comment]
Doppeltes Ticket
