### ISSUE TITLE
Infodatei zeigt "-1 bytes" als Größe bei leerer Filmlisten-Größe 

### ISSUE THREAD

**Issue by Little-Ben** [mediathekview/MediathekView#580]
In der Infodatei wird seit Version 13.7.0 bei leerer Größe in der Filmliste nun ein "-1 bytes" angezeigt.
Kam vermutlich durch die Änderungen zu Issue #510.

formatierte Filmliste:
"X" : [ "", "", "Crypto-Affäre, Tierschutz radikal, Tourismus Italien", "24.06.2020", "20:05", "00:42:30", "", "Die Schweiz hörte mit ...

gibt in Infodatei:
Größe:       -1 bytes

**Comment by Little-Ben** [comment]
besser wäre hier wieder ein Leerstring als Wert zu zeigen, also
Größe:       

oder meintwegen auch 
Größe:       0 bytes

aber "-1 bytes" ist halt nicht wirklich toll.

**Comment by derreisende77** [comment]
in einer der nächsten versionen wird die Angabe dann komplett entfernt wenn -1
