### ISSUE TITLE
Infodatei: "Größe [MB]" nun nur noch "Größe" und Einheit nun beim Wert

### ISSUE THREAD

**Issue by Little-Ben** [mediathekview/MediathekView#581]
Infodatei:
seit Version 13.7.0 wird FILM_GROESSE (MVInfoFile.kt) nun als "Größe" statt "Größe [MB]" bezeichnet. 
Dafür wird die Einheit (MB) nun an den Wert gehängt.

also jetzt:
Größe:       7 MB

statt vorher:
Größe [MB]:  7

Ungünstig für Programme welche im Nachgang die Infodatei parsen.
(Bin da gerade an einem kleinen Tool das die Inhalte der Infodatei verarbeitet)

Hier wäre es gut solche Datenformat-Änderungen im Changelog zu kommunizieren.
Kam vermutlich mit Änderung #510 dazu.

Wird da nun weiterhin immer MB als EInheit genutzt, oder kann das nun auch andere Einheiten haben - welche (GB/KB, weitere ?)

**Comment by derreisende77** [comment]
Nein, je nach Größe der bytes wird der Wert entweder KB/MB/GB/TB/PB sein. Das wird wie Du entdeckt hast in MVInfoFile durch eine Utilityfunktion erzeugt.
Die Änderung kam durch Aufräumarbeiten am code bei dem wir eigene redundante Funktionen durch vorhandene Standardbibliotheken ersetzt haben. Und da die Infodatei bisher kein spezifiziertes Datenformat ist sondern nur der Information der Nutzer dient die diese haben möchten wurde das nicht kommuniziert. Zukünftig wird es hier wohl aber auch eher weniger Änderungen mehr geben.

**Comment by Little-Ben** [comment]
ok, alles klar, danke. 
Da derzeit ja einige Dateien auf SQLite umgestellt werden: bleibt die Infodatei bestehen?
So wie ich Dich verstehe, soll sie ja als Information für den Nutzer dienen. Also geh ich mal davon aus, das sie bestehen bleibt.

BTW, danke für die ganze Arbeit - ist ein gutes Programm!

**Comment by derreisende77** [comment]
Ja sie bleibt in der Form bestehen. Es wird nur alles in Bezug auf History auf Datenbank umgestellt da dies u.a. Speicher spart und die Performance bei größeren Datenmengen verbessert. Die Infodatei würde als Datenbank keinen Sinn machen.
