### ISSUE TITLE
Updater settings backup

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MediathekView#588]
Add an option to the updater to create a backup of the settings folder .mediathek3

**Comment by Georg-J** [comment]
Bei einem Update oder einer Neuinstallation wäre es sinnvoll, die Auswahl anzubieten, die bisherigen Einstellungen beizubehalten oder zu verwerfen.

**Comment by derreisende77** [comment]
Da der Updater nicht auf allen Plattformen verwendet wird und es nicht trivial in der Umsetzung ist -> wont fix.
