### ISSUE TITLE
Konsolen-Nachricht

### ISSUE THREAD

**Issue by 2Andrew4** [mediathekview/MediathekView#593]
./Only_MediathekView.sh 
. Portable Mode: false
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
. HikariPool-1 - Starting...
. HikariPool-1 - Start completed.
. Programmstart: 16.02.2021 14:01:14
. maxMemory: 1073 MB
. Version: MediathekView 13.3.0
. Java:
. Vendor: Oracle Corporation
. VMname: OpenJDK 64-Bit Server VM
. Version: 11.0.2
. Runtimeversion: 11.0.2+9
. Programmpfad: /my/homepath/.local/share/medjava/
. Verzeichnis Einstellungen: /my/homepath/.mediathek3
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by mediathek.Main (file:/my/homepath/.local/share/medjava/MediathekView.jar) to field sun.awt.X11.XToolkit.awtAppClassName
WARNING: Please consider reporting this to the maintainers of mediathek.Main
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
. Konfig wurde gelesen!
. Liste Filme gelesen am: 16.02.2021, 14:01
.   erstellt am: 15.02.2021, 18:31
.   Anzahl Filme: 436540
. Die Filmliste ist 1169 Minuten alt
. MVHttpClient: Proxy not configured
. 
. Alte Liste erstellt am: 15.02.2021, 18:31
.   Anzahl Filme: 436540
.   Anzahl Neue: 1164
. Filmliste laden (Netzwerk)
. Filme in Downloads eintragen
. -------------------------------------------------------
. Einstellungen sichern
. Einstellungen wurden gesichert
. -------------------------------------------------------
. Daten Schreiben nach: /my/homepath/.mediathek3/mediathek.xml
. Config Schreiben nach: /my/homepath/.mediathek3/mediathek.xml startet
. Config Schreiben beendet
. MediaDB schreiben (0) Dateien :
.    --> Start Schreiben nach: /my/homepath/.mediathek3/mediadb.txt
.    --> geschrieben!
. Liste Filme gelesen am: 16.02.2021, 14:01
.   erstellt am: 16.02.2021, 12:32
.   Anzahl Filme: 436617
. Liste Kompl. gelesen am: 16.02.2021, 14:01
.   Liste Kompl erstellt am: 16.02.2021, 12:32
.   Anzahl Filme: 436617
. 
. Jetzige Liste erstellt am: 16.02.2021, 12:32
.   Anzahl Filme: 436617
.   Anzahl Neue:  1741
. 
. Filme schreiben (436617 Filme) :
.    --> Start Schreiben nach: /my/homepath/.mediathek3/filme.json
. Filme in Downloads eintragen
. Daten Schreiben nach: /my/homepath/.mediathek3/mediathek.xml
. Config Schreiben nach: /my/homepath/.mediathek3/mediathek.xml startet
. Config Schreiben beendet
.    --> geschrieben!
. Write duration: 2940 ms

**Comment by derreisende77** [comment]
Okay, and what is your issue? There is none visible in the text.

**Comment by 2Andrew4** [comment]
The warnings are not my problems!
These should do a better for you if you have an idea for.

**Comment by derreisende77** [comment]
This warnings are normal.

**Comment by 2Andrew4** [comment]
ok, no error, no critical,
 but an other question by me is - what means the usage "closed" at top from these thread?

**Comment by derreisende77** [comment]
there are open issues that are still an issue. a closed issue was either fixed, evaluated as not being an issue or otherwise not deemed necessary to stay open. just a management means
