### ISSUE TITLE
Anforderung - Suche nach Thema / Titel auf Google (oder anderem Suchanbieter)

### ISSUE THREAD

**Issue by Export33** [mediathekview/MediathekView#594]
# Anforderung

In vielen Fällen wäre es praktisch, wenn man per Kontextmenü nach `Thema` oder `Titel` auf Google (oder einem anderen Suchanbieter) suchen könnte, um weitere Filminformationen/Covereindrücke zu erhalten.

# Aktuelles Verhalten

Beschreibung der Windows-Version

Es ist nur über Umwege möglich, das Thema oder den Titel einens Films zu kopieren und per `Paste` im geöffneten Browser einzufügen (Umweg über Filminformation, zu viele Klicks benötigt).

Ein Kopieren eines einzelnen Wertes aus

* Filmliste
* Beschreibung

in die Zwischenablage ist nicht möglich. 

# Erwartetes Verhalten

Das Kontextmenü wird um die Einträge

* `Suche nach Titel` 
* `Suche nach Thema`

erweitert. 

Jeder Eintrag hat kann weiter aufgeklappt werden:

* `auf Google`
* `auf Youtube`
* `etc.`

Nach Auswahl wird der Browser geöffnet und mittels Suchstring auf dem entsprechenden Suchanbieter gesucht.

# Beachten
Der Suchstring muss für die Suche mit einem `URLEncoder` umgewandelt werden (Leerzeichen, Sonderzeichen etc.).

# Optional
Die im Kontextmenü angezeigten Suchanbieter können in den Einstellungen eingestellt werden. Per Checkbox können die gewünschten Suchanbieter ausgewählt werden.

# Optional 2
In den Einstellungen können eigene Suchanbieter (`Name`, `URL`) hinterlegt werden.

# Beispiel
Beispiel aus Erweiterung eines Browserplugins
![grafik](https://user-images.githubusercontent.com/25232960/108111226-b17a8700-7094-11eb-9bd7-5e6ed3310fdb.png)

# Mögliche Suchanbieter
```json
const searchProvider = [
  {
    name: "Google",
    url: "https://www.google.de/search?q="
  },
  {
    name: "Youtube",
    url: "https://www.youtube.com/results?search_query="
  },
  {
    name: "Amazon",
    url: "https://www.amazon.de/s?k="
  },
  {
    name: "Wikipedia",
    url: "https://de.wikipedia.org/wiki/"
  },
  {
    name: "Google Bilder",
    url: "https://www.google.com/search?q="
  },
  {
    name: "Startpage",
    url: "https://www.startpage.com/do/search?q="
  },
  {
    name: "DuckDuckGo",
    url: "https://duckduckgo.com/?q="
  },
  {
    name: "Bing",
    url: "https://www.bing.com/search?q="
  },
  {
    name: "TheTVDB",
    url: "https://thetvdb.com/search?query="
  }, 
  {
    name: "The Movie Database"
    url: "https://www.themoviedb.org/search?language=de-DE&query="
  },
  {
    name: "IMDB"
    url: "https://www.imdb.com/find?q="
  }
];
```

**Comment by derreisende77** [comment]
Hallo, ich habe das gewünschte Feature (aus meiner Sicht) implementiert:
![594](https://user-images.githubusercontent.com/8466092/108125954-7e8ebe00-70a9-11eb-9a9c-83dd2f59fb7d.png)

Ich habe nicht alle Anbieter übernommen da sie aus meiner Sicht nicht alle sinnvoll für die Suche nach Thema und Titel sind.
Es wird in der nächsten Version verfügbar sein, ab sofort auch im develop branch hier.

**Comment by DaDirnbocher** [comment]
Vielleicht kannst (zumindest beim Titel) imdb noch ergänzen, da gabs im Forum schon einmal einen Wunsch/Thread.

**Comment by derreisende77** [comment]
Ja, die habe ich übersehen :(

**Comment by Export33** [comment]
Du warst einfach zu schnell, die hab ich ca. 10 Minuten nach Erstellung nacheditiert :). Gut, dass du auch TVDB mit reingenommen hast, das ist zum Episodencheck doch hilfreich.

Danke für die sofortige Umsetzung, da hätte ich jetzt nicht mit gerechnet. Ich freu mich auf die nächste Version.

**Comment by derreisende77** [comment]
Puh, ich dachte schon es war gestern zu spät :D 
Die Anforderung war ja mehr als klar formuliert und hatte alle nötigen Daten mitgeliefert - und ich hatte ein wenig Zeit. Von daher war es ja mit überschaubarem Aufwand umsetzbar. 
Und wenn @alex1702 die nightly builds demnächst wieder hinbekommt solltest Du es schon vorher mal testen können.

**Comment by Export33** [comment]
Ich hatte heute Nachmittag schonmal geguckt und mich gewundert, dass die letzte Nightly Version schon was älter ist. Das erklärt es dann.
Ich werd die Tage nochmal reingucken und dann testen.

**Comment by Export33** [comment]
Hab gerade die Nightly getestet. Sieht gut aus, so hab ich mir das vorgestellt. Danke.

**Comment by toby63** [comment]
Nur als Anmerkung:
Für mich wäre am intuitivsten, wenn ich im Kasten "Beschreibung" einfach etwas markieren und kopieren könnte.
