### ISSUE TITLE
Abo: keine Untertitel

### ISSUE THREAD

**Issue by 2019-05-10** [mediathekview/MediathekView#595]
Obwohl die Sendung Untertitel enthält (im Download-Tab, Spalte UT auch so angezeigt), werden im Abo-Download keine Untertitel gespeichert.
![image](https://user-images.githubusercontent.com/50481865/108235872-949e8c00-7146-11eb-8970-f310348b38ff.png)

Wird die selbe Sendung aus dem Film-Tab erneut als Donwload angelegt, kann/muss der Download der Untertitelausgewählt werden und klappt dann auch.

- bei Anlage von Abos ist es überhaupt nicht möglich, Untertitel mit auszuwählen
- es scheint keine Einstellung (mehr) zu geben, um den Download von Untertitel überhaupt als Default zu setzen

**Comment by DaDirnbocher** [comment]
> * bei Anlage von Abos ist es überhaupt nicht möglich, Untertitel mit auszuwählen
> * es scheint keine Einstellung (mehr) zu geben, um den Download von Untertitel überhaupt als Default zu setzen

Im Speichern-Set: 

![grafik](https://user-images.githubusercontent.com/11771553/108244305-5bb6e500-714f-11eb-9b9f-0202baae2b44.png)

**Comment by 2019-05-10** [comment]
Ah, wenn man oben die unauffällige Checkbox "alle Einstellungen anzeigen" aktiviert.
Ist nach meinem Dafürhalten nicht wirklich eine erweiterte oder Experten-Option.

Und man muss trotzdem anschliessend MediathekVierw neu starten, damit die Einstellung wirkt.

**Comment by derreisende77** [comment]
Ja, das ist bei einigen Einstellungen durchaus notwendig. Weitergehende Hilfe erhälst Du im [Forum](https://forum.mediathekview.de)
