### ISSUE TITLE
Suggestion: Link to Homepage in Update Check Window

### ISSUE THREAD

**Issue by zackdvd** [mediathekview/MediathekView#596]
Hi,

please add a link to your Homepage or Download page in the "SW Update" Window.
So this makes it more easy to update. There is only the Close Button.
Suggestion: Offer Close button but also "Open Download Page" which open the URL in default browser. 

I'm using OSX, cannot say if this is only like this on OSX version or the others too.

Thank you!

**Comment by derreisende77** [comment]
Implemented in next release.
