### ISSUE TITLE
Set bearbeiten - Zieldateiname

### ISSUE THREAD

**Issue by 2019-05-10** [mediathekview/MediathekView#597]
Speicher-Set bearbeiten -> Zieldateiname
a) ich versuche am _Anfang_ des existierenden Patterns weitere Parameter einzufügen -- aber nach jedem KeyUp springt der Cursor an's Ende. Das ist nicht nur per se unverstädnlich, sondern noch viel mehr, weil die Parameter zwingend aus zwei Zeichen bestehen
b) die möglichen Parameter sind nicht ohne weiteres zu finden -- obwohl unterhalb des Bereiches viel leerer Platz ist oder ein Tooltip denkbar wäre
c) macht man das Hilfe-Fenster auf, in dem die Parameter aufgeführt sind, blockiert das die Eingabe -- dass ein modales Hilfe-Fenster überhaupt sinnvoll ist, bezweifele ich, hier jedenfalls ist es kontraproduktiv

**Comment by derreisende77** [comment]
Hilfe hierzu findest Du im [Forum](https://forum.mediathekview.de).

**Comment by 2019-05-10** [comment]
Welche Hilfe?
Ich habe in a) und c) je einen offensichtlichen Bug beschrieben.
In b) wird ein damit verbundener Verbesserungsvorschlag.

Für den un wahrscheinlichen Fall, dass das Forum (wo?) tatsächlich einschlägige Hilfe (wieso Hilfe?) biete, dann verlinbke das bitte konkret.
Ansonsten unterlasses es bitte,Tickets zu schliessen, die Du unübersehbar gar nicht gelesen hast!

**Comment by derreisende77** [comment]
Nimm mal die Spritze aus dem Arm. Ich habe deine Beiträge gelesen. 
Erstens solltest Du mal explizit angeben welches OS du verwendest Da a) auf meinem System funktioniert -> kein Bug bzw. nur auf einem bestimmten System.
b) ist deine persönliche Ansicht die viele existierende Nutzer nicht teilen bzw. die Informationen auch anderweitig gefunden haben.
c) -> kein Bug, es wurde genau so implementiert. Ich werde es auch ohne konkrete Verbesserungsäußerungen nicht angehen.

Nur weil DU einige Sachen als Bug ansiehst heißt das nicht dass dies andere auch so sehen.

Ich bin auch nicht deine kostenlose Suchtippse. 
Und ICH kann sehr wohl Tickets die es nicht wert sind offen gehalten zu werden schließen. Denn ICH schreibe hier den Code und nicht DU. Also nimm den dir zustehenden Platz in der Nahrungskette ein und schmolle irgendwoanders rum.

Und wenn Dir zukünftig etwas auffällt was fehelerhaft sein sollte kannst Du das gerne in einem vernünftigen Ton schreiben. Ansonsten werde ich das auch wieder schließen.
