### ISSUE TITLE
URL Parameter kollidieren mit Set-Option Download -> direkt speichern

### ISSUE THREAD

**Issue by SebiderSushi** [mediathekview/MediathekView#599]
In den Set-Einstellungen unter dem Reiter `Download` lässt sich im Abschnitt `direkt speichern` eine Reihe an Suffixen angeben, bei denen ein regulärer Download erfolgen soll. Enthält eine download url in der Filmliste jedoch URL Parameter, funktioniert dieser Mechanismus nicht mehr wie erwartet.

### Beispiel
URL `http://beispiel.de/film.mp4?x=5`
Optionen für `direkter download` sind Präfix `http` und Suffix `mp4`

### Erwartetes Verhalten
MediathekView ordnet die URL `http://beispiel.de/film.mp4?x=5` als reguläre `mp4`-Datei ein und führt einen Download aus.

### Beobachtetes verhalten
MediathekView erkennt nicht `mp4` als Suffix und greift auf Hilfsprogramme zurück, im standardfall VLC.

### Mögliche Lösung
Eine korrekte Lösung für dieses Problem könnte schwierig werden, da es möglicherweise auch URLs gibt, bei denen die Parameter dafür sorgen, dass keine Datei mehr zurückgegeben wird. Ein theoretisches Beispiel wäre etwas wie `http://beispiel.de/film.mp4?f=hls`, woraufhin der Server das zu `film.mp4` gehörende HLS-Manifest liefern könnte. Daher ist das aktuelle Verhalten womöglich letztendlich die stabilste Lösung.
In meinem Fall handelte es sich allerdings um regüläre mp4 Dateien bei denen ein Download durchaus erwünscht war.

**Comment by DaDirnbocher** [comment]
Du kannst - als Workaround - im Speichern-Sett das "mp4?x=5" als Endung aufnehmen, dann klappt das auch.

Üblicherweise werden solche URL Parameter vom MServer rausgefiltert und erscheinen erst gar nicht in der Filmliste. Dazu müsstest halt ein echtes auftretendes Beispiel nennen,, damit die Programmierer aufnehmen können.

**Comment by SebiderSushi** [comment]
Okay vielen Dank!
