### ISSUE TITLE
"Webseite-URL an JDownloader übergeben" (statt Video-URL)

### ISSUE THREAD

**Issue by styroll** [mediathekview/MediathekView#601]
Wenn man – wie [hier im Forum beschrieben](https://forum.mediathekview.de/post/25621) – direkt die URL der Webseite zur Sendung (also nicht die Video-URL) an JDownloader weitergeben könnte, dann hätte man folgende Vorteile:

- Zugriff auf Videos in anderen Sprachen und/oder Untertiteln (z.B. bei ARTE)
- weitere Auflösungen, die MV nicht anbietet
- aktuelle funktionierende DL-Möglichkeit für den Fall, wo die Video-URL gewechselt, aber der Crawler das nicht mitgekriegt hat (geschieht beim ZDF immer wieder) – für mich der wichtigste Punkt

Die aktuelle Implementation im Kontextmenü ist ja insofern nur beschränkt hilfreich, da sie nichts anders bewirkt, als wenn man den Kontextmenüeintrag darunter (URL kopieren) auswählen würde. Ein neuer Kontextmenüeintrag könnte wie folgt aussehen (der Screenshot unten zeigt die aktuelle Implementation):

1. Oberste Ebene: Den aktuellen Eintrag "Mit JDownloader herunterladen" stehen lassen und einen zusätzlichen wie "Webseite-URL an JD übergeben" darüber ergänzen. Diese Variante würde ich persönlich bevorzugen, da der Eintrag sofort zugänglich und das Kontextmenü vom Umfang her immer noch übersichtlich bleiben würde.
2. Verschachtelt: Man könnte in den bestehenden Eintrag "Mit JDownloader herunterladen" zuoberst zusätzlich einen Eintrag "Webseite-URL übergeben" ergänzen (also auf gleicher Ebene wie "in bester Qualität").
3. Ersatz: Den aktuellen Eintrag entfernen, d.h. mit dem Eintrag "Webseite-URL an JD übergeben" ersetzen. Ist vermutlich nicht so eine gute Idee, da die aktuelle Implementation von anderen Usern offenbar so mal gewünscht wurde (auch wenn man dasselbe schon immer mit "URL kopieren" erreichen konnte).

<img width="489" alt="Screenshot_ 2021-03-21 at 10 30 44" src="https://user-images.githubusercontent.com/24810728/111900172-49231a80-8a31-11eb-8ef0-8159a1597dc8.png">

Es wäre toll, wenn man diese Funktion implementieren könnte. Danke auf jeden Fall für die Prüfung meiner Idee.

Ansonsten: Gibt es eigentlich (bereits) einen Parameter für die Webseitenadresse (analog “%f” für die Video-URL)? Wenn ja, könnte man natürlich auch selbst ein eigenes Set basteln.

**Comment by MuenchenSued** [comment]
Ich unterstütze den Vorschlag, einen Parameter für die Webseitenadresse (z.B. %U) einzuführen, dann könnte ich mir ein Set für youtube-dl anlegen, das das Laden in einer gewünschten Auflösung über ein eigenes Set ermöglicht
z.B. youtube-dl -f best[height=720] ...

**Comment by derreisende77** [comment]
Sowohl @styroll Option Nr. 1 als auch @MuenchenSued Wunsch wurden umgesetzt. Der Parameter im Pset ist **%w**. Hilfetext wurde hierfür im Programm ergänzt.

**Comment by derreisende77** [comment]
Fehlende Dokumentation im CHANGELOG wurde ergänzt. Wäre cool wenn jemand das Feature testen und hier Feedback geben könnte.

**Comment by styroll** [comment]
> Wäre cool wenn jemand das Feature testen und hier Feedback geben könnte.

Besten Dank.

Hab zuerst den neuen **Kontextmenüeintrag** getestet. Funktioniert. Nachteile: Wie bekannt muss JD schon laufen, und auch dann muss noch das Hinzufügen eines Links durch ein externes Programm erlaubt werden. 

Dann hab ich ein eigenes Set für JD unter Verwendung des Parameters "%w" und der Option "externer Download-Manager" erstellt. Damit der Button für das Set funktioniert, musste ich MV frisch starten, während über das Kontextmenü und dann den Befehl "Film mit Set starten >" und der Auswahl des JD-Sets sofort funktionierte.

<img width="844" alt="MV_JD_Kontextmenu+Set" src="https://user-images.githubusercontent.com/24810728/113328639-dfeab380-931c-11eb-9fa0-3d6d75f39a07.png">

**Comment by styroll** [comment]
Eine Korrektur noch:
Es müsste "Web**seite**-URL an JDownloader übergeben" nicht "Website-URL an JDownloader übergeben" heissen, wie ich das in meinem OP auch korrekt geschrieben habe. 

Webseite = webpage (engl.), z.B. die Webseite zu einer Sendung
Website = website (engl.), z.B. die Website von "ard.de", welche Zugang zu zig Unterseiten (Webseiten von einzelne Sendungen) darstellt
