### ISSUE TITLE
(feature) appimage portable mode

### ISSUE THREAD

**Issue by ghost** [mediathekview/MediathekView#602]
here is a little suggestion regarding the linux appimage:

please enable the portability-function: https://docs.appimage.org/user-guide/portable-mode.html

as of now, portable-mode has no effect at all since all settings are still stored under ~/.mediathek3.

**Comment by derreisende77** [comment]
Thats true, but for this use-case we do have a portable mode for MediathekView as documented [here](https://mediathekview.de/anleitung/#starten-im-portablen-modus-mediathekview-portable).
I do not plan to support "native" appimage portable mode as we have an  option built-in and it will (unnecessarily) complicate the code which has to run on more platforms than linux.
