### ISSUE TITLE
Protokoll bei Duplikatsprüfung von Abos ignorieren

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MediathekView#603]
Durch die Änderung von https://github.com/mediathekview/MServer/issues/630 haben Abos viele neue Downloads erzeugt, obwohl diese schon einmal heruntergeladen wurden (siehe [Forum](https://forum.mediathekview.de/topic/4179/336-abos))

Ursache: durch die Umstellung von http auf https hat sich die Url geändert

Lösungsidee: Protokoll bei Duplikatsprüfung ignorieren.

**Comment by derreisende77** [comment]
Das betrifft noch den alten Listenanteil und würde bei jedem Programmstart zu doch erheblichen Verzögerungen durch zusätzliche String/regex Operationen führen. Von daher hoffe ich das eher das die crawler zeitnah auf https umgestellt sind und das Problem dann zukünftig nicht mehr auftritt.
