### ISSUE TITLE
ARTE doppelt

### ISSUE THREAD

**Issue by vitusson** [mediathekview/MediathekView#605]
Seit ungefähr Freitag erscheinen alle ARTE Inhalte doppelt noch einmal unter ARD, aller mit dem Thema "ARTE", was die ARD Liste IMHO unnötig aufbläht.
Mir ist klar dass ich das via Blacklist rausfiltern kann, aber ist das so beabsichtigt oder Bug im Crawler?

**Comment by codingPF** [comment]
Die ARD hat ARTE in ihrer Mediathek aufgenommen. Damit werden dann die Sendungen in der ARTE Mediathek und in der ARD Mediathek gefunden. Danke für den Hinweis...

**Comment by MuenchenSued** [comment]
Wobei die Übersichtlichkeit durch Diversifizierung bei ARTE höher ist als bei ARD unter einem gemeinsamen Thema. Und die Aussage "alle ARTE Inhalte sind doppelt" stimmt nicht, denn ARD listet nur 113 ARTE Sendungen gegenüber 13766 Sendungen bei ARTE.de.
Natürlich gehört dieser Issue überhaupt nicht hierher sondern zum Crawler https://github.com/mediathekview/MServer/issues, denn MediathekView zeigt nur das an, was der Crawler liefert.

**Comment by derreisende77** [comment]
Problematik ist der Server-Fraktion bekannt, daher wird das issue hier erst einmal dicht gemacht.
