### ISSUE TITLE
error: MediathekView-latest-linux.rpm: invalid signature tag Archivesize (1046)

### ISSUE THREAD

**Issue by neingeist** [mediathekview/MediathekView#607]
Ich habe Schwierigkeiten mit dem RPM zur Version 13.7.1:
~~~
 % sudo rpm -i MediathekView-latest-linux.rpm 
error: MediathekView-latest-linux.rpm: invalid signature tag Archivesize (1046)
error: MediathekView-latest-linux.rpm cannot be installed
~~~

**Comment by neingeist** [comment]
Falls Install4J verwendet wird, ist das hier vielleicht relevant: https://github.com/openaudible/openaudible/issues/603

**Comment by derreisende77** [comment]
@Nicklas2751 kannst Du dir das bitte ansehen?

**Comment by neingeist** [comment]
Scheint ein Problem von `rpm` zu sein: https://github.com/rpm-software-management/rpm/issues/1635

**Comment by neingeist** [comment]
Ich mach das Issue deswegen wieder zu, bitte wieder öffnen, falls das so nicht gewünscht ist :)

**Comment by neingeist** [comment]
Mindestens das letzte RPM lässt sich wieder installieren. 🍾
