### ISSUE TITLE
RPMs werden nicht mehr akzeptiert

### ISSUE THREAD

**Issue by SchwarzerA** [mediathekview/MediathekView#609]
Seit einiger Zeit gibt es Fehlermeldungen bei den RPMs von MediathekView (und Fakturama2):

   error: ….rpm: invalid signature tag Archivesize (1046)
   error: ….rpm: not an rpm package (or package manifest)

einerlei, ob mit zypper oder rpm direkt zugegriffen wird. Das gleiche Verhalten wird im Netz auch für Fedora und weitere Pakte beschrieben.

Die RPMs sind zwar installiert, können aber nicht aktualisiert oder erneut installiert wqerden. Auch die Aufnahme in ein eigenes Repository funktioniert nicht mehr.

**Comment by jnk0** [comment]
Das kann ich so bestätigen, ich habe die RPMs für 13.7.0 und 13.7.1 getestet.

Es sieht danach aus, als wärt ihr hier von einem Bug in install4j betroffen, das die aktuelle Version von rpm betrifft. In Version 9.0.2 von install4j sollte dieser Bug laut [Changelog](https://www.ej-technologies.com/download/install4j/changelog.html) behoben sein: "Fixed incompatibility with RPM 4.16.1.3".

**Comment by derreisende77** [comment]
13.8 wird mit install4j 9.0.2 oder später gebaut werden.
