### ISSUE TITLE
Updater (install4j) zeigt unter Windows nächste statt aktuelle Version an

### ISSUE THREAD

**Issue by styroll** [mediathekview/MediathekView#618]
Im Zusammenhang mit [dieser Issue](https://github.com/mediathekview/MediathekView/issues/615), ist mir Folgendes beim Starten von MV 13.7.0 aufgefallen:

<img width="376" alt="MV_Update-Fenster_Win" src="https://user-images.githubusercontent.com/24810728/132093748-dc015b32-b410-403f-96fe-aad97fcefffc.png">

Der Updater zeigt also die nächste Version 13.7.1 statt die aktuelle Version (13.8.0) an. Und es wird auch (konsequenterweise) die Version 13.7.1 runtergeladen.

Sinnvoll wäre es, wenn die aktuellste Version angezeigt (und heruntergeladen) würde. Falls das mit 13.7.1 oder 13.8.0 schon korrigiert wurde (in den [Changelogs](https://mediathekview.de/changelog/13-7-1/) habe ich keinen derartigen Eintrag gefunden), wäre diese Issue keine mehr…

**Comment by alex1702** [comment]
Ich kann mir ein Grund vorstellen eventuell, werde ich mal nachher gucken.

**Comment by alex1702** [comment]
Kannst du das noch mal testen bitte?

**Comment by styroll** [comment]
>Kannst du das noch mal testen bitte?

Hab nochmals 13.7.0 installiert. Jetzt kommt der Hinweis auf die aktuelle Version, welche auch gleich heruntergeladen werden kann. Dein Arbeit scheint also Früchte getragen zu haben. Danke.
