### ISSUE TITLE
Filterung von ZDF-tivi funktioniert nur nach Neustart

### ISSUE THREAD

**Issue by MuenchenSued** [mediathekview/MediathekView#626]
Wenn ich MediathekView 13.8.0 bzw. 13.8.1 starte, kann ich mit dem Filter "ZDF-tivi" die Liste filtern. Nach einem Klick auf das Wolkensymbol (Filmliste manuell laden) funktioniert der Filter nicht mehr. Alle anderen Senderknöpfe funktionieren weiterhin, nur der letzte wird durch das Laden einer Filmliste (auch, wenn keine neue Filmliste existiert) nicht mehr beachtet.
https://forum.mediathekview.de/topic/4449/zdf-tivi-l%C3%A4sst-sich-nicht-immer-filter

![2021-11-07_15-33](https://user-images.githubusercontent.com/71550657/140649390-85f21437-22ed-48f7-9c1b-593d84170063.png)
n

**Comment by derreisende77** [comment]
Ich hab das bei mir auf dem mac genau einmal nachvollziehen können, danach trotz mehrmaligem Start leider nicht. Ich schau mir das die tage auf den anderen systemen an und versuche das zu fixen. Könnte aber echt dauern wenn das nur sporadisch auftritt

**Comment by MuenchenSued** [comment]
Bei mir klappt das immer sicher. Ich starte MV, klicke dann einmal auf das Wolkensymbol und danach ist der letzte Sender nicht mehr zu filtern. Kannst Du mir die Stelle im Code nennen, wo nach dem Laden der Filmliste die Filterlöschfunktion aufgerufen wird? Dann kann ich mal schauen, ob eine Variable für die Senderliste im Filterfenster verändert wird.

**Comment by MuenchenSued** [comment]
Ich habe noch einen zweiten Weg zur Reproduktion gefunden.

1. Einstellungen so ändern, dass alle Filme angezeigt werden (Blacklist und Filter aus)
2. MV neu starten
3. ZDF-tivi drücken -> nur ZDF-tivi wird angezeigt
4. ZDF-tivi deaktivieren: komplette Liste (bis hierher alles ok)
4. Zeitraum auf 1 (einen Tag) stellen -> ZDF-tivi verschwindet aus der Filterliste
5. Zeitraum auf unendlich stellen -> ZDF-tivi ist wieder in der Filterliste
6. ZDF-tivi drücken -> keine Filterwirkung mehr

Ob es nur ZDF-tivi betrifft oder immer den letzten Eintrag in der Sendeliste? Ein- und Ausschalten meiner Blacklist hat den gleichen Effekt, hierdurch werden bei mir drei Sender (ARTe.FR, SRF.Podcast und ORF) aus der Liste entfernt.

**Comment by derreisende77** [comment]
Ok nun kann ich es auch unter Windows nachvollziehen. Mal sehen was macOS dazu sagt. Der Fehler wird nach jetzigem Stand auch bei 13.8.1 dabei sein und danach gefixt werden es sei denn ich finde ihn in nächster Zeit.

**Comment by derreisende77** [comment]
@MuenchenSued Habe gerade einen Fix gepostet. Kannst Du bitte den nächsten nightly testen ob es nun funktioniert?

**Comment by MuenchenSued** [comment]
Der Fix funktioniert einwandfrei. Vielen Dank.
