### ISSUE TITLE
13.8.1 crashes on initializing and downloading Filmliste (Alle Filter anwenden)

### ISSUE THREAD

**Issue by ggaussling** [mediathekview/MediathekView#630]
Hello, after upgrading from 13.8.0 to 13.8.1 mediathekview crashes and disappears on  (Alle Filter anwenden). Microsoft Windows [Version 10.0.19043.1348]

**Comment by derreisende77** [comment]
Without further information please try to resolve the problem first [with the help of the forum](https://forum.mediathekview.de)

**Comment by ggaussling** [comment]
Okay. I didn't restart the Computer. Now it works.

**Comment by thomasmerz** [comment]
"Have you try to turn it off and on again?" 🤣
