### ISSUE TITLE
13.8.1 - Filter Einstellungen - Feld "Thema" wird ignoriert

### ISSUE THREAD

**Issue by FrankBKK** [mediathekview/MediathekView#631]
MV 13.8.1 Portable Win10 

Ich habe verschiedene Filter fuer unterschiedliche Themen erstellt. 

Leider wird das Feld 'Thema' beim Speichern ignoriert und fuer alle Filter nur das letzte eingegebene Thema verwendet, was die Filter absolut unbrauchbar macht.

**Comment by derreisende77** [comment]
duplicate of #551
