### ISSUE TITLE
Blacklist not changeable

### ISSUE THREAD

**Issue by manniclick** [mediathekview/MediathekView#634]
since updating to 13.8.1 I do not get access to the blacklist for update and no entrioes are listed but working.
Kind regards
Manfred

I use:
Gerätename	DESKTOP-1SPGI2O
Prozessor	Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz   3.40 GHz
Installierter RAM	8,00 GB
Geräte-ID	69F8944A-F510-4A67-8E6E-A4FB4ABCC532
Produkt-ID	00325-80005-02082-AAOEM
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor
Stift- und Toucheingabe	Für diese Anzeige ist keine Stift- oder Toucheingabe verfügbar.

Edition	Windows 10 Home
Version	21H1
Installiert am	‎18.‎08.‎2020
Betriebssystembuild	19043.1415
Leistung	Windows Feature Experience Pack 120.2212.3920.0
![2021-12-18 13_41_34-Blacklist](https://user-images.githubusercontent.com/36923799/146641515-e27a8b6c-58f9-4dcc-a43b-416dcbc3ed60.jpg)

**Comment by derreisende77** [comment]
click on "Sender-Thema-Titel" Tab?
