### ISSUE TITLE
Benachrichtigungen für Abos ohne automatischen Download

### ISSUE THREAD

**Issue by Joshix-1** [mediathekview/MediathekView#636]
Ich würde gerne von MediathekView über neue Videos in einem Abo benachrichtigt werden und diese dann nur wenn sie mich interessieren downloaden oder streamen.

**Comment by derreisende77** [comment]
Die stehen doch im Download-Tab als Eintrag und können dort manuell geladen, angesehen oder gelöscht werden (es sei denn Du hast Abos sofort downloaden in den Einstellungen aktiviert).
Oder welche Art der Benachrichtigung schwebt dir vor?

**Comment by Joshix-1** [comment]
> Die stehen doch im Download-Tab als Eintrag
Ah, dann fänd ich es cool, wenn es für die Abos einen eigenen Tab gäbe in dem die Videos automatisch nach dem Datum der Veröffentlichung sortiert sind.

> Oder welche Art der Benachrichtigung schwebt dir vor?
Wenn MediathekView im Hintergrund läuft sollte es in einem einstellbaren Intervall gucken, ob bei meinen Abos neue Videos sind und mir dann eine Benachrichtigung schicken. (Benachrichtigung zum Beispiel über notify-send auf Linux)

**Comment by derreisende77** [comment]
Für Fragen der Bedienung wende dich bitte an das [Forum](https://forum.mediathekview.de). Hier werden nur Fehler gemeldet. 
Wenn die Filmliste aktualisiert wird wird auch je nach Einstellung automatisch die Abo-Downloads aktualisiert.
Und Du kannst auch auf dem Download-Tab die Combobox umstellen.
