### ISSUE TITLE
Suchfeld funktioniert nicht (getippte Zeichen werden ignoriert)

### ISSUE THREAD

**Issue by MuenchenSued** [mediathekview/MediathekView#637]
MV 13.8.1
Bei der Eingabe des Textes "#:.*astronomie.* im Feld "Thema/Titel durchsuchen" werden einige Zeichen verschluckt und es steht "#:.*asomie." im Suchfeld. Das Problem ist vermutlich, dass sofort nach Eingabe einiger Zeichen mit der Filterung begonnen wird und das Eingabefeld während dieser Zeit nicht reagiert und zudem der Tastaturpuffer geleert wird. Gerade bei regulären Ausdrücken mache ich viele Pausen um die Eingabe zu kontrollieren und mir weitere Elemente zu überlegen. Eine vorschnelle Ausführung ist hier nicht sinnvoll und ich würde mir wünschen, dass ich zum Abschluss der Eingabe Return drücken muss.
https://forum.mediathekview.de/topic/2905/aktuelle-nightlies-feedback-bugs-etc/29#
https://forum.mediathekview.de/topic/4533/l%C3%A4sst-sich-die-suche-verz%C3%B6gern

**Comment by derreisende77** [comment]
Ich habe die Wartezeit verdoppelt. Sollte im nightly besser sein.

**Comment by sedimentation-fault** [comment]
Wenn man solche *Pseudo-Verbesserungen* einführt, dann mit einer Möglichkeit zur Abschaltung - Punkt A. Punkt B: Nur nach einer *eingehender* Testphase, nicht hastig und halb-fertig.

Punkt C: Weiter denken, als nur dem Zeitgeist hinterherhächeln. 

Punkt C ist sehr wichtig. Es ist nicht nur, dass Mediathekview *unbrauchbar* geworden ist durch diese Sch..ße - nein, es geht weiter: Da es wahrscheinlich für diese "Funktion" die Maus-und Tastatur viel zu schnell und viel zu unbedacht "pollen" muss, verschwindet die Maus in meiner VirtualBox nach einer Weile auf Nimmerwiedersehen. Ja, es gibt Leute, die MediathekView in einer virtuellen Umgebung ausführen und hin- und her schalten zwischen einem Linux (als Host) und einem Windows (als Gast) mit Mediathekview als Top Fenster - daran denken, das ist Punkt C.

Wenn nun irgendein anderes Programm als Top-Fenster zu sehen ist, dann kann ich hin und her schalten, wie ich will. Wenn MediathekView ein paar Tage das Top Fenster ist, ist es garantiert, dass ich die Maus im virtuellen Windows verliere und dann hilft nur noch neu booten (von VirtualBox).

Solche Probleme hatte ich früher NIE. Früher war alles besser.

Kinders, Kinders....

**Comment by derreisende77** [comment]
Solange clowns nicht lesen können und sich ins Sediment nicht zurückziehen lösche ich stumpf solche gequirlte Scheisse. Wer meint hier beleidigen zu können soll das auf einen Zettel schreiben und diesen direkt in den Mülleimer werfen.

**Comment by sedimentation-fault** [comment]
Clown bist Du selber, wenn Du Dich so leicht beleidigen lässt. Typisch deutsch, mal wieder...

"Es tut uns leid, dass Du Probleme mit der Software hattest. Wir versprechen, das nächste Mal vorsichtiger zu sein, es wird nicht wieder passieren" hätte so gut in der Seele getan, nach einem halben Dutzend solcher Aufhängen...Aber nein, man muss ja gleich löschen, statt sich der Diskussion zu stellen, das Problem zu identifizieren (und nicht nur "die Wartezeit verdoppeln" - was, wenn man sie bei manchen verdreifachen, oder vervierfachen muss? - was für pseudo-kluge, billige, Workarounds!)  und sich eingestehen, dass man...nun ja, *selber Scheiße gebaut hat*, weil man blind, gedankenlos, ja *hirnlos* einer blöden, idiotischen Mode willig seinen Tribut leisten wollte...

**Comment by derreisende77** [comment]
Und wieder gelöscht…
