### ISSUE TITLE
Optimierungen am Filter-Panel

### ISSUE THREAD

**Issue by MuenchenSued** [mediathekview/MediathekView#640]
Am Filter-Panel gibt es (neben der noch fehlenden manuellen Speicherfunktion) noch ein paar Unschönheiten:
1) Sender sollten nicht angezeigt werden, wenn sie in der Blacklist stehen (dynamisch, wenn Blacklist ein/aus geschaltet wird).
2) Selektierte Sender und Thema sollten nicht deaktiviert werden, wenn der Zeitraum verändert wird.
3) Selektierte Sender und Thema sollten mit der Mülltonne (Aktuellen Filter zurücksetzen) ebenfalls deaktiviert werden. Bisher klappt das nur, wenn der Zeitraum verändert wird und dadurch 2. angewendet wird.

Ich würde es zudem begrüßen, wenn die Blacklist mit in das FilterPanel integriert wird, damit sie in einem Filterprofil aktiv und im anderen inaktiv sein kann. Bei 13.0.6 konnte man das zumindest selektiv konfigurieren.

**Comment by derreisende77** [comment]
Zu 1:
- wird wieder zurück kommen wenn die Stabilitätsprobleme mit der CheckBoxList umschifft werden können. Bis dahin wird es bei der jetzigen Versionn bleiben (müssen).

Zu 2:
- Das lässt sich zumindest für die Themenauswahl nicht verhindern da diese nach Änderung des Zeitraums neu erstellt wird (nicht vorhandene Themen werden herausgefiltert).
- Für die Sender wäre es derzeit nicht nötig da sich deren Inhalt derzeit nicht ändert. Wenn 1. umgesetzt wird wäre es auch erforderlich.

Zu 3:
Ja steht auf der TODO, leider ist der entsprechende Patch zu instabil gewesen um ihn zu integrieren.

Die Blacklist (teilweise je nach Einstellung auch als Whitelist vergewaltigt) ist eine globale Einstellung. Um deinen Wunsch umzusetzen müsste das gesamte Konzept geändert werden -> nur noch Blacklist, keine Whitelist. Und Einbau in den Filterdialog.
Hast Du einen Vorschlag wie Du das im UI umsetzen würdest? Auf meinem 13" Laptop wird der Bildschirm schon jetzt mit dem Filterdialog eng und wenn nun auch noch ein dann notwendiges Tab dazukommt macht es die Sache nicht besser.

**Comment by MuenchenSued** [comment]
Etwas anderes ist mir noch aufgefallen.
Ich selektiere das Thema "Tatort" und bekomme diverse Sendungen von ARD, den Dritten und anderen angezeigt. Jetzt drücke ich auf "ARD", um die Suche zu verfeinern. Leider wird dabei das Thema gelöscht und alle Sendungen des ARDs angezeigt. Löschen sollte aber nur ein Druck auf die Mülltonne.

**Comment by derreisende77** [comment]
Das Löschen der Themen bei Änderung der Sender ist richtig und zielführend, da in der Themenauswahl nur diejenigen angezeigt werden, die auch in der Senderauswahl vorhanden sind. Dies dient der Reduktion de Auswahlmgl und daraus resultierender leerer Anzeigen ohne diese Filterung.

**Comment by MuenchenSued** [comment]
Ich krame dieses Ticket noch mal hervor, da mich das Setzen der Filter jedes Mal wieder nervt. Hier ein paar Beispiele:

1. Sender, Thema, Mindestlänge und Zeitraum sind gesetzt, die  Mülltonne löscht alles - wie gewünscht
2. Sender, Thema und Mindestlänge sind gesetzt, die Mülltonne löscht nicht Sender und Thema
3. Sender wird gesetzt: Thema wird gelöscht, selbst wenn das Thema noch in der neuen Liste enthalten ist
4. Zeitraum setzen: Thema und Sender werden gelöscht.

Es ist also gar nicht so einfach, die richtige Reihenfolge zu finden, um die Filter korrekt zu setzen.

Was wäre mit folgendem Vorschlag: Statt ein echtes Thema auszuwählen, trägt man nur einen Suchbegriff ein (z.B. Spielfilm, Tatort oder Krimi). Das würde eventuell auch das Speichern der Profile (vordefinierte Filter) erleichtern, damit nicht jede Änderung sofort gespeichert wird sondern nur nach einer manuellen Aktion, damit die Filter beim nächsten Programmstart oder Filterwechsel wieder exakt gleich aussehen und nicht den Zustand des letzten Suchens widerspiegeln. Die Mülltonne löscht alles, eine Veränderung in einem Bereich hat keine Auswirkungen auf einen anderen.

**Comment by derreisende77** [comment]
Der Mülleimer-Button löscht nun auch die Sender- und Themaeinstellung mit. 
Das Speichern der Einstellungen ist ein nicht-triviales Thema was noch viel Zeit kosten wird da derzeit alle Lösungsansätze nicht funktioniert haben. Ist nunmal so aber auch nicht vergessen.
Das Themafeld als Suchfeld würde nur funnktionieren wenn ich die Lucene-Suche standardmäßig immer indizieren lasse da diese hierfür benötigt werden würde. Aber auch das wäre eine nicht-triviale Erweiterung des kaputten Filtersystems.

Für den Anfang muss es erst mal so bleiben.

**Comment by j4reporting** [comment]
die Filter scheinen irgendwie nicht wie gewünscht zu funktionieren, oder ich verstehe etwas anderes darunter.

Beispiel: 
Filter 1   ( alles default  leer / nichts aktiviert )
Filter 2   (  Sender gesetzt / Thema gesetzt  /   Mindestlänge z.B 60Minuten )

wenn man nun in der Filmübersicht oder im Filterdialog zwischen den beiden Filtern hin und her wechselt, dann wird nur auf Mindestlänge neu gefiltert.  Sender und Thema verbleiben auf den Werten im Filter 2!

dann scheinen die Filter auch nicht richtig in den Einstellungen gespeichert zu werden.  Nach Neustart fehlen  Sender/Thema im Filter2.  
Auch das Schliessen des Filterdialogs  lässt die Sender / Thema einstellungen nicht überleben, je nachdem welcher Filter zuletzt geändert wurde, Diese Änderungen scheinen dann für alle Filter zu gelten. 

probiert mit der aktuellen portablen version 14,0.0.1   2023-08-15

**Comment by DaDirnbocher** [comment]
> dann scheinen die Filter auch nicht richtig in den Einstellungen gespeichert zu werden. Nach Neustart fehlen Sender/Thema im Filter2.

Lange bekannt, siehe https://github.com/mediathekview/MediathekView/issues/551
