### ISSUE TITLE
Einstellungen zu "Filmliste laden" ändern (Sender, Zeitraum): automatisches Laden einer kompletten Filmliste erzwingen

### ISSUE THREAD

**Issue by styroll** [mediathekview/MediathekView#647]
- **Fall 1**: Das Entfernen von Sendern und die Verkürzung des Zeitraums für das Laden der Filmliste zeigen nach Neustart von MV und Neuladen der Filmliste – wie erwartet – Wirkung.

- **Fall 2**: Im umgekehrten Fall, d.h. beim Wiederhinzufügen von Sendern und Verlängern des Zeitraums muss man die aktuelle Filmliste manuell löschen oder auf den nächsten Morgen warten (keine Difflisten mehr), um eine vollständige Fimliste zu erhalten. _Dies kann für User höchst irritierend sein, denn sie sehen nicht die von anderen Usern erwähnte Anzahl von Filmen in einer kompletten Filmliste (vgl. [dieser Beitrag](https://forum.mediathekview.de/post/29379) im Forum). Für Mac-User ist es zudem nicht so trivial, die Filmliste zu löschen bzw. zu finden (vgl. [dieser Beitrag](https://forum.mediathekview.de/post/29380) im Forum)._

Sinnvoll wäre es, wenn für den **Fall 2** direkt über ein Dialogfeld ein Neustart von MV **unter automatischem Neuladen der kompletten Filmliste** erzwungen (oder wenigstens ermöglicht) wird.

Falls man die Änderung zum Fall 2 umsetzt, könnte man Analoges auch für den **Fall 1** umsetzen (da auch dort ein Neustart notwendig ist). Ein automatisches Neuladen der kompletten Filmliste ist zwar in diesem Fall nicht nötig. Man könnte jedoch hier das automatische Laden einer Diff-Liste nach dem Neustart von MV implementieren, so dass ein sichtbares Beschneiden (Dateigrösse) der Filmliste erfolgt.

**Comment by Georg-J** [comment]
Auf keine Fall darf eine filme.json einfach gelöscht werden. Das Problem sollte durch ein Laden einer aktuellen, kompletten Filmliste-akt.xz gelöst werden, wobei die alte Filmliste auf Wunsch nur erweitert wird.

**Comment by styroll** [comment]
>@Georg-J sagte: Auf keine Fall darf eine filme.json einfach gelöscht werden. Das Problem sollte durch ein Laden einer aktuellen, kompletten Filmliste-akt.xz gelöst werden.

Danke für den Hinweis – dachte da nicht an die Leute, welche die Filmliste jeweils erweitren lassen. Hab die Formulierung entsprechend angepasst.

**Comment by DaDirnbocher** [comment]
> * **Fall 2**: Im umgekehrten Fall, d.h. beim Wiederhinzufügen von Sendern und Verlängern des Zeitraums muss man die aktuelle Filmliste manuell löschen oder auf den nächsten Morgen warten (keine Difflisten mehr), um eine vollständige Fimliste zu erhalten.

Muss man wirklich auf den nächsten Morgen warten? Reicht da nicht schon ein bisserl warten? Löst nicht ein MV-Start mit einer Liste die mehr als 3 Stunden alt ist, das Laden einer Kompelttliste aus? (Wenn das Laden auf Automatisch eingestellt ist). War zumindest bei mir eben so, als ich versucht habe, das nachzustellen.

**Comment by derreisende77** [comment]
ja, indem Moment wo das Programm erkennt das eine komplette Liste geladen werden muss wird auch aktualisiert. Das "Problem" besteht nur solange Diff-Listen aktualisiert werden.

**Comment by styroll** [comment]
>@derreisende77 sagte: indem Moment wo das Programm erkennt das eine komplette Liste geladen werden muss wird auch aktualisiert. 

Das Problem ist im beschriebenen Fall ja gerade, dass das Programm nicht erkennt, dass eine vollständige Liste geladen werden sollte und zwar sofort bzw. nach einem Neustart.

>@DaDirnbocher sagte: Muss man wirklich auf den nächsten Morgen warten?

Meine Formulierung bezog sich auf das (wohl übliche, aber von mir tatsächlich nicht beschriebene) Szenario, wo man die beschriebene Änderung vornimmt, MV neu startet und nichts passiert und erst am nächsten Tag – nach Starten des Rechners – dann endlich eine vollständige Liste geladen wird.
Wenn du zum Beispiel die Spracheinstellung deines Systems von Englisch auf Deutsch wechselst, möchtest du auch nicht "ein bisserl", d.h  3 Stunden warten, bis die Änderung endlich angekommen ist…

**Comment by MuenchenSued** [comment]
Wenn ich einen Sender hinzu füge und "Neu laden" drücke erscheint die Meldung "Es liegt keine neuere Liste vor".

**Comment by styroll** [comment]
Aus dem Changlog zu MV 14:
`Bei geänderter Senderauswahl wird nun eine vollständige Filmliste geladen, solange die Filmliste nicht erweitert wird.`

Hab die Änderung nun getestet. Eine vollständige Filmliste wird nach dem Neustart von MV geladen. Danke.

Noch eleganter bzw. hilfreicher wäre es, wenn der Benutzer sowohl beim Entfernen wie auch beim Hinzufügen von Sendern – mittels eines Dialogfensters – darauf aufmerksam gemacht würde, das Programm neu zu starten oder noch besser starten zu lassen, damit die Änderungen wirksam werden.

> @styroll sagte: Sinnvoll wäre es, wenn für den Fall 2 direkt über ein Dialogfeld ein Neustart von MV unter automatischem Neuladen der kompletten Filmliste erzwungen (oder wenigstens ermöglicht) wird.

**Comment by derreisende77** [comment]
@styroll Mache bitte für den dialog ein neues issue auf damit es nachgehalten wird.
