### ISSUE TITLE
cpu-last im leerlauf

### ISSUE THREAD

**Issue by ossilator** [mediathekview/MediathekView#649]
MV tut "nichts" und das fenster ist minimiert, dennoch frisst es ~10% cpu. das ist eindeutig zu viel (so ca. 100x), und deutet auf exzessives polling von was auch immer hin.

**Comment by ossilator** [comment]
nach dem upgrade auf 13.8.1 (in debian ist immer noch 13.2 gepackaged; cf. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=941480), bin ich jetzt bei ~2,5% - besser, aber immer noch viel zu viel.

**Comment by derreisende77** [comment]
Das Debian Packet wird von uns nicht verantwortet und wir bieten genug Alternativen dazu.
Die Leerlauflast wird sich in nächster Zeit nicht ändern da das Programm seinen Ursprung aus 2008 hat und einige Dinge dementsprechend programmiert wurden. Im großen und ganzen ist das okay wenn man das Programm auch nicht den ganzen Tag laufen lässt.

**Comment by ossilator** [comment]
> da das Programm seinen Ursprung aus 2008 hat und einige Dinge dementsprechend programmiert wurden.

was ist das denn für ein argument? ereignisgesteuerte programmierung gab's auch schon vorher.

> Im großen und ganzen ist das okay wenn man das Programm auch nicht den ganzen Tag laufen lässt.

ist aber ganz nett, wenn man das "ungestraft" machen _kann_.
die startup-zeit ist bei der aktuellen version allerdings nicht so grausam wie bei der alten; insofern besteht jetzt auch nicht mehr sonderlich viel motivation es tatsächlich zu tun.
