### ISSUE TITLE
mediathekview manjaro arm? 

### ISSUE THREAD

**Issue by huggymann** [mediathekview/MediathekView#650]
Hallo, 

ich habe ein pinebook pro mit ARM architektur und Manjaro installiert. Ich kann Mediathekview aus dem App Store installieren, allerdings startet es nicht. 

Kann mir jemand weiter helfen? 

Liebe Grüße
Matthias

**Comment by derreisende77** [comment]
Ich weiß nicht wer das Programm dort pflegt, aber wir bieten grundsätzlich für Linux bisher nur Intel Varianten an. Davon abgesehen gibt es für Raspberry Pi auf unserer Download-Seite experimentelle Versionen für ARM 32 bit.
Alternativ bleibt die Installation eines JDK mit integriertem JavaFX und anschließender Selbstkompilierung um das Programm ggf. verfügbar zu machen.
Da ich Deine Umgebung nicht habe werde ich da nicht sehr hilfreich sein. Aber es sollte grundsätzlich lauffähig sein, vgl. hierzu den [Forum-Fred](https://forum.mediathekview.de/topic/4596/raspberry-mit-13-8-1/15)
