### ISSUE TITLE
MediathekView 13.8.0 on Mac OS 10.11.6 - Strange Fonts in Welcom Screen

### ISSUE THREAD

**Issue by francwalter** [mediathekview/MediathekView#651]
Hello
the last working version for my old MacBook with OS 10.11.6 is MediathekView 13.8.0
13.8.1 crashes on start so I cannot use it.
Since 13.7.1 I see a strange Welcome Screen Font:

![grafik](https://user-images.githubusercontent.com/927269/151859934-dd87eabf-697e-4449-85e1-c59cd1fd7120.png)

I don't know if this is an issue for my old Mac, if so, then better ignore it, as 10.11.6 is commonly unsupported now (never mind).
But maybe it is something real.

Thanks.
frank

**Comment by derreisende77** [comment]
I have seen this a few times on 10.11. Looks ugly but should be harmless. 
and as you said 10.11 is unsupported so there is no way to get this fixed.
