### ISSUE TITLE
Feature Request: Verspätete Untertitel zuerst speichern/separat speichern

### ISSUE THREAD

**Issue by 2019-05-10** [mediathekview/MediathekView#653]
Es kommt relativ häufig vor, dass zuerst das Video in der Mediathek erscheint und erst mit Verzögerung auch die Untertitel.
Da es viele Videos gibt, für die nie Untertitel bereitgestellt werden, speichere ich auch Videos ohne Untertitel.
Wenn nun die Untertitel doch später verfügbar sind, wird bei erneutem Herunterladen zuerst versucht, das Video zu speichern, das es ja schon gibt.
Um nun die passenden Untertitel dazu zu speichern, muss ich das Video überschreiben (==erneut herunterladen), bevor die tatsächlich neuen Untertitel gespeichert werden.

Es wäre gut, wenn 
- entweder die Untertitel vor dem Video gespeichert würden (dann könnte ich bei der "Video existiert schon"- Warnung einfach abbrechen)
- oder die Untertitel nachträglich einzeln zum bereits vorhandenen Video heruntergeladen werden könnten

**Comment by DaDirnbocher** [comment]
Siehe https://github.com/mediathekview/MediathekView/issues/450
