### ISSUE TITLE
Verbesserungsvorschlag: Dateinamenerzeugung nach Muster

### ISSUE THREAD

**Issue by muetzekoeln** [mediathekview/MediathekView#654]
Ich lade mit Mediathekview häufiger Dateien herunter um sie auf meiner Enigma2-Box zu speichern. Ich würde die Dateinamen dabei gerne so wählen, wie die Box sie erwartet: Datum Uhrzeit Sender Titel. Andere benötigen sicher eine andere Syntax.

Es wäre toll man könnte in den Einstellungen bei Mediathekview über Platzhalter flexibel den den Dateinamen zusammenbauen, z.B.
"%date %time %channel %title".

**Comment by vitusson** [comment]
Das kann man schon seit gefühlt schon immer. 
Einstellung/Set bearbeiten/ dort im Downloadset Speicherziel/Zieldateiname und dann mal auf den Hilfe-Button gehen
