### ISSUE TITLE
Regex search is intransparent: need a matches found part within "Abo anlegen" or "Abo ändern"

### ISSUE THREAD

**Issue by tps800** [mediathekview/MediathekView#656]
The ability to define regex searches for Abos is great, but it is most times difficult to make sure the regex matches what you want it to match. Would be nice to have an element within "Abo anlegen", "Abo ändern" showing what is matched while entering search terms.
At now it is a lot of "shooting the moon" defining a regex. You'll not see what it will match – you can just hope it is what you want.

**Comment by derreisende77** [comment]
There are tons of free websites which will help you defining regex rules for certain text which you can use in a following step in MV. Currently I do not plan to integrate any help with creating regex matches.
