### ISSUE TITLE
"Zusätzliche Filmdaten laden" after reboot activated

### ISSUE THREAD

**Issue by Streifi89** [mediathekview/MediathekView#657]
Hi, 

i have a linux virtual machine. If it starts up, MediathekView (13.8.1) is in autostart (graphical) to download newest abonnements. every day the virtual machine restarts for cleanup.

I dont need "Zusätzliche Filmdaten laden" - so i deactivated

- Trailer/Teaser/Vorschau
- Hörfassungen
- Gebärdensprache
- Livestreams

these options, save and restart application. 

Unfortunately, sometimes this 4 options will be activated automatically (dont know why) and i download too much versions. Any ideas to deactivate these options permanently?

<img width="927" alt="Bildschirmfoto 2022-04-16 um 10 53 15" src="https://user-images.githubusercontent.com/103278796/163668777-f6dedc17-6524-43bf-bf84-6427690bad4f.png">

**Comment by MuenchenSued** [comment]
These options are stored in ~/.mediathe3/setup.xml, when you close the program (the directory is hidden).
```
<filmlist>
....
  <load>
      <trailer>false</trailer>
      <audio_description>false</audio_description>
      <sign_language>false</sign_language>
      <livestreams>false</livestreams>
  </load>
</filmlist>

```
Please check the contents. It might get corrupted, if you shutdown the VM without leaving MV before. You can try to make this file read-only, once you have all adjusted. I use it also read-only, since I don't want my filters to be changed every time.

**Comment by Streifi89** [comment]
> These options are stored in ~/.mediathek3/setings.xml, when you close the program (the directory is hidden).
> 
> ```
> <filmlist>
> ....
>   <load>
>       <trailer>false</trailer>
>       <audio_description>false</audio_description>
>       <sign_language>false</sign_language>
>       <livestreams>false</livestreams>
>   </load>
> </filmlist>
> ```
> 
> Please check the contents. It might get corrupted, if you shutdown the VM without leaving MV before. You can try to make this file read-only, once you have all adjusted. I use it also read-only, since I don't want my filters to be changed every time.

Thats a good idea - but i dont have the setup.xml - the given options are stored in settings.xml ;-) made it not writable know - looking forward if it has any problems in the future. Thanks for that hint!

**Comment by derreisende77** [comment]
You are **not** supposed to write protect any of the config files as the application regularly writes data to them. If they change “automagically” then you have another problem with your setup. 
The forum may be a better information area as there are people who are you an almost same setup for MV.
