### ISSUE TITLE
VirusTotal shows Log4J Vulnerability for latest Windows Version

### ISSUE THREAD

**Issue by supaeasy** [mediathekview/MediathekView#659]
<img width="974" alt="image" src="https://user-images.githubusercontent.com/59504964/167231077-944677b0-7957-43b3-a595-af1e2ddb8b89.png">

**Comment by derreisende77** [comment]
Wird in 13.9 behoben sein. Die noch ungepatchte Sicherheitslücke an sich hat für MV in 13.8.1 aber keine Auswirkung.

**Comment by bulvara** [comment]
@supaeasy Das Programm läuft lokal, also völlig uninteressant!
