### ISSUE TITLE
Wrong subtitle URLs

### ISSUE THREAD

**Issue by Dobatymo** [mediathekview/MediathekView#661]
Recently I noticed the some of the subtitle URLs are not correct (lead to 404 errors)

For example, for `heute-show 2022-05-13` there are these urls
<https://utstreaming.zdf.de/mtt/zdf/22/05/220513_sendung454ltw_hsh/4/heute_show_130522.xml>
<https://utstreaming.zdf.de/mtt/zdf/22/05/220513_sendung454ltw_hsh/3/heute_show_130522.xml>

both are not working
Looking at the resources in the browser, I can find
<https://utstreaming.zdf.de/mtt/zdf/22/05/220513_sendung454ltw_hsh/5/abd_heute_show_130522.xml>
instead.

**Comment by derreisende77** [comment]
This would be an issue for the MServer which is producing the URLs. However maybe @pidoubleyou can have look at the problem.
