### ISSUE TITLE
Abspiel-Set: Variable für Untertitel

### ISSUE THREAD

**Issue by 2019-05-10** [mediathekview/MediathekView#664]
Allem Anschein nach gibt es keine Variable, um vlc/ffmpeg/avconv auch die Untertitel anzeigen zu lassen.
Statt dessen muss ich den Film erst samt Untertitel herunterladen, bevor er mit Untertiteln angeschaut werden kann.

**Comment by DaDirnbocher** [comment]
> Allem Anschein nach gibt es keine Variable, um vlc/ffmpeg/avconv auch die Untertitel anzeigen zu lassen.

Man kann zwar vlc via --sub-file ein Untertitelfile auf der comandline mitgeben, aber kann vlc das auch anzeigen, wenn das Untertitelfile eine http(s)-Url ist? Meines Wissens wird die auch dann im lokalen Filesystem gesucht, was zu einer Fehlermeldung führt.

Soll heissen: Ein Schalter in MV ist erst dann sinnvoll, wenn klar ist, ob vlc das dann auch richtig verarbeiten kann. Kurzum: Nimm einen Film Deiner Wahl mit Untertiteln, liefere einen funktionierenden Commandlineaufruf für vlc mit 2 urls (1x Film, 1x Untertitel) und dann glaub ich, wirds mit dem Schalter (vermutlich) auch was werden.

**Comment by styroll** [comment]
> @2019-05-10 sagte: Allem Anschein nach gibt es keine Variable, um vlc/ffmpeg/avconv auch die Untertitel anzeigen zu lassen.

ffmpeg bzw. avconv sind nicht für das Abspielen zuständig. Wenn schon müsstest du dir ein Abspiel-Set mit ffplay bauen. Dabei gibt es 2 Probleme: 

- Wie heisst der Parameter für die URL der Untertiteldatei? Mir ist dieser nicht bekannt; ich weiss nur, wie ich die entsprechende Adresse aus dem "Download editieren"-Fenster kopieren kann.
- Selbst wenn du eine Untertitel-URL hast, scheiterte ffplay bei meinen bisherigen Tests.

> @2019-05-10 sagte: Statt dessen muss ich den Film erst samt Untertitel herunterladen, bevor er mit Untertiteln angeschaut werden kann.

Hm, du kannst mit einem Klick auf die Webseite zur Sendung wechseln, mit einem zweiten Klick die Untertitel einblenden. Das scheint mir wesentlich effizienter.

**Comment by 2019-05-10** [comment]
Ich würde `mpv` benutzen, da gibt es `--sub-file`.
Allerdings scheitere ich beim Ausprobieren schon daran, dass ich keinen Film finde, der Untertitel im passenden Format anbietet.
Die ÖR verwenden offenbar alle TTML und das Konversionsproblem hast Du ja schon erwähnt.

Ich bin aber gerade nicht sicher, ob das hier nicht in die falsche Richtung geht!
Mir geht es um eine Pfadvariable/Platzhalter analog zu 
`%f`
im Set -> Schalter `%f --play-and-exit` für VLC.
Das `%f` wird doch wohl von MediathekView definiert und mit der Film-URL belegt, korrekt?
Analog wünsche ich mir ein
`%u`
das die Untertitel-URL enthält.
Dann wäre in einem hypothetischen(!) Set für mpv der Schalter
`%f --sub-file=%u`
denkbar, wobei eben Film- und Untertitel-URL übergeben würden.

> > @2019-05-10 sagte: Statt dessen muss ich den Film erst samt Untertitel herunterladen, bevor er mit Untertiteln angeschaut werden kann.
> 
> Hm, du kannst mit einem Klick auf die Webseite zur Sendung wechseln, mit einem zweiten Klick die Untertitel einblenden. Das scheint mir wesentlich effizienter.
Ich weiss nicht, ob ich Dich richtig versteheh -- wo klicken und auf welche Webseite?

Sofern Du die Seite in der jeweiligen Mediathek meinst ...
In den Mediatheken der ÖR kommt es regelmässig zu Problemen:
- Untertitel sind asynchron und lassen sich im Webinterface nicht synchronisieren (was mit `mpv` wunderbar geht)
- es sind immer wieder Sendungen "nicht verfügbar", die MediathekView problemlos auflistet und runterlädt

**Comment by styroll** [comment]
> @2019-05-10 sagte: Mir geht es um eine Pfadvariable/Platzhalter analog zu
> `%f`
> im Set -> Schalter `%f --play-and-exit` für VLC.
> Das `%f` wird doch wohl von MediathekView definiert und mit der Film-URL belegt, korrekt?
> Analog wünsche ich mir ein
> `%u`

Ja, der Parameter "%f" stammt von MV, aber was nützt dir ein Untertitel-Parameter (zu dem müsste sich der @derreisende77 äussern), wenn der in der Praxis infolge inkompatibler Untertitel gar nie erfolgreich zum Einsatz kommen kann? Wie schon von @DaDirnbocher für VLC erwähnt, müsstest du analog zuerst mal zeigen, dass es mit mpv alleine auf der Kommandozeile klappt…

> @2019-05-10 sagte: Ich weiss nicht, ob ich Dich richtig versteheh -- wo klicken und auf welche Webseite?

<img width="1157" alt="Screenshot_ 2022-07-14 at 19 16 43" src="https://user-images.githubusercontent.com/24810728/179044068-a4cc32e7-d0d5-45c3-9711-9b1d2112db83.png">

> @2019-05-10 sagte: In den Mediatheken der ÖR kommt es regelmässig zu Problemen:
> 
>     * Untertitel sind asynchron und lassen sich im Webinterface nicht synchronisieren (was mit `mpv` wunderbar geht)

Okay, erstaunlich, ich hab da keine breite Erfahrungen damit, aber ich benutze auch wegen der effizienten und konfigurierbaren Steuerung über die Tastatur mpv (v.a. bei AV-Sync-Issues unersetzlich).

**Comment by alex1702** [comment]
Schreib dir ein Skript, welches alles lokal downloaded und konvertiert (falls möglich) und dann abspielt :P
Das kannst du dann  bei MV hinterlegen und deine Wünsche abbilden.

**Comment by vitusson** [comment]
*plonk*

**Comment by derreisende77** [comment]
Da VLC unsere primär unterstützte Variante ist sehe ich b.a.w. keine Notwendigkeit das gewünschte Feature zu implementieren. Zumal sich der vorgestellte Workflow mir immer noch nicht in allem Umfang erschließt.

**Comment by derreisende77** [comment]
Falsch geclosed...
