### ISSUE TITLE
Fenster "Download editieren" merkt sich Position und Größe nicht

### ISSUE THREAD

**Issue by macpingel** [mediathekview/MediathekView#666]
Wenn man im Reiter "Downloads" einen der ausgewählten Filme anklickt, öffnet sich das Fenster "Download editieren". Das brauche ich in letzter Zeit häufig, um die 720p URL einzugeben. 
Das Fenster öffnet sich immer links oben auf dem Bildschirm und ist recht klein (ca. 745x693). Wenn ich es verschiebe und die Größe ändere und es wieder schliesse, ist es beim nächsten Aufruf trotzdem wieder links oben und klein. Dieses Verhalten war schon in 13.7.1 und 13.8.1 so.
Schön wäre es, wenn sich das Fenster zumindest während einer Sitzung seine Größe und Position merken könnte. Oder sogar über Neustarts des Programmes hinweg.

macOS Version 13.9.1, aber auch 13.7.1 und 13.8.1

Danke für Mediathekview.

**Comment by derreisende77** [comment]
in MV 14 wird es enthalten sein.
