### ISSUE TITLE
UI inconsistencies: Indicator checkboxes redundant, confusing UT information, not well integrated into color scheme

### ISSUE THREAD

**Issue by ushuc** [mediathekview/MediathekView#668]
New UI refresh in version 13.9(.1) is great and modern lookin, I love it!

But it has some issues. See mockup 1 where I marked all the issues.

**Red circles 2**
The background color of the rows does not show behind the checkboxes. Neither the status indicator color (in this case the green color for "completed download") nor the grey color for the alternating rows.

**Red circles 3**
The colums "UT" and "Untertitel" mean the same thing "Subtitles", right? So why are both of them there? One would be enough. At the same time for the same broadcast episode the column "UT" has an unchecked checkbox, but the colum "Untertitel" has a checked checkbox. This is confusing, which information is the right one? Does this broadcast episode have subs or not?

![mv](https://user-images.githubusercontent.com/109863013/180613231-b784073c-1777-4de0-b249-3a3bde552e59.png)

**Comment by derreisende77** [comment]
2: Most of the checkboxes will be gone/are already gone with MV 14 and replaced by icons. Those remaining currently will remain the indicated lack of background color as they are the default values for the table. There are planned changes for future versions to rework those things therefore I am going to close this issue as I am working on it.
3: No. "UT" column means that the sender provides a subtitle available for download. The "Untertitel" column just indicates whether for this download the subtitle download is requested or not. If it is not available but checked it won't be loaded. I agree that the naming is somewhat confusing but they are planned to disappear in the future. Maybe i will rename some of them in a future update.
