### ISSUE TITLE
[Feature enhancement idea] Individual download quality setting for every "Abo" / subscription, not just for "Programmsets"

### ISSUE THREAD

**Issue by ushuc** [mediathekview/MediathekView#669]
In MV it is possible to define a standard download quality (low, medium, high) in the settings for every "Programmset" individually.

It would be even more practical if the download quality setting could also be defined individually for every "Abo".

In the "Abo" edit dialog (see screenshot) there could be such a downlaod quality setting (low, medium, high), too. This would make setting a download quality for each individual "Abo" very very easy and fast. Because right now one hast so define a "Programmset" for each "Abo" and then connect them both. This is double the work.

![my](https://user-images.githubusercontent.com/109863013/180614152-3d137950-c2aa-4616-94a2-36df0051d531.png)

**Comment by DaDirnbocher** [comment]
You can define three programsets (high, medium, low) and you can choose the progamset in the abo.

**Comment by derreisende77** [comment]
@ushuc The use of program sets is even more practical in the future. By using dedicated PSets you could easily change only one PSet e.g. to download a even higher quality and it would be applied to all abos automagically. 
Therefore we will not append low/normal/high settings to each abos as there is no real benefit.
