### ISSUE TITLE
[Suggestion] Fehlende Skalierung fuer HiDPI Displays

### ISSUE THREAD

**Issue by ymybe** [mediathekview/MediathekView#67]
Auf hochauflösenden Displays mit kleiner Größe, ("QHD" auf 15" Displays zB.) ist die Darstellung des Programms (jedenfalls unter Windows 10...) nicht skaliert.

![screen-mediathekview](https://cloud.githubusercontent.com/assets/8144404/14065106/ab2a7bc0-f41c-11e5-9073-1e0ab42e1b2b.png)

**Comment by genodeftest** [comment]
Das ist ein Fehler in Java, nicht in MediathekView. Welche Java-Version hast du denn?

Auf die Schnelle hab ich nur https://bugs.openjdk.java.net/browse/JDK-8073320 gefunden, laut diesem bug report wird das Problem mit Java 9 behoben sein, was aber noch nicht veröffentlicht ist.

**Comment by genodeftest** [comment]
Wenn deine Java-Version nicht mindestens 8u101 ist, solltest du Java dringend aktualisieren, dann könnte das Problem behoben sein.

**Comment by maggu2810** [comment]
Ich habe dasselbe Problem unter Linux. Es wird weder unter einem aktuellen Java 8, noch mit dem 9er Snapshot skaliert.

**Comment by genodeftest** [comment]
Hast du Java 9 b130 oder später? Wenn ja, dann solltest du das mit einem einfachen Java-Programm testen und am besten im Upstream-Bug anmerken.

**Comment by genodeftest** [comment]
Unter Linux sollte der Bug in Version 9 laut https://bugs.openjdk.java.net/browse/JDK-8137571 auch schon gefixt sein. Bist du dir sicher, dass du Java 9 verwendet hast und einen aktuellen Snapshot benutzt?

JavaFX: https://bugs.openjdk.java.net/browse/JDK-8101788

**Comment by maggu2810** [comment]
Da ich direkt die Java Executable (`~/bin/pkgs/jdk-9/bin/java`) und das jar genommen habe (also nicht das shell Skript) bin ich mir ziemlich sicher, dass es die Version 9 war.
Ich hatte sie vorher runtergeladen, also daher auch die aktuelle.

Ich verwende Gnome unter Wayland und so wird für MediathekView dann auch XWayland benutzt...
Vielleicht liegt es an einer Kombination davon.

Die Eclipse IDE selber (die ja aber SWT verwendet) wird richtig skaliert.

Soll ich es mal unter Gnome unter X direkt, anstatt über Wayland + XWayland probieren?

**Comment by maggu2810** [comment]
Habe es soeben unter "Gnome on XORG" getestet.

```text
$ ~/bin/pkgs/jdk-9/bin/java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+149)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+149, mixed mode)
```

```text
$ ~/bin/pkgs/jdk-9/bin/java -jar MediathekView.jar
```

Keine Skalierung, alles ziemlich klein.

**Comment by maggu2810** [comment]
If I set the GDK scaling, it seems to work (tested unter Xorg -- will test it under Wayland and edit this comment after that):
`GDK_SCALE=2 ~/bin/pkgs/jdk-9/bin/java -jar MediathekView.jar`

**Comment by genodeftest** [comment]
Hm, das klingt seltsam. Was hast du denn für ein Linux?

**Comment by maggu2810** [comment]
Gentoo Linux, jedoch sehe ich hier keine Abhängigkeit zu einer Distribution.

* http://openjdk.java.net/jeps/263
* https://developer.gnome.org/gtk3/stable/gtk-x11.html

Das kann ja an einem liegen wie GTK Version, Version der X libraries usw.
Ich selbst hab hier noch keinen tiefen Einblick gewonnen, wo hier anzusetzen ist, aber da ich nun weiß, wie ich es starten muss, reicht mir dieser Workaround erstmal.

Wenn du hier tiefergehende Informationen hast, würde es mich dennoch interessieren.

**Comment by genodeftest** [comment]
Ich hatte an was anderes gedacht. Fedora patcht sein Java ja gründlich, aber das ist nur bei OpenJDK relevant. Und dein Gentoo sollte sowieso recht upstream-nah sein, dass die Frage erledigt sein dürfte.

**Comment by almereyda** [comment]
`GDK_SCALE` hat mit `java-1.8.0-openjdk-1.8.0.181-7.b13.fc28.x86_64` keine Auswirkungen gehabt. Bei Verwendung von `jdk-10.0.2-2000:10.0.2-ga.x86_64` direkt von Oracle erscheint nur:

> Falsche Java-Version
> MediethekView ist NUR mit Java 8 kompatibel.

Dies ist schade, da laut https://help.openstreetmap.org/questions/61236/how-can-i-scale-josm-for-a-4kuhd-display/61237 Scaling anscheinend erst ab Java 9 implementiert wurde.

**Comment by derreisende77** [comment]
13.3 wird Java 10 und Skalierung unterstützen. Bis jetzt sind diverse genutzte libs nicht Java 8+ kompatibel.

**Comment by io41** [comment]
@alex1702 da das Problem von HiDPI nun von Java JDK 9, 10 und 11 behoben ist, kann #67 wieder geöffnet werden, da es an MediathekView (oder deren benutzten Bibliotheken) liegt, dass es nicht mit einer moderneren JDK Version funktioniert, und daher keine HiDPI Unterstützung hat?

**Comment by derreisende77** [comment]
Wie ich schon geschrieben habe unterstützt 13.3 Java 11+. Und die Version wird auch zeitnah kommen da sie sich im Beta Test befindet. Warum also das issue aufmachen?

**Comment by io41** [comment]
@derreisende77 oh! Tut mir leid, ich hatte deine Nachricht missverstanden. Das ist ja super!! 🎆🎇 Stimmt, so gibt's kein Grund das zu öffnen. Danke!!
