### ISSUE TITLE
Option: nach Abarbeiten der Abos automatisch beenden

### ISSUE THREAD

**Issue by OrbitingOcelot** [mediathekview/MediathekView#670]
Ich hätte einen Wunsch bzw. ein Enhancement Request:

Es wäre sehr fein wenn es eine Option im Client gäbe, um das Programm nach dem abarbeiten der Downloads automatisch zu beenden (evt. mit einer grace period von 60 Sekunden, falls man die Option mal wieder abdrehen will). Oder als Alternative: man gibt dem grafischen Client eine entsprechende Option als Parameter mit.

Anwendungsszenario:
PC bootet, User loggt sich ein
MV startet via Autostart
MV holt die Filmliste+erstellt Downloadliste+arbeitet Abo Liste ab
MV zeigt Meldung in Statuszeile und wartet 60 Sekunden
MV beendet sich selbst

Das würde wahrscheinlich auch vielen helfen, die früher die CLI --auto Option verwendet haben.

**Comment by DaDirnbocher** [comment]
Dazu gibt es schon ein [Ticket](https://github.com/mediathekview/MediathekView/issues/543).

**Comment by OrbitingOcelot** [comment]
Sorry, da habe ich wohl schlecht gesucht. Habe das dort dazugeschrieben und werde das Ticket schließen.
