### ISSUE TITLE
Download-Tab sorgt für 100% CPU-Auslastung

### ISSUE THREAD

**Issue by mr-mister123** [mediathekview/MediathekView#671]
Hallo alle zusammen,

ich betreibe MediathekView 13.9.1 auf einem Linux-Mint Terminalserver. Nach längerer Laufzeit der Anwendung (meist mehrere Tage) kommt es zu dem Problem, dass MediathekView eine CPU zu 100% auslastet.
Das Problem tritt nur auf, wenn der Downloads-Tab geöffnet ist. Wechsel ich in die File-Liste, sinkt die CPU-Last sofort. Wechsel ich zurück in den Downloads-Tab, steigt diese sofort wieder auf 100%. Ein Neustart des Programms behebt das Problem.
Was mir grundsätzlich auffällt: Der Downloads-Tab zieht bei mir grundsätzlich mehr CPU-Ressourcen, als die Filme-Liste.
Filme-Liste: ca 5% CPU
Downloads-Tab: zwischen 8% und 20%, schwankend.
(Bitte nicht wundern über die hohen Werte, aber mein Terminalserver läuft als VM auf ziemlich schmaler Hardware).

Da ich selbst Java-Entwickler mit großer Erfahrung unter anderem im Bereich Performance-Optimierungen und Swing-GUIs bin, habe ich selbst schon etwas geforscht.
Leider kenne ich mich mit JavaFX nicht aus.
Wenn das Problem (100% CPU) auftritt, entsteht dieses durch den "JavaFX Application Thread". Anscheinend wird das Layout quasi als Endlosschleife neu ermittelt.
Im Anhang findet ihr eine Logdatei von mit jstack im 5sek. Abstand ermittelten Stacktraces des "JavaFX Application Thread". Wie man sehen kann, wächst die cpu-Zeit zwischen den Stacktraces ebenso immer um ca 5000msec, so dass dieser anscheinend in einer Endlosschleife läuft...

Ich hoffe, das hilft schon mal weiter.

Gruß,
Karsten

[javafx.log](https://github.com/mediathekview/MediathekView/files/9267434/javafx.log)

**Comment by derreisende77** [comment]
Hallo Karsten,

ja das JavaFX macht ne Menge Ärger. Deswegen bin ich auch gerade dabei dieses wieder zu entfernen und zurück zu Swing zu wechseln.
Installiere dir mal bitte ab morgen die MV 14 nightly. Diese sollte stabil sein und das Download-tab ist schon nach Swing umgearbeitet. Bin gespannt ob es dann stabiler bei dir läuft.

Davon abgesehen kann ich mir nicht verkneifen, dass das Programm nie dafür wirklich ausgelegt war tagelang betrieben zu werden ;)

**Comment by mr-mister123** [comment]
Hallo und danke für die Rückmeldung,

das werde ich dann die nächsten Tage mal ausprobieren und Rückmeldung geben.
Kann sein, dass es etwas dauert, da ja das Problem meist erst nach längerer Benutzung auftrat...

**Comment by derreisende77** [comment]
@mr-mister123 Kannst Du schon ein Feedback zur nightly geben?

**Comment by mr-mister123** [comment]
Hi, lustig, wollte gerade schreiben ;-)

Also das Problem ist seit dem Installieren der nightly-Version nicht wieder aufgetreten, die CPU-Last im Download-Tab auch viel geringer.
Außerdem scheint es auch ein anderes Problem zu beheben, welches ich noch nicht reported hatte, weil ich selber noch weitere Untersuchungen anstellen wollte: Mit der Version 13.9.1 hatte ich auch zwei mal das Problem, dass die Java-VM sehr viel Systemspeicher verbraucht hat. Obwohl die Memory-Setting ja auf 50% limitiert war (meine VM: 4GB Ram + 4GB Swap) - wäre dann ja bei mir also ca max 4GB für den Java-Prozess - kam es vor, dass das Betriebssystem den Java-Prozess aus Speichermangel getötet hat. Beide Male lag der Speicherverbrauch der Java-VM gemäß syslog des linux oom-killers  bei über 7GB... auch dieses Problem ist nicht mehr aufgetreten. Könnte mir Vorstellen, dass es irgendwie mit der Endlosschleife zusammenhing, so dass in manchen Situationen des Java-FX-Problems vielleicht größere Mengen Garbage angefallen sind und der Garbage-Collector nicht mehr hinterher kam...

Gruß,
Karsten

**Comment by derreisende77** [comment]
okay, dann schließe ich erst mal dieses Issue. Danke!
