### ISSUE TITLE
Blacklist - Zeilen löschen

### ISSUE THREAD

**Issue by MuenchenSued** [mediathekview/MediathekView#672]
Beim Blacklist Editor gibt es derzeit zwei Möglichkeiten, mehrere Zeilen zu löschen
1. Mit der Funktion "Alle Einträge löschen"
2. Mit der rechten Maus "Zeilen löschen"
Der Befehl "Alle Einträge löschen" ist gefährlich und überflüssig, da man mit CTRL-A alle Zeilen markieren und mit "Zeilen löschen" entfernen kann.

Ich würde vorschlagen, einen "Löschen" Knopf neben "Ändern" und "Hinzufügen" anzuordnen, der aktiv ist, wenn mindestens eine Zeile selektiert wird. Der entbehrliche Knopf "Alle Einträge löschen" sowie die Anzeige der gesamten Blacklisteinträge werden entfernt, letzte kann ggf. erweitert werden in x/y, wobei x die Anzahl der markierten und y die Anzahl aller Einträge sind. Ich halte diese Information aber für verzichtbar.

![2022-08-07_08-09](https://user-images.githubusercontent.com/71550657/183277816-cc8b0f6e-31c7-4aaf-8760-fcf5b0990660.png)
.

**Comment by derreisende77** [comment]
Ich werde das nicht ändern.
Ich brauche sowohl die Anzeige für mich als auch den alles löschen Button. Er ist auch nicht wirklich gefährlich da ein Dialog kommt und das Vorhaben des Nutzers verifiziert.
