### ISSUE TITLE
Downloads von SRF corrupt

### ISSUE THREAD

**Issue by Vrumfondel** [mediathekview/MediathekView#673]
Sämtliche Filme dich ich bisher von SRF geladen habe sind korrupt. So in der Hälfte bleiben die Files beim Abspielen hängen, und danach sind Audio und Video völlig asynchron (also nicht im ms Bereich, sondern der Ton passt gar nicht zur Szene).

**Comment by derreisende77** [comment]
[Im Forum](https://forum.mediathekview.de/topic/4864/srf-ton-ab-filmmitte-asynchron/17?_=1660195415090) gibt es einen Thread mit möglichen Erklärungen dazu. Nach bisherigen Erkenntnissen hat das nichts mit MV an sich zu tun.
