### ISSUE TITLE
Dauer der Sendung wird manchmal falsch angezeigt

### ISSUE THREAD

**Issue by mr-mister123** [mediathekview/MediathekView#674]
Hallo,

vorab: Installiert ist MV 14 nightly vom 06.08.2022

Bei 'Agatha Christies Poirot' wird bei den letzten Folgen die Dauer falsch angezeigt (siehe Screenshot). Ob dies auch bei anderen Einträgen passiert, kann ich nicht sagen.

Problem, das sich daraus ergibt: Ich habe ein Abo darauf angelegt. Um Trailer auszuschließen, habe ich eine Mindestdauer von 30min angegegeben (alle Folgen sind mindestens 45 min lang). Das führt dazu, dass diese Folgen nicht automatisch heruntergeladen werden.

Sollte sich das Problem nicht lösen lassen, schlage ich vor, im Abo-Dialog zusätzlich zur Mindest-Dauer auch eine Mindest-Größe pflegen zu können. Wäre das machbar?

Danke und Gruß,
Karsten

![image](https://user-images.githubusercontent.com/8041234/186100747-7ec62f54-359d-4ee1-b4f5-b375ef35b631.png)

**Comment by derreisende77** [comment]
Da scheint der Crawler die Dauer bei der ARD nicht richtig zu erkennen. Das ist kein MV Problem. Kannst Du das Issue bei MServer bitte einstellen?
