### ISSUE TITLE
JavaFX Dialoge unter HiDPI-Linux unleserlich klein

### ISSUE THREAD

**Issue by wolfseifert** [mediathekview/MediathekView#676]
Die JavaFX basierenden MediathekView-Dialoge sind unter HiDPI-Linux unleserlich klein.

**Das ist ein allgemeines Problem von JavaFX!**

Da MediathekView seit neuestem FlatLaf verwendet, erscheint mir die JavaFX-Abhängigkeit als Relikt aus der Vergangenheit und somit obsolet. Ein vollständiges Entfernen von JavaFX würde vermutlich nicht nur das Problem mit der Leserlichkeit lösen.

Die Kombination Swing/Kotlin erscheint mir als tragfähige, zukunftsträchtige Lösung (mit IntelliJ IDEA als Leutturm), obwohl ich persönlich eigentlich SWT/Kotlin preferiere (wegen des nativen L&F).

Da mich die Unleserlichbarkeit beim [InfoDialog.kt.txt](https://github.com/mediathekview/MediathekView/files/9643432/InfoDialog.kt.txt) am meisten gestört hat, habe ich diesen mal testweise nach Java-Swing portiert: 
[InfoDialog2.kt.txt](https://github.com/mediathekview/MediathekView/files/9643453/InfoDialog2.kt.txt). Und voilà, ich kann ihn wieder lesen (getestet unter Linux und Windows). Wozu die `Platform.runLater` da sind, habe ich nicht verstanden und sie durch `SwingUtilities.invokeLater` ersetzt. Wichtig war auch ein `pack()` nach dem Lesen der Daten.

Dann hab ich noch mehr aufgeräumt: [InfoDialog3.kt.txt](https://github.com/mediathekview/MediathekView/files/9643498/InfoDialog3.kt.txt). Wodurch sich aber auch die Funktionalität etwas geändert hat: statt Merken der Position wird nun zentriert, die Grösse ändert sich bei einem Wechsel des Films etc. Auch ein modaler Dialog erscheint mir hier u.U. sinnvoll. Eine exakte Reproduktion der Funktionlität ist schwierig (bzw. unmöglich), sollte aber hier auch nicht das Ziel sein.

Sollte die "Reise" von MediathekView in Richtung Swing/Kotlin gehen, wäre ich bereit, noch weitere Dialoge zu migrieren.

**Comment by derreisende77** [comment]
Das Entfernen von JavaFX steht langfristig auf dem Plan und wird in jeder Version weniger werden wenn die Zeit es zulässt. 

Swing ist langfristig eigentlich keine Lösung das es seitens Oracle EOL ist und eigentlich sollte JavaFX "the new hot sh*t" sein - aber das funktioniert wirklich nur halbwegs gut auf modernen Maschinen und mit Windows. SWT ist gerade wegen der nativen Abhängigkeiten ein Problem da wir so noch mehr Builds machen müssen. 

Zum Thema InfoDialog und Portierung im Allgemeinen:
Im aktuellen develop-Branch ist dieser schon komplett ohne bisherigen Funktionsverlust nach Swing portiert. Ein Erhalt der bisherigen Funktionalitäten ist zwingend erforderlich wenn man etwas portieren möchte, da diese im Laufe der Jahre von den Usern gewünscht wurden. Des weiteren macht es bzgl Info Dialog durchaus Sinn dass dieser **kein** Modal Dialog ist da der user primär in der Tabelle sucht und sich dann jeweils die zusätzlichen Infos reinziehen kann. Ein modaler Dialog wäre hier absolut kontraproduktiv.

Was noch zu beachten ist: Auch mit Swing gibt es Unterschiede, wie sich programmierte UI Elemente unter Linux/Windows/macOS verhalten. Gerade wenn etwas unter Linux geht muss dies nicht mehr für Windows und mac gelten - und umgekehrt. Dies liegt u.a. am anderen mouse handling unter Linux.

Platform.runLater() calls sorgen dafür dass Anweisungen auf dem JavaFX Thread ausgeführt werden, die SwingUtilities.invokeXXX werden auf dem Swing Event Dispatcher Thread ausgeführt. Diese zu vermischen führt zu unvorhersehbaren Ereignissen und schwer nachzuvollziehenden Fehlern. Etwas ähnliches sollte auch für SWT gelten.

Nur weil IntelliJ noch Swing nutzt ist es IMHO kein Leuchtturmprojekt sondern es setzt (wie MV und andere) auf eine EOL-Technologie. Der Unterschied ist aber das JetBrains einen Haufen guter Coder hat und diverse Dinge entweder je plattform native umsetzt oder eigene Replacements programmiert. Die UI Anteile von IntelliJ sind außerhalb von IntelliJ meines Wissens nach nur schwer/gar nicht nutzbar.

**Comment by wolfseifert** [comment]
Das mit der Swing Oracle EOL liest sich [hier](https://www.oracle.com/technetwork/java/javase/javaclientroadmapupdatev2020may-6548840.pdf) (ganz am Ende) aber anders. Da hat Oracle offensichtlich eine Kehrtwendung vollzogen.

JetBrains hat ein eigenes JDK und es gibt das OpenJDK, so dass die Zukunft von Swing nicht alleine in den Händen von Oracle liegt.
