### ISSUE TITLE
Download-Filterpanel wird nicht vollständig angezeigt beim ersten Start von MV

### ISSUE THREAD

**Issue by styroll** [mediathekview/MediathekView#677]
Beim ersten Start von MV (also bei Erstinstallation) wird das Filterpanel im Tab "Downloads" insofern nicht vollständig angezeigt, als keine sichtbare Eingabe von Zahlen in den zwei Feldern möglich ist (oder anders gesagt: Man sieht die zwei Felder "gleichzeitig" und "max. Bandbreite" nicht vollständig und die Einheit KiB/s gar nicht.

<img width="780" alt="MV_Downloadfilterpanel" src=https://forum.mediathekview.de/assets/uploads/files/1665544831991-2022-10-12_05-18.png>

Erst das Breitermachen des Panels bringt Abhilfe, danach lässt sich die Breite nicht mehr auf die ursprüngliche Breite zurückbringen. Die Breite ist dann allerdings unnötig breit, das heisst platzverschwendend.

Eigentlich wäre die gesetzte Breite des Panels beim ersten Start sinnvoll, aber die fixe Feldbreite selbst ist viel zu breit.

MV 13.9.1 unter macOS 10.14.6 (das Problem tritt jedoch erwartungsgemäss auch unter Win und Linux auf, [vgl. Forum](https://forum.mediathekview.de/post/32196))

**Comment by derreisende77** [comment]
Ja, das tritt in allen OS auf. Ich denke der fix sollte nun zuverlässig funktionieren unter Inkaufnahme das das erstmalige Darstellen breiter als notwendig ist.
Kleiner als das bisherige Verbot geht es aber nicht da dies die derzeitigen Minimummaße für das Panel sind. Ggf. kann ich das zukünftig noch etwas kleiner machen.
