### ISSUE TITLE
"Filme als (un)gesehen markieren" funktioniert nicht über Auswahl des Menübefehls

### ISSUE THREAD

**Issue by styroll** [mediathekview/MediathekView#678]
Die Befehle "Filme als gesehen markieren" und "Filme als ungesehen markieren" im Menü "Filme" ergeben bei mir (MV 13.9.1, macOS 10.14.6) eine Fehlermeldung:

<img width="1054" alt="MV_als_gesehen-markieren" src="https://user-images.githubusercontent.com/24810728/195575041-26152171-1782-4e52-9079-229ecbb760b9.png">

In der Tabelle wurden jedoch sehr wohl Einträge ausgewählt, die entsprechenden Shortcuts "ctrl + G" bzw. "ctrl + N" funktionieren jedoch.

**Comment by derreisende77** [comment]
Du hast das gesehen markieren für den Bereich Downloads gewählt, aber die Filme im Tab "Filme" ausgewählt. Dafür wäre der entsprechende Eintrag im Menü "Filme" zu benutzen.
Die Fehlermeldung ist insofern korrekt als der gewählte Befehl keine selektierten Einträge im Tab "Downloads" gefunden hat. Hier wäre ggf. eine etwas deutlichere Formulierung der Fehlermeldung richtiger.
Die shortcuts funktionieren da die Menüeinträge (illegalerweise zur Darstellung) dieselben sind, die jeweilig aktive Tabelle diese jedoch abfängt und für sich richtig verarbeitet.
Ich gebe zu dass war eine unkluge Entscheidung von Xaver damals, aber der aus meiner Sicht einzig logisch korrekte Schritt wäre, die Einträge in den Menüs zu entfernen und diese nur noch über das jeweilige Kontextmenü verfügbar zu machen.

**Comment by styroll** [comment]
>@derreisende77 sagte: Du hast das gesehen markieren für den Bereich Downloads gewählt, aber die Filme im Tab "Filme" ausgewählt. Dafür wäre der entsprechende Eintrag im Menü "Filme" zu benutzen.

Oops, tatsächlich, sorry, also Fehlalarm. Eigentlich wäre mir das schon klar, hab jedoch nicht realisiert, das ich im falschen Menü war.

>@derreisende77 sagte: der aus meiner Sicht einzig logisch korrekte Schritt wäre, die Einträge in den Menüs zu entfernen und diese nur noch über das jeweilige Kontextmenü verfügbar zu machen.

Da hätten wir aber wieder das Problem, dass man keine Kontextmenü-Befehle bei einer Mehrfachauswahl von Einträgen anwählen kann…
