### ISSUE TITLE
Flatpak manifest

### ISSUE THREAD

**Issue by lunaryorn** [mediathekview/MediathekView#679]
Following https://github.com/mediathekview/MediathekView/issues/382 I've created a flatpak manifest for MediathekView at <https://github.com/lunaryorn/de.mediathekview.MediathekView>.

May I submit this to flathub to make it available in the standard flatpak repository?  See https://github.com/flathub/flathub/wiki/App-Submission

**Comment by alex1702** [comment]
Hi, vielen Dank für die Arbeit. Wenn du möchtest würde ich das hier in die Organisation über führen und dich als Entwickler hinterlegen. Gerne kannst du dich dann auch um das einreichen bei denen kümmern, da ich keine Ahnung davon habe. Was hälst du davon?

**Comment by lunaryorn** [comment]
Vielen Dank 🙏Ich würde das Repo gerne hierher verschieben, aber ich glaube, diesen Schritt brauchen wir nicht gehen.  Für den flathub Store muss das Repo mit dem Manifest ohnehin in der flathub Organisation auf GitHub liegen.

Ich wollte Mediathekview nur nicht einreichen, ohne vorher nachgefragt zu haben 😇

Ich werde den Bugtracker Link vorher noch aus den Metadaten entfernen, damit Probleme mit dem Flatpak nicht hier aufschlagen.  Das Flatpak Repo bekommt seinen eigenen Issue Tracker, an welchen Ihr dann gerne alle verweisen könnt, die Probleme mit dem Flatpak haben 🙂

Falls es also okay ist für Euch, dann würde das Manifest beim Flatpak Store einreichen 😊

**Comment by lunaryorn** [comment]
@alex1702 Ich habe https://github.com/flathub/flathub/pull/3616 erstellt, um MediathekView auf flathub einzureichen.

**Comment by alex1702** [comment]
> Vielen Dank prayIch würde das Repo gerne hierher verschieben, aber ich glaube, diesen Schritt brauchen wir nicht gehen. Für den flathub Store muss das Repo mit dem Manifest ohnehin in der flathub Organisation auf GitHub liegen.

Mir ging es eher darum, wenn jemand Probleme mit dem Flatpak hat oder das Manifest sucht (weil er z.B. neugierig ist wie das funktioniert oder jemand möchte das Flatpak selber bauen) dann würde er halt eher hier in der Organisation danach suchen.

Ansonsten freue ich mich über die Einreichung bei dem Flatpak Repo.

**Comment by lunaryorn** [comment]
Verstehe ic 🙂

Aber ein Repo unter der flathub Organisation ist zwangsläufig Vorraussetzungen für den flathub Store, weil flathub aus diesem Repo dann automatisch das Flatpak baut.  Das gilt für alle Apps in flathub; da kommt man nicht drum herum 🤷

Sobald flathub Mediathekview akzeptiert, hätte ich mein Repo deswegen dann auch einfach gelöscht, bzw. archiviert.

Ein Repo hier in dieser Organisation wäre zwar möglich, aber im Prinzip doppelte Arbeit, weil es das Repo unter flathub nicht ersetzen kann 🙂. Man müsste die Repos dann synchronisieren, etc. und diese Arbeit würde ich mir ungern machen wollen 😇

**Comment by lunaryorn** [comment]
PS: Die Repos sind dort auch zugänglich. Hier ist beispielsweise das für VLC: https://github.com/flathub/org.videolan.VLC

Dort gibt es auch ein Issue Tracker für Probleme mit dem Flatpak Build und die Möglichkeit, Pull Requests für das Manifest zu stellen.

So würde das bei Mediathekview dann auch laufen 🙂

**Comment by alex1702** [comment]
Ok ich meinte natürlich nicht, dass das flatpak repo von denen bei uns sein soll :D 
Meinte nur deins zum einreichen, aber wenn das eh nicht mehr aktiv ist, dann macht es natürlich kein Sinn stimmt wohl :D
Passt also.

**Comment by lunaryorn** [comment]
Mediathekview ist jetzt auf flathub verfügbar: https://github.com/flathub/de.mediathekview.MediathekView
