### ISSUE TITLE
Überflüssige Warnung

### ISSUE THREAD

**Issue by KBDCALLS** [mediathekview/MediathekView#680]
Wenn ich die Filmliste mauell laden will dann erscheint eine Warnung.  Und die halte ich für überflüssig.

Die Liste soll nämlich nur erweitert werden und nicht jedesmal komplett erneuert werden. 

Version 13.9.1

**Comment by derreisende77** [comment]
Da meine Glaskugel gerade Urlaub hat: Was für eine vermeintlich überflüssige Warnung kommt denn?

**Comment by KBDCALLS** [comment]
Bitte vermeiden sie das laden der Filmliste von unseren Servern über ein manuell eingegebene URL.
https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
![Screenshot_20221104_224757](https://user-images.githubusercontent.com/11138249/200080170-518c23df-0234-4b4c-931a-b2ecdf0b4961.png)

usw. usw.

**Comment by alex1702** [comment]
Ich sehe da kein Problem. Der Hinweis ist halt wichtig!

**Comment by derreisende77** [comment]
Ein manuelles Laden der FIlmliste von uns ist möglich, auch wenn **keine** URL zu uns im Textfeld eingetragen ist. MV wählt dann automatisch eine richtige aus.
Sobald jedoch eine URL von uns manuell eingetragen ist, wird (richtigerweise) die o.g. Warnmeldung angezeigt - wir möchten nicht dass User mgl. veraltete URLs zu uns nutzen und ggf. load balancing Maßnahmen torpedieren.
Von daher ist diese Warnmeldung wichtig und richtig.

**Comment by KBDCALLS** [comment]
Und warum ist dann so vorgegeben ? Das war schon so bei den Versionen  mit den es möglich war die Sever der Sendern direkt abzufragen . Außerdem wäre ein Hinweis auch nicht verkehrt.
