### ISSUE TITLE
error: Unmatched argument at index 1

### ISSUE THREAD

**Issue by 4ch1m** [mediathekview/MediathekView#683]
Seit Version 13.9.1 funktioniert bei mir unter Linux der Aufruf der "Portable"-Variante (mit Pfadangabe zum Einstellungsverzeichnis als erster/einziger Parameter) nicht mehr:

```
./MediathekView_Portable '/home/achim/.MediathekView'
```

Im `error.log` findet sich folgendes:

```
Unmatched argument at index 1: '/home/achim/.MediathekView'
Usage: MediathekView [-efhm] [<Pfad zum Verzeichnis>]
      [<Pfad zum Verzeichnis>]
                           Pfad zum Einstellungsverzeichnis für Portablen
                             Betrieb
  -e, --enhanced-logging   Erweiterten Log-Modus aktivieren
  -f, --disable-file-logging
                           Speichern des Log output in Datei deaktivieren
  -h, --help               Hilfe anzeigen
  -m, --maximized          Programmfenster beim Start maximieren
```

Bei Version 13.8.0 lief das noch.

**Comment by 4ch1m** [comment]
> Mit den richtigen Einstellungen läuft das sicher auch noch in 13.9.1 ;)

Definiere bitte "_sicher_"?
Hast Du es denn selbst mal ausprobiert? Oder ist das nur eine Vermutung?

Ich habe beide Versionen vorliegen:

* `13.8.0`
* `13.9.1`

Aufruf mit jeweils gleichem Parameter:

```
./MediathekView_Portable '/home/achim/.MediathekView'
```

Bei `13.8.0` funktioniert's. Bei `13.9.1` funktionert's **nicht** mehr.

Die Parameteranzahl/-beschreibung hat sich laut Doku/Konsolenausgabe auch nicht geaendert. Ist bei beiden Versionen identisch:

```
./MediathekView_Portable --help
```

```
Usage: MediathekView [-efhm] [<Pfad zum Verzeichnis>]
      [<Pfad zum Verzeichnis>]
                           Pfad zum Einstellungsverzeichnis für Portablen
                             Betrieb
  -e, --enhanced-logging   Erweiterten Log-Modus aktivieren
  -f, --disable-file-logging
                           Speichern des Log output in Datei deaktivieren
  -h, --help               Hilfe anzeigen
  -m, --maximized          Programmfenster beim Start maximieren
```

Fuer mich ist das definitiv eine Regression.

Es geht hier im Uebrigen auch explizit um das "MediathekView **_Portable** "-Skript; nicht das normale "MediathekView"-Skript. Letzteres funktioniert noch wie beschrieben.

**Comment by derreisende77** [comment]
@4ch1m Hast Du MV zufällig mit dem Installer installiert? Gemäß der Anleitung versucht die Portable die Einstellungen in das Programmverzeichnis zu schreiben, welches z.B. beim deb Paket unter /opt/mediathekview liegt und nicht beschreibbar ist, es funktioniert nur mit einer manuell installierten MediathekView-Version.
Bei der Nutzung des Portable Scripts kann auch kein Verzeichnis angegeben werden da das Startskript dies schon von sich aus setzt, daher kommt es zu dem von dir beschriebenen Fehler.
Wenn Du das Verzeichnis ändern willst nutze bitte `MediathekView <pfad>`. 

Ich habe die Anleitung diesbezüglich angepasst, die Änderungen sind aber noch nicht aktiv gesetzt.
