### ISSUE TITLE
Download mittels DirectHttpDownload erzeugt unnötig hohe CPU-Last auf schwachen Systemen

### ISSUE THREAD

**Issue by mr-mister123** [mediathekview/MediathekView#685]
Hi,

wird eine Datei ohne Hilfsprogramme durch die Klasse DirectHttpDownload heruntergeladen, so entsteht auf schwacher Hardware eine hohe CPU-Last.

Getestet mit: 14.0.0 vom 06.08.2022
DirectHttpDownload.class wurde schon länger nicht mehr geändert, Problem sollte auch in aktuellen Builds bestehen.

![grafik](https://user-images.githubusercontent.com/8041234/211276921-28fd9540-9e4c-4238-822d-ef38a11441b8.png)

Erste Tests mit jVisualVM zeigen mir, dass es mit dem publishen des Fortschritts zusammenhängt:
Von ca 30 Sek Sampling-Zeit war der Download-Thread zwar die meiste Zeit geblockt beim warten auf System-IO, was aber ja in sofern nicht schadet, da das Betriebssystem diese Zeit nutzen kann, um andere Prozesse zu verarbeiten. Die eigentlich Verarbeitung der heruntergeladenen Daten dauerte nur 1100 msecs (lesen von tcp/ip, schreiben auf hdd), das publishen des Fortschritts hingegen 2800msecs.
Oder anders gesagt: Die Verarbeitung des Fortschritts benötigt ca 3x so viel CPU wie der eigentliche Download:

![grafik](https://user-images.githubusercontent.com/8041234/211278081-314e0565-9606-44b6-abfa-8ca7fc8a8ce9.png)

Das Problem liegt meiner Meinung nach darin, dass in der Methode downloadContent() die Variable 'melden' bei jedem Schleifendurchlauf true wird, da bei jedem Schleifendurchlauf die Größe der heruntergeladenen Datei sich geändert hat. bei einer Puffergröße von 1kb und z.B. einer Download-Geschwindigkeit von 4mb/s bedeuted dies 4000 Statusupdates pro Sekunde.

Ich schlage vor, einzubauen dass die Meldung nur published wird, wenn seit der letzten Meldung mindestens eine Sekunde vergangen ist oder das Ende der Schleife (download abgeschlossen) erreicht wurde.

Gruß,
Karsten

**Comment by derreisende77** [comment]
Von welcher Hardware reden wir hier? Auf meinen Systemen kann ich das nicht nachvollziehen da es beim profiling kein Faktor ist.

**Comment by mr-mister123** [comment]
Es handelt sich um einen AMD E2-6110.
Also Netbook-hardware. Das ganze auch noch virtualisiert mit qemu+kvm.

Ich weiß, die Hardware ist echt lahm, aber die Kiste schlägt sich als File- und Datenbank- Server eigentlich super. Und da der immer läuft, läuft da mein Mediathekview.

Vielleicht verfälscht die langsame CPU aber auch das Ergebnis des Profilings ;-)

**Comment by derreisende77** [comment]
Ich befürchte das werde ich nicht beheben können. Lahme HW in Verbindung mit wenig Speicher war bisher schon immer ein Problem, weshalb wir mit dem Wechsel nach 64bit den ersten großen Schnitt eingeleitet haben damit wir zukünftig mehr Funktionalität einbauen können. Und bei der Konstellation auch noch über remote Verbindung: Oh mein Gott 😄
