### ISSUE TITLE
"Mit diesem Namen neu starten" erscheint genau oberhalb vom "Ok" Button

### ISSUE THREAD

**Issue by Tims777** [mediathekview/MediathekView#686]
Wenn ein Downloadfehler (z.B. "Connection reset") auftritt, erscheint ein informatives Dialogfeld, das mit Klick auf "Ok" geschlossen werden kann. Ungefähr eine Sekunde später öffnet sich dann allerdings zusätzlich das "Download weiterführen"-Dialogfeld, wobei die Schaltfläche "Mit diesem Namen neu Starten" genau oberhalb von "Ok" erscheint.

Die Wahrscheinlichkeit dafür, die Option "Mit diesem Namen neu Starten" versehentlich auszuwählen (wenn man eigentlich nur auf "Ok" klicken möchte) ist daher extrem hoch!

**Comment by dadidadit** [comment]
> Wenn ein Downloadfehler (z.B. "Connection reset") auftritt, erscheint ein informatives Dialogfeld, das mit Klick auf "Ok" geschlossen werden kann. Ungefähr eine Sekunde später öffnet sich dann allerdings zusätzlich das "Download weiterführen"-Dialogfeld, wobei die Schaltfläche "Mit diesem Namen neu Starten" genau oberhalb von "Ok" erscheint.
> 
> Die Wahrscheinlichkeit dafür, die Option "Mit diesem Namen neu Starten" versehentlich auszuwählen (wenn man eigentlich nur auf "Ok" klicken möchte) ist daher extrem hoch!

Die Wahrscheinlichkeit dafür, dass bei unvollständigen Angaben zu Programmversion und OS jemand die 
 Nonplusultra-Glaskugel  zur Hand hat, ist dafür extrem niedrig ;)

**Comment by Tims777** [comment]
OS: Windows 11 Home (Version 22H2)
MV: 13.9.1

**Comment by dadidadit** [comment]
Das Dialogfeld mit der Fehlermeldung lässt sich sowohl verschieben als auch im Menu DATEI unter Downloads dauerhaft deaktivieren. 
Das Dialogfeld zum Weiterführen kann man ebenfalls an eine andere Position verschieben.

**Comment by Tims777** [comment]
![grafik](https://user-images.githubusercontent.com/1769601/214797530-939f7999-f5d2-4f6b-89bd-b8fd6c3e81c1.png)

Das Problem ist nicht, dass man den dahinterliegenden Button nicht drücken kann, sondern dass man den weiter vorne liegenden Button versehentlich drückt, genau wenn dieser gerade auftaucht. Deaktivieren wäre eine Option, verschieben eher nicht, da alle neuen Popups immer an derselben stelle auftauchen.
Meine Gedanken gingen eher dahin, dass man vielleicht die Position des "Mit diesem Namen neu Starten"-Button ändern könnte (z.B. einfach nach links statt nach rechts ausrichten). Der Klick geht dann im Zweifelsfall einfach ins leere und man hat genug Zeit, um auf beide Popups zu reagieren.

**Comment by dadidadit** [comment]
> Das Problem ist ...
>
keins!
Ob du den OK-Button gleich, später oder überhaupt nicht betätigst, ist völlig egal, das Fenster ist lediglich ein HINWEIS-Fenster. Was mit dem Download geschieht, entscheidet man mit Abbrechen, Weiterführen oder Neustarten. Wenn damit eine entsprechende Aktion erfolgt ist, kannst du den OK-Button immer noch betätigen ....

**Comment by DaDirnbocher** [comment]
> > Das Problem ist ...
> 
> keins! 

Auch wenn Du das Problem nicht verstehst, ist es für jemand anderen eines.

> Ob du den OK-Button gleich, später oder überhaupt nicht betätigst, ist völlig egal,

Blubber da nicht am Thema vorbei, es geht auch nicht um den OK Button, sondern darum, dass man versehentlich einen anderen Button drückt, den man vielleicht gar nicht drücken wollte.

**Comment by dadidadit** [comment]
> Auch wenn Du das Problem nicht verstehst, ist es für jemand anderen eines.
> 
In AT ist das eben so, dass man vor lauter Verwirrtheit nix versteht, wie man das  bei dir mal wieder feststellen kann. :D

.>.. man versehentlich einen anderen Button drückt, den man vielleicht gar nicht drücken wollte.
>
Man kann auch nach einem  (möglichen) Versehen den Download noch abbechen und sogar entferne :D 
WER hier was nicht schnallt, lasse ich mal offen.
EOD

**Comment by Tims777** [comment]
Wenn ich versehentlich den Download neu gestartet habe, kann ich den natürlich wieder abbrechen. Was ich nicht kann, ist meinen vorherigen Download danach wieder aufzunehmen. Es gehen also im Zweifelsfall einige GB an heruntergeladenen Daten verloren, was je nach Internetverbindung durchaus einem Zeitverlust von über einer Stunde entsprechen kann.

**Comment by Tims777** [comment]
Btw, ich würde mich freuen, wenn bei so einer Diskussion beide Seiten sachlich bleiben. Alles andere führt im Zweifelsfall nur dazu, dass noch mehr Verwirrung aufkommt :)

**Comment by alex1702** [comment]
Irgendwie eine interessante und schwachsinnige Diskussion. 

Ich kann vollkommen nachvollziehen was @Tims777 meint. Es ist halt einfach ein UI Problem, dass ein zweites Fenster zeitversetzt auftaucht und einen Button dort hat wo das andere Fenster einen Bestätigungsbutton hat. Das muss man nicht wegdiskutieren, wenn es ein valides Problem ist (Nicht jedes Problem ist ein technisch behinderndes Problem).

Ich denke @derreisende77 wird sicher keinen "mal eben" fix umsetzen können, aber in Zukunft sicher beim überarbeiten der gesamten UI so etwas mit in seine Entscheidungen einfließen lassen.

**Comment by dadidadit** [comment]
> Wenn ich versehentlich den Download neu gestartet habe, kann ich den natürlich wieder abbrechen. Was ich nicht kann, ist meinen vorherigen Download danach wieder aufzunehmen. 

Doch, kannst du. Das Fenster überlagert doch die Fehlermeldung, und was in der Fehlermeldung steht ist für'*s Weiterarbeiten völlig uninteressant und wird immer wieder vom "Aktions"-Fenster überlagert, falls erforderlich. Du musst schon aufpassen, auf welche der 3 zur Verfügung stehenden Optionen du klickst. Wenn du unsicher bist, klicke auf _Abbrechen_, dann verschwindet das  Fenster und du kannst im Download-TAB den Download neu starten, indem du eine evtl. Fehleranzeige wegklickst (Radiergummoi) und auf den Pfeil klickst. 
Wenn der Fehler wieder auftreten sollte, beginnt das Spiel halt von vorn und das Fenster erscheint erneut. Stell doch die Benachrichtigung ab, (F4) > Download, du wirst auch so merken, wenn ein Fehler aufgetreten ist.

**Comment by dadidadit** [comment]
> Irgendwie eine interessante und schwachsinnige Diskussion.
> 
> Ich kann vollkommen nachvollziehen was @Tims777 meint. Es ist halt einfach ein UI Problem, dass ein zweites Fenster zeitversetzt auftaucht und einen Button dort hat wo das andere Fenster einen Bestätigungsbutton hat. Das muss man nicht wegdiskutieren, wenn es ein valides Problem ist (Nicht jedes Problem ist ein technisch behinderndes Problem).
> 
@alex1702
> Ich denke @derreisende77 wird sicher keinen "mal eben" fix umsetzen können, aber in Zukunft sicher beim überarbeiten der gesamten UI so etwas mit in seine Entscheidungen einfließen lassen.

Bei mir erscheint unter Windows 10 keine durchscheinende Überlagerung, das Aktionsfenster überschreibt das Fenster mit der Fehlermeöldung vollständig. Möglicherweise ist das bei 11 anders.

**Comment by alex1702** [comment]
> Bei mir erscheint unter Windows 10 keine durchscheinende Überlagerung, das Aktionsfenster überschreibt das Fenster mit der Fehlermeöldung vollständig. Möglicherweise ist das bei 11 anders.

Gerne auch mal einen Screenshot hier posten.

**Comment by dadidadit** [comment]
Nö. In den Off-Topics habe ich eine mögliche Lösung erklärt. Der ganze Diskussion ist imo eine Scheindiskussion. Für mich ist hier das Thema erledigt.

**Comment by Tims777** [comment]
> Du musst schon aufpassen, auf welche der 3 zur Verfügung stehenden Optionen du klickst.

Also nochmal Schritt für Schritt:
1. Ich will auf die Aktion "Ok" bei der Fehlermeldung klicken und bewege meinen Cursor über den Button.
2. Das Dialogfeld "Download Weiterführen" öffnet sich.
3. Ich klicke, weil mein Gehirn noch nicht verarbeitet hat, dass gerade ein anderer Button an der selben Stelle erschienen ist.
4. Der Download wird neu gestartet, ich bemerke meinen Fehler, kann aber nichts mehr dran ändern.

**Comment by Tims777** [comment]
Ich denke für einen Fix müsste man einfach nur die Ausrichtung von `jButtonNeuerName` in der [DialogContinueDownload.form](https://github.com/mediathekview/MediathekView/blob/master/src/main/java/mediathek/gui/dialog/DialogContinueDownload.form) von rechts nach links ändern - vvorbehatlich, dass sich die Popups auch bei anderen Bildschirmauflösungen in ähnlicher Art und Weise überlagern. Leider habe ich selber keinerlei Erfahrung mit GUI-Gestaltung in Java und weiß daher nicht, wie genau das bewerkstelligt werden kann, ohne das übrige Layout zu zerstören.

**Comment by derreisende77** [comment]
Die Position des Buttons wird nicht geändert werden da dies allen handelsüblichen UI widerspricht. In der nächsten Version wird der Fortsetzen-Dialog etwas tiefer auf dem Bildschirm dargestellt so dass klicks an der Position ins Leere gehen.
