### ISSUE TITLE
Regex funktionieren nicht wie erwartet

### ISSUE THREAD

**Issue by tps800** [mediathekview/MediathekView#687]
Eine Filmauswahl in "Thema-Titel" mit folgender Regex

> `"#:^Inspector\ Barnaby.*(?!\((Audio|OmU|AD|H).*\).*)"`

Schließt Filme, die irgendwo in der Beschreibung eine "(" gefolgt von Audio, OmU, AD, H, gefolgt von weiteren Zeichen, danach eine ")", gefolgt von möglichen weiteren Zeichen, nicht aus.

Wird im "Thema" "Inspector Barnaby" angegeben und im "Titel" mit der Regex

> `#:^.*(?!\((Audio|OmU|AD|H).*\).*)`

Alles was im Titel eine Klammer mit Audio, OmU, AD, H, gefolgt von weiteren Zeichen, gefolgt von einer schließenden Klammer, gefolgt von möglichen weiteren Zeichen bis zum Zeilenende enthält gibt es überhaupt keinen Match mehr. Die Downloadliste bleibt leer.

Es gibt kein klare Beschreibung, wie sich in welchem Feld die Regulären Ausdrücke verhalten. Es ist nicht nachvollziehbar. Es ist nicht erklärt. Mal funktionieren Ausschlüsse, mal nicht. Mal werden bei Sendungen, mit identisch aufgebauten Regulären Ausdrücken Sendungen gefunden, mal führt das zu keinem Ergebnis.

Die Hilfen im Forum geben das wieder. Keiner weiß so recht warum es mal funktioniert und mal nicht. Warum mal im Suchenfeld im Tab Filmliste, ein regulärer Ausdruck funktioniert, mal nicht. Zum Beispiel schließt der reguläre Ausdruck im Suchenfeld der Filmliste nicht die Titel mit Klammern im Titel aus:

> `"#:^Inspector\ Barnaby.*(?!\((Audio|OmU|AD|H).*\).*)"`

In der Filmliste bleiben die `(Audio.*)` enthalten:
`Inspector Barnaby - Mord ist keine Hexerei - Nach den Romanen von Caroline Graham (Audiodeskription)`

**Comment by dadidadit** [comment]
> Eine Filmauswahl in "Thema-Titel" mit folgender Regex
> 
> > `"#:^Inspector\ Barnaby.*(?!\((Audio|OmU|AD|H).*\).*)"`
> 
> Schließt Filme, die irgendwo in der Beschreibung eine "(" gefolgt von Audio, OmU, AD, H, gefolgt von weiteren Zeichen, danach eine ")", gefolgt von möglichen weiteren Zeichen, nicht aus.

> 
> Wird im "Thema" "Inspector Barnaby" angegeben und im "Titel" mit der Regex
> 
> > `#:^.*(?!\((Audio|OmU|AD|H).*\).*)`
> 
> Alles was im Titel eine Klammer mit Audio, OmU, AD, H, gefolgt von weiteren Zeichen, gefolgt von einer schließenden Klammer, gefolgt von möglichen weiteren Zeichen bis zum Zeilenende enthält gibt es überhaupt keinen Match mehr. Die Downloadliste bleibt leer.
> 
> Es gibt kein klare Beschreibung, wie sich in welchem Feld die Regulären Ausdrücke verhalten. Es ist nicht nachvollziehbar. Es ist nicht erklärt. Mal funktionieren Ausschlüsse, mal nicht. Mal werden bei Sendungen, mit identisch aufgebauten Regulären Ausdrücken Sendungen gefunden, mal führt das zu keinem Ergebnis.
> 
> Die Hilfen im Forum geben das wieder. Keiner weiß so recht warum es mal funktioniert und mal nicht. Warum mal im Suchenfeld im Tab Filmliste, ein regulärer Ausdruck funktioniert, mal nicht. Zum Beispiel schließt der reguläre Ausdruck im Suchenfeld der Filmliste nicht die Titel mit Klammern im Titel aus:
> 
> > `"#:^Inspector\ Barnaby.*(?!\((Audio|OmU|AD|H).*\).*)"`
> 
> In der Filmliste bleiben die `(Audio.*)` enthalten: `Inspector Barnaby - Mord ist keine Hexerei - Nach den Romanen von Caroline Graham (Audiodeskription)`

**Comment by dadidadit** [comment]
> Es gibt kein klare Beschreibung, wie sich in welchem Feld die Regulären Ausdrücke verhalten. Es ist nicht nachvollziehbar. 

Doch, gibt es!

[Anleitung im Programm, nennt sich Online-Anleitung, zu finden im Menü Hilfe](https://mediathekview.de/anleitung/#verwenden-von-regex)
[Regex Hilfe](https://github.com/mediathekview/MediathekView/issues/687)
[Regex Titorial](https://github.com/mediathekview/MediathekView/issues/687)

Warum einfach, wenn es auch umständlich geht? 
Ausschlusskriterien kann man am einfachsten in der Blacklist definieren, ganz ohne Regex (geht auch schneller). Und für die Suche  bietet sich das Suchfeld im Filter an für Thema ODER Titel, das Thema lässt sich im Filterpanel definieren, sofern es überhaupt in der Filmliste vorhanden ist, und in den Checkboxen lassen sich auch einige Ausschlüsse definieren.
