### ISSUE TITLE
Das Herunterladen ist nicht die bestmögliche Qualität

### ISSUE THREAD

**Issue by mogol07** [mediathekview/MediathekView#688]
Ich habe festgestellt, dass der Downloads (mit Abo) nicht die bestmögliche Qualität bietet.
Ich wähle Höchste/Hoch und lade 1280x720 herunter, aber auf der Website ist 1920x1080 verfügbar. 
yt-dlp ist FullHD heruntergeladen.

Serien ist https://www.zdf.de/serien/der-staatsanwalt/im-totenforst-100.html
MediathekView ist 13.9.1

**Comment by m4tt075** [comment]
Kann ich bestätigen. Gleiche MediathekView Version (13.9.1.). Andere Serie. Gleiche Erfahrung.

**Comment by dadidadit** [comment]
Vorschlag: [Anleitung im Forum](https://forum.mediathekview.de/topic/5085/zdf-und-3sat-teilweise-ohne-hd/7)

1280 x 720 ändern in 3360k_p36v17.mp4 
Falls vorhanden:
1920 x 1080 ändern in 6628k_p61v17.mp4

**Comment by pidoubleyou** [comment]
ist durch verschiedene Anpassungen in MServer bereits behoben
