### ISSUE TITLE
Nightly 14 : Fehlerhafte ffmpeg.exe enthalten

### ISSUE THREAD

**Issue by dadidadit** [mediathekview/MediathekView#689]
Im Bin-Verzeichnis in der Windows-Version residiert eine 134 Byte große ffmpeg.exe mit folgendem Inhalt: 
###
version https://git-lfs.github.com/spec/v1
oid sha256:0557f26bb233a46339cd54c18887eb115cafec8d22ff1f67ac2681ed3a4f5e3f
size  121831424
###

Damit funktioniert kein Speichern aus einer .m3u8-Datei. Mit der passenden 121.831.424 Byte großen ffmpeg.exe, die bisher in der 64-Bit-Version 13.9.x verwendet wird schon.

**Comment by alex1702** [comment]
Teste morgen das neuste Nightly bitte noch mal.

**Comment by dadidadit** [comment]
Das mache ich doch glatt ! :+1:

**Comment by dadidadit** [comment]
Die Aktualisierung ist erfolgreich. Danke
