### ISSUE TITLE
Filter vergisst Sender-Auswahl

### ISSUE THREAD

**Issue by nanofish** [mediathekview/MediathekView#690]
Wenn ich einen Filter anpasse, werden Änderungen sofort übernommen. Nur die Sender-Auswahl ist immer wieder leer.

**Comment by dadidadit** [comment]
[Das hängt wohl damit](https://github.com/mediathekview/MediathekView/issues/551) zusammen. Das Speichern von Thema und Filter ist immer noch "In Bearbeitung"

**Comment by nanofish** [comment]
Duplicate of https://github.com/mediathekview/MediathekView/issues/551
