### ISSUE TITLE
Mediathekview.de down!?

### ISSUE THREAD

**Issue by Skeeve** [mediathekview/MediathekView#691]
Gestern festgestellt, dass Mediathekview nicht startet.

<img width="540" alt="image" src="https://user-images.githubusercontent.com/725404/220260542-b085eec4-1bd6-4051-ae1c-3232e32035b2.png">

**Comment by derreisende77** [comment]
Ja das ist bekannt, @alex1702 arbeitet daran.

**Comment by Skeeve** [comment]
Danke!

**Comment by alex1702** [comment]
Ist behoben.
