### ISSUE TITLE
[Enhancement] Option to start MV in Download tab

### ISSUE THREAD

**Issue by ushuc** [mediathekview/MediathekView#692]
When starting MV then it automatically shows the "Filme" tab.
There should be a setting somewhere in the preferences that makes MV start in the "Downloads" tab. It is this Download tab where I always go to see the movies that really interest me, because in there only the movies of my "Abos" appear.

**Comment by derreisende77** [comment]
MV will save the selected tab on exit and restore it on start.

**Comment by derreisende77** [comment]
off by default, can be configured in settings dialog.
