### ISSUE TITLE
[Enhancement] Add "Play URL" button in the list view.

### ISSUE THREAD

**Issue by ushuc** [mediathekview/MediathekView#694]
In the Download tab there are the two buttons "Download" and "Delete" (see screenshot with red marked area).
It would be great to have a third button there "Play URL", because most of the time I don't download the movies, instead I stream them. To stream the movies, I have to select "Play URL" from the right click context menu.
Please add an option to MV to show a "Play URL" button directly in the list next to the other two buttons. (Users could also be able to customize which of the three buttons they want to appear there, all of them or only a custom selection.)

![grafik](https://user-images.githubusercontent.com/109863013/234387996-9b416884-1186-4977-96e7-834742d0fed9.png)

**Comment by derreisende77** [comment]
You can stream directly from film tab. Tab Downloads is primarily for downloading items therefore a play button doesnt make sense here and is in fact redundant functionality.
Similar functionality is available via "Merkliste verwalten". There you don't store downloads but bookmarks to the film entries and you have option to either download or play the entry.
