### ISSUE TITLE
[Enhancement] Play button in download tab toolbar with double functionality: If film is not downloaded then play/stream URL; if film is downloaded, then play file

### ISSUE THREAD

**Issue by ushuc** [mediathekview/MediathekView#696]
In the Download tab there is already a play button in the toolbar. When a film is downloaded, this button of course starts playing the movie file. But when a film is not yet downloaded, this button has no function and only produces an error message telling that the film is not yet downloaded.
Maybe you could make this play button have a double functionality: If film is not downloaded then play/stream URL; if film is downloaded, then play file.

**Comment by derreisende77** [comment]
In the download tab the description of the button is wrong. The menu item always was "Gespeicherten Film abspielen" and the toolbar button does actually call the specific funtion. However the toolbar action description missed the part "Gespeicherten". It was never meant to start a download of play a film. Therefore I will fix the description in MV14+ version but will not implement your desired function as this would completely change the behaviour of a long existing function.

However in a future UI revamp this logic should change both in film and download tab and I put it on my TODO list. 

When the text change will come into the next update this issue will be closed.
