### ISSUE TITLE
Feature-Anfrage: Rai Südtirol hinzufügen

### ISSUE THREAD

**Issue by Ottaviocr** [mediathekview/MediathekView#703]
Ich würde gerne sehen, dass der Sender "[Rai Südtirol](http://raisudtirol.rai.it/de/index.php)" zur Mediathekview hinzugefügt wird.

Mit "[yt-dlp](https://github.com/yt-dlp/yt-dlp)" kann man bereits die einzelnen Fernsehprogramme herunterladen, daher sollte es meiner Meinung nach nicht allzu schwierig sein, die URL zu extrahieren und sie der Mediathekview hinzuzufügen.

Z.B:

```
$ yt-dlp -F https://www.rainews.it/tgr/tagesschau/notiziari/video/2023/06/Tagesschau---27062023-2210-777fda5f-37dc-41b6-974b-ef1e5144c9e7.html
[RaiNews] Extracting URL: https://www.rainews.it/tgr/tagesschau/notiziari/video/2023/06/Tagesschau---27062023-2210-777fda5f...4b-ef1e5144c9e7.html
[RaiNews] 777fda5f-37dc-41b6-974b-ef1e5144c9e7: Downloading webpage
[RaiNews] 777fda5f-37dc-41b6-974b-ef1e5144c9e7: Downloading XML metadata
[RaiNews] 777fda5f-37dc-41b6-974b-ef1e5144c9e7: Downloading m3u8 information
[info] Available formats for 777fda5f-37dc-41b6-974b-ef1e5144c9e7:
ID         EXT RESOLUTION │   FILESIZE   TBR PROTO │ VCODEC  ACODEC
────────────────────────────────────────────────────────────────────
hls-1800   mp4 1024x576   │ ~282.20MiB 1758k m3u8  │ unknown unknown
https-1700 mp4 1024x576   │ ≈282.20MiB 1758k https │ unknown unknown
```

**Comment by derreisende77** [comment]
Das Issue ist für das falsche Programm erstellt worden, MServer wäre die richtige Adresse gewesen. 

Derzeit besteht von unserer Seite wenig Interesse, weitere Sender aufzunehmen. Erst wenn die anderen Senderbaustellen wie z.B. ARTE vollständig behoben sind kann man darüber nachdenken. Bis dahin nein.
