### ISSUE TITLE
debian-paket funzt nicht richtig

### ISSUE THREAD

**Issue by ossilator** [mediathekview/MediathekView#705]
das frische 14.0-er debian-paket installiert - so weit so gut.
führe ich nun /opt/MediathekView/MediathekView als normaler user aus passiert ... gar nichts - er beendet sich prompt ohne irgendeine meldung.
probeweise habe ich das dann als root probiert, und das geht dann auch tatsächlich. das dürfte aber wohl kaum im sinne des erfinders sein.

**Comment by codingPF** [comment]
Hast du mal im Forum gefragt? Ich meine dort gibt es viele Debian User…

https://forum.mediathekview.de/

**Comment by ossilator** [comment]
nö, und ich betrachte es auch nicht als meine aufgabe, das zu debuggen. ich habe es jetzt als normaler user aus dem tar.gz ins homedir installiert, was erwartungsgemäß funktioniert. kommt mit dem bonus daher, daß das nächste update aus der app heraus auch tatsächlich funktionieren sollte, wenn die notification kommt (jup, das ist ein separater bug, der mit packaging zusammenhängt).

im übrigen kam nach der neuinstallation als normaler user die meldung, es würde bereits ein MV-prozess laufen. vlt. war dieser untote auch ursächlich für die "stillen" exits zuvor.

**Comment by vitusson** [comment]
PEBKAC aber noch rumpampen. Köstlich…
*plonk*

**Comment by DaDirnbocher** [comment]
> das frische 14.0-er debian-paket installiert - so weit so gut.

ich auch.

> führe ich nun /opt/MediathekView/MediathekView als normaler user aus passiert ... gar nichts - er beendet sich prompt ohne irgendeine meldung.

kann ich nicht bestätigen, klappt hier wunderbar.. liegt wohl an irgendetwas in deinem system.

**Comment by ossilator** [comment]
> liegt wohl an irgendetwas in deinem system.

das kann schon sein, aber daß er sich wortlos verabschiedet ist trotzdem ein bug.

ich rate einfach mal drauf los, weil ich mich da an was erinnere: er versucht error.log im install-verzeichnis zu schreiben (aus dem ich ihn gestartet habe), das geht aber logischerweise nicht. den "double-fault" überlebt er nicht. wenn das stimmt, wären das zwei bugs: suboptimale location für den log bei eingeschränkten rechten, und suboptimaler umgang mit fehlern beim versuch zu loggen.

**Comment by DaDirnbocher** [comment]
> ich rate einfach mal drauf los,

Ist sicher die optimale Strategie, damit Du eine Lösung für Dein Problem bekommst.

**Comment by derreisende77** [comment]
error.log wird nun als mv_error.log ins user home dir geschrieben und nicht mehr am Installationsort. Ist in der nächsten Version drin.

**Comment by derreisende77** [comment]
@ossilator Könntest Du dir ab morgen ggf. das nächste nightly anschauen ob es das problem mit dem log behebt? "Eigentlich" sollte der launcher gar keine logs in irgendeinem Verzeichnis ablegen...

**Comment by ossilator** [comment]
jo, ich probiere mal. ich hoffe, ich schaffe es, den ursprünglichen trigger zu reproduzieren.

**Comment by ossilator** [comment]
so ... hat leider nicht so richtig funktioniert:
```
java.io.FileNotFoundException: log file directory '/opt/MediathekView/~' doesn't exist.
        at com.exe4j.runtime.LauncherEngine.checkRedirectionFile(LauncherEngine.java:196)
        at com.exe4j.runtime.LauncherEngine.doRedirection(LauncherEngine.java:179)
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:59)
        at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:71)
        at install4j.mediathek.Main_MediathekView.main(Unknown Source)
```
hochgefahren ist er aber trotzdem und "labert" auf der konsole.

das ursprüngliche wortlose verabschieden bleibt aber weiterhin bestehen, wenn ein MV-prozess schon läuft. das wäre ja an sich nicht verwunderlich, wenn a) der alte prozess in den vordergrund poppen würde (wovon nix zu sehen ist) und b) ich nicht diese "läuft schon"-meldung bekommen würde, wenn ich die nicht-debianisierte version starte.

wie der untote prozess das letzte mal entstanden ist, kann ich jetzt nicht nachvollziehen - ich dachte, das könnte ein resultat des drüberinstallierens während die alte version noch lief gewesen sein, aber das war's nicht. :man_shrugging:

**Comment by derreisende77** [comment]
@ossilator Ich befürchte da werde ich nichts ändern können, der Fehler kommt aus install4j. Ich kann da höchstens einen bug report aufmachen da auch die Konfigurationsmechanismen für das error log offenbar nicht funktionieren.

**Comment by ossilator** [comment]
> Ich kann da höchstens einen bug report aufmachen

das wäre eine angemessene lösung, danke. poste bitte den link als referenz.

**Comment by ossilator** [comment]
hast du [das](https://www.ej-technologies.com/support/bugReport) gemacht?
(zum verlinken wird's wohl nix geben ...)
