### ISSUE TITLE
Can MediathekView use aria2c instead of ffmpeg to download files?

### ISSUE THREAD

**Issue by Ottaviocr** [mediathekview/MediathekView#706]
I wonder if aria2c can replace ffmpeg entirely. Has anybody tried? What would be the configuration? I have problems downloading some programs from MV but i can download them fine using yt-dlp and aria2c as backend.

**Comment by vitusson** [comment]
Apples and oranges…
I'm doing all my downloads via aria2c, except when it comes to m3u8.
aria2c is a download utility while ffmpeg deals with converting videos. You cant use aria2c for getting a video out of a m3u URL. And yt-dlp relies on ffmpeg to do so too.

**Comment by Ottaviocr** [comment]
Ok. It makes sense. Thanks.
