### ISSUE TITLE
MV 14.0: Blacklist und Lucene Indizierung vertragen sich nicht

### ISSUE THREAD

**Issue by MuenchenSued** [mediathekview/MediathekView#707]
Wenn beim Indizieren für die Lucene-Suche die Blacklist eingeschaltet ist (beispielsweise direkt beim Start oder beim Neuladen einer Filmliste), dann werden diese Filme auch nicht angezeigt, wenn die Blacklist ausgeschaltet wird. Momentan muss man dafür sorgen, dass die Blacklist ausgeschaltet ist, bevor die Indizierung durchgeführt wird, was beispielsweise einen Neustart der Anwendung mit abgeschalteter Blacklist erforderlich macht.
Schaltet man die Blacklist während der Indizierung ab, gibt es eine Fehlermeldung und das Programm wird beendet.

Die Indizierung sollte auf allen Filmen inkl. Blacklist durchgeführt werden, damit im Betrieb schnell zwischen mit/ohne Blacklist umgeschaltet werden kann.

**Comment by dadidadit** [comment]
Das Verhalten kann ich unter Windows 10 nachvollziehen und teilweise bestätigen mit einer Ausnahme:

> Schaltet man die Blacklist `während` der Indizierung ab, gibt es eine Fehlermeldung und das Programm wird beendet.

Das passiert bei mir nur, wenn in den Einstellungen unter > Blacklist Bearbeiten die Option` Im Tab Filme einschalten` aktiviert ist. Nur dann erscheint eine Fehlermeldung und nach Bestätigung mit OK wird das Programm beendet. Ist diese Option deaktiviert, bekomme ich ohne Fehlermeldung eine leere Filmliste angezeigt mit voller Anzahl vorhanderner Filme und 0 angezeigte Filme  und muss das Programm händisch beenden.

**Comment by MuenchenSued** [comment]
Ich denke, hier passt etwas generell noch nicht. Wenn ich MV neu starte und die Blacklist ist **nicht** eingeschaltet, dann erscheint in der Statusleiste trotzdem zuerst "Blacklist anwenden" und dann "Indiziere Filme". Den genauen Ablauf muss man sich vermutlich genauer ansehen, jedoch sollte die Indizierung über alles gehen und die Blacklist nur für Anzeige und Abos verwendet werden.

**Comment by dadidadit** [comment]
Mit der neuen nightly 14.0.1 habe ich festgestellt, dass  ein- und ausschalten auch ohne  den o. a. Workaround funktioniert, wenn die 3 Optionen unter `Blacklist bearbeiten` ausgeschaltet sind. Dann kann nach dem MV-Start die Blacklist eingeschaltet (aktiviert) werden und die Option `Im Tab Filme einschalten` wird automatisch aktiv, die ist nach dem Beenden des Programms wieder inaktiv. Mit Abos habe ich nichts ausprobiert, da ich keine Abos verwende.

**Comment by MuenchenSued** [comment]
Da ich die Filmliste manuell lade, wird danach jedes Mal neu indiziert und in 14.0.1 wurde diesbezüglich noch nichts geändert..

**Comment by derreisende77** [comment]
> Wenn beim Indizieren für die Lucene-Suche die Blacklist eingeschaltet ist (beispielsweise direkt beim Start oder beim Neuladen einer Filmliste), dann werden diese Filme auch nicht angezeigt, wenn die Blacklist ausgeschaltet wird. Momentan muss man dafür sorgen, dass die Blacklist ausgeschaltet ist, bevor die Indizierung durchgeführt wird, was beispielsweise einen Neustart der Anwendung mit abgeschalteter Blacklist erforderlich macht. Schaltet man die Blacklist während der Indizierung ab, gibt es eine Fehlermeldung und das Programm wird beendet.

Die Blacklist darf während der Indizierung natürlich nicht abgeschaltet werden, da sich dann beide Anteile ins Gehege kommen. Das habe ich in 14.0.1 gefixt, man kann während die Indizierung läuft nicht mehr die Blacklist manipulieren.
> 
> Die Indizierung sollte auf allen Filmen inkl. Blacklist durchgeführt werden, damit im Betrieb schnell zwischen mit/ohne Blacklist umgeschaltet werden kann.

Das funktioniert so nicht. Die Suche (alt wie neu) arbeitet über den Ergebnissen der Filmliste **nach** der Blacklist-Filterung. Das einzige was hier als bug derzeit aus meiner Sicht übrig bleibt ist die Tatsache, dass nach Modifikation des Blackliststatus keine Reindizierung durchgeführt wird. Das schaue ich mir für die Zukunft an aber ich glaube das dauert etwas länger einzubauen.

**Comment by derreisende77** [comment]
> Ich denke, hier passt etwas generell noch nicht. Wenn ich MV neu starte und die Blacklist ist **nicht** eingeschaltet, dann erscheint in der Statusleiste trotzdem zuerst "Blacklist anwenden" und dann "Indiziere Filme". Den genauen Ablauf muss man sich vermutlich genauer ansehen, jedoch sollte die Indizierung über alles gehen und die Blacklist nur für Anzeige und Abos verwendet werden.

Es ist völlig normal dass "Blacklist anwenden" erscheint egal ob aus oder an, das Programm muss dennoch Funktionen ausführen in diesem Schritt. Und nein, die Indizierung sollte nicht über alles gehen da es bei Suchabfragen danach keine Blacklistfilterung gibt. Dies entspricht exakt dem bisherigen Verhalten der Suche. Um das zu ändern ist ein komplett neuer Client notwendig.
