### ISSUE TITLE
Problem mit MediathekView 14 (.deb) und Symlink

### ISSUE THREAD

**Issue by msamesch** [mediathekview/MediathekView#709]
Hi,

das Programm startete nicht und zeigte im Terminal auch keine Fehlermeldung.

Die Ursache war, dass /opt nur ein Link war (hatte bisher funktioniert). Nachdem ich das geändert hatte, funktioniert es wieder.

System: Devuan Chimaera, Icewm

Vielleicht hilfts jemand.

BTW, danke an die Entwickler!

**Comment by derreisende77** [comment]
Also kein Problem an sich mit MV sondern eher mit dem System. Aber good to know :) Ich schließe das issue, es bleibt ja dokumentiert.
