### ISSUE TITLE
Umbenennen eines Sets

### ISSUE THREAD

**Issue by DaDirnbocher** [mediathekview/MediathekView#710]
Wenn ich mit MV14 unter Linux Mint 21.2 versuche ein Set umzubenennen, wird nach jedem Buchstaben das Set umbenannt und der Fokus wechselt links davon in die Liste der Sets. D.h. ich muss für den nächsten Buchstaben wieder in das Eingabefeld wechseln.

Mache ich dasselbe mit 13.9 unter Windows 10, wird zwar auch nach jedem Buchstaben umbenannt, aber der Fokus bleibt in dem Feld und ich kann weitertippen.

Ob das an 14 vs 13.9 oder an Linux vs. Win oder an meinem Linux MInt liegt, kann ich nicht sagen. 

So oft benenne ich Sets auch nicht um - insofern ists nicht so dringend. Ich wollts nur erwähnt haben.

**Comment by dadidadit** [comment]
> Wenn ich mit MV14 unter Linux Mint 21.2 versuche ein Set umzubenennen, wird nach jedem Buchstaben das Set umbenannt und der Fokus wechselt links davon in die Liste der Sets. D.h. ich muss für den nächsten Buchstaben wieder in das Eingabefeld wechseln.
> 

So ist das unter Windows 10 in MV14 auch, das Verhalten hat sich also gegenüber 13.9.1 unter Windows geändert.

**Comment by derreisende77** [comment]
wird mit #741 gefixt, daher schließe ich das hier schon vorab.
