### ISSUE TITLE
MV 14: Link zur Webseite lässt sich nicht mehr kopieren

### ISSUE THREAD

**Issue by MuenchenSued** [mediathekview/MediathekView#711]
Der Link unterhalb der Beschreibung, mit dem man zur Webseite der Sendung kommt, lässt sich nicht mehr kopieren, ein Kontext-Menü wie es früher vorhanden war, wurde wohl entfernt. Ich nutze diese Funktion recht häufig und muss nun zuerst den Link anklicken, um ihn dann aus der Browser-Adressleiste wieder heraus zu kopieren.

Bitte das Kontextmenü 
![256965104-689c8f1d-d040-44fc-836d-d5faea71c957](https://github.com/mediathekview/MediathekView/assets/71550657/ff90e97c-edae-47f6-a7cd-8e036fcc20f7)
wieder einbauen.

**Comment by derreisende77** [comment]
Ist im nächsten Nightly bzw. in 14.0.1 wieder dabei.
