### ISSUE TITLE
Einstellungen -> Allgemein: Kein Textumbruch beim Verkleinern des Fensters

### ISSUE THREAD

**Issue by styroll** [mediathekview/MediathekView#715]
Es handelt sich bei dieser Issue bloss um einen Schönheitsfehler: Grundsätzlich wird in den Einstellungen nirgends Text beim Verändern der Fenstergrösse umgebrochen, d.h. es liegt kein Fliesstext vor, sondern es scheint harte Zeilenumbrüche zu geben, was z.B. hier ersichtlich ist:

<img width="1161" alt="Screenshot_ 2023-08-11 at 00 47 54" src="https://github.com/mediathekview/MediathekView/assets/24810728/4fd30d4a-1ba5-40a0-9312-7032727d5114">

Der Text, der im Reiter "Allgemein" mit MV 14 im Bereich "Moderne Suche" neu dazugekommen ist, scheint nun allerdings Fliesstext zu sein, zumindest wenn man das Fenster vergrössert:

<img width="1306" alt="Screenshot_ 2023-08-11 at 00 19 43" src="https://github.com/mediathekview/MediathekView/assets/24810728/54fd5751-8422-4c43-b12a-0d917972eec0">

Wenn man dann allerdings das Fenster verkleinert, liegt kein Fliesstext mehr vor, sondern der Text wird abgeschnitten:

<img width="1063" alt="Screenshot_ 2023-08-11 at 00 20 21" src="https://github.com/mediathekview/MediathekView/assets/24810728/0a0d123b-d8c3-40dd-ba46-a2e197d05db9">

Evtl. kann man das Verhalten des Texts korrigieren oder harte Zeilenumbrüche vornehmen.

**Comment by derreisende77** [comment]
Das bei den Pfadangaben liegt am verwendeten Layoutmanager, das kann ich mir ansehen.

Der Fließtext bei moderne Suche verkleinert sich leider nicht mehr wenn der geöffnete Dialog vergrößert und danach verkleinert wird. Das liegt an der Art wie Xaver damals den Dialog gestaltet hat. Er wird ja auch nicht wirklich abgeschnitten, es erscheint die unten sichtbare Scrollbar mit der man dort hin scrollen kann.
Wird der Dialog geschlossen und wieder geöffnet passt sich das control wieder richtig an die Dialoggröße an. 
Das kann ich leider so erst mal nicht korrigieren.

**Comment by styroll** [comment]
Danke für die Erklärung.

>@derreisende77 sagte: Wird der Dialog geschlossen und wieder geöffnet passt sich das control wieder richtig an die Dialoggröße an.

Aber nur nach einem Neustart von MV (v14.0)…

**Comment by derreisende77** [comment]
Da hast Du recht, aber das werde ich vorerst nicht fixen. Dann müsste ich den Dialog komplett neu machen. Das ist meines Erachtens derzeit den Aufwand nicht wert.
