### ISSUE TITLE
Umschalten Dunkel/Hellmodus  aktualisiert nicht alle Menupunkte im right-click  menu

### ISSUE THREAD

**Issue by j4reporting** [mediathekview/MediathekView#717]
betroffene Versionen:  MV14.0.0 / aktuelle MV14.0.1 nightly  

Wenn man von Hell in den Dunkelmodus wechselt, dann werden nicht alle Menupunkte im Rechtsklickmenü (Filmliste ) in der richtigen Farbe angezeigt. Dies  funktioniert erst nach einem Neustart der Anwendung. 
Gleiches Spiel wenn man von Dunkel in den Hellmodus wechselt.

![MediathekView_dark](https://github.com/mediathekview/MediathekView/assets/45177907/93d3f8bb-094b-4505-9e4d-b83357e39b61)
![MediathekView_light](https://github.com/mediathekview/MediathekView/assets/45177907/6c620a71-18b9-409e-b0fe-2435a7f48055)

**Comment by derreisende77** [comment]
Ja, ist auch im CHANGELOG dokumentiert das noch nicht alles den dark mode unterstützt. Wird in zukünftigen Versionen behoben.
