### ISSUE TITLE
Fehlende JVM Parameter erkannt

### ISSUE THREAD

**Issue by toby63** [mediathekview/MediathekView#719]
Beim Start von Mediathekview erscheint folgende Fehlermeldung:

```
Bitte stellen Sie sicher dass folgende Paramter übergeben werden:

- -XX:+UseShenandoahGC
- -XX:ShenandoagGCHeuristics=compact
- -XX:+UseStringDeduplication
- -XX:MaxRAMPercentage=XX.X
- --add-opens=java.desktop/sun.awt.X11=ALL-UNNAMED

-Xmx sollte nicht mehr genutzt werden!
```

Version: 14.0.0. (kompiliert)
OS: Manjaro Linux

**Comment by dadidadit** [comment]
> Bitte stellen Sie sicher dass folgende Paramter übergeben werden:
< .....

Und, hast du sichergestellt, dass die entsprechenden Parameter auch vorhanden sind bzw. die Xmx..-Parameter entfernt wurden?

In den fertigen angebotenen Mediathekview-Paketen für Linux tritt dieser Fehler sicher nicht auf, denn darin sind die erforderlichen Parameter  und die benötigte Java-Version 20 enthalten.

https://mediathekview.de/download/

**Comment by toby63** [comment]
@dadidadit Danke für den Hinweis.

Da bisher garkeine Parameter in den jeweiligen Start-Dateien übergeben wurden, ging ich davon aus, dass das irgenteine Code-Sache oder sogar einfach ein Bug ist.
Allerdings habe ich tatsächlich im offiziellen Appimage entsprechende Passagen (https://github.com/mediathekview/MediathekView/blob/master/scripte/appimage.sh#L88) gefunden.

Dann werde ich das wohl anpassen müssen.

**Comment by derreisende77** [comment]
Nun das sehe ich etwas anders. Der normale Nutzer wird nicht durch den Dialog tangiert, die Startparameter sind für jede Plattform in den install4j Dateien hinterlegt. Das CHANGELOG dient auch primär der Information der „normalen“ Nutzer.
Letztendlich trifft es nur Wagemutige die die Software selbst bauen wollen/müssen. Da diese i.d.R. Zugriff auf den kompletten Quellcode haben können diese in den .install4j Ordnern auch die aktuell zu nutzenden Parameter je nach Plattform einsehen. 
Und da wir/ich die Maintainer der Pakete sind werden Aktualisierungen der Parameter ja auch hier im git dokumentiert.
