### ISSUE TITLE
dark mode: Font color in download list is hardly readable

### ISSUE THREAD

**Issue by Little-Ben** [mediathekview/MediathekView#720]
Hello, 

great work and thank you for giving us a dark mode :-)
Is there a possibility to modify the font color of downloads?
The light grey on colored background is hardly readable. 
I have not found a possibility to change it in preferences color options.

Of course, this should be separate of the color in the rest of the program, e.g. Filmliste is fine as it is.

![Downloads](https://github.com/mediathekview/MediathekView/assets/7840648/9949e218-ba86-4c10-8a8a-3e10a0466a6b)
![Filmliste](https://github.com/mediathekview/MediathekView/assets/7840648/05d93e06-118b-4881-8875-cea27e156b47)

**Comment by dadidadit** [comment]
Of course it is possible to change the preferred color.

Click on [F4]  (a shorcut for  "Datei  > Einstellungen") > Farben > **Color**-line (**not** on the text!)  you wish to change ....

**Comment by Little-Ben** [comment]
I do not see a possibility to change the text color in that preferrences dialog/tab.
![2023-09-30 18_38_22-Window](https://github.com/mediathekview/MediathekView/assets/7840648/d6e3bb03-fa59-4ce2-a151-284921a420e1)

**Comment by dadidadit** [comment]
Sorry, i have misunderstood you. :-(

As far as i know the text-font color is fixed and dependent by configuration in your used os. 
Exactly more info you can get from developer @derreisende77
