### ISSUE TITLE
Interne Verarbeitung der Filmliste ist viel zu langsam/Optimierung erforderlich

### ISSUE THREAD

**Issue by BugExplorer-Plus** [mediathekview/MediathekView#721]
Die Zeitdauer vom Erscheinen des Hauptfensters bis zur Benutzbarkeit des Programms ist auch dann zu langsam. wenn gar keine neue Filmliste geladen wird - bei mir ca. 55 Sekunden bei aktueller Hardware (intel i5-12600/32 GB).
Keine Ahnung woran das liegen könnte - wurden bereits Versuche zur Verbesserung unternommen oder muss dies bei den verwendeten Methoden und einer Filmliste von ca. 700.000 Einträgen akzeptiert werden?

**Comment by dadidadit** [comment]
Die Einträge in der Filmliste werden beim `Starten des Programms` indexiert, auch wenn keine neue Filmliste geladen wurde. Wie lange das dauert, ist abhängig von der Programmversion, des Inhalts einer evtl. Blacklist, der Anzahl an Einträgen und der Einstellungen der vorhanden Filter usw. 
Kleiner wird die Filmliste übrigens nicht, da kommt noch Einiges auf uns alle zu.

**Comment by derreisende77** [comment]
Also bei mir dauert das Starten auf einem 2020er MacBook Air knapp 13 Sekunden, auf einem AMD Ryzen 4700H mit Win11 ca. 15 Sekunden. Beide Systeme haben ca 200k gesehene Filme und knapp 20 Abos die verarbeitet werden zzgl. ein 400 Einträge umfassenden Blacklist.
Das Programm wird kontinuierlich darauf optimiert möglichst schnell zu laden. Aber irgendeinen Tod muss man sterben wenn man möglichst viel Daten lokal verarbeiten will.
Was massive Auswirkung auf die Performance hat: Die Verwendung einer HDD anstatt einer SSD.

**Comment by BugExplorer-Plus** [comment]
Eine HDD ist nicht im Spiel - eine kurze Rechnung ergibt Plausibilität: 3,5 * 200k = 700k, 13 Sekunden * 3,5 =45,5

**Comment by derreisende77** [comment]
Ich glaube du hast einen Denkfehler. Meine 200k gesehene Filme werden beim Start dynamisch aus den 700k filmen gefiltert und nicht angezeigt. Die rechner haben dennoch Stand gestern getestet die 700k filme in 13-15 sekunden verarbeitet. Selbst in einer VM dauert das bei mir nicht annäherungsweise 56 Sekunden. Beide Systeme haben 16GB RAM und windows ist in der regel 20-30% langsamer als macOS bzw linux. Aber das ist ein bekanntes MS phänomen.

**Comment by derreisende77** [comment]
Ein Problem beim Start können aber viele Einträge in der Downloadliste sein. Diese werden beim Start aktualisiert und fragen die Dateigröße im Netz ab. Dann sieht es so aus als ob das Programm hängt

**Comment by BugExplorer-Plus** [comment]
Danke für die Antworten - die Downloadliste ist komplett leer - da wir uns aber jetzt Richtung Troubleshooting bewegen, sollte ich diesen Thread wahrscheinlich besser im Forum posten!?

**Comment by derreisende77** [comment]
Ja
