### ISSUE TITLE
Beim Start Auswahl anbieten: Filmliste neu laden bzw. mit vorhandener Filmliste starten

### ISSUE THREAD

**Issue by ruchuf** [mediathekview/MediathekView#722]
Es gibt zur Zeit zwei Möglichkeiten, die Filmliste zu laden: Automatisch beim Programmstart oder manuell.
Hilfreich wäre aus meiner Sicht eine dritte Option: Beim Start vor dem Laden der lokalen Filmliste zu fragen, ob die vorhandene Filmliste gelesen werden soll, oder doch eine neue aus dem Netz geladen werden soll.

Weiterhin wäre es sinnvoll, beim Laden der Filmliste die jeweils vorige Liste zu sichern und eine Option anzubieten, die vorige Version der lokalen Liste zu laden. Leider kommt es bei knappen Speicher immer mal wieder zu Situationen, dass beim Neuladen der Liste Mediathekview crasht, und die Listendatei defekt ist.

Ich löse dies aktuell durch eine Batchdatei, die jeweils vor dem Programmaufruf die derzeit aktuelle Listendatei kopiert.

Die Möglichkeit jeweils das Delta zwischen zwei Listendateien sehen zu können (nur neue Filme anzeigen) ist essentiell. Dies geht jedoch nach jedem Crash verloren.

**Comment by MuenchenSued** [comment]
Der Automatismus greift "nur", wenn die alte Liste älter als 2 Stunden ist. Zusätzlich gibt es eine automatische Aktualisierung alle 12 Stunden. Letzteres für mich ein Grund, nur noch manuell zu laden.
Verweis: https://forum.mediathekview.de/post/22880

**Comment by ruchuf** [comment]
Genau das mache ich auch. Nur stört mich hier, dass wenn ich neu laden will, ich zunächst das Laden der lokalen Liste abwarten muss, bevor ich dann auf "Neu Laden" klicken kann.
Daher fände ich eine Variante sinnvoll, bei der -nach Programmstart- noch vor dem Laden der Liste gefragt wird, ob die alte lokale oder eine neu geladene Liste verwendet werden soll.

**Comment by alex1702** [comment]
Das nennst du benutzerfreundlich? Tut mir leid, aber mich würde es stören, wenn ich bei jedem Start gefragt werde ob ich die vorhandene Liste verwerfen möchte und eine neue Liste laden möchte. Abgesehen davon, dass du mit der Option mehr Traffik bei uns verursachst.

Ich würde dir empfehlen mal in die Zukunft zu investieren und mehr RAM dir zu besorgen.

**Comment by derreisende77** [comment]
@ruchuf Also den Vorschlag werde ich nicht implementieren. Die lokale Liste ist vorab erforderlich um in der neuen Liste auch die wirklich neuen Filme zu identifizieren. Weiterhin ist Arbeitsspeicher heutzutage kein wirkliches KO-Kriterium mehr und wir haben schon daran gearbeitet den Bedarf deutlich zu reduzieren. MV ist nicht dafür gedacht auf Mini-Systemen zu arbeiten und wir haben uns dafür entschieden hier keine Rücksicht mehr darauf zu nehmen da es den Code unnötig verkompliziert und zu Verzögerungen bei den anderen Usern führt, die in der Mehrzahl den notwendigen RAM zur Verfügung stellen können.
Zumal ich von deinem Vorschlag auch aktiv negativ betroffen wäre und mich die ständige Nachfrage beim manuellen Laden extrem nerven würde.

**Comment by ruchuf** [comment]
@alex1702, @derreisende77:

Was herrscht hier für ein Ton?
Wer von Euch ist von einer OPTION betroffen, die niemand gezwungen wird einzuschalten?
Sachlichkeit wäre in einer technischen Diskussion schon sinnvoll!

**Comment by derreisende77** [comment]
@ruchuf Nimm mal die Spritze aus dem Arm. Bis gerade eben war der Ton von meiner Seite Seite sachlich. Und wie dir ggf entgangen ist herrscht ab hier kein Diskussionsgrund mehr da ich dein issue geschlossen habe mit "wird nicht umgesetzt".
Zumal handelt es sich nicht um eine "technische Diskussion" sondern um eine mögliche Ergänzung des prozeduralen Ablaufs des Programms. 

ICH bin von deiner Option betroffen da ICH auch derjenige bin der dies implementieren würde. Und ich habe dir u.a. geschildert weshalb ich diese Option nicht integrieren werde und auch dass wir zukünftig keine Rücksicht mehr auf schwachbrüstige Systeme nehmen. UND ich habe dir geschildert dass deine "Option" wenn ich sie implementieren würde mich auch extrem stören würde - und nein, es wird sicherlich keine Option zum abschalten der Option geben (Stichwort Komplexität).
Abschließend habe ich dir geschildert dass die vorhandene lokale Liste zwingend erforderlich ist um neue Filme zu entdecken - ansonsten hast Du bei jedem Ladevorgang nur neue Filme. Also ist die Option auch Quatsch.

Nur weil Du meinst dass etwaige Features essentiell (für dich) sind bedeutet dies nicht dass andere das auch so sehen. Es steht dir aber selbstverständlich frei das Programm deinen Wünschen entsprechend anzupassen und wenn Du fertig bist um Aufnahme deiner Änderungen zu bitten. Ich setze es nicht um.

**Comment by dadidadit** [comment]
> Genau das mache ich auch. Nur stört mich hier, dass wenn ich neu laden will, ich zunächst das Laden der lokalen Liste abwarten muss, bevor ich dann auf "Neu Laden" klicken kann.

:Das kannst du ganz einfach und ohne Programm-_Optimierung_ selbst lösen: Erstelle dir eine Batchdatei, in der du VOR dem Aufruf von Mediathekview die **filme.json** im Verzeichnis .mediathek3\Einstellungen löschst und dann die Exe startest.
