### ISSUE TITLE
Die Anwendung hängt sich unter macOS immer wieder auf

### ISSUE THREAD

**Issue by maxweissboeck** [mediathekview/MediathekView#723]
Hier der Dump, vielleicht könnt ihr damit ja etwas anfangen.
Danke für die tolle Arbeit!

[mediathekview-dump.txt.zip](https://github.com/mediathekview/MediathekView/files/13259813/mediathekview-dump.txt.zip)

**Comment by dadidadit** [comment]
Wenn du gleich auf der Homepage im Forum von mediathekvview.de nachgesehen hättest, wärest du schon seit 12 Tagen darüber informiert gewesen, dass es wohl mit dem neue  Mac-OS `zusammenhängt und wi ma dem Fehler begegnen kann.

https://forum.mediathekview.de/topic/5430/macos-sonoma-14-1-update-kann-mediathekview-massiv-beeintr%C3%A4chtigen

**Comment by markuswinter** [comment]
Da es sich auch auf meinem alten MacOS 10.14.6 Mojave und auf 12.6 Monterey auch dauernd aufhängt wär es vielleicht mal an der Zeit den Fehler bei MediathekView zu suchen? Die "Schnappreaktion" alle Fehler von sich zu weisen ist auch nicht hilfreich. Tatsache ist daß die Mac Version von Mediathekview von Version zu Version weniger funktioniert hat - wohlgemerkt auf denselben alten MacOS Versionen (10.12.6 Sierra auf iMac, 10.14.6 auf Mac Pro, 12.6 auf MacBook Air). Die aktuelle Version 14.0.0 ist komplett unbrauchbar. App öffnet, läd Daten, zeigt Datenliste, man klickt auf den Downloads Tab - nix passiert außer daß der Tab ebenfalls das Highlight bekommt. Wie etwas wie ein Tab nicht funktionieren kann (auf 3 verschiedenen Macs mit jeweils anderem System) ist mir ein Rätsel - testet das irgendwer?

**Comment by derreisende77** [comment]
@maxweissboeck Danke für den report aber leider hilft der Auszug nicht weiter, da die Ausgaben der Java VM fehlen :(
MV 14.1 wird diese Woche released und sollte die größten Probleme unter macOS 14 beseitigen.

@markuswinter 10.14 ist seit Oktober 2021 EOL, dein zitiertes 10.12 seit 2019. Glaubst Du ernsthaft ich habe hier eine Farm von asbach alten Macs rumstehen die meine Bude vollheizen um sicherzustellen dass MV auf jeder dahergelaufenen Konfiguration läuft? Wenn Du das Forum verfolgen würdest wäre dir aufgefallen dass ich nun ein M1 MacBook Air habe und auf diesem entwickele. Und ja, ich nutze meine Software auch und teste sie.  Desweiteren gibt es dutzende andere User die die Software erfolgreich auf ihren alten Maschinen am laufen haben.

Rumzunölen ohne irgendwelche Anhaltspunkte was nicht geht finde ich immer Klasse....

Und ein kleiner Tipp für das Upgrade deiner alten Maschinen: Seit MV 13.9.0 ist (dokumentiert) die Minimum macOS-Version macOS 10.14...
Wenn Du es weiterhin auf älteren macOS Versionen laufen lassen willst, bedanke dich bei Oracle und kaufe bei denen sündhaft teuren Support für die JDK. Die sind dafür verantwortlich wenn das Java auf den alten Kisten nicht mehr richtig will, nicht ich.
Wenn mein altes MacBook pro mit Intel CPU von 2013 den Geist aufgibt wird es dann wohl auch keine getestete Intel Version von MV mehr geben.

**Comment by markuswinter** [comment]
Danke für die Antwort, aber es ist dir schon klar daß du dir selbst widersprichst? "Minimumversion ist 10.14" - ja, und ich hab 10.14.6 auf meinem Mac Pro und 12.6 auf meinem MBA … BEIDE erfüllen also die Anforderungen. Die Probleme auf MacOS X 10.12 bezogen sich auf ÄLTERE Mediathek-Versionen und daß Mediathek von Version zu Version benutzerunfreundlicher und instabiler wurde. Genauer lesen hätte geholfen aber dann wird der Bote historisch gesehen ja immer gern erschossen bevor man mal nachdenkt … 

Mal davon abgesehen bin ich zwar kein professioneller Programmierer, aber ich programmier seit 1983 schon nebenbei für die Arbeit und Zuhause … und wie schwer ist es denn die Systemversion zu testen? Antwort: gar nich schwer. Kann sogar ich. Aber das fällt ja unter Bedienerfreundlichkeit (auf die ICH beim Programmieren immer großen Wert gelegt hab) und mit der happerts gewaltig … 

Ein Berkannter der Professioneller Programmierer ist und seine eigene Firma mit einem halben Dutzend Angestellten hat schwärmt mir immer vor wie stabil Java wäre. Ich hab ihn mal auf dieses Projekt aufmerksam gemacht - vielleicht hat er ja mal Lust beizutragen nachdem ich ihm erklärt hat daß es sein Predigen über Java schlecht aussehen lässt …

**Comment by dadidadit** [comment]
@markuswinter 
> Genauer lesen hätte geholfen 

Dann fass dich mal an die eigene Nase und lies mal, anstatt hier rumzulabern und zu nölen..
