### ISSUE TITLE
Fenster "Filminformation": Grösse änderbar machen und selbe speichern

### ISSUE THREAD

**Issue by styroll** [mediathekview/MediathekView#727]
[Im Forum](https://forum.mediathekview.de/post/35628) hat ein User vorgeschlagen, die Fenstergrösse des Fensters "Filminformation" veränderbar machen zu können, damit man nicht – infolge des fallweise nicht vollständig sichtbaren Beschreibungstexts – vertikal scrollen muss.

Da der Beschreibungstext – maximal – immer gleich lang ist (er wird ja beschnitten ab einer bestimmten Länge), könnte man eine der folgenden Vorschläge implementieren (von schlechter zu besser aus User-Perspektive):

1. Fenster fix vertikal um "4 Zeilen" (Äquivalente) länger machen, sodass selbst bei zweizeiligem Titel und Beschreibungstext maximaler Länge bei den meisten Einträgen in der Liste nicht gescrollt werden muss.
2. Fenster fix breiter machen, sodass selbst bei Beschreibungstext maximaler Länge bei den meisten Einträgen in der Liste nie gescrollt werden muss.
3. Fenster in der Grundeinstellung so lassen, aber das Fenster in Länge und Breite veränderbar machen, wobei diese Einstellungen gespeichert werden.

**Comment by derreisende77** [comment]
Option 3 wurde umgesetzt.
