### ISSUE TITLE
Start mit IDE mit Linux -> Warnmeldung falsche Parameter

### ISSUE THREAD

**Issue by Kasperx** [mediathekview/MediathekView#731]
Hi
Beim Start des Programms mit Java 21 LTS mit Ubuntu kommt die Warnmeldung mit falschen Parametern aus der Klasse "src/main/java/mediathek/Main.java" Zeile 266 bis 334.
Führt diese Warnmeldung zu einem tieferen Zweck oder warnt die nur? Auch mit den korrigierten Parametern erscheint diese Meldung. Was ist also der Sinn dahinter?
![grafik](https://github.com/mediathekview/MediathekView/assets/10506030/60c3b652-451b-4352-bd2c-6dc343815422)

**Comment by derreisende77** [comment]
Wenn die Parameter korrekt sind kommt **keine** Warnung. Ergo hast Du noch einen Fehler drin. Poste mal wie du aufrufst. Und ja die warnung hat einen tieferen Sinn sonst hätte ich keine Zeit verwendet diese zu integrieren.

**Comment by Kasperx** [comment]
Danke für die Antwort.
Der Zweck dieser Warnmeldung ist hier nicht erkennbar, denn auch mit "falschen" Parametern startet das Programm, vermutlich ohne Fehler.
Ich nutze intellij mit Java 21 LTS und keinen Optionen, also Rechtsklick auf "src.main.java.mediathek.Main" -> debug. Dann, nach wenigen Sekunden, kommt die Meldung. Nach "OK" startet das Programm.

**Comment by Kasperx** [comment]
Ist hier die Nutzung von Standardparametern geplant? Denn jede Linuxumgebung wird diese Meldung anzeigen, wenn keine Anpassung passiert. Nicht sehr intuitiv :(

**Comment by alex1702** [comment]
Normale Programmstarts, wenn es als Release raus ist, bekommen diese Meldung nicht.

**Comment by derreisende77** [comment]
@kasperx wer MV selbst compiled und nutzt sollte schon in der Lage sein die Funktion des Programms zu verstehen und ggf wissen wie die regulären von uns erstellten binaries funktionieren. Dort sind keine Geheimnisse versteckt und man kann auch erkennen wie was gestartet wird. "Nicht sehr intuitiv" ist es nur für denjenigen der sich nicht mit der Materie auseinandersetzt und glaubt eine selbstgebaute Version funktioniert besser als die von uns bereitgestellte. 
Eine Vielzahl Deiner Fragen kann im Forum bedeutend besser beantwortet werden, denn es handelt sich hierbei um keine Fehler sondern grundlegende Fragestellungen. Github issues sind zum Melden von Fehlern bestimmt daher schliesse ich das topic erstmal.
