### ISSUE TITLE
MV auf RaspberryPi bauen und starten

### ISSUE THREAD

**Issue by dgottstein** [mediathekview/MediathekView#733]
Hallo,

ich habe [hier](https://forum.mediathekview.de/topic/5533/mv-auf-raspberrypi-bauen-und-starten) schon vor längerer Zeit einen Forumseintrag geschrieben, leider bis jetzt keine Antwort, deshalb versuche ich es hier nochmal.

Ich möchte eine aktuelle Version für armhf auf dem RaspberryPi bauen. MV 14.0.0 wird erfolgreich gebaut und ins Maven Repo installiert, allerdings weiß ich nicht, wie ich MV nun starte.

Folgende Schritte habe ich durchgeführt:
```
cd ~/Downloads
git clone https://github.com/mediathekview/MediathekView.git
git checkout 14.0.0
cd MediathekView
source ~/.sdkman/bin/sdkman-init.sh
sdk use java 20.fx-librca
./mvnw clean install
```

Ausgabe (gekürzt):
```
[INFO] Installing /home/pi/Downloads/MediathekView/target/MediathekView.jar to /home/pi/.m2/repository/de/mediathekview/MediathekView/14.0.0/MediathekView-14.0.0.jar
[INFO] Installing /home/pi/Downloads/MediathekView/pom.xml to /home/pi/.m2/repository/de/mediathekview/MediathekView/14.0.0/MediathekView-14.0.0.pom
[INFO] Installing /home/pi/Downloads/MediathekView/target/MediathekView-sources.jar to /home/pi/.m2/repository/de/mediathekview/MediathekView/14.0.0/MediathekView-14.0.0-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:58 min
[INFO] Finished at: 2024-01-07T11:58:55+01:00
[INFO] ------------------------------------------------------------------------
```

Versuch zu starten:
```
java -jar /home/pi/.m2/repository/de/mediathekview/MediathekView/14.0.0/MediathekView-14.0.0.jar

kein Hauptmanifestattribut, in /home/pi/.m2/repository/de/mediathekview/MediathekView/14.0.0/MediathekView-14.0.0.jar
```

Wie kann ich die gebaute .jar nun starten? Welchen Schritt habe ich vergessen?

Weitere Frage: Welche Schritte wurden bei den experimentellen (leider relativ alten) Builds für armhf durchgeführt, um ein Debian Package (.deb) zu erzeugen?

Grüße

**Comment by derreisende77** [comment]
Die notwendige jar findet sich im Ordner `target`.
```
cd target
java -jar MediathekView.jar
```
Es müssen natürlich noch alle fehlenden Startparameter hier ergänzt werden.

**Comment by derreisende77** [comment]
@dgottstein Hat es funktioniert?

**Comment by dgottstein** [comment]
@derreisende77 : Tut mir leid, hatte vorher keine Zeit es zu testen und dann tatsächlich vergessen. Werde es aber gleich testen, danke für den Hinweis!

**Comment by dgottstein** [comment]
Leider funktioniert es mit den Startparametern auch nicht:
```
java  -Xmx2g --enable-preview -jar /home/pi/.m2/repository/de/mediathekview/MediathekView/14.0.0/MediathekView-14.0.0.jar
kein Hauptmanifestattribut, in /home/pi/.m2/repository/de/mediathekview/MediathekView/14.0.0/MediathekView-14.0.0.jar
```
Mit welchen Parametern muss ich denn starten?

Laut Fehlermeldung müsste es doch aber eigentlich an einem fehlenden Attribut `Main-Class: ` in `META-INF/MANIFEST.MF` liegen, oder irre ich mich da?

Wie wurde denn bisher die Raspberry Pi Version gebaut?

**Comment by derreisende77** [comment]
cd MediathekView
mvn clean install
cd target
java -Xmx2G -jar MediathekView.jar

dann sollte es starten.

**Comment by dgottstein** [comment]
Das wäre super, danke!

Ansonsten: macht es Sinn, dass ich Maven in der passenden Version einrichte und das nochmal teste?

**Comment by derreisende77** [comment]
so, ich war gerade auf einem RPi 4 mit dem 64 bit Raspbian gerade drauf, welcher jungfräulich war. Ich habe das git repo gecloned und folgendes gemacht um MediathekView 14.0.1 zu bauen:
```
cd MediathekView
git switch develop
git pull

sdk install java 22.fx-liberica
sdk install maven 3.9.6

mvn clean install
cd target

java -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -XX:+UseStringDeduplication --add-opens=java.desktop/sun.awt.X11=ALL-UNNAMED -XX:MaxRAMPercentage=75.0 --add-exports javafx.controls/com.sun.javafx.scene.control.inputmap=ALL-UNNAMED --add-exports javafx.base/com.sun.javafx.event=ALL-UNNAMED -jar MediathekView.jar
```

Damit erhalte ich folgendes:

![Bildschirmfoto 2024-04-23 um 16 51 26](https://github.com/mediathekview/MediathekView/assets/8466092/551aacba-9461-410c-bddc-4b782a7e0288)

Es funktioniert, ansonsten liegt es an deiner config. Wichtig ist mein java call oben, da müssen mehr Parameter hinzugefügt werden ansonsten bleibt das Programm hängen.

**Comment by dgottstein** [comment]
Hi,
ich kann mit der 14.0.1 und der damit verbundenen Java 22 leider nicht bauen, er findet etliche JavaFX Controls nicht.
Ich war bisher auf einem 32-bit Raspbian unterwegs, habe zum Test nochmal auf 64-bit umgestellt (geht ja über die Config.txt ganz einfach), gab aber keine Verbesserung.

Da du aber auf einem "leeren" Pi4 mit 64-bit Raspbian offensichtlich ohne Probleme bauen kannst, muss bei mir irgendwas vermurkst sein.
Ich werde mal bei Gelegenheit eine zweite SD-Karte einsetzen und ein frisches System aufsetzen und nochmal testen.

Viele Grüße und vielen Dank für die Unterstützung!

**Comment by derreisende77** [comment]
Der war komplett frisch mit raspbian imager aufgesetzt, danach nur sdkman.io installiert und die Anleitung hier durchexerziert. 32bit systeme werden nicht mehr unterstützt, das kann deine Probleme erklären v.a. wenn es ein mischsystem wurde.

**Comment by dgottstein** [comment]
Hi,
ich habe nun endlich einen neuen RPI4 mit Bookworm (64bit) aufgesetzt und damit ging es auf anhieb.
Vielen Dank nochmal für die Unterstützung!
