### ISSUE TITLE
Action nach abgeschlossenem Download (Wunsch)

### ISSUE THREAD

**Issue by TueftelTyp** [mediathekview/MediathekView#736]
Moin, 
erstmal einen riesen Dank für diese tolle Software.

Habe es eben das erste mal ausprobiert und bin begeistert.

Aber, was ich mir sehr wünschen würde wäre eine ausführbare Aktion, nachdem alle Downloads abgeschlossen wurden (z.B. automatisch herunterfahren).
_Wer nicht gerade einen MiniPc / RPi oder Server sein Eigen nennt müsste somit nicht hin und wieder schauen, wie weit die Downloads sind und ob der PC heruntergefahren werden könnte._

👍

**Comment by DaDirnbocher** [comment]
Versuche MV bei laufenden Downloads zu beenden und lies, was da am Bildschirm erscheint.

**Comment by TueftelTyp** [comment]
Top, danke für den Hinweis.
Da wäre ich alleine wohl eher nicht drauf gekommen xD

Frohes Osterfest weiterhin :)
