### ISSUE TITLE
Letzte Nightly 14.1.0 vom 22 und 25.05.24 ffmpeg: Falsches Verzeichnis

### ISSUE THREAD

**Issue by dadidadit** [mediathekview/MediathekView#740]
Im Installtionsverzeichnis von Mediathekview unter Windows liegt ffmpeg im Unterverzeichnis **bin\ffmpeg\\**  , dadurch funktioniert ein Download von .m3u8-URL z. B. bei SRF und ORF nicht.
Außerdem ist die Info bei "Codec-Details erkennen"  (Filmliste - Speichern) bei allen Dateien nicht funktionsfähig. Im gleichen Verzeichnis ist auch ein Unterverzeichnis für Mac-OS enthalten, was damit geschieht, ist mir nicht bekannt.

Die im Verzeichnis **bin\ffmpeg\\** enthaltenen Dateien müssen für Windows nach **bin\\** verschoben werden, damit funktioniert alles.

**Korrigiert in Nightly vom 11.08.2024**

**Comment by derreisende77** [comment]
fix ist in develop
