### ISSUE TITLE
Pläne auf eine JDK LTS zu wechseln oder eine supported Version?

### ISSUE THREAD

**Issue by jensbin** [mediathekview/MediathekView#742]
Derzeit besteht eine Abhängigkeit auf JDK 20, welche seit dem 19. September 2023 EOL ist. Extended support kann nicht erworben werden.

Bestehen Pläne auf eine LTS Version zu migrieren (z.B.: JDK 21 - Support bis 30 Sep 2028, Oracle extended Support bis 30 Sep 2031)

**Comment by styroll** [comment]
Vgl [hier](https://github.com/mediathekview/MediathekView/issues/730).

**Comment by jensbin** [comment]
Ok. Danke für den Link. Non-LTS sind nur 6 Monate maintained, d.h. auch danach gibt es keine Sicherheitsupdates mehr.
Aus https://github.com/mediathekview/MediathekView/issues/730 verstehe ich, dass das nicht als problematisch angesehen wird, weil die JDK gebündelt wird.
