### ISSUE TITLE
Fehlerhaften download automatisch fortsetzen

### ISSUE THREAD

**Issue by daCostaeurogard** [mediathekview/MediathekView#745]
Hallo,
ich habe eine instabile Verbindung und somit hört der Downlaod von Filmen
und ich bekomme

![Fehlermediathekview](https://github.com/user-attachments/assets/8b39c2c9-a644-4c0d-ac14-0698240e2893)

Als nächstes muss man dann auf das Dreieck im Downloadfenster klicken

Dann hier klicken
![Fildownloadne](https://github.com/user-attachments/assets/cca4f41a-f366-4055-83b6-32f91d5be0e5)

Dann auch hier klicken

![Filmweiderherstellen](https://github.com/user-attachments/assets/0f2a4422-5d7c-4b45-b50f-3d8c9667d293)

Damit habe ich 4 Klicks bis ich den Film weiter herunterladen kann.

Es wäre gut wenn das automasiert werden kann, schlieesslich möchte ich ja den Film haben und heute habe ich bereits das ganze oben viele viel Male gemacht.

Danke

**Comment by derreisende77** [comment]
Also deinen tag mismatch kann ich leider nicht abfangen und automatisch weiterführen.
In 14.1 habe ich den connection timeout der verbindung angepasst - das sollte sich bei instabilen Verbindungen positiv auswirken.
Weiterhin kann man in 14.1 auch den Timeout von 60 Sekunden in den Einstellungen auf bis zu 1 Sekunde heruntersetzen.

Das vermeidet zwar nur einen Klick aber immerhin. Mehr ist leider nicht drin und primär sollte das Problem der instabilen Verbindung gelöst werden.

14.1 wird demnächst released, bis dahin kannst Du ab morgen dir ggf eine nightly version laden und es schon vorab testen.

**Comment by daCostaeurogard** [comment]
Netflix und Co laufen gut, nur downloads bekommen solche Abbrüche, da das sehr seletov ist, ist eine Ursache nicht ersichtlich, zumal die erste Fehlermeldung seltsam ist.

**Comment by derreisende77** [comment]
Ja, das Thema wurde im Forum schon ausführlich diskutiert. Meist liegt es an schlechten WLAN-Verbindungen. Java scheint da anfälliger zu sein als andere „richtige“ Windows-Programme.
