### ISSUE TITLE
MediathekView 14.0.0 und 14.0.1 finden bestimmte Serie nicht: "Irgendwie und Sowieso" im BR

### ISSUE THREAD

**Issue by frispete** [mediathekview/MediathekView#746]
Hi,
english version below. 

beide Versionen, MediathekView 14.0.0 und 14.0.1 finden eine bestimmte Serie nicht: "Irgendwie und Sowieso" im BR, während diese in der [ARD mediathek](https://www.ardmediathek.de/sendung/irgendwie-und-sowieso/Y3JpZDovL2JyLmRlL2Jyb2FkY2FzdFNlcmllcy9icm9hZGNhc3RTZXJpZXM6L2JyZGUvZmVybnNlaGVuL2JheWVyaXNjaGVzLWZlcm5zZWhlbi9zZW5kdW5nZW4vaXJnZW5kd2llLXVuZC1zb3dpZXNv) verfügbar sind.

Irgendeine Idee, was hier schief läuft?

both versions, MediathekView 14.0.0 and 14.0.1 cannot locate a certain tv series: "Irgendwie und Sowieso" in BR, while it is available in the [ARD mediathek](https://www.ardmediathek.de/sendung/irgendwie-und-sowieso/Y3JpZDovL2JyLmRlL2Jyb2FkY2FzdFNlcmllcy9icm9hZGNhc3RTZXJpZXM6L2JyZGUvZmVybnNlaGVuL2JheWVyaXNjaGVzLWZlcm5zZWhlbi9zZW5kdW5nZW4vaXJnZW5kd2llLXVuZC1zb3dpZXNv). 

An idea, what's going wrong here?

**Comment by derreisende77** [comment]
MV verarbeitet nur die Filmlisten, für die Erzeugung dieser ist [MServer](https://github.com/mediathekview/MServer) zuständig.
Für die Meldung/Nachfrage von fehlenden Filmen ist die Nutzung des Forums besser geeignet.

**Comment by DaDirnbocher** [comment]
> Irgendeine Idee, was hier schief läuft?

Irgendwelche Filter oder sonstige Einstellungen bei Dir, siehe [Webversion](https://mediathekviewweb.de/#query=irgendwie%20und%20sowieso).

**Comment by frispete** [comment]
@DaDirnbocher Nö, praktisch alles andere ist da! Hab die Anfrage gemäß @derreisende77 nach MServer verschoben...

@derreisende77 Danke für den Hinweis!

Nur noch eine Frage, wie werden die Projekte verbunden? Holen sich die Nightly builds den Master von MServer?

**Comment by DaDirnbocher** [comment]
> @DaDirnbocher Nö, praktisch alles andere ist da!

MediathekView und MediathekViewWeb verwenden dieselbe Filmliste (grundsätzlich, wenn Du sie zum selben "Zeitpunkt" anschaust).

Wenn Du also in MediathekView Filme nicht hast, die in MediathekViewWeb da sind, liegt die Ursache in der Regel lokal bei Dir. Alte Filmliste, Filter, Blacklist, .... whatever.

Deswegen steht in der A[nleitung zum Melden fehlender Filme im Forum](https://forum.mediathekview.de/topic/99/fehlende-sendung-melden) auch folgender Hinweis:

> Um ausschließen zu können, dass es an der Blacklist, den Filtereinstellungen oder sonstigen lokalen Einstellungen liegt empfiehlt es sich die Sendung bei [MediathekView Web](https://mediathekviewweb.de/) zu suchen.

**Comment by frispete** [comment]
@DaDirnbocher Nö, praktisch alles andere ist da, und die Filter auch zurückgesetzt! Hab die Anfrage gemäß @derreisende77 nach https://github.com/mediathekview/MServer/issues/1004 verschoben...

@derreisende77 Danke für den Hinweis!

Nur noch eine Frage, wie werden die Projekte verbunden? Holen sich die Nightly builds den Master von MServer?

**Comment by DaDirnbocher** [comment]
Just for the record: du wurdest an das Forum verwiesen:


> MV verarbeitet nur die Filmlisten, für die Erzeugung dieser ist [MServer](https://github.com/mediathekview/MServer) zuständig.

Das ist die Erklärung wie dinge zusammenspielen, und ...

>Für die Meldung/Nachfrage von fehlenden Filmen ist die Nutzung des Forums besser geeignet.

... das ist der Hinweis wo Du Dieine Frage stellen solltest.
