### ISSUE TITLE
Filter nach Sender funktioniert nicht oder ich kapiere den Filterdialog nicht

### ISSUE THREAD

**Issue by frispete** [mediathekview/MediathekView#747]
Hallo,

beim Versuch, einen einfachen Filter nach Sender zu erstellen, fiel mir auf, dass die Senderliste auf alle erfassten Filter wirkt, nicht nur auf den aktuell selektierten Filter. Ist das so erwünscht?

Habe zwei Filter definiert: BR und Alles, in BR ist Sender BR selektiert, und in Alles kein Sender selektiert.
Dabei wirkt die jeweils letzte Auswahl auf beide Filter, entweder BR auf beiden, oder keiner auf beiden Filtern. 

Funktional würde ich mir wünschen, wenn die Senderliste per Filter individuell bestimmt werden könnte, mit einer Ausnahme: keinen Sender auszuwählen sollte alle Sender matchen.

**Comment by DaDirnbocher** [comment]
> Habe zwei Filter definiert: BR und Alles, in BR ist Sender BR selektiert, und in Alles kein Sender selektiert.

[Nachdem Sender und Thema in den Filtern noch gar nicht gespeichert werden](https://github.com/mediathekview/MediathekView/issues/551), kannst du diese 2 Filter gar nicht definiert haben.

**Comment by frispete** [comment]
> Definiert haben kann man die schon, nur funktionieren wird das beim Wechsel nicht 😄

Genau so ist es.
 
> @frispete Wenn du nur einen Sender (oder auch mehrere) definieren willst, brauchst du eigentlich nur einen Filter. Du musst halt nur den oder die entsprechenden Sender aktivieren. Beim Neustart sind die Einstellungen aber wieder weg. Wenn du alle Sender haben willst, nimmst du die Häkchen halt wieder weg.

Hab's kapiert, die Senderauswahl (und anderes) ist nicht persistent. Gut zu wissen, und vielleicht ein hinreichender Grund, einen entsprechenden Kommentar in die Oberfläche einzubauen, bis die Funktionalität mal steht!

> Welche Version von Mediathekview nutzt du denn?

14.0.0 und 14.0.1 unter openSUSE Tumbleweed, selbst in OBS gebaut.

Hab mich auf #728 verewigt. Danke an alle! -> Closed!

**Comment by dadidadit** [comment]
Nur noch als Tipp:
> 14.0.0 und 14.0.1 unter openSUSE Tumbleweed, selbst in OBS gebaut.
Mit der neuen Lucene-Suchfunktion, die seit der 14er Version wahlweise vorhanden ist, kannst du unter Anderem  nur nach Sendern suchen. Der Eintrag wird dann in der dortigen History festgehalten, so dass du auch so eine entsprechende Auswahl treffen könntest.
