### ISSUE TITLE
Einträge in Filmliste fehlen

### ISSUE THREAD

**Issue by CarstenHa** [mediathekview/MediathekView#749]
Hallo,
in letzter Zeit ist mir hin und wieder mal aufgefallen, das Filme die in der ARD Mediathek zu finden sind, nicht in der Filmliste enthalten sind. Ein aktuelles Beispiel:
[Allmen und das Geheimnis des Koi](https://www.ardmediathek.de/film/allmen-und-das-geheimnis-des-koi/Y3JpZC4vL2Rhc2Vyc3RlLmRlL2FsbG1lbi11bmQtZGFzLWdlaGVpbW5pcy1kZXMta29p)
Vielleicht hilft Euch das ja bei der Analyse. Und das Wichtigste: Vielen Dank für Eure tolle Arbeit!

Gruß

Carsten

**Comment by derreisende77** [comment]
Bitte im [Forum](https://forum.mediathekview.de) ein entsprechendes Topic erstellen. Dort kann man dir in der Regel schnell weiterhelfen. MV erstellt die Filmliste nicht, dies wird von MServer gemacht und die Entwickler verfolgen auch i.d.R. das Forum.
