### ISSUE TITLE
NIghtly Builds  win/linux nicht aktuell  

### ISSUE THREAD

**Issue by j4reporting** [mediathekview/MediathekView#751]
derzeit werden aus welchen Gründen auch immer  nur noch die MAC  nightly builds auf  https://download.mediathekview.de/unstabil/  zur verfügung gestellt.

**Comment by alex1702** [comment]
Spannend mal gucken ob ich was fixen muss oder @derreisende77 ^^

**Comment by alex1702** [comment]
Sollte wieder funktionieren
