### ISSUE TITLE
Mediathekview crashes while writing film list...

### ISSUE THREAD

**Issue by umbertones** [mediathekview/MediathekView#753]
I hadn't used mediathekview on Kubuntu 24.04LTS for 25d.

Today I started it again and while writing the film list the machine (16 GB RAM) froze (no mouse movement, high fan speed)  for a minute then mediathekview crashed and took the Konsole down as well.

I reinstalled the deb from the server, deleted the .mediathek3-folder and tried again.

Same, same.

Last entries in the the log are...
INFO  2024-10-17 21:34:30,949  [FilmeImportierenAutoThread] filmlisten.FilmeLaden (FilmeLaden.java:301) - Jetzige Liste erstellt am: 17.10.2024, 20:38
INFO  2024-10-17 21:34:30,950  [FilmeImportierenAutoThread] filmlisten.FilmeLaden (FilmeLaden.java:302) -   Anzahl Filme: 800976
INFO  2024-10-17 21:34:31,075  [FilmeImportierenAutoThread] filmlisten.FilmeLaden (FilmeLaden.java:303) -   Anzahl Neue:  800976
INFO  2024-10-17 21:34:31,075  [FilmeImportierenAutoThread] filmlisten.FilmeLaden (FilmeLaden.java:304) - 
INFO  2024-10-17 21:34:31,529  [ForkJoinPool.commonPool-worker-2] writer.FilmListWriter (FilmListWriter.java:77) - Filme schreiben (800976 Filme) :
INFO  2024-10-17 21:34:31,530  [ForkJoinPool.commonPool-worker-2] writer.FilmListWriter (FilmListWriter.java:78) -    --> Start Schreiben nach: /home/uwe/.mediathek3/filme.json

31G free disk space should be enough.

Found an error.log in the installation folder:
Okt. 17, 2024 9:33:54 PM com.sun.javafx.application.PlatformImpl startup
WARNUNG: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @2e385cce'

$ java --version
java 17.0.12 2024-07-16 LTS

Any hints for me, any additional info you want to know? Full log available on request..

Thanks and regards

**Comment by umbertones** [comment]
When I use the builtin jre and the command from the readme the computer just freezes, no crash, had to reset machine

**Comment by derreisende77** [comment]
Which command do you use to launch MV?
The local java 17 is definitely not used by MV as we require Java 22 and deliver it locally.
Is it running in a VM?

**Comment by umbertones** [comment]
I had a link in my $HOME/bin. This has been working for years. 

I removed the link and setup a new one to /opt/Mediathekview/Mediathekview and it's working as expected now.

Weird.
