### ISSUE TITLE
Doesn't start with OpenJDK 9

### ISSUE THREAD

**Issue by nidico** [mediathekview/MediathekView#83]
Mediathek 11 fails to start on OpenJDK 9 on Ubuntu Xenial with the following error:

```
/usr/lib/jvm/java-9-openjdk-amd64/bin/java -jar ~/Downloads/MediathekView_11/MediathekView.jar
.  Proxy Authentication: not configured
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff719c37009, pid=13955, tid=13984
#
# JRE version: OpenJDK Runtime Environment (9.0) (build 9-internal+0-2016-04-14-195246.buildd.src)
# Java VM: OpenJDK 64-Bit Server VM (9-internal+0-2016-04-14-195246.buildd.src, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libjava.so+0x1d009]  JNU_GetEnv+0x19
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %P" (or dumping to /home/nidi/core.13955)
#
# An error report file with more information is saved as:
# /home/nidi/hs_err_pid13955.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
zsh: abort (core dumped)  /usr/lib/jvm/java-9-openjdk-amd64/bin/java -jar
```

Running it with OpenJDK 8 works fine.

**Comment by criztovyl** [comment]
You may should attach `/home/nidi/hs_err_pid13955.log`, that error message is kind of generic.

**Comment by nidico** [comment]
I didn't attach it yet, as it might simply be a known issue that MediathekView doesn't run on OpenJDK 9 and is trivial to reproduce for everyone.

If it's supposed to be working with OpenJDK 9, I'll attach the logfile. Is it?

**Comment by criztovyl** [comment]
Don't know if it's supposed to do so.

**Comment by xaverW** [comment]
Unter Linux kann man Java von Oracle nehmen oder wenn openjdk verwendet wird, muss zusätzlich openjfx vorhanden sein.
Ist das Paket "openjfx" vorhanden?

**Comment by nidico** [comment]
Installiing openjfx doesn't change anything. I can workaround the issue easily by simply running it with OpenJDK 8. Still it'd be good to be able to run the program with OpenJDK 9.

**Comment by nidico** [comment]
MediathekView 12 still doesn't start with OpenJDK 9, though with another error:

```
$ /usr/lib/jvm/java-9-openjdk-amd64/bin/java -jar ~/Downloads/MediathekView_12/MediathekView.jar
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/collections/FXCollections
        at mSearch.tool.SysMsg.<clinit>(SysMsg.java:27)
        at mediathek.Main.main(Main.java:94)
Caused by: java.lang.ClassNotFoundException: javafx.collections.FXCollections
        at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@9-internal/BuiltinClassLoader.java:366)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@9-internal/ClassLoaders.java:184)
        at java.lang.ClassLoader.loadClass(java.base@9-internal/ClassLoader.java:419)
        ... 2 more
```

This (new) error is now indeed due to the missing openjfx, as the `openjfx` ubuntu package seems to belong to OpenJDK 8 and I don't know how to easily install openjfx for OpenJDK 9 in ubuntu xenial.

**Comment by GogoLogo** [comment]
I have the same error - I would like to use OpenJDK, not oracle binaries. How can i run MediathekView with OpenJDK? Thanks! openjfx package is installed, same error!

**Comment by nidico** [comment]
> How can i run MediathekView with OpenJDK?

Use OpenJDK 8.
