### ISSUE TITLE
MediathekView 12 doesn't start

### ISSUE THREAD

**Issue by SimGer** [mediathekview/MediathekView#86]
I'm running Fedora 24 (x86-64) and MediathekView 11 starts fine.

```
$ java -version
openjdk version "1.8.0_101"
OpenJDK Runtime Environment (build 1.8.0_101-b14)
OpenJDK 64-Bit Server VM (build 25.101-b14, mixed mode)
```

MediathekView 12 gives the following error:

```
$ ./MediathekView__Linux.sh 
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/collections/FXCollections
        at mSearch.tool.SysMsg.<clinit>(SysMsg.java:27)
        at mediathek.Main.main(Main.java:94)
Caused by: java.lang.ClassNotFoundException: javafx.collections.FXCollections
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 2 more
```

**Comment by xaverW** [comment]
im root des zip liegt eine Datei "Hilfe__bitte_lesen.txt" und darin steht:

* Java ist nicht oder nicht in der richtigen Version installiert (Java8). Zum 
  Java-Download: http://java.com/de/
  Unter Linux müssen dazu 2 Pakete installiert werden!
  bei arch: java-openjfx und jre8-openjdk,
  bei Ubuntu 16.04: default-jre (entspricht openjdk-8-jre) und openjfx

im Wiki sind auch ein paar Beispielinstallationen vorgeführt:
https://sourceforge.net/p/zdfmediathk/wiki/Linux/

Bitte LESEN

**Comment by xaverW** [comment]
Vielleicht noch als Hintergrund: Oracle packt die fx Pakete mit dazu, bei Linux sind sie in OpenJDK nicht enthalten und müssen extra installiert werden.

**Comment by SimGer** [comment]
OK, bin offensichtlich blind. ;-)

openjfx gibt's allerdings bei Fedora leider nicht in den Paketquellen, mal sehen was ich da mache.

**Comment by nidico** [comment]
Would it be possible to show a more meaningful hint in runtime instead of crashing? I also stumbled upon this (as I could just start the program "as usual java programs" in previous versions).

**Comment by bmhm** [comment]
I'll want to create a pull request to this issue, @nidico. 

@xaverW: Schonmal danke, dass nur die ant-buildfiles eingecheckt sind. Bei z.B. Jameica/Hibiscus gibt es eclipse-files, ant-files und Maven-Files… Muss ich nochwas beim Pull request beachten?

**Comment by xaverW** [comment]
nein
