### ISSUE TITLE
Mehr Optionen für Blacklist

### ISSUE THREAD

**Issue by claell** [mediathekview/MediathekView#98]
Da bei manchen Sendungen z.B. das Thema sehr generisch ist oder neben dem Sendungsnamen auch noch ein spezifischer Titel mit im Thema ist, wäre es denke ich sinnvoll, weitere Optionen für die Blacklist zu haben.

Also z.B. auch Filtern nach Titel, oder nach einer Suche etc.

**Comment by zxsd** [comment]
Schon lange vorhanden ... 

![mv-blacklist](https://cloud.githubusercontent.com/assets/23268595/20027740/68a487c0-a2f2-11e6-8a59-0c54e5c4796d.PNG)

**Comment by claell** [comment]
Danke für den Hinweis, das habe ich übersehen. Hatte mich da immer an den verfügbaren Optionen bei einem Rechtsklick orientiert.

**Comment by alex1702** [comment]
Ist das issue damit geklärt?

**Comment by claell** [comment]
Ja, kann denke ich geschlossen werden, da andere Optionen direkt im Kontextmenü bei Rechtsklick auf eine Sendung vermutlich nicht sinnvoll wären.
Titel oder Thema-Titel in der Blacklist sind ja meistens anders, als der Titel der gerade ausgewählten Sendung und müssen daher sowieso manuell bearbeitet werden und auch eine Blacklist anhand einer Suche (so wie bei Abos) ergibt vermutlich keinen wirklichen Sinn.
